### ISSUE TITLE
scala.sys.process.Process.cat() seems to ignore all but first argument

### ISSUE THREAD

**Issue by tkw1536** [scala/bug#10823] opened 2018-04-11 09:43 UTC
I have the following snippet of code: 

```scala
import scala.sys.process.Process
import java.io.File

object HelloWorld {
  def main(args: Array[String]): Unit = {
    (Process.cat(List(new File("hello"), new File("world"))) #> new File("helloworld")).!
  }
}
```

When run, I would expect this code to concatenate the content of the files “hello” and “world”, and write them into the file “helloworld” (i.e. cat hello world > helloworld in bash terms).

However when I run this code, the following happens:
```bash
bash-3.2$ echo "hello" > hello
bash-3.2$ echo "world" > world
bash-3.2$ scala example.scala
bash-3.2$ cat helloworld
hello
bash-3.2$
```

It seems that Process.cat() simply ignores the second file and only uses the first one.

I was using Scala 2.12.5 and Java 1.8 on Mac OS X: 

```
bash-3.2$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
bash-3.2$ scala -version
Scala code runner version 2.12.5 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
```

**Comment by tkw1536** [comment] 2018-04-11 09:44
I originally posted this as a question on scala-users, but only got a very confusing answer https://users.scala-lang.org/t/weird-behaviour-of-scala-sys-process-process-cat/2572/2

**Comment by som-snytt** [comment] 2018-04-11 23:26
It works in 2.11, hangs in 2.12.0, and acquires its current behavior in 2.12.1.

This works, so it's not just the cat:
```
Process.cat(List(new File("hello"), new File("world"))).!!
```

That's all I confirmed in my time box. It suggests the problem is with how `#>` is wired; the changes around that time had to do with closing streams and interrupting threads.

**Comment by alex1712** [comment] 2018-06-22 09:34
I am taking a look on the issue, and the behaviour in the current 2.13.x branch is even worst.

If I try `Process.cat(List(new File("hello"), new File("world"))).!!`, I get `java.lang.StackOverflowError`

Sending them as separate arguments (`Process.cat(new File("hello"), new File("world"))`) the behaviour is as in previous versions, appending only the content of the first file.

I'll keep trying to find out the problem

**Comment by alex1712** [comment] 2018-06-22 13:42
I will create a new Issue for the StackOverflowError in 2.13.x when sending a Seq[File]

**Comment by alex1712** [comment] 2018-06-22 14:42
I did a PR for the other Issue but still don't get why the final File gets only the cat result of the first Process. At least the StackOverflowError should not come in scala 2.13 :)

**Comment by alex1712** [comment] 2018-07-05 14:11
In case anyone else wants to take the issue, I am not able to work further here at least for now. From my investigation I think the problem is in the way the `AndBuilder` in `scala/sys/process/ProcessImpl.scala` is creating the Process from the both `cat`.

**Comment by veera83372** [comment] 2018-08-08 20:26
Can I start working on it ?

**Comment by SethTisue** [comment] 2018-08-08 20:30
@veera83372 go for it!

**Comment by veera83372** [comment] 2018-08-08 20:33
@SethTisue  Thanks for confirmation

**Comment by SethTisue** [comment] 2019-03-04 23:02
@som-snytt did this get fixed, should we close this?

**Comment by som-snytt** [comment] 2019-03-04 23:24
Fixed by https://github.com/scala/scala/pull/7362 under aegis of scala-dev issue.

**Closed by som-snytt** 2019-03-04 23:24 UTC
Labels: good first issue, help wanted, library
