### ISSUE TITLE
Exponential compile times when pattern matching on type alias

### ISSUE THREAD

**Issue by jdrphillips** [scala/bug#12489] opened 2021-11-10 12:14 UTC
## reproduction steps

using Scala 2.13.5,

```scala
// Note: Removing `+` here has no effect on the issue:
type ~[+A, +B] = (A, B)

// Dummy type to allow us to map + pattern match
trait A[T] { def map[U](fn: T => U): A[U] = new A[U] {} }

// 25 nested Int's, both the same type
type B = ((((((((((((((((((((((((Int, Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int), Int)
type C = Int ~ Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int ~Int~Int

val ab = new A[B] {}
val ac = new A[C] {}

// Instant compile time:
ab.map { case ((((((((((((((((((((((((_, _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _) => 7 }

// Exponential compile time:
ac.map { case ((((((((((((((((((((((((_, _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _) => 7 }
```

## problem

Deconstructing a simple alias for a type in a case match causes exponentially increasing compile times, dependent on the depth of the deconstruction.

In the code above, `type B` and `type C` are the same, but `C` is constructed through aliases. Deconstructing type `C` takes vastly longer than deconstructing type `B`.

I would expect that `ab.map...` and `ac.map...` should take the same length of time to compile.

**Comment by pabloazul** [comment] 2021-11-10 16:14
Confirmed on Scala 2.13.7 but fixed in Scala 3.

**Comment by SethTisue** [comment] 2021-11-18 16:01
Nitpick: likely quadratic not exponential, I would think.

Handling of type aliases is often a fragile and complicated area, so it's hard to know whether an easy fix might be possible or whether the problem is fundamental.

**Comment by jdrphillips** [comment] 2021-11-18 17:07
I think it might be quite a bit more than quadratic, and quite a bit weirder than you may think.

Take a second alias:

```scala
type ~~[+A, +B] = (A, B)
```

Identical to the first. Now define another 25-int type, interlacing the aliases:

```scala
// ~ then ~~ then ~ etc, 25 ints
type D = Int ~ Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int ~~Int ~Int~~Int
```

Then perform the test:

```scala
val ad = new A[D] {}
ad.map { case ((((((((((((((((((((((((_, _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _), _) => 7  }
```

In my rough benchmarks:

```
ac.map: 39s
ad.map: 14s
```

_One third_ of the time to compile. Interlace a third type `~~~` and the compile time reduces by 2/3rds again: 5s to compile.

It's something very funky going on inside the compiler when dealing specifically with a stack of nested identical aliases. You can define `type ~~ = ~` as well if you like, and you see the same improvement.

Incidentally this is also why traditional `Nat` is so slow to compile and therefore pretty useless in practise, it's all type aliases. At least that will be fixed in scala 3!

**Comment by jdrphillips** [comment] 2021-11-18 17:48
It's actually weirder than that.

The type

```scala
type E = Int ~ Int ~~Int ~~~Int ~Int ~~Int ~~~Int ~Int ~~Int ~~~Int ~Int ~~Int ~~~Int ~Int ~~Int ~~~Int ~Int ~~Int ~~~Int ~Int ~~Int ~~~Int ~Int ~~Int~~~Int
```

Contains the type `~[~~[~~~...` 8 times, nested. If you instead define the structure randomly

```scala
type E = Int ~ Int ~~Int ~~Int ~~~Int ~Int ~~~Int ~~Int ~Int ~Int ~~~Int ~~Int ~~Int ~~Int ~~~Int ~Int ~Int ~~~Int ~~~Int ~~Int ~Int ~~Int ~~Int ~~~Int~Int
```

such that there is no repeating structure... You get near-instant compile times. `ae.map` here for me takes barely longer than the console printing time.

**Comment by jdrphillips** [comment] 2021-11-18 17:53
It even works with just the two aliases `~` and `~~` as long as you define your type `E` with no to little nesting

```scala
// ~ and ~~x1, then ~ and ~~x2, then...
type E = Int ~ Int ~~Int ~Int ~~Int ~~Int ~Int ~~Int ~~Int ~~Int ~Int ~~Int ~~Int ~~Int ~~Int ~Int ~~Int ~~Int ~~Int ~~Int ~~Int ~Int ~~Int ~~Int~~Int
```

< 2s

**Comment by SethTisue** [comment] 2021-11-18 18:10
> If you instead define the structure randomly such that there is no repeating structure... You get near-instant compile times

omg. like that scene in Dune where they have to walk in an irregular rhythm so the sandworms don't hear them and eat them

**Comment by joroKr21** [comment] 2021-12-04 12:30
@dwijnand I assume we can't run patmat after uncurry?

**Comment by joroKr21** [comment] 2021-12-07 19:03
The slowness comes from here: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/transform/patmat/Logic.scala#L756

The fact that each nested pattern match creates a binding and it's type is compared repeatedly in this way.

**Comment by dwijnand** [comment] 2021-12-12 12:48
> @dwijnand I assume we can't run patmat after uncurry?

Technically, I don't know, but I wouldn't be surprised if the answer is no, or not without a lot of work.  But also I don't think we can change the order of phases in a minor release either, because of plugins.

> The slowness comes from here: [scala/scala@`2.13.x`/src/compiler/scala/tools/nsc/transform/patmat/Logic.scala#L756](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/transform/patmat/Logic.scala?rgh-link-date=2021-12-07T19%3A03%3A37Z#L756)
> 
> The fact that each nested pattern match creates a binding and it's type is compared repeatedly in this way.

Nice find!  But why is that slow with tildes and not with tuples?

**Comment by joroKr21** [comment] 2021-12-12 15:23
> Nice find! But why is that slow with tildes and not with tuples?

Probably because of the extra work to dealias

**Comment by joroKr21** [comment] 2021-12-12 22:17
Maybe we can dealias patterns before expanding them?

**Closed** 2022-01-19 11:29 UTC
Labels: performance, typer, fixed in Scala 3
