### ISSUE TITLE
Unicode support broken in interpreter/console with Scala 2.13.5

### ISSUE THREAD

**Issue by balagez** [scala/bug#12370] opened 2021-04-09 20:42 UTC
## reproduction steps

The Scala 2.13.5 interpreter seems to incorrectly print unicode characters:

```scala
Welcome to Scala 2.13.5 (OpenJDK 64-Bit Server VM, Java 1.8.0_282).
Type in expressions for evaluation. Or try :help.

scala> "\u00C1rv\u00EDzt\u0171r\u0151"
val res0: String = ?rv?zt?r?
```

With Scala 2.13.4 the problem does not exist:

```scala
Welcome to Scala 2.13.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_282).
Type in expressions for evaluation. Or try :help.

scala> "\u00C1rv\u00EDzt\u0171r\u0151"
val res0: String = Árvíztűrő
```

Using the following system:
* OS: macOS Mojave 10.14.6
* JVM:
   ```
   $ java -version
   openjdk version "1.8.0_282"
   OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
   OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
   ```
* Locale:
   ```
   $ locale
   LANG="en_US.UTF-8"
   LC_COLLATE="en_US.UTF-8"
   LC_CTYPE="en_US.UTF-8"
   LC_MESSAGES="en_US.UTF-8"
   LC_MONETARY="en_US.UTF-8"
   LC_NUMERIC="en_US.UTF-8"
   LC_TIME="en_US.UTF-8"
   LC_ALL="en_US.UTF-8"
   ```
* Tested with Scala installed via both homebrew and sbt

## problem

It seems like the Scala 2.13.5 interpreter is unable to print unicode characters correctly while it still worked with Scala 2.13.4. The operating system, the JVM and all other environment settings were the same, the only difference was the Scala version.

**Comment by SethTisue** [comment] 2021-04-09 20:43
duplicate of #12360

**Closed by SethTisue** 2021-04-09 20:43 UTC

**Comment by som-snytt** [comment] 2021-04-09 21:17
Alas, it seems my plan to enforce US-ASCII hegemony has failed.
