### ISSUE TITLE
Failed to run scala on Eclipse OpenJ9 VM, Java 13

### ISSUE THREAD

**Issue by SchrodingerZhu** [scala/bug#11762] opened 2019-10-07 05:05 UTC
The Error Code:
```
❯ scala                             
Welcome to Scala 2.13.0-20190613-143643-unknown (Eclipse OpenJ9 VM, Java 13).
Type in expressions for evaluation. Or try :help.

scala> val a = 1;
java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
        at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
        at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:216)
        at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:63)
        at scala.tools.nsc.classpath.AggregateClassPath$$Lambda$1470.0000000000000000.apply(Unknown Source)
        at scala.collection.StrictOptimizedIterableOps.strictOptimizedFlatMap(StrictOptimizedIterableOps.scala:118)
        at scala.collection.StrictOptimizedIterableOps.strictOptimizedFlatMap$(StrictOptimizedIterableOps.scala:115)
        at scala.collection.immutable.Vector.strictOptimizedFlatMap(Vector.scala:113)
        at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:106)
        at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
        at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
        at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:63)
        at scala.tools.nsc.interpreter.IMain.compilerClasspath(IMain.scala:93)
        at scala.tools.nsc.interpreter.IMain.makeClassLoader(IMain.scala:352)
        at scala.tools.nsc.interpreter.IMain.ensureClassLoader(IMain.scala:275)
        at scala.tools.nsc.interpreter.IMain.classLoader(IMain.scala:278)
        at scala.tools.nsc.interpreter.IMain.runtimeMirror$lzycompute(IMain.scala:168)
        at scala.tools.nsc.interpreter.IMain.runtimeMirror(IMain.scala:168)
        at scala.tools.nsc.interpreter.IMain.$anonfun$getModuleIfDefined$1(IMain.scala:177)
        at scala.tools.nsc.interpreter.IMain$$Lambda$1543.0000000000000000.apply(Unknown Source)
        at scala.tools.nsc.interpreter.IMain.noFatal(IMain.scala:170)
        at scala.tools.nsc.interpreter.IMain.getModuleIfDefined(IMain.scala:177)
        at scala.tools.nsc.interpreter.IMain.readRootPath(IMain.scala:289)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.resolvePathToSymbol(IMain.scala:662)
        at scala.tools.nsc.interpreter.IMain$Request.resultSymbol$lzycompute(IMain.scala:919)
        at scala.tools.nsc.interpreter.IMain$Request.resultSymbol(IMain.scala:918)
        at scala.tools.nsc.interpreter.IMain$Request.$anonfun$typeMap$1(IMain.scala:930)
        at scala.tools.nsc.interpreter.IMain$Request$$Lambda$1542.0000000000000000.apply(Unknown Source)
        at scala.reflect.internal.util.Collections.$anonfun$mapFrom$1(Collections.scala:220)
        at scala.reflect.internal.util.Collections$$Lambda$816.0000000000000000.apply(Unknown Source)
        at scala.collection.immutable.List.map(List.scala:222)
        at scala.reflect.internal.util.Collections.mapFrom(Collections.scala:220)
        at scala.reflect.internal.util.Collections.mapFrom$(Collections.scala:219)
        at scala.reflect.internal.SymbolTable.mapFrom(SymbolTable.scala:28)
        at scala.tools.nsc.interpreter.IMain$Request.typeMap(IMain.scala:930)
        at scala.tools.nsc.interpreter.IMain$Request.typeOf$lzycompute(IMain.scala:935)
        at scala.tools.nsc.interpreter.IMain$Request.typeOf(IMain.scala:935)
        at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:897)
        at scala.tools.nsc.interpreter.IMain.$anonfun$compile$1(IMain.scala:493)
        at scala.tools.nsc.interpreter.IMain.$anonfun$compile$1$adapted(IMain.scala:493)
        at scala.tools.nsc.interpreter.IMain$$Lambda$1485.0000000000000000.apply(Unknown Source)
        at scala.util.Either.filterOrElse(Either.scala:400)
        at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:493)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:487)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:470)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:930)
        at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:787)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:462)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:485)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:1019)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:102)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:107)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.lang.RuntimeException: /packages cannot be represented as URI
        ... 54 more

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
```

OS Info:
```
5.3.4-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 5 13:44:11 UTC 2019 x86_64 GNU/Linux
```
JDK Info:
```
openjdk 13 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.16.0, JRE 13 Linux amd64-64-Bit 20190916_73 (JIT enabled, AOT enabled)
OpenJ9   - 867dab457
OMR      - d4c85c31
JCL      - 2858e3f001 based on jdk-13+33)
```

**Comment by SchrodingerZhu** [comment] 2019-10-07 05:10
Is it supposed to be already fixed in #11608 ?

**Comment by Jasper-M** [comment] 2019-10-07 08:28
Can you reproduce it on Scala 2.13.1?

**Comment by Jasper-M** [comment] 2019-10-07 12:36
Looks like this is fixed then.

**Comment by hrhino** [comment] 2019-10-07 13:09
I'm closing this, then; @SchrodingerZhu: it may be worth it to report this to Arch somehow (I'm not an arch user so I don't know how they manage their packages)

**Closed by hrhino** 2019-10-07 13:09 UTC
Labels: duplicate, jdk13

**Comment by SethTisue** [comment] 2019-10-08 16:13
our JDK compat page should cover 13; I opened https://github.com/scala/docs.scala-lang/issues/1542 on it
