### ISSUE TITLE
Invalid covariant class implementation crashes the Scala compiler 2.13.1 and 2.13.2

### ISSUE THREAD

**Issue by eshu** [scala/bug#12001] opened 2020-05-15 11:37 UTC
## reproduction steps

using Scala 2.13.1 or 2.13.2,

```scala
class Event[+T](weight: Int, data: T) extends Ordered[Event[_ <: T]] {
  def compare(that: Event[_ <: T]): Int = weight - that.weight
}
```

## problem
Compiler should print an error message, it should not be crashed.
If I replace ```weight - that.weight``` with ```???```, I receive an expected error.

**Comment by joroKr21** [comment] 2020-05-15 12:00
Duplicate of #11775?

**Comment by SethTisue** [comment] 2020-05-15 15:41
```
java.lang.StackOverflowError
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.thisTypeAsSeen(TypeMaps.scala:650)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:442)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2358)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:445)
	at scala.reflect.internal.Types$TypeBounds.mapOver(Types.scala:1577)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:445)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:123)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:117)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:121)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:135)
	at scala.reflect.internal.Types$ExistentialType.mapOver(Types.scala:3211)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:445)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:415)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2367)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:445)
	at scala.reflect.internal.Types$Type.asSeenFrom(Types.scala:698)
	at scala.reflect.internal.Types$TypeRef.seenFromOwnerInstantiated$1(Types.scala:2486)
	at scala.reflect.internal.Types$TypeRef.relativize(Types.scala:2490)
	at scala.reflect.internal.Types$TypeRef.$anonfun$baseTypeSeqImpl$2(Types.scala:2615)
	at scala.reflect.internal.BaseTypeSeqs$BaseTypeSeq.map(BaseTypeSeqs.scala:157)
	at scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2615)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef(Types.scala:2789)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef$(Types.scala:2780)
	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:28)
	at scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2622)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getClassParts$1(Implicits.scala:1359)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1394)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.$anonfun$companionImplicitMap$10(Implicits.scala:1395)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1395)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getClassParts$1(Implicits.scala:1362)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1394)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.$anonfun$companionImplicitMap$10(Implicits.scala:1395)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1395)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getClassParts$1(Implicits.scala:1362)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1394)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.$anonfun$companionImplicitMap$10(Implicits.scala:1395)
```

**Closed** 2020-05-15 15:43 UTC
Labels: compiler crash
