### ISSUE TITLE
VectorMap#{remove, init, tail} broken in Scala 2.13.0-M5

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11100] opened 2018-08-22 04:19 UTC
https://github.com/scala/scala/blob/98a68df30390337425388bc9d586a46dacc7c6c4/src/library/scala/collection/immutable/VectorMap.scala#L65-L72

```
Welcome to Scala 2.13.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable.VectorMap
import scala.collection.immutable.VectorMap

scala> val x = VectorMap(1 -> "a", 2 -> "b")
x: scala.collection.immutable.VectorMap[Int,String] = VectorMap(1 -> a, 2 -> b)

scala> lazy val y = x remove 1
y: scala.collection.immutable.VectorMap[Int,String] = <lazy>

scala> y.size
res0: Int = 1

scala> y.toString
java.util.NoSuchElementException: key not found: 1
  at scala.collection.MapOps.default(Map.scala:217)
  at scala.collection.MapOps.default$(Map.scala:216)
  at scala.collection.AbstractMap.default(Map.scala:343)
  at scala.collection.MapOps.apply(Map.scala:133)
  at scala.collection.MapOps.apply$(Map.scala:132)
  at scala.collection.AbstractMap.apply(Map.scala:343)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:56)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:49)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:552)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1131)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1126)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1186)
  at scala.collection.MapOps.addString(Map.scala:290)
  at scala.collection.MapOps.addString$(Map.scala:289)
  at scala.collection.AbstractMap.addString(Map.scala:343)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1076)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1074)
  at scala.collection.AbstractIterable.mkString(Iterable.scala:898)
  at scala.collection.Iterable.toString(Iterable.scala:83)
  at scala.collection.Iterable.toString$(Iterable.scala:83)
  at scala.collection.Map.toString(Map.scala:60)
  at scala.collection.Map.toString$(Map.scala:60)
  at scala.collection.AbstractMap.toString(Map.scala:343)
  ... 40 elided

scala> y + (1 -> "c")
res2: scala.collection.immutable.VectorMap[Int,String] = VectorMap(1 -> c, 1 -> c)
```

/cc @mdedetrich

**Comment by xuwei-k** [comment] 2018-08-22 05:36
```
Welcome to Scala 2.13.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable.VectorMap
import scala.collection.immutable.VectorMap

scala> val x = VectorMap(1 -> "a", 2 -> "b")
x: scala.collection.immutable.VectorMap[Int,String] = VectorMap(1 -> a, 2 -> b)

scala> x.init
java.util.NoSuchElementException: key not found: 1
  at scala.collection.MapOps.default(Map.scala:217)
  at scala.collection.MapOps.default$(Map.scala:216)
  at scala.collection.AbstractMap.default(Map.scala:343)
  at scala.collection.MapOps.apply(Map.scala:133)
  at scala.collection.MapOps.apply$(Map.scala:132)
  at scala.collection.AbstractMap.apply(Map.scala:343)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:56)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:49)
  at scala.collection.Iterator$SliceIterator.next(Iterator.scala:1126)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:552)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1131)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1126)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1186)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1076)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1074)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1186)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:230)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:239)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:247)
  at .$print$lzycompute(<synthetic>:8)
  ... 37 elided

scala> x.tail
java.util.NoSuchElementException: key not found: 2
  at scala.collection.MapOps.default(Map.scala:217)
  at scala.collection.MapOps.default$(Map.scala:216)
  at scala.collection.AbstractMap.default(Map.scala:343)
  at scala.collection.MapOps.apply(Map.scala:133)
  at scala.collection.MapOps.apply$(Map.scala:132)
  at scala.collection.AbstractMap.apply(Map.scala:343)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:56)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:49)
  at scala.collection.Iterator$SliceIterator.next(Iterator.scala:1126)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:552)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1131)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1126)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1186)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1076)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1074)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1186)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:230)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:239)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:247)
  at .$print$lzycompute(<synthetic>:8)
  ... 37 elided
```

**Comment by mdedetrich** [comment] 2018-08-22 08:42
Will fix this today

**Comment by adriaanm** [comment] 2018-08-22 13:44
@mdedetrich I've invited you to the contributors team, so we can actually assign this to you ;-)

**Comment by SethTisue** [comment] 2018-08-22 15:08
@Ichoran (who I think is on vacation) would a wave of the collections-laws wand have caught this...?

**Comment by SethTisue** [comment] 2018-08-22 18:58
@xuwei-k nice catch!

@mdedetrich cool, sounds good. we discussed internally whether to rebuild M5 over this (and it also came up on Gitter), but I don't think rebuilding is necessary. this is brand new code nobody is relying on yet, RC1 is fine for a fix. and if anyone wants to beat on `VectorMap` specifically, they can use a nightly build that includes the fix.

we're extremely pleased to have `VectorMap` landing, regardless. 💯

**Comment by adriaanm** [comment] 2018-08-22 19:04
@emilypi and @fommil, if you have anything of substance to contribute, great! If not, please do refrain. (Wow this is getting old.)

**Comment by fommil** [comment] 2018-08-22 19:10
@adriaanm what on earth are you talking about?

**Comment by emilypi** [comment] 2018-08-22 19:28
I have amended my emojis to adhere to Lightbend's contribution policy. @adriaanm do you need anything else from me? My only substantive suggestion is to fully test PRs before merging them. 

Thanks
E

**Comment by fommil** [comment] 2018-08-22 19:38
@adriaanm why am I being pulled into this conversation, and why are my comments (asking you why I'm being pulled in) being deleted?

Actually, I don't care. Please just stop pestering me. I am no longer interested in Scala.

**Comment by emilypi** [comment] 2018-08-22 19:43
Thanks for your report @xuwei-k! This is a difficult problem to abstract, but it does come down to testing each method of your data structure in a variety of settings. If there is not present already, I would hope that this contribution came with both a test suite and example usages that would expose bugs like this, and I hope this is Scala's stance in the future to require these sorts of things.

**Comment by SethTisue** [comment] 2018-08-22 19:44
@emilypi that's enough. take it elsewhere

**Comment by mdedetrich** [comment] 2018-08-22 20:44
@xuwei-k 

Okay so, I can replicate your first issue, i.e.

```
scala> import scala.collection.immutable.VectorMap
import scala.collection.immutable.VectorMap

scala> val x = VectorMap(1 -> "a", 2 -> "b")
x: scala.collection.immutable.VectorMap[Int,String] = VectorMap(1 -> a, 2 -> b)

scala> lazy val y = x remove 1
y: scala.collection.immutable.VectorMap[Int,String] = <lazy>

scala> y.size
res0: Int = 1

scala> y.toString
```

However I can't replicate your second issue, i.e.
```
scala> import scala.collection.immutable.VectorMap
import scala.collection.immutable.VectorMap

scala> val x = VectorMap(1 -> "a", 2 -> "b")
x: scala.collection.immutable.VectorMap[Int,String] = VectorMap(1 -> a, 2 -> b)

scala> x.init
java.util.NoSuchElementException: key not found: 1
  at scala.collection.MapOps.default(Map.scala:217)
  at scala.collection.MapOps.default$(Map.scala:216)
  at scala.collection.AbstractMap.default(Map.scala:343)
  at scala.collection.MapOps.apply(Map.scala:133)
  at scala.collection.MapOps.apply$(Map.scala:132)
  at scala.collection.AbstractMap.apply(Map.scala:343)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:56)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:49)
  at scala.collection.Iterator$SliceIterator.next(Iterator.scala:1126)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:552)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1131)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1126)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1186)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1076)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1074)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1186)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:230)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:239)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:247)
  at .$print$lzycompute(<synthetic>:8)
  ... 37 elided

scala> x.tail
java.util.NoSuchElementException: key not found: 2
  at scala.collection.MapOps.default(Map.scala:217)
  at scala.collection.MapOps.default$(Map.scala:216)
  at scala.collection.AbstractMap.default(Map.scala:343)
  at scala.collection.MapOps.apply(Map.scala:133)
  at scala.collection.MapOps.apply$(Map.scala:132)
  at scala.collection.AbstractMap.apply(Map.scala:343)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:56)
  at scala.collection.immutable.VectorMap$$anon$1.next(VectorMap.scala:49)
  at scala.collection.Iterator$SliceIterator.next(Iterator.scala:1126)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:552)
  at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1131)
  at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1126)
  at scala.collection.AbstractIterator.addString(Iterator.scala:1186)
  at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1076)
  at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1074)
  at scala.collection.AbstractIterator.mkString(Iterator.scala:1186)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:230)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:239)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:247)
  at .$print$lzycompute(<synthetic>:8)
  ... 37 elided
```

Note that I am not using the repl, instead I am writing a failing test which contains your code, i.e. in the second case I am writing

```scala
  property("iterator") = {
    val x = VectorMap(1 -> "a", 2 -> "b")
    x.init
    x.tail
    true
  }
```

And the exception is never thrown, can something be up with the repl here?

So along with the first problem that I was able to reproduce, something really weird is happening here. The issue is with the `-` method, i.e. the remove method, I have added some `println` statements, i.e.

```scala
  def remove(key: K): VectorMap[K, V] = {
    underlying.get(key) match {
      case Some((index, _)) =>
        println(s"index is: $index")
        println(s"underlying is: $underlying")
        println(s"key is: $key")
        new VectorMap(fields.patch(index, Nil, 1), underlying - key)
      case _ =>
        this
    }
  }
```

To debug this example

```scala
  property("iterator") = {
    val x = VectorMap(1 -> "a", 2 -> "b")
    lazy val y = x remove 1
    y.size
    y.toString
    true
  }
```

The `println` statements print the following
```
index is: 1
underlying is: HashMap(1 -> (1,a), 2 -> (2,b))
key is: 1
```

What is causing the `java.util.NoSuchElementException: key not found: 1` exception specifically is the `underlying - key` section. The thing is the `1` key is clearly inside the HashMap, i.e. ` 1 -> (1,"a")`. Something really weird is going on here, @julienrf do you have any idea?

**Comment by mdedetrich** [comment] 2018-08-22 21:19
NVM, ended finding it was a dumb fencepost error, fixed in https://github.com/scala/scala/pull/7123

**Comment by adriaanm** [comment] 2018-08-22 21:36
Nice! Thanks for getting this fixed so quickly.

**Comment by SethTisue** [comment] 2018-08-22 21:58
we still need to figure out what's up with the `.init` case, though

**Comment by SethTisue** [comment] 2018-08-22 22:12
> can something be up with the repl here?

ahhh... the reason the result is different in the REPL is that it doesn't blow up until `.toString` as called:

```
scala> collection.immutable.VectorMap(1 -> "a", 2 -> "b").init.size
res1: Int = 1

scala> collection.immutable.VectorMap(1 -> "a", 2 -> "b").init.toString
java.util.NoSuchElementException: key not found: 1
```

**Comment by SethTisue** [comment] 2018-08-22 22:34
(had to unlock briefly so someone could unsubscribe from the ticket, GitHub wasn't permitting it otherwise)

**Comment by SethTisue** [comment] 2018-08-22 22:36
> we still need to figure out what's up with .init and .tail, though

found it. added a commit to Matthew's PR with the fix

**Comment by SethTisue** [comment] 2018-08-23 17:14
keeping this open because scala/scala#7123 fixes some of the bugs but not all of them, see the comments on the PR

**Comment by SethTisue** [comment] 2018-08-24 22:29
hopefully https://github.com/scala/scala/pull/7134 restores correctness

**Closed** 2018-09-04 21:13 UTC
Labels: blocker, collections
