### ISSUE TITLE
to(collection.IndexedSeq) should not create a new collection if the source collection is a collection.IndexedSeq

### ISSUE THREAD

**Issue by Atry** [scala/bug#11868] opened 2020-01-29 07:54 UTC
``` scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.1).
Type in expressions for evaluation. Or try :help.

scala> val s = Array(1): collection.IndexedSeq[Int]
s: scala.collection.IndexedSeq[Int] = ArraySeq(1)

scala> s.to(collection.IndexedSeq) eq s // should be true
res0: Boolean = false
```

**Comment by julienrf** [comment] 2020-01-29 08:19
I am not sure. My opinion is that it is probably safer to create a new collection if the source collection is a mutable collection. However, if the source collection is immutable we can do the optimization you are looking for: https://scastie.scala-lang.org/QcTwjN63RkyTHLgZSblZpw

~~~ scala
val s = List(1): collection.Seq[Int]
s.to(collection.Seq) eq s // true
~~~

That being said, the current behavior should be clearly documented.

**Comment by Jasper-M** [comment] 2020-01-29 08:19
I think that mutable collections always copy. Otherwise you get unpredictable behavior.

**Comment by Atry** [comment] 2020-01-29 08:34
Suppose you are creating a function to create a sorted array from whatever collection, you might create something like this:
``` scala
def createSortedArrayFrom(iterable: Iterable[Int]): Array[Int] = {
  iterable.to(collection.Seq).view.sorted.toArray
}
```
Unfortunately, it performs the unnecessary element copy when the parameter is a `collection.Seq`, like `createSortedArrayFrom(Array(3, 2, 4))`. How can we provide an API to avoid the copy?

**Comment by Atry** [comment] 2020-01-29 08:35
I wonder if we can make `SeqView` a `Factory` to support this use case:

``` scala
def createSortedArrayFrom(iterable: Iterable[Int]): Array[Int] = {
  iterable.to(collection.SeqView).sorted.toArray
}
```

**Comment by dwijnand** [comment] 2020-01-29 08:47
> Otherwise you get unpredictable behavior.

Such as?  I've wanted the behaviour described here too.

**Comment by julienrf** [comment] 2020-01-29 08:53
@dwijnand Both behaviours make sense, but whatever behaviour is implemented it has to be clearly documented. In Scala 2.12 the `to` operation was also copying. If we change this now to aliasing instead of copying, we might break existing code relying on the old behaviour.

**Comment by sjrd** [comment] 2020-01-29 08:58
In Scala 2.12, `toSeq` and `toArray` are definitely *not* copying, at least for `Array`s:
```scala
$ scala
Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).
Type in expressions for evaluation. Or try :help.

scala> val arr = Array(1, 2, 3)
arr: Array[Int] = Array(1, 2, 3)

scala> val s: Seq[Int] = arr
s: Seq[Int] = WrappedArray(1, 2, 3)

scala> val x = s.toArray
x: Array[Int] = Array(1, 2, 3)

scala> x eq arr
res0: Boolean = true

scala> arr.toSeq.toArray eq arr
res1: Boolean = true
```

**Comment by Jasper-M** [comment] 2020-01-29 08:58
> Such as? I've wanted the behaviour described here too.

```
import scala.collection.mutable

val x: collection.IndexedSeq[Int] = mutable.ArrayBuffer(1, 2, 3)
val a = x.to(mutable.ArrayBuffer)
val b = x.to(mutable.ArraySeq)

a(0) = 9
b(1) = 8
println(x) // ArrayBuffer(9, 1, 2) ???
```

**Comment by sjrd** [comment] 2020-01-29 08:59
Same thing with `ListBuffer`s:
```scala
scala> val b = scala.collection.mutable.ListBuffer.empty[Int]
b: scala.collection.mutable.ListBuffer[Int] = ListBuffer()

scala> b += 5
res3: b.type = ListBuffer(5)

scala> val s = b.toSeq
s: Seq[Int] = List(5)

scala> b += 4
res4: b.type = ListBuffer(5, 4)

scala> s
res5: Seq[Int] = List(5, 4)
```

**Comment by julienrf** [comment] 2020-01-29 09:02
> I wonder if we can make `SeqView` a `Factory` to support this use case:
> 
> ```scala
> def createSortedArrayFrom(iterable: Iterable[Int]): Array[Int] = {
>   iterable.to(collection.SeqView).sorted.toArray
> }
> ```

Maybe, yes, although I’m not sure how we should implement the `SeqView` for collections that are _not_ `Seq`s (e.g. `Set`).

@sjrd
> In Scala 2.12, `toSeq` and `toArray` are definitely _not_ copying, at least for `Array`s:

`to[collection.Seq]` does copy, but `toSeq` does not. There was an inconsistency.

**Comment by julienrf** [comment] 2020-01-29 09:04
> Ouch ... did I just create a `scala.collection.immutable.List` that is actually _not_ immutable!? That's bad.

Good catch, that’s a bug!

**Comment by dwijnand** [comment] 2020-01-29 09:05
> Ouch ... did I just create a `scala.collection.immutable.List` that is actually _not_ immutable!? That's bad.

Yeah, the fact that `b.toSeq` doesn't copy is really risky.

I'm not convinced that it's inconsistent to downcast without copying (as in Jasper's `sc.Seq` to `ArrayBuffer` example), but I'm vastly more interested in the immutable collection side of things.

**Comment by Jasper-M** [comment] 2020-01-29 09:10
> Ouch ... did I just create a scala.collection.immutable.List that is actually not immutable!? That's bad.

Unfortunately GitHub doesn't provide a "shocked to my very core" type of emoji reaction.

**Comment by julienrf** [comment] 2020-01-29 09:39
The bug demonstrated in @sjrd’s comment is only present on 2.12, I’ve created #11869 for it.

**Comment by ritschwumm** [comment] 2020-01-29 18:23
hm... why am i not surprised at all?

**Comment by SethTisue** [comment] 2020-01-29 19:37
we intend to build 2.12.11 in a few weeks, so there's an opportunity to get a fix for #11869 out in relatively short order, someone want to tackle it?

**Comment by hrhino** [comment] 2020-01-30 11:48
Apparently I do.

**Comment by lrytz** [comment] 2020-01-30 13:59
Should we close this PR (works as intended)?

**Comment by SethTisue** [comment] 2020-01-30 15:26
> should we close this ticket (works as intended)?

agree. if you want something you know can't change, you should `to(collection.immutable.IndexedSeq)`

**Comment by dwijnand** [comment] 2020-01-30 17:35
> Should we close this ticket (works as intended)?

I say no, but only to use the ticket, as @julienrf says, to clearly document the behaviour.

Btw, it looks like it works nicely even when downcasting immutable collections:

```scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.6).
Type in expressions for evaluation. Or try :help.

scala> val xs: scala.collection.Seq[String] = List("foo")
xs: scala.collection.Seq[String] = List(foo)

scala> xs.to(scala.collection.immutable.Seq) eq xs
res0: Boolean = true

scala> val ys: scala.collection.Seq[String] = Vector("bar")
ys: scala.collection.Seq[String] = Vector(bar)

scala> ys.to(scala.collection.immutable.Seq) eq ys
res1: Boolean = true
```

**Comment by lrytz** [comment] 2020-01-31 08:29
Created a new ticket: https://github.com/scala/bug/issues/11872

**Closed by lrytz** 2020-01-31 08:29 UTC
Labels: library:collections
