### ISSUE TITLE
2.13 regression: "polymorphic expression cannot be instantiated to expected type"

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11537] opened 2019-05-16 09:04 UTC
This compiles on 2.12, but not on 2.13:

```scala
object t {
  def foo(a: String, b: collection.Seq[String]) = 0
  def foo(a: Int, b: collection.Seq[String]) = 1
}

t.foo(1, collection.Set("").toArray)
```

2.13 error:

```scala
scala> t.foo(1, collection.Set("").toArray)
                                   ^
       error: polymorphic expression cannot be instantiated to expected type;
        found   : [B >: String]Array[B]
        required: scala.collection.Seq[String]
```

Pulling `collection.Set("").toArray` into a local variable fixes it.

However, if `foo` is **not** overloaded, the example fails on both 2.12 and 2.13. Here's the error in 2.12:

```scala
scala> object t {
     |   def foo(a: Int, b: collection.Seq[String]) = 1
     | }

scala> t.foo(1, collection.Set("").toArray)
<console>:13: error: polymorphic expression cannot be instantiated to expected type;
 found   : [B >: String]Array[B]
 required: Seq[String]
       t.foo(1, collection.Set("").toArray)
                                   ^
```

**Comment by adriaanm** [comment] 2019-05-24 09:25
This is a consequence of the second argument now being typed with an expected type, since the types collapse. Once you eliminate that difference, it fails on 2.12 as well, as shown in the non-overloaded case, or even more distilled:

```
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> collection.Set("").toArray: collection.Seq[String]
<console>:12: error: polymorphic expression cannot be instantiated to expected type;
 found   : [B >: String]Array[B]
 required: Seq[String]
       collection.Set("").toArray: collection.Seq[String]

```


```
Welcome to Scala 2.13.0-RC2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> collection.Set("").toArray: collection.Seq[String]
                          ^
       error: polymorphic expression cannot be instantiated to expected type;
        found   : [B >: String]Array[B]
        required: scala.collection.Seq[String]
```

**Comment by adriaanm** [comment] 2019-05-24 09:33
I think this is actually a duplicate of https://github.com/scala/bug/issues/2394, dating from the last collection rewrite :-)

**Comment by SethTisue** [comment] 2023-07-23 01:57
#2394 was closed as wontfix, so, doing the same here.

**Closed by SethTisue** 2023-07-23 01:57 UTC
Labels: fixed in Scala 3
