### ISSUE TITLE
s.c.m.Buffer#append method is ambiguous

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11112] opened 2018-08-26 15:51 UTC
`scala.collection.mutable.Buffer` defines two `append` methods. One is single-arg, the other is var-arg. This means that you cannot call the single-arg version because it is ambiguous with a single-elem var-arg call.

the method definitions:
```scala
  @`inline` final def append(elem: A): this.type = addOne(elem)

  @deprecated("Use appendAll instead", "2.13.0")
  @`inline` final def append(elems: A*): this.type = addAll(elems)
```
an example error:
```
[error] /Users/joshlemer/IdeaProjects/scala2/src/library/scala/collection/immutable/ChampHashSet.scala:831: ambiguous reference to overloaded definition,
[error] both method append in trait Buffer of type (elems: Any*)hc.content.type
[error] and  method append in trait Buffer of type (elem: Any)hc.content.type
[error] match argument types (A)
[error]         hc.content.append(element)
[error]                    ^
```

**Comment by som-snytt** [comment] 2018-08-26 15:58
https://github.com/scala/bug/issues/11015

**Comment by joshlemer** [comment] 2018-09-02 14:42
Well, somehow this seems to work in 2.13.0-M5  
  
```scala
Welcome to Scala 2.13.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.mutable._
import scala.collection.mutable._

scala> ArrayBuffer(1,2,3).append(1)
res0: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(1, 2, 3, 1)

scala> ArrayBuffer(1,2,3).append(1,2,3)
warning: there was one deprecation warning (since 2.13.0); for details, enable `:setting -deprecation' or `:replay -deprecation'
res1: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(1, 2, 3, 1, 2, 3)

scala> ArrayBuffer(1,2,3).prepend(1)
res2: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(1, 1, 2, 3)

scala> ArrayBuffer(1,2,3).prepend(1,2,3)
warning: there was one deprecation warning (since 2.13.0); for details, enable `:setting -deprecation' or `:replay -deprecation'
res3: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(1, 2, 3, 1, 2, 3)
```

**Comment by som-snytt** [comment] 2018-09-02 19:44
It works when it doesn't infer `Any`. That is what changes the specificity test.

```
scala> ArrayBuffer[Any](1,2,3).append(1)
                               ^
       error: ambiguous reference to overloaded definition,
       both method append in trait Buffer of type (elems: Any*)scala.collection.mutable.ArrayBuffer[Any]
       and  method append in trait Buffer of type (elem: Any)scala.collection.mutable.ArrayBuffer[Any]
       match argument types (Int)
```
I think you didn't show what you were trying originally.

**Comment by szeiger** [comment] 2019-01-10 15:42
Duplicate of https://github.com/scala/bug/issues/11015

**Closed by szeiger** 2019-01-10 15:42 UTC
Labels: blocker, collections, library, varargs
