### ISSUE TITLE
StackOverflow in Typechecker

### ISSUE THREAD

**Issue by freddie-freeloader** [scala/bug#10446] opened 2017-08-02 10:15 UTC
I tried the following in 2.12.3:
```scala
def f(implicit x : Int) = x
def g(h: Int => Int) = h(42)
g(f _)
```

The compiler fails with this message:
```
java.lang.StackOverflowError
	at scala.reflect.internal.Symbols$TermSymbol.isClassConstructor(Symbols.scala:2818)
	at scala.reflect.internal.Symbols$TermSymbol.isConstructor(Symbols.scala:2820)
	at scala.tools.nsc.typechecker.Contexts$Context.nextOuter(Contexts.scala:615)
...
```

**Comment by lrytz** [comment] 2017-08-02 10:18
Probably a duplicate of #10279, checking that now. In that case it would be fixed by https://github.com/scala/scala/pull/5983.

**Comment by lrytz** [comment] 2017-08-02 10:18
Yep

**Comment by freddie-freeloader** [comment] 2017-08-02 10:19
Thanks for the quick response. :smile:

**Closed by lrytz** 2017-08-02 10:18 UTC
