### ISSUE TITLE
Private types can be inferred but not explicitly typed

### ISSUE THREAD

**Issue by ShaneDelmore** [scala/bug#10366] opened 2017-06-13 05:46 UTC
Two examples:
https://scastie.scala-lang.org/wdskxrQQRbeB2ZHkDdXaoA

And
```scala
package factory{
  private [factory] class Factory
  object Factory{
    def f(): factory.Factory = new Factory()
  }
}
object G {
 //type annotation fails to compile!
  val f: factory.Factory = factory.Factory.f()
}
```

**Comment by lrytz** [comment] 2017-06-13 08:15
For reference, in Java:

```java
public class A {
    private class B { public void m() { return; } }
    B b() { return new B(); }
}
class C {
    public int t() { (new A()).b().m(); }
}
```

gives
```
A.java:6: error: m() in A.B is defined in an inaccessible class or interface
    public int t() { (new A()).b().m(); }
                                  ^
1 error
```

**Comment by paulp** [comment] 2017-07-19 20:57
I've opened many other tickets about this. It will not be fixed.

**Comment by SethTisue** [comment] 2017-07-19 21:29
Duplicate of #6794

**Closed by SethTisue** 2017-07-19 21:29 UTC

**Comment by ShaneDelmore** [comment] 2017-07-20 14:51
@paulp Open and marked critical for 5 years now.  It may take me another 5 years to reconcile those facts.  The well linked history was entertaining at least.

**Comment by SethTisue** [comment] 2017-07-21 15:50
on the subject of "marked critical": https://github.com/scala/scala-dev/issues/406

**Comment by ShaneDelmore** [comment] 2017-07-22 04:27
@SethTisue Makes sense, thanks.

**Comment by som-snytt** [comment] 2021-07-20 09:34
@ShaneDelmore As of today, your 1-year clock is ticking on "It may take me another 5 years to reconcile those facts."

Duplicative of https://github.com/scala/bug/issues/1800

**Comment by joroKr21** [comment] 2021-07-20 11:35
I think #6794 has the most catchy title
