### ISSUE TITLE
[2.13.0-M4] IterableOnce#copyToArray should return number of elements written to Array

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11002] opened 2018-07-08 01:58 UTC
I would like to suggest that these three `copyToArray` methods on IterableOnce could return the number of elements written to the array passed in, rather than returning the array itself. My reasoning is that  

1) the number of elements written to the array is non-deterministic -- the IteratorOnce may run out of elements at any time. It doesn't seem very easy to determine which elements written to the array are actually newly written elements after the method returns since of course they all have the same type.

2) The caller of the method of course already has access to the Array[T], so not much is lost by not returning the array, except if anyone really wants to avoid assigning the array to an identifier.

The methods in question are:

https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/IterableOnce.scala#L645

https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/IterableOnce.scala#L673

**Comment by MasseGuillaume** [comment] 2018-07-08 19:33
looks like this bug: https://github.com/scala/bug/issues/8469

**Comment by Ichoran** [comment] 2018-07-08 21:49
Agreed.  Not knowing what you copied makes for an error-prone API.  If we don't provide an integer return value, we should do something else that allows the information to be gathered.

**Comment by SethTisue** [comment] 2018-07-10 19:29
duplicate of #8469

**Closed by SethTisue** 2018-07-10 19:29 UTC
Labels: collections
