### ISSUE TITLE
Execution context thread starvation

### ISSUE THREAD

**Issue by remk** [scala/bug#10810] opened 2018-03-29 10:08 UTC
If we run a batch of Future not in a blockcontext after a batch of Future in a blocking context,
with a batch size greater or equal  than the initial number of threads in the pool + 256. 
The second batch will be executed on a single thread.

The gist reproducing the issue. Tune it with your thread pool size.
https://gist.github.com/remk/afb869fc09b530cb076f9cf28adfb759

problem encountered on mac osx, with java "1.8.0_162" and "1.8.0_144" and Scala 2.12.4

**Comment by SethTisue** [comment] 2018-03-29 13:57
perhaps of interest to @viktorklang

**Comment by remk** [comment] 2018-03-29 14:07
the problem should be in scala.concurrent.impl.ExecutionContextImpl

**Comment by edmundnoble** [comment] 2018-03-30 23:37
Perhaps the fix to this is to stop encouraging blocking on the default `ExecutionContext`?

**Comment by NthPortal** [comment] 2018-03-31 10:10
I think, broadly, the problem is that a thread with a blocking task needs to spawn a new thread to "replace" itself while it blocks, and it doesn't do that.

I think it's possible that Java's FJP implementation already handles this, but `ExecutionContextImpl` breaks it by also tracking thread count itself, rather than leaving that to the underlying FJP. I need to do more investigation before saying that for certain though.

**Comment by NthPortal** [comment] 2018-03-31 20:06
@remk my point was that `reserveThread()` is itself the problem

**Comment by NthPortal** [comment] 2018-03-31 20:35
Probably related to #8955

**Comment by remk** [comment] 2018-04-01 08:59
I proposed a fix in #6484.

**Comment by NthPortal** [comment] 2018-04-02 04:14
@viktorklang Do they never get garbage collected?

**Comment by viktorklang** [comment] 2018-04-02 14:21
@NthPortal I'm currently AFK—please run my reproducer and check with jconsole.

**Comment by viktorklang** [comment] 2018-04-10 12:05
I have an isolated Java-only reproducer now, I'll send this to the concurrency-interest ML to see what they have to say on the matter.

~~~java
package test;

import java.time.Instant;
import java.util.function.Function;
import java.util.stream.Stream;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.ForkJoinWorkerThread;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

public final class Foo {

  public final static int MAX_THREADS = 128;
  public final static int MAX_BLOCKERS = 256;
  public final static int CORES = Runtime.getRuntime().availableProcessors();

  public static final class FJWTF extends AtomicInteger implements ForkJoinPool.ForkJoinWorkerThreadFactory {
    private final boolean allocate() {
       for(;;) {
         final int current = get();
         if (current == MAX_THREADS || current == Integer.MAX_VALUE) return false;
         else if (compareAndSet(current, current + 1)) return true;
       }
    }

    private final boolean deallocate() {
      for(;;) {
         final int current = get();
         if (current == 0) return false;
         else if (compareAndSet(current, current - 1)) return true;
       }
    }

    public ForkJoinWorkerThread newThread(final ForkJoinPool fjp) {
      if (allocate()) {
        final ForkJoinWorkerThread worker = new ForkJoinWorkerThread(fjp) {
          @Override public void onTermination(final Throwable cause) {
            try {
              deallocate();
            } finally {
              super.onTermination(cause);
            }
          }
        };
        return worker;
      } else return null;
    }
  };

  static String printAndGetTime(final String prefix, String name) {
    try {
    System.out.println("start " + prefix + " " + name);
    final Instant now = Instant.now();
    Thread.sleep(1000);
    final String res = "done " + prefix + " " + name + " : " + now;
    System.out.println(res);
    return res;
    } catch (final InterruptedException ie) {
      Thread.currentThread().interrupt();
      return "interrupted";
    }
  }

  static CompletableFuture<Void> generate(final int n, Function<String, CompletableFuture<String>> f) {
    return CompletableFuture.allOf(Stream.iterate(0, i -> i + 1).limit(n).map(String::valueOf).map(f).toArray(CompletableFuture[]::new));
  }

  static CompletableFuture<Void> managedBlockers(final int n, final ForkJoinPool fjp) {
    return generate(n, (String name) -> {
        return CompletableFuture.completedFuture("").thenApplyAsync(unused ->
            {
              try {
                ForkJoinPool.managedBlock(new ForkJoinPool.ManagedBlocker() {
                  @Override public boolean block() {
                    printAndGetTime("managed", name);
                    return true;
                  }
                  @Override public boolean isReleasable() { return false; }
                });
              } catch (final InterruptedException ie) {
                Thread.currentThread().interrupt();
              }
            return name;
          }, fjp);
      });
  }

  static CompletableFuture<Void> unmanagedBlockers(final int n, final ForkJoinPool fjp) {
    return generate(n, (String name) -> CompletableFuture.completedFuture("").thenApplyAsync(unused -> printAndGetTime("unmanaged", name), fjp));
  }

  public static void main(final String[] args) throws Exception {
    final ForkJoinPool fjp = new ForkJoinPool(CORES, new FJWTF(), (t, c) -> c.printStackTrace(System.err),true);
    final int n = CORES + MAX_BLOCKERS;

    CompletableFuture.completedFuture("").
      thenComposeAsync(unused -> managedBlockers(n,fjp), fjp).
      thenComposeAsync(unused -> unmanagedBlockers(n, fjp), fjp).
      get(100, TimeUnit.SECONDS);
  }
 
}
~~~

**Comment by viktorklang** [comment] 2018-04-11 15:14
Update: Doug's given a preliminary indication that this is unexpected behavior and possibly a bug.

**Comment by viktorklang** [comment] 2018-04-16 14:29
Possible fix: https://github.com/scala/scala/pull/6529/files

**Comment by dwijnand** [comment] 2018-07-16 09:23
Fixed in https://github.com/scala/scala/pull/6529, due in 2.12.7.

**Closed by dwijnand** 2018-07-16 09:23 UTC
Labels: concurrency, has PR
