### ISSUE TITLE
Cannot create an instance of the case class with some encoded field names

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/bug#10825] opened 2018-04-12 08:50 UTC
It looks like a bug in scalac and affects case classes which have 2 fields where name of one is a prefix for the another name that contains a character that should be encoded immediately after the prefix (like `o` and `o-o`).

For 2.11.12 I got a compilation error:
```
[error] scala.reflect.internal.Types$TypeError: type mismatch;
[error]  found   : Int
[error]  required: Seq
[error] 	at scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1402)
[error] 	at scala.tools.nsc.typechecker.Contexts$ContextReporter.issue(Contexts.scala:1254)
[error] 	at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:573)
[error] 	at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:106)
```

While in 2.12 it fails in the runtime during a call of the constructor:
```
java.lang.Integer cannot be cast to scala.collection.Seq
java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.collection.Seq
	at Publication.<init>(KebabFieldNameSpec.scala:3)
	at KebabFieldNameSpec.$anonfun$new$2(KebabFieldNameSpec.scala:8)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
```

Code to reproduce:
```
import org.scalatest.{Matchers, WordSpec}

case class Publication(title: String, author: String, `reference-count`: Int, reference: Seq[String])

class KebabFieldNameSpec extends WordSpec with Matchers {
  "Publication" should {
    "be created by the constructor" in {
      new Publication("", "", 0, Nil)
    }
  }
}
```

**Comment by hrhino** [comment] 2018-04-12 12:54
```scala
    // The constructor parameter with given name. This means the parameter
    // has given name, or starts with given name, and continues with a `$` afterwards.
    def parameterNamed(name: Name): Symbol = {
      def matchesName(param: Symbol) = param.name == name || param.name.startsWith(name + nme.NAME_JOIN_STRING) // nme.NAME_JOIN_STRING = "$"

      primaryConstrParams filter matchesName match {
        case Nil    => abort(name + " not in " + primaryConstrParams)
        case p :: _ => p
      }
```

More fallout from using `$` for everything name-y. This may hail from '06: scala/scala@cb7711db82c381848a6571047c68145e4f2d3c46.

**Comment by som-snytt** [comment] 2018-05-31 23:15
Another symptom https://github.com/scala/bug/issues/8831

**Comment by som-snytt** [comment] 2018-10-18 18:10
@hrhino should this and 10625 also be closed in favor of 8831 as an umbrella issue? Asking in case you understand any nuances. I haven't re-read the issues.

**Comment by hrhino** [comment] 2018-10-18 18:15
I'm not a very nuanced person. Re-rereading the issues, this is almost certainly a duplicate of #8831, and has the same root cause as #10625 (IIRC, if I remember `constructors`) but I don't feel confident saying, externally, that it's a duplicate. Not sure what the criteria for that are.

**Comment by hrhino** [comment] 2018-10-18 18:15
Also, what happened to the touted GitHub "duplicate of" feature from a few months ago? Did it get rebased away?

**Comment by som-snytt** [comment] 2018-10-18 18:49
I'll take a @hrhino "almost certainly" and "don't feel confident" any day. I think the issue that says "bizarre" always takes priority.

On github, it's easy to navigate between linked issues, so I won't try to copy/paste to #8831.

**Closed by som-snytt** 2018-10-18 18:49 UTC
Labels: name mangling, runtime crash, should compile

**Comment by dwijnand** [comment] 2019-05-13 09:28
Duplicate of #8831

**Comment by hrhino** [comment] 2019-10-26 01:46
Woah, I just noticed that when @dwijnand says "duplicate of #...", github listens!
