### ISSUE TITLE
False "match may not be exhaustive" warning in pattern matching

### ISSUE THREAD

**Issue by soronpo** [scala/bug#12377] opened 2021-04-20 10:06 UTC
## reproduction steps

using Scala 2.13.5,

```scala
val list : List[List[Int]] = List(1, 2, 3) match {
  case head :: Nil => List(List(head))
  case head :: tail :: Nil => List(List(head), List(tail))
  case head :: (mid :+ tail) => List(List(head), mid, List(tail))
  case Nil => List(List())
}
```

## problem

```
match may not be exhaustive.
It would fail on the following input: List(_, _, _)
val list : List[List[Int]] = List(1, 2, 3) match {
```

It's interesting to see that Scala 3 also (falsely) warns, but on different case `List(_, _, _, _*)`.
See https://github.com/lampepfl/dotty/issues/12155

**Comment by joroKr21** [comment] 2021-06-01 16:54
`(mid :+ tail)` -> the compiler doesn't know that this would match any non-empty list

**Comment by SethTisue** [comment] 2021-06-01 18:23
@dwijnand ?

**Comment by dwijnand** [comment] 2021-06-01 19:41
@joroKr21 is right - the match translates into:

```scala
  case ::(head, Nil) => List(List(head))
  case ::(head, ::(tail, Nil)) => List(List(head), List(tail))
  case ::(head, mid :+ tail) => List(List(head), mid, List(tail))
  case Nil => List(List())
```

And, because `:+` is a general extractor, it can't know that, given the `::(tail, Nil)` above, the extraction is irrefutable.

There's a bunch more cases like this and I've been working on addressing them with my "sealed types" SIP: https://contributors.scala-lang.org/t/sip-sealed-types/5082

(Not sure if to keep this issue open as evidence of the problem, or close it as "best we can do atm, pending SIP approval"...)

**Comment by SethTisue** [comment] 2021-06-01 19:48
working-as-designed

**Closed by SethTisue** 2021-06-01 19:48 UTC
Labels: patmat

**Comment by som-snytt** [comment] 2021-06-01 21:06
I would buy an "as designed" t-shirt. Bracketing the "working" part.
