### ISSUE TITLE
Scala 2.13.x import precedence not respected

### ISSUE THREAD

**Issue by rbarazzutti** [scala/bug#11617] opened 2019-07-07 23:01 UTC
Local classes should have precedence over classes imported with wildcards (as in Java)

Scala 2.10.x, 2.11.x, and 2.12.x are respecting this precedence and thus are behaving like Java.

Oppositely, Scala 2.13.x takes the class imported with a wildcard.

**Comment by NthPortal** [comment] 2019-07-07 23:08
duplicate of #11593?

**Comment by rbarazzutti** [comment] 2019-07-07 23:43
The release notes of Scala 2.13.0 mention the precedence of explicit imports, but not wildcards, it is somehow misleading.

Otherwise, thanks @NthPortal, it's a dup.

**Comment by som-snytt** [comment] 2019-07-08 04:55
Yes, it's not easy to summarize in a one-liner. (The summary is also misleading because it's kind of wrong.)

I'll try to transfer words from the linked ticket to an "overview" page in the docs. That may be useful later as a point of reference for Scala 3 import/export.

I also see that I proposed a lint option. Or maybe `--explain-imports` as a companion to `--explain-types`. After all, types are self-explanatory, but imports are magic.

**Closed by som-snytt** 2019-07-08 04:55 UTC

**Comment by SethTisue** [comment] 2019-07-08 18:33
I changed the release notes wording from "Explicit imports" to "Imports, including wildcard imports"

**Comment by som-snytt** [comment] 2019-07-08 18:43
I don't even know if that wording is less wrong :) but I did start an edit for an explanatory overview page. I got out my old copy of Odersky/the ScalaTest guy/Spoon please don't laugh at my name fail and noticed this facet of name binding is not addressed at all. I remembered the confusing chapter on nested packages and imports and Bob's love toys or whatever the example was.

Bill Venners. It just takes me a few minutes. I knew he was Bill, I was waiting for Venners.

It's kind of a name-binding pun.

**Comment by rbarazzutti** [comment] 2019-07-08 20:42
thanks, @som-snytt, and @SethTisue for these clarifications.
