### ISSUE TITLE
MethodSymbol fullName produce a wrong String

### ISSUE THREAD

**Issue by NoamShaish** [scala/bug#11674] opened 2019-08-11 08:17 UTC
Scala version: 2.12.8

reproduce:
```scala
scala> case class A(a: String)
defined class A

scala> :paste
// Entering paste mode (ctrl-D to finish)

import scala.reflect.runtime.universe._

def typeFields[T: TypeTag]: List[String] = typeOf[T].members.collect {
    case m: MethodSymbol if m.isCaseAccessor => m.fullName
  }.toList

// Exiting paste mode, now interpreting.

import scala.reflect.runtime.universe._
typeFields: [T](implicit evidence$1: reflect.runtime.universe.TypeTag[T])List[String]

scala> typeFields[A].map(_.toArray)
res0: List[Array[Char]] = List(Array($, l, i, n, e, 3, ., $, r, e, a, d, ., $, i, w, ., $, i, w, ., A, ., a))

scala> typeFields[A]
res1: List[String] = List(A.a)

scala> val expected: String = "A.a"
expected: String = A.a

scala> res1.contains(expected)
res2: Boolean = false
```

As you can see the resulting string if broken to Char array is different than the string presented by repl

**Comment by joroKr21** [comment] 2019-08-11 10:40
What happens if you `println(typeFields[A])`?

**Comment by hrhino** [comment] 2019-08-11 15:40
This is a REPL quirk: the result of `fullName` there is (correctly) `"$line3.$read.$iw.$iw.A.a"` due to the way that the REPL mangles the input code. Since that's likely to confuse users, the printing logic strips off all of the wrapper object names. 

I don't think there's a real bug here.

**Comment by SethTisue** [comment] 2019-08-11 15:47
duplicate of #9335

**Closed by SethTisue** 2019-08-11 15:47 UTC
