### ISSUE TITLE
Spurious warning in for expression

### ISSUE THREAD

**Issue by lambdista** [scala/bug#12018] opened 2020-05-28 16:39 UTC
## reproduction steps

using Scala 2.13.2,

```scala
$ scala -Wunused
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

val optA: Option[Int] = Option(42)
val optB: Option[Int] = Option(0)

val x1: Option[Int] = for {
  a <- optA
  b <- optB
  if a != b
} yield a


// Exiting paste mode, now interpreting.


  b <- optB
  ^
<pastie>:6: warning: parameter value b in anonymous function is never used
val optA: Option[Int] = Some(42)
val optB: Option[Int] = Some(0)
val x1: Option[Int] = Some(42)
```

## problem

It gives the warning because `b` is not used in yield. Still, it is used in `if a != b`. I guess that for comprehension is desugared more or less in:
```scala
optA.flatMap { a =>
  optB.withFilter(b => a != b).map(b => a)
}
```
Instead it should be desugared in the following one in order not to get the warning:
```scala
optA.flatMap { a =>
  optB.withFilter(b => a != b).map(_ => a)
}
```

**Comment by som-snytt** [comment] 2020-05-29 21:01
The umbrella issue https://github.com/scala/bug/issues/10287 

Similar to https://github.com/scala/bug/issues/11175 (different part of the desugared expression) and https://github.com/scala/bug/issues/11400 (in the map but refutable pattern).

Probably it's time to consolidate at https://github.com/scala/bug/issues/10287

**Comment by SethTisue** [comment] 2020-05-29 22:09
agreed, duplicate of #10287, feel free to add the code in question as a comment there

**Closed by SethTisue** 2020-05-29 22:09 UTC
