### ISSUE TITLE
CCE with enum value serialization, only with -Dpartest.exec.in.process

### ISSUE THREAD

**Issue by lrytz** [scala/bug#10909] opened 2018-05-28 09:24 UTC
Current 2.13.x, with a test re-enabled (was disabled in https://github.com/scala/scala/pull/6676/files#diff-e24063c0aa9e2f16a3cffeb86a736d90)

```
➜  scala13 git:(2.13.x) ✗ git diff | cat
diff --git a/test/files/run/enums.scala b/test/files/run/enums.scala
index b4e8e523db..164874634f 100644
--- a/test/files/run/enums.scala
+++ b/test/files/run/enums.scala
@@ -119,7 +119,7 @@ object SerializationTest {

   def run: Unit = {
     /* This is no longer possible with the proxy-based serialization for collections: */
-    //serialize(new B())
+    serialize(new B())
     serialize(new A())
   }
 }
```

```
➜  scala13 git:(2.13.x) ✗ sbt
> partest test/files/run/enums.scala --show-log
!! 1 - run/enums.scala                           [output differs]
java.lang.ClassCastException: cannot assign instance of scala.collection.generic.DefaultSerializationProxy to field SerializationTest$B.types of type scala.collection.immutable.Set in instance of SerializationTest$B
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2233)

> set (javaOptions in test in IntegrationTest) := (javaOptions in test in IntegrationTest).value.filterNot(_.contains("exec.in.process"))

> partest test/files/run/enums.scala
ok 1 - run/enums.scala
```

Compiling and running the test on the command line also succeeds. We should figure out what's going on here.

**Comment by szeiger** [comment] 2018-06-07 15:55
It's probably an instance of https://github.com/scala/bug/issues/9237. Running with `partest.exec.in.process` puts the test classes into a different ClassLoader than the standard library so you get circular dependencies between the classloaders on deserialization. When you run it standalone everything is in the same classloader.

**Comment by lrytz** [comment] 2018-06-08 06:54
Ah, that makes sense, thanks.

**Comment by szeiger** [comment] 2019-01-08 18:45
Closing as duplicate of https://github.com/scala/bug/issues/9237

**Closed by szeiger** 2019-01-08 18:45 UTC
Labels: collections, serialization
