### ISSUE TITLE
ListMap .updated order inconsistent between 2.12 & 2.13

### ISSUE THREAD

**Issue by japgolly** [scala/bug#11719] opened 2019-09-01 09:28 UTC
### Scala 2.12

```
> scala
Welcome to Scala 2.12.8 (OpenJDK 64-Bit GraalVM CE 19.2.0, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable._
import scala.collection.immutable._

scala> ListMap("a" -> 1, "b" -> 2).updated("a", 0)
res0: scala.collection.immutable.ListMap[String,Int] = ListMap(b -> 2, a -> 0)
```

### Scala 2.13

```
> scala
Welcome to Scala 2.13.0 (OpenJDK 64-Bit GraalVM CE 19.2.0, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable._
import scala.collection.immutable._

scala> ListMap("a" -> 1, "b" -> 2).updated("a", 0)
res0: scala.collection.immutable.ListMap[String,Int] = ListMap(a -> 0, b -> 2)
```

The results are in a different order, i.e. `ListMap(b -> 2, a -> 0)` ≠ `ListMap(a -> 0, b -> 2)`

**Comment by FabioPinheiro** [comment] 2019-09-01 16:40
This may be a inconsistent between Scala versions
But is not a bug and IMHO prefer the behavior of Scala 2.13

```
import scala.collection.immutable._
println(ListMap("a"-> 1, "b" -> 2, "c" -> 3).updated("b", 0))
```

Scala 2.12.8 will print `ListMap(a -> 1, c -> 3, b -> 0)`
Scala 2.13.0 will print `ListMap(a -> 1, b -> 0, c -> 3)`

ListMap does not infer anything about map order and the method `updated` is free to change the order (can be useful for optimizations). 
Maybe we should use TreeMap that implements SortedMap


btw in the mutable collection is inconsistent with the immutable collection
```
import scala.collection.mutable._

println(ListMap("a"-> 1, "b" -> 2, "c" -> 3).updated("b", 0))
```
Scala 2.12.8 will print `Map(b -> 0, c -> 3, a -> 1)`
Scala 2.12.8 will print `ListMap(b -> 0, c -> 3, a -> 1)` *
* `method updated in trait MapOps is deprecated (since 2.13.0): Use m.clone().addOne((k,v)) instead of m.updated(k, v)`
* `object ListMap in package mutable is deprecated (since 2.13.0): Use an immutable.ListMap assigned to a var instead of mutable.ListMap`

**Comment by som-snytt** [comment] 2019-09-02 03:52
It seems the concern about a breaking change was acknowledged on the [previous ticket](https://github.com/scala/bug/issues/11306).

TIL the mutable version has always been [afflicted](https://github.com/scala/bug/issues/9893), as [others already know](https://github.com/scala/scala/pull/3593).

The behavior was intended to be specified, but I'm not sure it is in the docs. I would expect language at `SeqMap`, that `updated` respects the initial insert order by key. The current phrase, "k-v pairs in the order they were first inserted" is ambiguous.

**Closed by som-snytt** 2019-09-02 03:52 UTC
Labels: good first issue, library:collections

**Comment by gaeljw** [comment] 2021-12-20 09:43
To anyone coming here, `TreeSeqMap` offers a ordering feature that can be chosen from `OrderBy.Insertion` or `OrderBy.Modification`.

**Comment by som-snytt** [comment] 2021-12-20 13:52
I'll update the doc per my previous comment, and improve:
```
returns

    A new map with the new key/value mapping added to this map. <invalid inheritdoc annotation>
```
There's also a comment about `TreeSeqMap` where `empty` must respect ordering, both the instance method (which is commented out because `MapFactoryDefaults` already works?) and the companion method. The `empty` bug was an "unused parameter" lint situation.
