### ISSUE TITLE
Implicit resolution regression in 2.13.x

### ISSUE THREAD

**Issue by Atry** [scala/bug#11068] opened 2018-08-11 15:50 UTC
``` scala
import scala.language.higherKinds
import scala.concurrent.Future

object Regression {
  
  trait Functor[F[_]]
  trait Monad[F[_]] extends Functor[F]
  trait MonadError[F[_], E] extends Monad[F]
  implicit def futureMonad: Monad[Future] = ???
  
  

  object OptionT extends OptionTInstances0 {
    implicit final def OptionTFunctor[F[_]](implicit F0: Functor[F]): Functor[({type T[A] = OptionT[F, A]})#T] = ???

  }

  sealed abstract class OptionTInstances0 {
    implicit final def OptionTMonadError[F[_]](implicit F0: Monad[F]): MonadError[({type T[A] = OptionT[F, A]})#T, Throwable] = ???

  }

  trait OptionT[F[_], A]

  def main(args: Array[String]): Unit = {

    def f = implicitly[Functor[({type T[A] = OptionT[Future, A]})#T]]

  }

}
```

* It compiles in Scala 2.12.6: https://scastie.scala-lang.org/ifY5zoUzQTO2qzmviNxv6g
* It does not compile in Scala 2.13.0-M4 https://scastie.scala-lang.org/5CenTZ5qRnSeE1tyhRUXfw

**Comment by SethTisue** [comment] 2018-08-11 17:09
is it reproducible without outside dependencies?

**Comment by xuwei-k** [comment] 2018-08-12 01:03
compile success if swap these `implicit def`. 

```diff
@@ -11,12 +11,12 @@
object Regression {
   
 
   object OptionT extends OptionTInstances0 {
-    implicit final def OptionTFunctor[F[_]](implicit F0: Functor[F]): Functor[({type T[A] = OptionT[F, A]})#T] = ???
+    implicit final def OptionTMonadError[F[_]](implicit F0: Monad[F]): MonadError[({type T[A] = OptionT[F, A]})#T, Throwable] = ???
 
   }
 
   sealed abstract class OptionTInstances0 {
-    implicit final def OptionTMonadError[F[_]](implicit F0: Monad[F]): MonadError[({type T[A] = OptionT[F, A]})#T, Throwable] = ???
+    implicit final def OptionTFunctor[F[_]](implicit F0: Functor[F]): Functor[({type T[A] = OptionT[F, A]})#T] = ???
 
   }
```

Some libraries encountered the same error (since Scala 2.13.0-M3)
- https://github.com/scalaz/scalaz/commit/2fdd887f536e17d59b586b93bf8639e5b84eccd9
- https://github.com/typelevel/kittens/commit/04394a8523f3d226c015057a11acf4e68380b582#diff-3bca8c4f5e0332228ddac09f73898b24R54

**Comment by xuwei-k** [comment] 2018-08-12 07:00
https://github.com/scalaz/scalaz/issues/1629

**Comment by joroKr21** [comment] 2018-09-28 06:27
MonadError is a subtype of Functor therefore this is not a bug but a bug fix! Granted, breaking change hence in 2.13

**Comment by barambani** [comment] 2018-10-01 12:37
I think I ran into this as well. So I guess that the instance summoned by
```scala
implicitly[Functor[({type T[A] = OptionT[Future, A]})#T]]
```
will be `MonadError`, correct ?

**Comment by joroKr21** [comment] 2018-10-01 14:06
> will be MonadError, correct ?

This example doesn't make much sense in practice. E.g. why would we say that `OptionT` has an instance of `MonadError` for `Throwable`? That seems wrong to me. Maybe for `Unit`, but how useful is that?

Anyway in this example, given that `Future` has a `Monad` instance then yes, `MonadError` will be selected as the `Functor` implementation.

**Comment by adriaanm** [comment] 2018-11-13 13:30
Closing since this is working as intended. Let us know if we should reopen.

**Closed by adriaanm** 2018-11-13 13:30 UTC
Labels: typer
