### ISSUE TITLE
High CPU load used by MurmurHash3

### ISSUE THREAD

**Issue by yanns** [scala/bug#12130] opened 2020-08-27 13:57 UTC
## reproduction steps

using Scala 2.13.3

## problem

We have several http servers running [sangria](https://github.com/sangria-graphql/sangria).
They receive a good amount of GraphQL requests.

Very rarely (it happened 2 times since the beginning of the year), one of the server is suddenly consuming a lot of CPU.
The flame graph almost always ends up in `MurmurHash3`:
![Screenshot 2020-08-27 at 15 52 36](https://user-images.githubusercontent.com/51669/91451124-6322c300-e87d-11ea-8822-4d69a0e1cc2d.png)

It's quite strange that only one server, only irregularly, has this issue.
I don't know if this information can be valuable for you.

**Comment by SethTisue** [comment] 2020-10-12 15:45
I'm going to close this since we don't have reproduction details. We can reopen if more information comes to light.

**Closed by SethTisue** 2020-10-12 15:45 UTC
