### ISSUE TITLE
2.13.2: Spurious octal literal warnings for ordinary `0` literal with -Woctal-literal

### ISSUE THREAD

**Issue by neko-kai** [scala/bug#11967] opened 2020-04-29 13:49 UTC
## reproduction steps

To reproduce execute:

```
git clone https://github.com/7mind/izumi.git
cd izumi
git checkout bug/octal-literal
sbt compile
```

## problem

A LOT of spurious warnings appear for ordinary, non-octal `0` literals, such as:

```scala
[warn] izumi/fundamentals/fundamentals-platform/src/main/scala/izumi/fundamentals/platform/strings/IzString.scala:103:26: Decimal integer literals should not have a leading zero. (Octal syntax is obsolete.)
[warn]     else if (s.length == 0) ""
```

## expectation

Expected no octal literal warnings

**Comment by lrytz** [comment] 2020-04-29 14:10
This is a duplicate of https://github.com/scala/bug/issues/11950, already fixed in 2.13.x :)

**Closed by lrytz** 2020-04-29 14:10 UTC
