### ISSUE TITLE
Pattern matching in for loop does not type-check

### ISSUE THREAD

**Issue by Atry** [scala/bug#10440] opened 2017-07-31 08:51 UTC
``` scala
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> val myList = List(Some(1), None)
myList: List[Option[Int]] = List(Some(1), None)

scala> for (some @ (_: Some[Int]) <- myList) {
     |   println(some)
     | }
<console>:13: error: type mismatch;
 found   : Some[Int] => Unit
 required: Option[Int] => ?
       for (some @ (_: Some[Int]) <- myList) {
                                  ^
```

**Comment by milessabin** [comment] 2017-07-31 12:04
Duplicate of https://github.com/scala/bug/issues/900.

**Closed** 2017-07-31 19:58 UTC
