### ISSUE TITLE
false positive "you must write the annotation class in Java" warning in "sbt doc"

### ISSUE THREAD

**Issue by scabug** [scala/bug#10134] opened 2017-01-03 07:54 UTC
A.scala

```scala
object A
```

Row.java

```scala
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface Row {
  String value() default "";
}
```

build.sbt

```scala
scalaVersion := "2.12.1"
```

execute "sbt doc" 

```scala
[warn] Row.java:5: Implementation restriction: subclassing Classfile does not
[warn] make your annotation visible at runtime.  If that is what
[warn] you want, you must write the annotation class in Java.
[warn] public @interface Row {
[warn]                   ^
model contains 3 documentable templates
[warn] one warning found
[info] Main Scala API documentation successful.
```

**Comment by KarelCemus** [comment] 2017-09-05 07:30
Affects also Scala 2.12.3

**Comment by missingfaktor** [comment] 2019-03-04 17:38
Is there a workaround for this bug?

**Comment by eed3si9n** [comment] 2020-06-14 18:23
This seems to have been fixed in Scala 2.12.9.

```
sbt:hello> ++2.12.8!
[info] Forcing Scala version to 2.12.8 on all projects.
[info] Reapplying settings...
[info] Set current project to hello (in build file:/private/tmp/hello/)
sbt:hello> clean
[success] Total time: 0 s, completed Jun 14, 2020 1:13:18 AM
sbt:hello> doc
[info] Main Scala API documentation to /private/tmp/hello/target/scala-2.12/api...
[warn] /private/tmp/hello/Row.java:5:19: Implementation restriction: subclassing Classfile does not
[warn] make your annotation visible at runtime.  If that is what
[warn] you want, you must write the annotation class in Java.
[warn] public @interface Row {
[warn]                   ^
model contains 4 documentable templates
[warn] one warning found
[info] Main Scala API documentation successful.
[success] Total time: 3 s, completed Jun 14, 2020 1:13:24 AM
sbt:hello> ++2.12.9!
[info] Forcing Scala version to 2.12.9 on all projects.
[info] Reapplying settings...
[info] Set current project to hello (in build file:/private/tmp/hello/)
sbt:hello> clean
[success] Total time: 0 s, completed Jun 14, 2020 1:13:29 AM
sbt:hello> doc
[info] Main Scala API documentation to /private/tmp/hello/target/scala-2.12/api...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.9. Compiling...
[info]   Compilation completed in 9.998s.
model contains 4 documentable templates
[info] Main Scala API documentation successful.
```

I can't tell which of the changes in https://github.com/scala/scala/releases/tag/v2.12.9 had the intentional or unintentional effect of fixing this, but I'd vote to close it.

**Comment by lrytz** [comment] 2020-06-15 07:12
👍

Any volunteer for a regression test PR? I hope the infrastructure is in place to do scaladoc tests with mixed Java/Scala sources.

**Comment by SethTisue** [comment] 2020-12-04 03:14
there doesn't appear to be any such infrastructure. see remarks on https://github.com/scala/scala/pull/9250 . closing since it doesn't seem worth adding infrastructure over

**Closed by SethTisue** 2020-12-04 03:14 UTC
Labels: annotations, good first issue, has PR, help wanted, scaladoc tool
