### ISSUE TITLE
SortedMap regression in 2.13

### ISSUE THREAD

**Issue by Taig** [scala/bug#11637] opened 2019-07-16 18:10 UTC
I'm seeing a lot of crashes after updating to 2.13 that are related to the use of `immutable.SortedMap`. The crashes usually occur when the application has been running for a few minutes so I haven't been able to come up with a reproducible example yet, but will add information as I find out more.

```
java.lang.NullPointerException
	at scala.collection.immutable.RedBlackTree$.joinRight(RedBlackTree.scala:660)
	at scala.collection.immutable.RedBlackTree$.joinRight(RedBlackTree.scala:660)
	at scala.collection.immutable.RedBlackTree$.joinRight(RedBlackTree.scala:660)
	at scala.collection.immutable.RedBlackTree$.join(RedBlackTree.scala:690)
	at scala.collection.immutable.RedBlackTree$.doTake(RedBlackTree.scala:278)
	at scala.collection.immutable.RedBlackTree$.take(RedBlackTree.scala:85)
	at scala.collection.immutable.TreeMap.take(TreeMap.scala:217)
	at scala.collection.immutable.TreeMap.take(TreeMap.scala:73)
        ...
```

```
java.lang.RuntimeException: Defect: invariance violation
	at scala.collection.immutable.RedBlackTree$.balRight(RedBlackTree.scala:610)
	at scala.collection.immutable.RedBlackTree$.delRight$1(RedBlackTree.scala:576)
	at scala.collection.immutable.RedBlackTree$.del(RedBlackTree.scala:580)
	at scala.collection.immutable.RedBlackTree$.delLeft$1(RedBlackTree.scala:573)
	at scala.collection.immutable.RedBlackTree$.del(RedBlackTree.scala:579)
	at scala.collection.immutable.RedBlackTree$.delRight$1(RedBlackTree.scala:577)
	at scala.collection.immutable.RedBlackTree$.del(RedBlackTree.scala:580)
	at scala.collection.immutable.RedBlackTree$.delete(RedBlackTree.scala:72)
	at scala.collection.immutable.TreeMap.removed(TreeMap.scala:130)
	at scala.collection.immutable.TreeMap.removed(TreeMap.scala:73)
	at scala.collection.immutable.MapOps.$minus(Map.scala:77)
	at scala.collection.immutable.MapOps.$minus$(Map.scala:77)
	at scala.collection.immutable.AbstractMap.$minus(Map.scala:483)
	...
```

```
java.lang.RuntimeException: Defect: invariance violation
	at scala.collection.immutable.RedBlackTree$.balLeft(RedBlackTree.scala:603)
	at scala.collection.immutable.RedBlackTree$.delLeft$1(RedBlackTree.scala:573)
	at scala.collection.immutable.RedBlackTree$.del(RedBlackTree.scala:579)
	at scala.collection.immutable.RedBlackTree$.delLeft$1(RedBlackTree.scala:573)
	at scala.collection.immutable.RedBlackTree$.del(RedBlackTree.scala:579)
	at scala.collection.immutable.RedBlackTree$.delRight$1(RedBlackTree.scala:576)
	at scala.collection.immutable.RedBlackTree$.del(RedBlackTree.scala:580)
	at scala.collection.immutable.RedBlackTree$.delete(RedBlackTree.scala:72)
	at scala.collection.immutable.TreeMap.removed(TreeMap.scala:130)
	at scala.collection.immutable.TreeMap.removed(TreeMap.scala:73)
	at scala.collection.immutable.MapOps.$minus(Map.scala:77)
	at scala.collection.immutable.MapOps.$minus$(Map.scala:77)
	at scala.collection.immutable.AbstractMap.$minus(Map.scala:483)
	...

```

**Comment by lrytz** [comment] 2019-07-17 07:01
Marking as a blocker, this needs to be investigated.

**Comment by SethTisue** [comment] 2019-07-18 20:31
@Taig any progress on isolating this...?

**Comment by Taig** [comment] 2019-07-18 21:59
No, sorry. I kept observing the crashes, but it was always one of the three stacktraces I already shared. I tried to recreate it in a potentially similar scenario only using `take` and `remove` but had no luck unfortunately. The crashes happen minutes, sometimes hours after the app started performing hundreds of thousands of these operations but I did not manage to get behind what the cause of this is exactly.

In the meantime I had to go back to 2.12.

**Comment by Taig** [comment] 2019-07-19 10:09
I still didn't get behind what exact code path triggers this, but I managed to come up with a scalacheck test that reproduces one of the errors:

```
import org.scalacheck.Gen
import org.scalatest.FlatSpec
import org.scalatest.Matchers._
import org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks._

import scala.collection.immutable.SortedMap

class TakeCrash extends FlatSpec {
  "SortedMap" should "crash" in {
    forAll(Gen.listOfN(100000, Gen.posNum[Int])) { items =>
      items.zipWithIndex.foldLeft(SortedMap.empty[Int, String]) {
        case (collection, (key, index)) if index % 2 == 0 =>
          (collection + (key -> "foobar")).take(10)
        case (collection, (key, _)) => (collection - key).take(10)

      }.size should be <= 10
    }
  }
}
```

```
[info] TakeCrash:
[info] SortedMap
[info] - should crash *** FAILED ***
[info]   RuntimeException was thrown during property evaluation.
[info]     Message: Defect: invariance violation    
[info]     Occurred when passed generated values (
[info]       arg0 = List(18, 0, 0, -1, 3, -1, 4, 1, 1, -1, 11, -1, 14, -1, -1, -3, 2, -2, 17, 14, 9, -3, 15, 0, 16, 11, 11, 1, 12, 4, 0, 11) // 88 shrinks
[info]     )
[info] ScalaTest
[info] Run completed in 599 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

**Comment by lrytz** [comment] 2019-07-19 10:14
Nice, you beat me to it, I was also trying to get a reproducer with scalacheck :-)

**Comment by Taig** [comment] 2019-07-19 10:19
It's kinda tricky. As far as I can tell the combination of `+`, `-` and `take` is crucial here. When removing any of those operations the error goes away. The reproducer is very ajar to my failing production code.

**Comment by lrytz** [comment] 2019-07-19 10:56
So the reproducer:

```
import scala.collection.immutable.SortedMap

val l = List(18, 0, 0, -1, 3, -1, 4, 1, 1, -1, 11, -1, 14, -1, -1, -3, 2, -2, 17, 14, 9, -3, 15, 0, 16, 11, 11, 1, 12, 4, 0, 11)
l.zipWithIndex.foldLeft(SortedMap.empty[Int, String]) {
  case (collection, (key, index)) if index % 2 == 0 =>
    (collection + (key -> "foobar")).take(10)
  case (collection, (key, _)) => (collection - key).take(10)
}
```

Anyone working on this, maybe post a note here to avoid duplicating efforts.

**Comment by szeiger** [comment] 2019-07-30 12:56
I'll take a look.

**Comment by szeiger** [comment] 2019-07-30 17:18
The problem is in `RedBlackTree.take`. Starting with a `null` tree, the following sequence of operations reproduces it:

```scala
      RB.update(_, 18, null, overwrite = false),
      RB.update(_, 0, null, overwrite = false),
      RB.update(_, 3, null, overwrite = false),
      RB.update(_, 4, null, overwrite = false),
      RB.update(_, 1, null, overwrite = false),
      RB.update(_, 11, null, overwrite = false),
      RB.update(_, 14, null, overwrite = false),
      RB.update(_, -1, null, overwrite = false),
      RB.update(_, 2, null, overwrite = false),
      RB.update(_, 17, null, overwrite = false),
      RB.delete(_, 14),
      RB.update(_, 9, null, overwrite = false),
      RB.update(_, 15, null, overwrite = false),
      RB.take(_, 10),
```

The `take` call produces the following invalid tree (with two nested RedTrees on top of each other):

BlackTree(3, null, BlackTree(1, null, BlackTree(0, null, RedTree(-1, null, null, null), null), BlackTree(2, null, null, null)), BlackTree(9, null, BlackTree(4, null, null, null), BlackTree(11, null, null, RedTree(15, null, null, RedTree(17, null, null, null)))))

All invariants still hold before this call.

**Comment by lrytz** [comment] 2019-07-31 07:38
I checked the same sequence in 2.12, since we're close to releasing 2.12.9, and we're fine there. Here's the output:

BlackTree(3, (), BlackTree(1, (), BlackTree(0, (), RedTree(-1, (), null, null), null), BlackTree(2, (), null, null)), BlackTree(11, (), BlackTree(4, (), null, RedTree(9, (), null, null)), BlackTree(15, (), null, RedTree(17, (), null, null))))

**Comment by szeiger** [comment] 2019-07-31 10:56
I wouldn't expect any problems in 2.12. This is one of the methods I reimplemented with a more efficient algorithm for .2.13.

**Closed** 2019-08-05 14:41 UTC
Labels: blocker, has PR, library:collections, regression
