### ISSUE TITLE
[2.13.9] `productIterator` change to case classes breaks bincompat if the class is also a value class

### ISSUE THREAD

**Issue by adamw** [scala/bug#12650] opened 2022-09-23 17:00 UTC
MiMA reports the following error when trying to update to 2.13.9, for value classes:

```scala
[error] core: Failed binary compatibility check against com.softwaremill.sttp.model:core_2.13:1.5.2! Found 2 potential problems
[error]  * extension static method productIterator$extension(java.lang.String)scala.collection.Iterator in class sttp.model.Method does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("sttp.model.Method.productIterator$extension")
[error]  * extension method productIterator$extension(java.lang.String)scala.collection.Iterator in object sttp.model.Method does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("sttp.model.Method.productIterator$extension")
```

this is for a value case class:

```scala
case class Method(method: String) extends AnyVal
```

is this something that can be safely ignored?

**Comment by som-snytt** [comment] 2022-09-23 17:09
I think it is not safe.

Reported at https://github.com/lightbend/mima/issues/723

**Comment by adamw** [comment] 2022-09-23 17:10
Oh thanks! I'll close this one as it is clearly a duplicate :)

**Comment by som-snytt** [comment] 2022-09-23 17:21
I'll probably need a ticket over here...

**Comment by adamw** [comment] 2022-09-23 17:26
Ah sure, sorry, reopening then ;)

**Comment by som-snytt** [comment] 2022-09-23 17:42
```
➜ scalac -d /tmp value.scala
➜ scalac -d /tmp -cp /tmp valuation.scala
➜ scala -cp /tmp Test
hello, world
➜ skalac -d /tmp value.scala  # recompile the case class
➜ scala -cp /tmp Test
Exception in thread "main" java.lang.NoSuchMethodError: 'scala.collection.Iterator Value$.productIterator$extension(java.lang.String)'
        at C.f(valuation.scala:4)
```
where `scalac` is 2.13.8 and `skalac` is 2.13.9 and
```
➜ cat value.scala

case class Value(s: String) extends AnyVal
➜ cat valuation.scala

class C {
  def f() =
    Value("hello, world").productIterator.foreach(println)
}

object Test extends App {
  new C().f()
}
```

**Comment by SethTisue** [comment] 2022-09-23 17:56
In addition figuring out how to address the issue itself, we should also give a little thought to whether our overall testing regimen could have or should have caught this.

**Comment by som-snytt** [comment] 2022-09-23 17:59
For convenience, copying my comment

A case class extending AnyVal had product methods:
```
  public static java.lang.String productElementName$extension(java.lang.String, int);
  public static scala.collection.Iterator<java.lang.Object> productIterator$extension(java.lang.String);
  public static java.lang.Object productElement$extension(java.lang.String, int);
  public static int productArity$extension(java.lang.String);
  public static java.lang.String productPrefix$extension(java.lang.String);
  public scala.collection.Iterator<java.lang.String> productElementNames();
  public java.lang.String productPrefix();
  public int productArity();
  public java.lang.Object productElement(int);
  public scala.collection.Iterator<java.lang.Object> productIterator();
  public java.lang.String productElementName(int);
```
where productElementNames lacks an extension method and would therefore always box.

Now productIterator also lacks an $extension method for some reason. (Presumably, the reason is that methods inherited from a trait don't get the value class treatment.)

Product extends Any is a universal trait.

**Comment by som-snytt** [comment] 2022-09-23 18:08
Worth noting that we had considered binary compatibility in the PR for case classes, but value classes did not appear on the radar.

Sometimes a bytecode diff is performed to witness any changes in output; it would be a bit much to attempt that on CB scala; but one could imagine a modest set of classes in test to validate diffs in bytecode (not only for compatibility).

**Comment by som-snytt** [comment] 2022-09-23 18:56
To confirm, the SIP specifically excludes inherited members. https://docs.scala-lang.org/sips/value-classes.html

It is cold comfort that Scala 3 does not generate `productIterator` for case classes.

**Comment by mkurz** [comment] 2022-09-26 09:50
If this is getting fixed, how long until Scala 2.13.10?

**Comment by lrytz** [comment] 2022-09-26 10:54
I think we should do 2.13.10 very soon to avoid (too many) releases built with 2.13.9 to make their way into the wild.

Should we keep this ticket open to make it easier to find?

**Comment by armanbilge** [comment] 2022-09-26 12:34
> I think we should do 2.13.10 very soon to avoid (too many) releases built with 2.13.9 to make their way into the wild.

Can we trust MiMa to catch all instances of this? Or should we avoid releasing projects on 2.13.9 altogether?

**Comment by lrytz** [comment] 2022-09-26 19:46
If you're using MiMa you should be safe - modulo unknowns, of course...

**Comment by SethTisue** [comment] 2022-09-29 19:23
> I think we should do 2.13.10 very soon

There's now a thread to discuss release contents and timing: https://contributors.scala-lang.org/t/scala-2-13-10-release-planning/5943

**Comment by SethTisue** [comment] 2022-10-08 14:54
> Should we keep this ticket open to make it easier to find?

Closing now since we'll be releasing soon, and since we've done a bunch of publicity about the regression in various venues (GitHub release notes, Discourse, Twitter, etc)

**Closed** 2022-10-08 14:53 UTC
Labels: has PR, regression, blocker
