### ISSUE TITLE
macro Context typecheck fails to detect co/contravariance issues in class declarations

### ISSUE THREAD

**Issue by McBrainy** [scala/bug#10865] opened 2018-05-06 22:05 UTC
In a whitebox or blackbox macro with `c: Context`, `c.typecheck(c.parse("class Foo[+A](var a: A)"))` fails to detect the covariant type in invariant position. I would expect it to report a type error, but instead it returns without error. Here is a REPL session that illustrates this:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

import scala.language.experimental.macros
import scala.reflect.macros.blackbox.Context // Or whitebox

def fooImpl(c: Context): c.Expr[Unit] = {
  c.typecheck(c.parse("class Foo[+A](var a: A)"))
  // Or: import c.universe._; c.typecheck(q"class Foo[+A](var a: A)")
  ???
}

def foo: Unit = macro fooImpl

// Exiting paste mode, now interpreting.

import scala.language.experimental.macros
import scala.reflect.macros.blackbox.Context
fooImpl: (c: scala.reflect.macros.blackbox.Context)c.Expr[Unit]
defined term macro foo: Unit

scala> foo
<console>:15: error: exception during macro expansion:
scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
        at .fooImpl(<console>:16)

       foo
       ^
```

As you can see, evaluation reaches `???` instead of throwing an exception at `typecheck`. However, the class `Foo` doesn't typecheck (and shouldn't):
```scala
scala> class Foo[+A](var a: A)
<console>:13: error: covariant type A occurs in contravariant position in type A of value a_=
       class Foo[+A](var a: A)
                         ^
```

Some other things `typecheck` falsely thinks are okay:
```scala
class Foo[-A](val a: A)  // Contravariant type in covariant position
case class Foo[-A](a: A)  // Also contravariant type in covariant position
class Foo[-A](var a: A)  // Contravariant type in invariant position
trait Foo[+A] { def bar(a: A) }  // Covariant type in contravariant position
```

**Comment by hrhino** [comment] 2018-05-07 01:53
This is a duplicate of #8724, from back in 2014. The macro `typecheck` method only runs the typechecker; variance checks (and others, see that ticket) are done later on in the `refchecks` phase, which the macro framework doesn't run.

If you want a somewhat gnarly workaround (for the scalatest issue), you can try using `c.eval` on that tree, which compiles it into an in-memory filesystem, loads, and runs it. A possible enhancement to support this sort of use case would be to expose `ToolBox`'s `compile` method as well as its `eval` method to macro users.

**Closed** 2018-05-07 01:53 UTC
Labels: duplicate

**Comment by hrhino** [comment] 2018-05-07 01:56
To elaborate by way of example:

```scala
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_161).
Type in expressions for evaluation. Or try :help.

scala> :power
Power mode enabled. :phase is at typer.
import scala.tools.nsc._, intp.global._, definitions._
Try :help or completions for vals._ and power._

scala> val ctx = analyzer.macroContext(typer, EmptyTree, Ident(NoSymbol))
ctx: $r.intp.global.analyzer.MacroContext = MacroContext(<none>@NoPosition +0)

scala> ctx.eval(ctx.Expr(q"""class Foo[+A](var a: A)"""))
scala.tools.reflect.ToolBoxError: reflective compilation has failed:

covariant type A occurs in contravariant position in type A of value a_=
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:320)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:202)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:256)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.$anonfun$compile$13(ToolBoxFactory.scala:433)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:359)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:426)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:448)
  at scala.reflect.macros.contexts.Evals.eval(Evals.scala:20)
  at scala.reflect.macros.contexts.Evals.eval$(Evals.scala:14)
  at scala.reflect.macros.contexts.Context.eval(Context.scala:6)
  ... 32 elided
```

**Comment by McBrainy** [comment] 2018-05-08 03:53
Thanks, Harrison. `eval` should be good enough for my use case.
