### ISSUE TITLE
"never used" warning in for comprehension with filter even though variable is used

### ISSUE THREAD

**Issue by gaeljw** [scala/bug#12050] opened 2020-06-23 08:30 UTC
## reproduction steps

Using Scala 2.12.11 (with `Ywarn-unused...` and `-Xfatal-warnings` flags),

```scala
def getA(): Future[String] = ???
def getB(a: String): Future[Int] = ???

for {
  a <- getA() if a == "foo"
  b <- getB(a) if b == 0
} yield a
```

```
Error:(28, 7) parameter value b in value $anonfun is never used
      b <- getB(a) if b == 0
```

## problem

Hi

I believe the above piece of code which triggers the "never used" warning should not.
Am I right or am I missing something?

I didn't try on 2.13 yet.

**Comment by SethTisue** [comment] 2020-06-23 13:03
duplicate of #11175 which we consolidated under #10287

**Closed by SethTisue** 2020-06-23 13:03 UTC
