### ISSUE TITLE
ScalaRunTime.replStringOf(immutable.Queue.empty[Int], 1000) return "Queue.EmptyQueue()"

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10303] opened 2017-05-08 08:26 UTC
should be return `Queue()` instead of `Queue.EmptyQueue()` ?

2.12.0-M5

```
Welcome to Scala 2.12.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.immutable.Queue.empty[Int]
res0: scala.collection.immutable.Queue[Int] = Queue()

scala> println(scala.collection.immutable.Queue.empty[Int])
Queue()

scala> scala.collection.immutable.Queue[Int]()
res2: scala.collection.immutable.Queue[Int] = Queue()
```

2.12.0-RC1

```
Welcome to Scala 2.12.0-RC1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.immutable.Queue.empty[Int]
res0: scala.collection.immutable.Queue[Int] = Queue.EmptyQueue()

scala> println(scala.collection.immutable.Queue.empty[Int])
Queue()

scala> scala.collection.immutable.Queue[Int]()
res2: scala.collection.immutable.Queue[Int] = Queue()
```

**Comment by som-snytt** [comment] 2017-05-08 21:25
The difference is probably in picking apart the name in

https://github.com/scala/scala/commit/44971d104f4364a0ddaa4f05afc4cc61ee39cdf7

which I am too lazy to pick apart.

The daughter is home from school; I kind of wish I'd taken her to the morning matinee of Guardians of the Galaxy instead.

**Comment by atiqsayyed** [comment] 2017-06-04 17:24
@som-snytt I wanted to work on it, how do i reproduce it?..  i tried reproducing it from master, it works as expected..

**Comment by som-snytt** [comment] 2017-06-04 22:49
@atiqsayyed +1

There is no master branch.

```
$ ./build/pack/bin/scala
Welcome to Scala 2.13.0-20170530-172738-1521e00 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> import runtime._, collection._
import runtime._
import collection._

scala> ScalaRunTime.replStringOf(immutable.Queue.empty[Int], 1000)
res0: String =
"Queue.EmptyQueue()
"
```

**Comment by SethTisue** [comment] 2017-06-04 22:59
2.12.x branch, same. this could be fixed for 2.12.x, no need to wait for 2.13

**Comment by SethTisue** [comment] 2017-06-04 23:01
note that `scala` is also the name of an sbt task, so

```text
% sbt
...
[info] *** Welcome to the sbt build definition for Scala! ***
...
> scala
...
Welcome to Scala 2.12.3-20170530-235421-bd6294d ...
...

scala> scala.collection.immutable.Queue.empty[Int]
res0: scala.collection.immutable.Queue[Int] = Queue.EmptyQueue()
```

**Comment by som-snytt** [comment] 2017-06-04 23:01
Also, my previous comment maybe points to an irrelevant commit, I didn't look closely.

I did just mention to my French friend who gave me a copy of the book, apropos of TraversableLikeTest:

So we have nom de plume. I guess nom de classe is like "Count of Montecristo", an alias you assume to enter a different social class.

**Comment by som-snytt** [comment] 2017-06-04 23:02
And it was really gauche of me to inline my +1. Corrected.

**Comment by atiqsayyed** [comment] 2017-06-05 11:15
@som-snytt 
I've found the issue, it's because in `scala.collection.immutable.Queue` didn't override `stringPrefix` method..
I've fixed it, but I wanted to know should I add test for such scenario, if yes we may also have to do it for other classes overriding `stringPrefix`

**Comment by SethTisue** [comment] 2017-06-15 21:42
> should I add test for such scenario

it's not really worth adding a test just for the one class, and the fix shouldn't be held up by a demand to add testing for this collections-library-wide, either. merged.

**Closed** 2017-06-15 21:44 UTC
Labels: collections, help wanted, quickfix
