### ISSUE TITLE
StringContext.unapplySeq slays 2.13 compiler

### ISSUE THREAD

**Issue by mslinn** [scala/bug#11605] opened 2019-07-02 15:55 UTC
`StringContext.unapplySeq` works for the happy case:

```scala
scala> "Hello, James" match {
  case s"Hello, $name" => println(s"Greeted $name")
  case x => println(s"Could not parse '$x'")
}
Greeted James
```

When `StringContext.unapplySeq` fails the compiler explodes:

```
scala> "Goodbye, James" match {
   case s"Hello, $name" => println(s"Greeted $name")
   case x => println(s"Could not parse '$x'")
}
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:632)
        at scala.None$.get(Option.scala:631)
        at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.<init>(MacroRuntimes.scala:65)
        at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:50)
        at scala.collection.mutable.MapOps.getOrElseUpdate(Map.scala:149)
        at scala.collection.mutable.MapOps.getOrElseUpdate$(Map.scala:146)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:260)
        at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:50)
        at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:43)
        at scala.tools.nsc.Global$$anon$5.standardMacroRuntime(Global.scala:482)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:455)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:452)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:452)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:452)
        at scala.tools.nsc.Global$$anon$5.pluginsMacroRuntime(Global.scala:482)
        at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:37)
        at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:37)
        at scala.tools.nsc.Global$$anon$5.macroRuntime(Global.scala:482)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:559)
        at scala.tools.nsc.Global.withInfoLevel(Global.scala:225)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:553)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:540)
        at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:715)
        at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:713)
        at scala.tools.nsc.Global$$anon$5.standardMacroExpand(Global.scala:482)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:439)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:436)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:436)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:436)
        at scala.tools.nsc.Global$$anon$5.pluginsMacroExpand(Global.scala:482)
        at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:704)
        at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:697)
        at scala.tools.nsc.Global$$anon$5.macroExpand(Global.scala:482)
        at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1213)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1278)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5881)
        at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3414)
        at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgWithFormal$1(PatternTypers.scala:115)
        at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.$anonfun$typedArgsForFormals$4(PatternTypers.scala:129)
        at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals(PatternTypers.scala:129)
        at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals$(PatternTypers.scala:110)
        at scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:209)
        at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3722)
        at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3773)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$27(Typers.scala:4864)
        at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:715)
        at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4864)
        at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4948)
        at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4959)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5821)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
        at scala.tools.nsc.typechecker.Typers$Typer.typedCase(Typers.scala:5942)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedCases$1(Typers.scala:2622)
        at scala.tools.nsc.typechecker.Typers$Typer.typedCases(Typers.scala:2621)
        at scala.tools.nsc.typechecker.Typers$Typer.typedMatch(Typers.scala:2633)
        at scala.tools.nsc.typechecker.Typers$Typer.typedVirtualizedMatch$1(Typers.scala:4653)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5800)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5831)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
        at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5942)
        at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1121)
        at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1713)
        at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1884)
        at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1848)
        at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:938)
        at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2033)
        at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2031)
        at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2026)
        at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1544)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1517)
        at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1691)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5466)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2050)
        at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1925)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5776)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2050)
        at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1925)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5776)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2050)
        at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1925)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5776)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5475)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5778)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1510)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1494)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:704)
        at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:895)
        at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:493)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:487)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:470)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:930)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$interpretStartingWith$3(ILoop.scala:950)
        at scala.tools.nsc.interpreter.shell.ReplCompletion.withPartialInput(ReplCompletion.scala:28)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:940)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$interpretStartingWith$3(ILoop.scala:950)
        at scala.tools.nsc.interpreter.shell.ReplCompletion.withPartialInput(ReplCompletion.scala:28)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:940)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$interpretStartingWith$3(ILoop.scala:950)
        at scala.tools.nsc.interpreter.shell.ReplCompletion.withPartialInput(ReplCompletion.scala:28)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:940)
        at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:787)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:462)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:485)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:1019)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:102)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:107)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
```

**Comment by dwijnand** [comment] 2019-07-02 16:30
Duplicate of #11564

**Closed by dwijnand** 2019-07-02 16:30 UTC
