### ISSUE TITLE
PartialFunction$Combined.isDefinedAt throws an exception when the first function throws

### ISSUE THREAD

**Issue by federico-caimi-rally** [scala/bug#12426] opened 2021-07-06 12:44 UTC
## reproduction steps
```scala
val f1: PartialFunction[Integer, Nothing] = { case _: Integer => throw new RuntimeException("f1 blew up") }
val f2: PartialFunction[Integer, Nothing] = { case _: Integer => throw new RuntimeException("f2 blew up") }
f1.andThen(f2).isDefinedAt(3)
```
Using Scala 2.11.12, the last line returns `true`

Using Scala 2.13.6, the last line throws the first exception (`java.lang.RuntimeException: f1 blew up`)

## problem
The behavior of `isDefinedAt` across versions is inconsistent. 
Given that with both Scala versions `f1.isDefinedAt(3)` and `f2.isDefinedAt(3)` return true, I think that returning true is the correct result.

**Comment by SethTisue** [comment] 2021-07-06 15:55
see https://github.com/scala/scala/pull/7263 — I suspect we will close this as "working as designed", but take a look and see what you think

**Comment by SethTisue** [comment] 2021-07-06 16:14
I understand the desire to have a mental model of `isDefinedAt` where its behavior depends only on whether a matching `case` exists. But the path through `f1.andThen(f2)` doesn't involve only left-hand sides. To even reach `f2`, the value must go through `f1`, including `f1`'s right-hand side. Hence the failure.

**Comment by dwijnand** [comment] 2021-07-06 16:17
Yeah, you could say that `isDefinedAt` is throwing because the partial function is implemented with non-total RHS.

**Comment by Jasper-M** [comment] 2021-07-06 16:39
Indeed, as Seth explains `f2.isDefinedAt(3)` returning true is irrelevant here. We're dealing with `f2.isDefinedAt(throw new RuntimeException("f1 blew up"))`.

**Comment by som-snytt** [comment] 2021-07-06 18:49
Thanks, I had missed the previous change, which has an interesting discussion.

I found dubious the follow-up to make `f.andThen(g)` work the same if g is actually a pf, but that's really because PF should be the parent of Function.

The class doc for PF does not mention applyOrElse. I'll try to PR a rewrite that foregrounds it. IIRC this came up before, when applyOrElse was improved; pedagogically, the instinct is to say `PF adds isDefinedAt` like you're supposed to be calling it all the time. I wonder how the latest PiS book talks about it.

Otherwise, I agree with everyone's intuition that OMG no one told me not to use isDefinedAt all the time. Maybe the bad part is efficiency, or multiple evaluations, I don't know what else. Oh, if it throws anyway, does that mean it wasn't defined at after all?

**Comment by federico-caimi-rally** [comment] 2021-07-06 18:59
I think that the arguments above make sense, and that the code that let me to expose this change in behavior needs to change anyway, but what confuses me the most is the following:
```
val f1: PartialFunction[Integer, Nothing] = { case _: Integer => throw new RuntimeException("f1 blew up") }
val f2: Integer => Nothing = (_: Integer) => throw new RuntimeException("f2 blew up")
f1.andThen(f2).isDefinedAt(3)
```

The above returns true. `isDefinedAt` only throws the exception if f2 is also a partial function. This looks like an inconsistency that should be addressed, unless there is an explanation that is escaping me ;)

**Comment by som-snytt** [comment] 2021-07-06 19:21
@federico-caimi-rally Quickly before I forget: that is the converse of what I thought was dubious.

For `f.andThen(g)`, `isDefinedAt` means `f.isDefinedAt` and also `g.isDefinedAt(f(x))`. But if the second condition is trivially true, as it is for a putatively total function, you only need to check `f.isDefinedAt`.

If PF were the parent type, then it would always do both checks. `isDefinedAt` for a function would either be true or maybe try/catch of apply. (Just guessing.)

**Comment by lrytz** [comment] 2021-07-07 08:36
Nothing to add, thanks everyone.

**Closed by lrytz** 2021-07-07 08:36 UTC
Labels: library
