### ISSUE TITLE
TypeError in case class with member name in back ticks

### ISSUE THREAD

**Issue by jarosmpost** [scala/bug#12389] opened 2021-05-03 16:52 UTC
I receive an compiler error with the following code:

```scala
case class Abc(`abc-def`: String, abc: Long)

object Test {
  def main(args: Array[String]): Unit = println(Abc("123", 123L))
}
``` 

**Scala 2.11.13 produces:** 
> scala.reflect.internal.Types$TypeError: type mismatch;
>  found   : String
>  required: Long

**Scala 2.12.13 produces:**
> java.lang.ClassCastException:` java.lang.String cannot be cast to java.lang.Long

**Work around:**
Switch the order of the the members in the case class:

```scala
case class Abc(abc: Long, `abc-def`: String)

object Test {
  def main(args: Array[String]): Unit = println(Abc(123L, "123"))
}
```

**Comment by SethTisue** [comment] 2021-05-03 17:04
duplicate of #8831?

**Comment by som-snytt** [comment] 2021-05-04 01:30
Like the man says.

I was gonna add that it's too bad REPL prints:
```
Abc(123,123)
```
instead of
```
Abc("123", 123L)
```
Compiler messaging should add, "Thank-you for using L for Long!"

**Closed by som-snytt** 2021-05-04 01:30 UTC

**Comment by jarosmpost** [comment] 2021-05-04 07:00
This is a duplicate of https://github.com/scala/bug/issues/8831

That seems like a bug of the harder kind. Is there a chance that the fix in 2.13 will be ported back to 2.11 and 2.12 or do I have to live with the work around?

**Comment by Jasper-M** [comment] 2021-05-04 10:53
Backporting to 2.12.x might make sense. Let's give it a shot scala/scala#9607

**Comment by SethTisue** [comment] 2021-05-04 13:33
(And we no longer do 2.11.x releases.)
