### ISSUE TITLE
Scala 2.13.5 has false warning for match exhaustive check.

### ISSUE THREAD

**Issue by counter2015** [scala/bug#12358] opened 2021-03-11 10:47 UTC
## reproduction steps

using Scala (2.13.5),

```scala
Welcome to Scala 2.13.5 (OpenJDK 64-Bit Server VM, Java 11.0.9.1).
Type in expressions for evaluation. Or try :help.

scala> def test(xs: Option[List[Int]]): Int = {
     |  xs match {
     |      case Some(Nil) | None => 0
     |      case Some(l) if l.nonEmpty => l.length
     |  }
     | }
       	xs match {
       	^
On line 2: warning: match may not be exhaustive.
       It would fail on the following input: Some(List(_))
def test(xs: Option[List[Int]]): Int

scala> test(Some(List(2)))
val res0: Int = 1

scala> test(Some(List()))
val res1: Int = 0

scala> test(None)
val res2: Int = 0
```

## problem

In scala 2.13.3 it works well.
```scala
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 11.0.9.1).
Type in expressions for evaluation. Or try :help.

scala> def test(xs: Option[List[Int]]): Int = {
     |  xs match {
     |      case Some(Nil) | None => 0
     |      case Some(l) if l.nonEmpty => l.length
     |  }
     | }
def test(xs: Option[List[Int]]): Int

scala> test(Some(List(2)))
val res0: Int = 1

scala> test(Some(List()))
val res1: Int = 0

scala> test(None)
val res2: Int = 0
```

It seems that statements after `if` cant be considered fully. For example, in 2.13.5
```scala
scala> def t2(xs: List[Int]): Int = {
     |  val b = xs.length > 1
     |  xs match {
     |      case x if b => 1
     |     case x if !b => 2
     |  }
     | }
       	xs match {
       	^
On line 3: warning: match may not be exhaustive.
def t2(xs: List[Int]): Int
```

**Comment by joroKr21** [comment] 2021-03-11 10:59
You don't need `if l.nonEmpty` - it's only making it impossible for the compiler to know that it's exhaustive.

**Comment by counter2015** [comment] 2021-03-11 11:03
@joroKr21 I see what you mean, but I wonder why in 2.13.3 it doesn't raise warning. 

Or it's just getting more stricter?

**Comment by joroKr21** [comment] 2021-03-11 11:06
2.13.3 only raises a warning if it knows for sure you didn't cover all cases.
Whereas 2.13.5 raises a warning if it doesn't know for sure that you did cover all cases.
It's a subtle difference but there are cases in between (like yours) - you covered all cases, but the compiler doesn't know.

**Comment by dwijnand** [comment] 2021-03-11 11:33
What @joroKr21 said.  To push the reasoning a little further: there's nothing that forces `Nil`'s `nonEmpty` to (always) return false, so there's nothing at the type-level (which is the source of truth for the exhaustivity checker) that guarantees that {Nil, nonEmpty} is a complete set of patterns for all lists.

Your `if b`/`if !b` is great because it's the perfect trivial case, but starting to analyse/interpret expressions at compile-time is going to very quickly get very complex IMO.

Closing as this is the exhaustivity checker working as designed.

**Closed by dwijnand** 2021-03-11 11:33 UTC
