### ISSUE TITLE
Type inference not working for `Nothing`

### ISSUE THREAD

**Issue by hseeberger** [scala/bug#10657] opened 2017-12-15 16:00 UTC
``` scala
object Test {

  final class Foo[A]

  def foo[A](f: A => Foo[A]): Foo[A] =
    ???

  // This does compile
  val fooBaz1: Foo[String] =
    foo(_ => new Foo)

  // This does compile,
  // but having to give the type argument to foo sucks
  val fooBaz2: Foo[Nothing] =
    foo[Nothing](_ => new Foo)

  // This does not compile
  val fooBaz3: Foo[Nothing] =
    foo(_ => new Foo)
}
```

Here's the quite hard to understand error message:
```
[error]  found   : Nothing => Test.Foo[Nothing]
[error]  required: A => Test.Foo[A]
```

**Comment by som-snytt** [comment] 2017-12-16 04:34
To be fair, nobody wants to work for nothing.

**Comment by hseeberger** [comment] 2017-12-16 08:48
Well, you and me wouldn‘t, but in Akka Typed there is a good use case: Root actors which shouldn‘t handle any message.

**Comment by milessabin** [comment] 2017-12-18 08:49
Duplicate of: https://github.com/scala/bug/issues/9453. I'd love to fix this.

**Closed** 2017-12-19 00:32 UTC
Labels: duplicate
