### ISSUE TITLE
False positive in for comprehension

### ISSUE THREAD

**Issue by fmeriaux** [scala/bug#11186] opened 2018-10-02 12:27 UTC
Hello, in 2.12.7, this warning appear: 

```
[warn] /Users/(..)/Constraint.scala:189:9: parameter value endDate in value $anonfun is never used
[warn]         endDate ← Checks.getDateTime(data, end, endFormat)
[warn]         ^
[warn] one warning found
```

code:

```scala
 def check(data: JsObject)(implicit failures: FailureBuffer): Unit = {
      for {
        beginDate ← Checks.getDateTime(data, start, startFormat)
        endDate ← Checks.getDateTime(data, end, endFormat)
        if beginDate.isAfter(endDate)
      } yield Checks.failWith(failure)
    }
```
PS:  `Checks.getDateTime` returns `Option[DateTime]`

scalac option `-Ywarn-unused:params`.

**Comment by hrhino** [comment] 2018-10-02 13:38
looks like a duplicate of #11175

**Closed** 2018-10-02 13:39 UTC
Labels: duplicate
