### ISSUE TITLE
`:type` widens `23`

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11786] opened 2019-10-30 03:02 UTC
Probably expected the precise type:

```
$ scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.3).
Type in expressions for evaluation. Or try :help.

scala> val x: 23 = 23
x: 23 = 23

scala> :type x
Int
```

**Comment by chuchao333** [comment] 2019-11-22 19:57
I had a look and wanted to take this as my first one to contribute to scala; however, I think this is not specific to `:type` command, but a general issue about the inferrer of literal type?

```scala
scala> val x: 23 = 23
val x: 23 = 23

scala> val y = x
val y = x
val y: Int = 23
```

**Comment by som-snytt** [comment] 2019-11-22 20:34
`:help` says it prints the type of the expression, but it would be nice if the command also just printed the type of the element named by the simple identifier.

`print-tab` displays actual and not inferred:
```
scala> x //print
   x // : Int(23)
```
hypothetically:
```
scala> :type x
Int // : Int(23)
```

**Comment by chuchao333** [comment] 2019-11-23 03:06
@som-snytt sorry, I didn't get what's your proposal above.

But according to the literal type SIP: https://docs.scala-lang.org/sips/42.type.html, the type would only be inferred when there is an upper bound to `Singleton`, otherwise the type would be widen.

the `:type` command's impl just tries to 'type' a 'def' of the command's input, thus won't get the expected literal type.

@retronym (as you are shown as the "get in touch" for REPL), do you see a potential fix for this in REPL?

**Comment by som-snytt** [comment] 2019-11-23 03:50
I'm suggesting change `:type` to do the obvious thing. Or, as shown, add the more specific info.

It's reasonable to want tooling to tell me what I can assign to `y`:

```
scala> val x: 23 = 23
x: 23 = 23

scala> def f[A <: Singleton](a: A): A = a
f: [A <: Singleton](a: A)A

scala> f(x)
res0: x.type = 23

scala> val y: 23 = x
y: 23 = 23

scala> val y: 23 = f(x)
y: 23 = 23

scala> :type f(x)
Int
```
Another possible feature: `:type` puts you in a mode where REPL output always shows you the tree type as in `print-tab`. Or a `:print` mode.
```
scala> :type

scala> f(23)
res2: Int = 23 // : 23

scala> :print 

scala> f(23)
res2: Int = 23 // f[23](23) : 23
```

**Comment by SethTisue** [comment] 2019-11-24 04:34
hmm. at the time I threw “good first issue” on this, I hadn't yet understood that this is already working-as-designed.

`:type` operates on expressions; as an expression, `x`'s type is `Int`, except in contexts where a singleton type is already expected, just as `23`'s type is `Int`, not `23`, unless a singleton type is already expected.

so, as covered in the other comments above, there is a design question here and the best answer is unclear.

I'm going to remove the label, but not because I would necessarily oppose any change.

**Comment by eed3si9n** [comment] 2019-11-24 21:43
When did power mode stop making beep boop whir sound?

```scala
$ scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> val x: 23 = 23
x: 23 = 23

scala> :type x
Int

scala> :power
Power mode enabled. :phase is at typer.
import scala.tools.nsc._, intp.global._, definitions._
Try :help or completions for vals._ and power._

scala> intp.typeOfTerm("x")
res0: $r.intp.global.Type = => 23
```

In any case, it seems to know that `x` is typed to something 23, so that's promising.

**Comment by eed3si9n** [comment] 2019-11-24 22:24
Here's my attempt at this. Not sure if it's a "good first" but it was a good kata for Scala dojo - https://github.com/scala/scala/pull/8553

**Comment by chuchao333** [comment] 2019-11-25 04:16
@eed3si9n left a comment in your PR; as mentioned, your fix seems quite limited to me.

after poking around the implementation of 'literal type', I think I found a reasonable work around of this:
https://github.com/scala/scala/blob/3444ad1532e7acb8d428586d0f4bef7379327bbd/src/compiler/scala/tools/nsc/typechecker/Namers.scala#L1111

from the above: the use of final on a val definition could help to infer an unwidened type, then we could try to 'type' on a 'final val' of the type command's input, instead of a 'def'

```scala
diff --git a/src/repl/scala/tools/nsc/interpreter/ExprTyper.scala b/src/repl/scala/tools/nsc/interpreter/ExprTyper.scala
index ed808c56d6..ef2b9ec463 100644
--- a/src/repl/scala/tools/nsc/interpreter/ExprTyper.scala
+++ b/src/repl/scala/tools/nsc/interpreter/ExprTyper.scala
@@ -18,7 +18,7 @@ trait ExprTyper {
   val repl: IMain
 
   import repl._
-  import global.{ phase, Symbol, Type, exitingTyper, NoSymbol, NoType, NoPrefix, TypeRef, WildcardType }
+  import global.{ phase, Symbol, Type, exitingTyper, NoSymbol, NoType, NoPrefix, TypeRef, WildcardType, SingleType }
   import naming.freshInternalVarName
   import global.definitions.{ MaxFunctionArity, NothingTpe }
 
@@ -40,7 +40,21 @@ trait ExprTyper {
         case Success =>
           val sym0 = symbolOfTerm(name)
           // drop NullaryMethodType
-          sym0.cloneSymbol setInfo exitingTyper(sym0.tpe_*.finalResultType)
+          sym0.cloneSymbol setInfo exitingTyper {
+            val tp = sym0.tpe_*
+            if (tp.resultType.isTrivial) {
+              // when we know it's safe to to use a 'final val' to represent the expression so that we could
+              // get the non-widen type by interpreting the 'code' again
+              val name1  = freshInternalVarName()
+              val line1 = "final val " + name1 + " = " + code
+              doInterpret(line1) match {
+                case Success =>
+                  val sym1 = symbolOfTerm(name1)
+                  sym1.cloneSymbol.tpe_*.finalResultType
+                case _ => tp.finalResultType
+              }
+            } else tp.finalResultType
+          }
         case _          => NoSymbol
       }
     }
```

I have tried the fix, this worked for both cases below:

```
scala> val x: 23 = 23
val x: 23 = 23

scala> :type x
23

scala> :type (23: 23)
23
```

Please let me know your thoughts, I can submit the pr if no objections.

**Comment by eed3si9n** [comment] 2019-11-25 04:21
@chuchao333

> Please let me know your thoughts, I can submit the pr if no objections.

My thought is that you should go for it :)

**Comment by chuchao333** [comment] 2019-11-25 04:26
@eed3si9n cool, thanks! I will just shamelessly take your tests :)

**Comment by som-snytt** [comment] 2019-11-25 07:06
@eed3si9n 
```
$ scala -Dscala.repl.power.banner=classic 
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> :power
** Power User mode enabled - BEEP WHIR GYVE **
** :phase has been set to 'typer'.          **
** scala.tools.nsc._ has been imported      **
** global._, definitions._ also imported    **
** Try  :help, :vals, power.<tab>           **
```

**Comment by lrytz** [comment] 2019-11-25 08:19
I'm a bit late to the party, but I feel like wideing is the right thing to do here.

If we change it for literals, it would be pretty inconsistent to keep widening singletons; however, making `:type x` say `x.type` is quite obviously undesired. Also, who's going to ask the type of a literal in real life? That's definitely not a game-changer.

So IMO, `:type x` should give the same type that's assigned to `y` in `val y = x`.

**Comment by eed3si9n** [comment] 2019-11-25 15:11
> So IMO, `:type x` should give the same type that's assigned to `y` in `val y = x`.

[SLS 6.26.4 Local Type Inference](https://scala-lang.org/files/archive/spec/2.12/06-expressions.html#local-type-inference) explicitly rules out inference of singleton types, so it's lossy by design.

The middle ground solution that @chuchao333 took is interesting, which could be paraphrased as: `:type x` should give the same type that's assigned to `y` in `final val y = x`.

```scala
scala> val x: 23 = 23
x: 23 = 23

scala> val y = x
y: Int = 23

scala> final val y = x
y: 23 = 23
```

After all `:type` is supposed to display the type of expression (as opposed to the type that Scala would infer if given as LHS).

**Comment by lrytz** [comment] 2019-11-25 21:02
So the only difference would be in `:type e` where `e` is a literal, or something that the compiler can constant-fold into a literal. I don't see the value in adding code and investing time to change this - maybe I'm missing something?

**Comment by som-snytt** [comment] 2019-11-25 22:47
I remember the ticket was motivated by something someone said on gitter, but I've forgotten the context. Maybe if I correlate the ticket create time with gitter history...

On the `private[this]` thread, I wanted to make a joke about `private[23]`, but I guess I'll joke about it here instead.

**Comment by chuchao333** [comment] 2019-11-26 22:58
I still think it would make more sense if the `:type` command could give the literal type when it's trying to type an expression to a `final val`, which is consistent with compiled code, so I updated my PR a bit to reflect that:

```scala
scala> :type 42
Int

scala> val x: 23 = 23
val x: 23 = 23

scala> :type x
23

scala> val y = x
val y: Int = 23

scala> :type y
Int

scala> final val z = x
val z: 23 = 23

scala> :type z
23

scala> def xx: 23 = 23
def xx: 23

scala> :type xx
Int

scala> final val yy = xx
val yy: 23 = 23

scala> :type yy
23
```

Please let me know if I should proceed with this. @som-snytt changed it so that it also won't force evaluation when it shouldn't.

**Comment by lrytz** [comment] 2019-11-27 08:31
OK, what I was missing is that it's about changing `:type x` to show the type that was actually assigned to the symbol `x`, not about changing `:type 23` to `23`. I agree this is an improvement.

**Closed** 2020-01-14 11:55 UTC
Labels: repl
