### ISSUE TITLE
Lambda doesn't have a runtime class symbol

### ISSUE THREAD

**Issue by tribbloid** [scala/bug#11828] opened 2019-12-16 02:04 UTC
The following code is written in scalatest, if you are interested in reproducing it in plain code please just use the code in `it("can reflect lambda") {}`:

```
import org.scalatest.FunSpec

class RuntimeMirrorSpike extends FunSpec {

  import org.apache.spark.sql.catalyst.ScalaReflection.universe._

  it("can reflect lambda") {

    val ll = { v: String =>
      v.toInt
    }

    val clazz = ll.getClass
    val mirror = runtimeMirror(clazz.getClassLoader)

    val sym = mirror.classSymbol(clazz)

    print(sym)
  }
}
```

This simple runtime reflection code used to work in scala 2.11, but now in scala 2.12 it generates a very general error:

```
assertion failed: no symbol could be loaded from class <...>.spike.RuntimeMirrorSpike$$Lambda$124/78204644 in package spike with name RuntimeMirrorSpike$$Lambda$124/78204644 and classloader sun.misc.Launcher$AppClassLoader@18b4aac2
java.lang.AssertionError: assertion failed: no symbol could be loaded from class <...>.spike.RuntimeMirrorSpike$$Lambda$124/78204644 in package spike with name RuntimeMirrorSpike$$Lambda$124/78204644 and classloader sun.misc.Launcher$AppClassLoader@18b4aac2
    at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala1(JavaMirrors.scala:1061)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$classToScala$1(JavaMirrors.scala:1019)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:130)
    at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:50)
    at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:46)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:128)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:1019)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:231)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:68)
```

Ideally it should maintain consistency with 2.11, or throw a `scala.reflect.ScalaReflectionException`, depending on how would you encourage this kind of usage.

Personally I prefer to have every JVM object to have a runtime classSymbol. This is OOP convention.

**Comment by SethTisue** [comment] 2019-12-16 03:43
At minimum, I agree that the error could be improved.

Are you familiar with how lambdas are represented in Java 8? Scala 2.12 represents its lambdas the same way. It's very different than the representation 2.11 used, by design.

Rather than being surprised that no class symbol is available in 2.12, I'm at least somewhat surprised that a symbol was available in 2.11, since there isn't a corresponding symbol in the source code. I assume it's because in the 2.11 scheme, the lambda's class must be synthesized at compile time, causing a symbol to be created. But in the 2.12/Java8 representation, the class is something spun up at runtime by the lambda metafactory in the JVM. So it seems natural to me that it would have no corresponding symbol.

Also, class symbols are something highly specific to Scala reflection in particular. I don't understand what the argument is for claiming that "OOP convention" requires a class symbol to exist in this case?

What's your use case for wanting the symbol, what is your real goal?

**Comment by tribbloid** [comment] 2019-12-18 03:40
I'm trying to construct a TypeTag/Type dynamically for an object of which type or class is unknown during compile time. If inferring from classSymbol is impossible there must be a better way, as I'm very sure that scala Type can well represent a lambda or anonymous class:

```
    val ll = { v: String =>
      v.toInt
    }

    def sniff[T](v: T)(implicit ev: TypeTag[T]) = ev.tpe.toString

    val ss = sniff(ll)

    print(ss)
```

This is indeed not an 'OOP convention', but a contract of type erasure:

"type erasure is the load-time process by which explicit type annotations are removed from a program"

This implies that the type of any object should always be visible in runtime, maybe in a more generic format. There is nothing in JVM that has a class but doesn't have a type, and mapping from class to type should be surjectory.

If scala compiler & reflection is designed in a way that type has nothing to do with class, then there should be a strong reason to do so

**Comment by SethTisue** [comment] 2019-12-18 05:12
> the type of any object should always be visible in runtime

this way of speaking is imprecise and full of pitfalls. every value conforms to many types, there is no "the" type

here's what the runtime gives us to work with:

```
scala 2.13.1> ll.getClass.getSuperclass.toString
res52: String = class java.lang.Object

scala 2.13.1> ll.getClass.getInterfaces
res54: Array[Class[_]] = Array(interface scala.Function1, interface java.io.Serializable)

scala 2.13.1> mirror.classSymbol(ll.getClass.getInterfaces.head)
res55: reflect.runtime.universe.ClassSymbol = trait Function1
```

there's the `ClassSymbol` you asked for; does this help?

note that I had to make an arbitrary choice of which answer I preferred to receive, `Function1` or `Serializable`

in your `implicit ev: TypeTag[T]` example, yes the compiler does infer a particular type for `T`, but the compiler has information at compile-time that doesn't exist anymore at runtime.

I'm closing the ticket since this is an open-ended discussion, not a bug report; it believe that everything here is working as designed.

we can keep discussing if you like; but if you want to propose a different design, you'd likely get a broader audience on https://contributors.scala-lang.org

**Closed by SethTisue** 2019-12-18 05:12 UTC
Labels: reflection

**Comment by tribbloid** [comment] 2019-12-18 18:27
No problem, but it's supposed to be the easiest way ever:

```
    val ll = new AnyRef with Function1[String, Int] with Serializable {

      override def apply(v: String) = v.toInt
    }

    val clazz = ll.getClass
    val mirror = runtimeMirror(clazz.getClassLoader)

    val sym = mirror.classSymbol(clazz)

    print(sym)
```

output: `$anon`

see, easy :)

I hope it could be equally easy in runtime, otherwise from a programming perspective it feels like I'm only allow to use constant, not variable for any Type information. Java never had this problem: The concept of class works equally easy in compilion or runtime/reflection

**Comment by SethTisue** [comment] 2019-12-18 18:55
> Java never had this problem: The concept of class works equally easy in compilion or runtime/reflection

Java 8 changed things for both Scala _and_ Java, it seems to me:

```
public class J {
  public static void main(String[] argv) {
    java.util.function.Function<Object, String> f = (x) -> x.toString();
    System.out.println(f.getClass());
    System.out.println(f.getClass().getSuperclass());
    System.out.println(f.getClass().getInterfaces()[0]);
  }
}
```

prints

```
class J$$Lambda$1/531885035
class java.lang.Object
interface java.util.function.Function
```

note especially `class java.lang.Object` in the second line, just as in Scala

**Comment by tribbloid** [comment] 2019-12-18 19:35
Wow that's a good point, I wasn't even aware that JVM support spinning up new classes (otherwise shapeless feels redundant: why making a generic product when you can have a real product?)

In the meantime, I think your code just demonstrated exactly that Java reflection doesn't have this problem: no weird exception or assertion error was thrown, Function interface `>:>` the runtime class, no surprise.

And as you suggested, let's carry out the discussion on the contributor's forum:

https://contributors.scala-lang.org/t/is-it-normal-that-lambda-not-having-any-class-symbol/3880
