### ISSUE TITLE
Scaladoc 2.12 does not show subpackages of a package in the main pane

### ISSUE THREAD

**Issue by sjrd** [scala/bug#10397] opened 2017-06-30 14:23 UTC
For example, at https://www.scala-js.org/api/scalajs-library/1.0.0-M1/index.html, all I see in the main pane is "package root". It's not very informative, and quite disturbing not to see anything below. I have to use the right column to navigate to subpackages.

Scaladoc 2.11 handled this nicely, and displayed subpackages together with other term members of a package. For example: https://www.scala-js.org/api/scalajs-library/0.6.18/#scala.scalajs.package

I would consider this a regression wrt. Scaladoc 2.11.

**Comment by SethTisue** [comment] 2018-06-12 02:36
duplicate of https://github.com/scala/bug/issues/10749 (which is a newer ticket, but it attracted more discussion than this one, so I'm closing this one)

**Closed by SethTisue** 2018-06-12 02:36 UTC
Labels: scaladoc tool
