### ISSUE TITLE
scalac fail with java.lang.AssertionError: assertion failed: mkAttributedQualifier(triplet.type, <none>)

### ISSUE THREAD

**Issue by tribbloid** [scala/bug#10636] opened 2017-11-30 08:12 UTC
When compiling a large Scala project, Scala compiler fail with the following error (and no reason of compilation failure).

The error was triggered by [this file](https://github.com/tribbloid/spookystuff/blob/scala-error/uav/src/main/scala/com/tribbloids/spookystuff/uav/spatial/point/PointViewBase.scala)

```
Exception in thread "main" java.lang.AssertionError: assertion failed: mkAttributedQualifier(triplet.type, <none>)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:89)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:62)
	at scala.reflect.internal.TreeGen.mkAttributedRef(TreeGen.scala:122)
	at scala.reflect.internal.TreeGen.mkAttributedStableRef(TreeGen.scala:161)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:79)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:62)
	at scala.reflect.internal.TreeGen.mkAttributedRef(TreeGen.scala:122)
	at scala.reflect.internal.TreeGen.mkAttributedStableRef(TreeGen.scala:161)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:79)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:62)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:597)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:579)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:448)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:898)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:926)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:983)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1372)
	at scala.tools.nsc.typechecker.Implicits$class.inferImplicit(Implicits.scala:73)
	at scala.tools.nsc.Global$$anon$1.inferImplicit(Global.scala:489)
	at scala.tools.nsc.typechecker.Implicits$class.inferImplicit(Implicits.scala:41)
	at scala.tools.nsc.Global$$anon$1.inferImplicit(Global.scala:489)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$wrapImplicit$1(Typers.scala:219)
	at scala.tools.nsc.typechecker.Typers$Typer.inferView(Typers.scala:226)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToMember(Typers.scala:1222)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$adaptToMemberWithArgs$1.apply(Typers.scala:1277)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$adaptToMemberWithArgs$1.apply(Typers.scala:1277)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:693)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToMemberWithArgs(Typers.scala:1277)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectInternal$1(Typers.scala:4731)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedSelect$1(Typers.scala:4709)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:4848)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5371)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5492)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedFunction(Typers.scala:2983)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedFunction$1$1.apply(Typers.scala:5311)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedFunction$1$1.apply(Typers.scala:5311)
	at scala.tools.nsc.typechecker.Typers$Typer.typedFunction$1(Typers.scala:5311)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5348)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5380)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3163)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedArgToPoly$1(Typers.scala:3514)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$75.apply(Typers.scala:3522)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$75.apply(Typers.scala:3522)
	at scala.reflect.internal.util.Collections$class.map2(Collections.scala:79)
	at scala.reflect.internal.SymbolTable.map2(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3522)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3533)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4580)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4608)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5501)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5507)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:4839)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5371)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$102.apply(Typers.scala:4559)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$102.apply(Typers.scala:4559)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:680)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4558)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4608)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5492)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5583)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:967)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1490)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1641)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1650)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:869)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1677)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:868)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:860)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1799)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1807)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1797)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1680)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5035)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2376)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5345)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5345)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5344)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5380)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5634)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2203)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5335)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1916)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1757)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5336)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5042)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5339)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5477)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:95)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:168)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:94)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:84)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:159)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:68)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:201)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:183)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:174)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:165)
	at sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:94)
	at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:303)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:119)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:584)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

```

**Comment by tribbloid** [comment] 2017-11-30 18:50
This error can be triggered in both Scala 2.10.6 and Scala 2.11.11

**Comment by sophiexdotai** [comment] 2018-09-27 16:59
+1

**Comment by SethTisue** [comment] 2018-09-27 17:08
is it reproducible in 2.12.x and/or 2.13.x? no further 2.11.x releases are planned

**Comment by SethTisue** [comment] 2021-09-30 23:27
Closing, provisionally, since we have no definite information that the bug still exists.

**Closed by SethTisue** 2021-09-30 23:27 UTC
Labels: compiler crash
