### ISSUE TITLE
Value class java interop

### ISSUE THREAD

**Issue by regadas** [scala/bug#11771] opened 2019-10-14 15:57 UTC
Hello!

Up until `2.12.8` value classes when used in Java used to return the underlying type, it's no longer the case with `2.12.9` to `2.13.1`. Dummy example follows:

```scala
sealed trait Say[+A] {
  def say: A
}

final case class Hi(str: String) extends AnyVal

object Example {
  def sayHi: Say[Hi] = new Say[Hi] {
    override def say = Hi("hi")
  }
}
```

```java
class ExampleInJava {
    public static Say<String> sayHi() {
        return Example$.MODULE$.sayHi();
    }
}
```

created a [repo]( https://github.com/regadas/scala-valueclass-bug) to reproduce this.

**Comment by martijnhoekstra** [comment] 2019-10-14 16:34
PR #8167 seems relevant.

**Comment by joroKr21** [comment] 2019-10-14 16:38
Duplicate of #11733

**Closed** 2019-10-14 21:00 UTC

**Comment by hrhino** [comment] 2019-10-14 21:40
FWIW I don't know how it ever worked for you in Java: if you say, say, `sayHi().str().length()` you _will_ get an exception at runtime in Scala <2.12.10, as I understand it.

**Comment by regadas** [comment] 2019-10-14 22:21
Hi @hrhino correct it throws `ClassCastException` and it doesn't allow you to compile with `public static Say<Hi> sayHi()` either.

I just saw the referenced links to this and things make more sense now! 😄 

Thanks you all!
