### ISSUE TITLE
Scala 2.12.3 regression: interfaces of a class are removed if they exist in a superclass

### ISSUE THREAD

**Issue by sjrd** [scala/bug#10473] opened 2017-08-17 18:01 UTC
Scala 2.12.2:
```scala
$ scala
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions for evaluation. Or try :help.

scala> final class RuntimeLong extends java.lang.Number with java.io.Serializable {
     |   def intValue(): Int = 0; def longValue(): Long = 0L; def floatValue(): Float = 0.0f; def doubleValue(): Double = 0.0
     | }
defined class RuntimeLong

scala> classOf[RuntimeLong].getInterfaces
res0: Array[Class[_]] = Array(interface java.io.Serializable)

scala> class A extends java.io.Serializable
defined class A

scala> class B extends A with java.io.Serializable
defined class B

scala> classOf[B].getInterfaces
res1: Array[Class[_]] = Array(interface java.io.Serializable)
```
Scala 2.12.3:
```scala
$ scala
Welcome to Scala 2.12.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions for evaluation. Or try :help.

scala> final class RuntimeLong extends java.lang.Number with java.io.Serializable {
     |   def intValue(): Int = 0; def longValue(): Long = 0L; def floatValue(): Float = 0.0f; def doubleValue(): Double = 0.0
     | }
defined class RuntimeLong

scala> classOf[RuntimeLong].getInterfaces
res0: Array[Class[_]] = Array()

scala> class A extends java.io.Serializable
defined class A

scala> class B extends A with java.io.Serializable
defined class B

scala> classOf[B].getInterfaces
res1: Array[Class[_]] = Array()
```
This causes MiMa to report compatibility errors like the following, when upgrading a library from Scala 2.12.2 to 2.12.3:
```
[info] Scala.js library: found 1 potential binary incompatibilities while checking against org.scala-js:scalajs-library_2.12:0.6.19
[error]  * the type hierarchy of class scala.scalajs.runtime.RuntimeLong is different in current version. Missing types {java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scala.scalajs.runtime.RuntimeLong")
```
I discovered this in https://github.com/scala-js/scala-js/pull/3098. See the log of the failing build at https://scala-webapps.epfl.ch/jenkins/job/scalajs-task-worker/189205/console

**Comment by lrytz** [comment] 2017-08-17 21:01
Isn't that change binary compatible and it's a MiMa issue? It might be caused by https://github.com/scala/scala/pull/5792

**Comment by sjrd** [comment] 2017-08-17 21:08
It's binary compatible if you control your parent classes. MiMa (correctly IMO) assumes that classes from separate jars are not under your control.

In any case, IMO dropping the interface is wrong. If I explicitly write it in my source code, I want it to be 1) in the doc and 2) in the class files.

**Comment by gzm0** [comment] 2017-08-19 11:20
Just to be absolutely sure, does this mean that the following code produces different results on 2.12.2 and 2.12.3?

```scala
trait A
trait B extends A
class C

println(classOf[C].getInterfaces)
```

**Comment by sjrd** [comment] 2017-08-19 11:23
@gzm0 I think you forgot some `extends ...` after `class C`.

**Comment by lrytz** [comment] 2017-08-19 12:08
No, the change is only with respect to Java-defined interfaces. We're minimizing parent interfaces for a long time. For example in

```
trait A
trait B extends A
class C extends A with B
```

only `B` ends up as an interface in `C`. That's in 2.10, 2.11, 2.12.

**Comment by sjrd** [comment] 2017-08-19 12:16
So ... does that mean that this change is intended and will stay forever? It's not consistent with Java, FWIW:
```java
public class Test {
  public static void main(String[] args) {
    for (Class<?> intf: C.class.getInterfaces())
      System.out.println(intf);
  }
}

interface A {}

class B extends Object implements A {}

class C extends B implements A {}
```
prints
```
interface A
```
`A` is not deduplicated in `C`.

**Comment by lrytz** [comment] 2017-08-28 12:46
One observation we made while changing the trait method implementation to default methods in 2.12: default method resolution (during classfile parsing, in the JVM) gets a huge slowdown by the number of parent interfaces (https://github.com/scala/scala-dev/issues/98#issuecomment-194602923).

Minimizing parents was originally added in 7a99c03da1, the commit message mentions android (probably referring to https://groups.google.com/forum/#!topic/scala-debate/El3QZEbIwHg) and https://github.com/scala/bug/issues/5278.

**Comment by lrytz** [comment] 2017-09-04 13:46
So I'd still call this a MiMa bug. If one of your parents changes to remove one of its interfaces, then that's where the binary incompatible change is, and not in your code.

I'm for closing this ticket.

**Comment by sjrd** [comment] 2017-09-04 14:43
I still think it's not normal that the compiler would just ignore things I have textually specified.

But I won't fight this. For our specific issue we've anyway worked around it already: https://github.com/scala-js/scala-js/pull/3098/commits/2cdbbfd4dd7182bb0cbedb088cfbe6bd2cbe72e7

**Closed** 2020-11-17 03:48 UTC
