### ISSUE TITLE
[compiler] [incremental] [regression] StackOverflowError for the long string interpolation

### ISSUE THREAD

**Issue by fancywriter** [scala/bug#11214] opened 2018-10-18 16:59 UTC
We had some legacy code which compiles well with scala-2.12.4, but is broken after upgrade to any of 2.12.5, 2.12.6, 2.12.7. Not sure what exactly could be broken in 2.12.5, struggled to make better example.

But I have one which compiles well in 2.12.6, but is broken in 2.12.7:
```
object TestObject {

  def test: String = {
    val a = 0
    s"$a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a $a ".stripMargin
  }

}
```

So, 79 variables inside string interpolation, together with stripMargin. In real example there is long multiline string (few hundred lines) with triple quotes with stripMargin added in purpose. And with much more than 79 dollar-references inside (not all of them point to the same value, and not all are different, it doesn't matter really). Of course I don't like this code (probably good case for template engine like twirl), but it's legacy and I don't want to change it.

If I reduce it to 78 or remove any space, it compiles. Also compiles if I remove `stripMargin`. Also compiles well in 2.12.6, but something was changed in 2.12.5 too, because it is possible to write code which compiles by scala-compiler of 2.12.4, but not newer.

The error message looks very likely to an infinite cycle
```
[error] java.lang.StackOverflowError
[error] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1364)
[error] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1362)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[error] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[error] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
[error] 	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
[error] 	at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1725)
[error] 	at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1720)
[error] 	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
[error] 	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:430)
[error] 	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
[error] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1373)
```
Such stack trace is repeated 86 times.

SBT version (just in case) 1.1.2, no extra compiler options, no dependencies.

**Comment by SethTisue** [comment] 2018-10-18 19:47
duplicate of #10870

**Closed by SethTisue** 2018-10-18 19:47 UTC

**Comment by fancywriter** [comment] 2018-10-19 08:53
well, was strange the didn't find it by keywords "string interpolation and stackoverflow"... github search =)

sorry, will vote for another one.
