### ISSUE TITLE
Can't recognize java interface's  inherited member

### ISSUE THREAD

**Issue by colin4124** [scala/bug#11226] opened 2018-10-26 06:02 UTC
Here‘s java code example for demo. interface `IntStream` has member `EOF`, and `CharStream` extends it. Java can recognize `EOF` from `CharStream` **directly**, but scala can't.

```java
// IntStream.java
package test;

public interface IntStream {
    public static final int EOF = -1;
}
```

```java
// CharStream.java
package test;

public interface CharStream extends IntStream {}
```

```java
import test.CharStream;

public class Test {
    public static void main(String[] args) {
        System.out.println(CharStream.EOF);
    }
}
```
![java_result](https://user-images.githubusercontent.com/1255176/47547124-c9a7c480-d926-11e8-9a2a-0f6ad299b6be.png)

```scala
import test.CharStream

object Test extends App {
  println(CharStream.EOF)
}
```

![scala_result](https://user-images.githubusercontent.com/1255176/47547193-17243180-d927-11e8-93d8-6841acd2bdb5.png)

```scala
import test.IntSream

object Test extends App {
  println(IntSream.EOF)
}
```
![fixed](https://user-images.githubusercontent.com/1255176/47547287-741fe780-d927-11e8-85aa-59d4c73c4a90.png)

**Comment by lrytz** [comment] 2018-10-26 08:32
Thanks for the report! This is a duplicate of https://github.com/scala/bug/issues/9272.

**Closed by lrytz** 2018-10-26 08:32 UTC

**Comment by colin4124** [comment] 2018-10-26 09:21
@lrytz I have read the #9272 , but I still wonder is it a bug? If so, you maybe fix it in the future?

In #10568 , your suggested workaround is that  I should explicitly import the member from supper interface ?

**Comment by lrytz** [comment] 2018-10-26 10:03
It's a bit unclear if this is a bug. It's a consequence of the way Scala models Java static members. But #9272 shows that there are limitations that cannot be worked around.

In your example, you should just use `IntSream.EOF`.

**Comment by colin4124** [comment] 2018-10-26 10:14
Got it, thank you
