### ISSUE TITLE
Scala 2.12 compiler crashes with: no-symbol does not have a type constructor

### ISSUE THREAD

**Issue by silviobierman** [scala/bug#10438] opened 2017-07-28 09:55 UTC
Bug shows up in Scala version: 2.12.3 (2.12.2 shows same behavior)
Last confirmed working version: 2.11.5
Scala-ide (Eclipse) wise: the last working versions is 4.5.0 (uses scala 2.11.8) while 4.6.1 (2.12.2) fails.

Bug description:
I maintain a medium size Scala code base (~1K sources, ~100K loc) that compiles successfully with Scala versions < 2.12 but all 2.12 versions I tried up to 2.12.3 resuls in the compiler crashing. 
My production build uses Ant and simply calls the Scala compiler using the &lt;scalac/&gt; task and the crash dumps some info plus a stack trace to the Ant output window.

The error reads:

no-symbol does not have a type constructor (this may indicate scalac cannot find fundamental classes)

The printed info contains some hints about where the errors occurs. Making some minor changes (making a lazy val non-lazy, separating a local object definition into a class and an instantiation)  sometimes fixes the error but then the same crash occurs somewhere else.

Full copy-paste of the Ant-console error output:

      [scalac] error:
      [scalac]   no-symbol does not have a type constructor (this may indicate scalac cannot find fundamental classes)
      [scalac]      while compiling: /home/silvio/java_root/projects/jambo-xi/scriptlet/src/nl/idfix/scriptlet/scripts/components/surveyeditor/ValidationMessageItem.scala
      [scalac]         during phase: fields
      [scalac]      library version: version 2.12.3
      [scalac]     compiler version: version 2.12.3
      [scalac]   reconstructed args: -deprecation -classpath /home/silvio/java_root/extern/commapi/comm.jar:/home/silvio/java_root/extern/jetty/jetty9.4/cdi-core-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/cdi-servlet-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/cdi-websocket-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/http2-common-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/http2-hpack-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/http2-server-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-alpn-server-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-annotations-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-client-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-continuation-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-deploy-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-gcloud-session-manager-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-http-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-infinispan-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-io-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jaas-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jaspi-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jmx-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jndi-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-memcached-sessions-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-nosql-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-plus-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-proxy-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-quickstart-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-rewrite-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-schemas-3.1.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-security-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-server-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-servlet-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-servlets-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-unixsocket-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-util-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-webapp-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-xml-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/servlet-api-3.1.jar:/home/silvio/java_root/extern/cos/cos.jar:/home/silvio/java_root/extern/poi/dom4j-1.6.1.jar:/home/silvio/java_root/extern/poi/poi-3.14-20160307.jar:/home/silvio/java_root/extern/poi/poi-ooxml-3.14-20160307.jar:/home/silvio/java_root/extern/poi/poi-ooxml-schemas-3.14-20160307.jar:/home/silvio/java_root/extern/poi/poi-scratchpad-3.14-20160307.jar:/home/silvio/java_root/extern/poi/xmlbeans-2.6.0.jar:/home/silvio/java_root/extern/javamail/javax.mail-1.5.6.jar:/home/silvio/java_root/extern/markdown/markdown4j-2.2.jar:/home/silvio/java_root/extern/jsch/jsch-0.1.49.jar:/home/silvio/java_root/extern/ssj/ssj.jar:/home/silvio/java_root/extern/nu/htmlparser-1.3.1.jar:/home/silvio/java_root/extern/h2-jdbc/h2-1.4.195.jar:/home/silvio/java_root/extern/jgroups/jgroups-3.2.4.Final.jar:/home/silvio/java_root/extern/apache/commons-codec-1.8.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-anim.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-awt-util.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-bridge.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-codec.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-css.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-dom.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-ext.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-extension.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-gui-util.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-gvt.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-parser.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-script.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-svg-dom.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-svggen.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-swing.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-transcoder.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-util.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-xml.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/js.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/pdf-transcoder.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xalan-2.6.0.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xerces_2_5_0.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xml-apis-ext.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xml-apis.jar:/home/silvio/java_root/extern/zxing/qrgen-1.1.jar:/home/silvio/java_root/extern/zxing/zxing-core-1.7.jar:/home/silvio/java_root/extern/zxing/zxing-j2se-1.7.jar:/home/silvio/java_root/extern/scala/scala-2.11.5/lib/scala-library.jar:/home/silvio/java_root/extern/scala/scala-2.11.5/lib/scala-xml_2.11-1.0.3.jar:/home/silvio/java_root/projects/jambo-xi/piglet_dependencies.jar -d /home/silvio/java_root/projects/jambo-xi/scriptlet/classes_ant -dependencyfile /home/silvio/java_root/projects/jambo-xi/.scala_dependencies
      [scalac]   last tree to typer: TypeTree(object lang)
      [scalac]        tree position: line 71 of /home/silvio/java_root/projects/jambo-xi/scriptlet/src/nl/idfix/scriptlet/scripts/components/surveyeditor/ValidationMessageItem.scala
      [scalac]             tree tpe: ValidationTopicEntry.this.lang.type
      [scalac]               symbol: private object lang in trait TopicEntry
      [scalac]    symbol definition: private class lang extends Object (a ModuleClassSymbol)
      [scalac]       symbol package: nl.idfix.scriptlet.scripts.components.surveyeditor
      [scalac]        symbol owners: object lang -> trait TopicEntry
      [scalac]            call site: method unapply in object ValidationTopicEntry in package surveyeditor
      [scalac] == Source file context for tree position ==
      [scalac]     68
      [scalac]     69 		var topicEntries : Seq[ValueHandle[_]] = Seq.empty
      [scalac]     70
      [scalac]     71 		case class ValidationTopicEntry(val surveyItem : SurveyItem) extends TopicEntry
      [scalac]     72 		{
      [scalac]     73 			implicit val session = ValidationMessageItem.this.session
      [scalac]     74
      [scalac] scala.reflect.internal.FatalError: 
      [scalac]   no-symbol does not have a type constructor (this may indicate scalac cannot find fundamental classes)
      [scalac]      while compiling: /home/silvio/java_root/projects/jambo-xi/scriptlet/src/nl/idfix/scriptlet/scripts/components/surveyeditor/ValidationMessageItem.scala
      [scalac]         during phase: fields
      [scalac]      library version: version 2.12.3
      [scalac]     compiler version: version 2.12.3
      [scalac]   reconstructed args: -deprecation -classpath /home/silvio/java_root/extern/commapi/comm.jar:/home/silvio/java_root/extern/jetty/jetty9.4/cdi-core-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/cdi-servlet-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/cdi-websocket-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/http2-common-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/http2-hpack-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/http2-server-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-alpn-server-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-annotations-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-client-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-continuation-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-deploy-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-gcloud-session-manager-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-http-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-infinispan-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-io-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jaas-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jaspi-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jmx-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-jndi-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-memcached-sessions-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-nosql-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-plus-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-proxy-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-quickstart-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-rewrite-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-schemas-3.1.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-security-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-server-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-servlet-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-servlets-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-unixsocket-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-util-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-webapp-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/jetty-xml-9.4.6.v20170531.jar:/home/silvio/java_root/extern/jetty/jetty9.4/servlet-api-3.1.jar:/home/silvio/java_root/extern/cos/cos.jar:/home/silvio/java_root/extern/poi/dom4j-1.6.1.jar:/home/silvio/java_root/extern/poi/poi-3.14-20160307.jar:/home/silvio/java_root/extern/poi/poi-ooxml-3.14-20160307.jar:/home/silvio/java_root/extern/poi/poi-ooxml-schemas-3.14-20160307.jar:/home/silvio/java_root/extern/poi/poi-scratchpad-3.14-20160307.jar:/home/silvio/java_root/extern/poi/xmlbeans-2.6.0.jar:/home/silvio/java_root/extern/javamail/javax.mail-1.5.6.jar:/home/silvio/java_root/extern/markdown/markdown4j-2.2.jar:/home/silvio/java_root/extern/jsch/jsch-0.1.49.jar:/home/silvio/java_root/extern/ssj/ssj.jar:/home/silvio/java_root/extern/nu/htmlparser-1.3.1.jar:/home/silvio/java_root/extern/h2-jdbc/h2-1.4.195.jar:/home/silvio/java_root/extern/jgroups/jgroups-3.2.4.Final.jar:/home/silvio/java_root/extern/apache/commons-codec-1.8.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-anim.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-awt-util.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-bridge.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-codec.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-css.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-dom.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-ext.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-extension.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-gui-util.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-gvt.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-parser.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-script.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-svg-dom.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-svggen.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-swing.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-transcoder.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-util.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/batik-xml.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/js.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/pdf-transcoder.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xalan-2.6.0.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xerces_2_5_0.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xml-apis-ext.jar:/home/silvio/java_root/extern/apache/batik-1.7/lib/xml-apis.jar:/home/silvio/java_root/extern/zxing/qrgen-1.1.jar:/home/silvio/java_root/extern/zxing/zxing-core-1.7.jar:/home/silvio/java_root/extern/zxing/zxing-j2se-1.7.jar:/home/silvio/java_root/extern/scala/scala-2.11.5/lib/scala-library.jar:/home/silvio/java_root/extern/scala/scala-2.11.5/lib/scala-xml_2.11-1.0.3.jar:/home/silvio/java_root/projects/jambo-xi/piglet_dependencies.jar -d /home/silvio/java_root/projects/jambo-xi/scriptlet/classes_ant -dependencyfile /home/silvio/java_root/projects/jambo-xi/.scala_dependencies
      [scalac]   last tree to typer: TypeTree(object lang)
      [scalac]        tree position: line 71 of /home/silvio/java_root/projects/jambo-xi/scriptlet/src/nl/idfix/scriptlet/scripts/components/surveyeditor/ValidationMessageItem.scala
      [scalac]             tree tpe: ValidationTopicEntry.this.lang.type
      [scalac]               symbol: private object lang in trait TopicEntry
      [scalac]    symbol definition: private class lang extends Object (a ModuleClassSymbol)
      [scalac]       symbol package: nl.idfix.scriptlet.scripts.components.surveyeditor
      [scalac]        symbol owners: object lang -> trait TopicEntry
      [scalac]            call site: method unapply in object ValidationTopicEntry in package surveyeditor
      [scalac] == Source file context for tree position ==
      [scalac]     68 		
      [scalac]     69 		var topicEntries : Seq[ValueHandle[_]] = Seq.empty
      [scalac]     70 		
      [scalac]     71 		case class ValidationTopicEntry(val surveyItem : SurveyItem) extends TopicEntry
      [scalac]     72 		{
      [scalac]     73 			implicit val session = ValidationMessageItem.this.session
      [scalac]     74 			
      [scalac] 	at scala.reflect.internal.Reporting.abort(Reporting.scala:61)
      [scalac] 	at scala.reflect.internal.Reporting.abort$(Reporting.scala:57)
      [scalac] 	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.internal.Symbols$Symbol.typeConstructor(Symbols.scala:1479)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.mkLazyLocalDef(Fields.scala:579)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:749)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.$anonfun$transformStats$4(Fields.scala:776)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:776)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:540)
      [scalac] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1377)
      [scalac] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:755)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:540)
      [scalac] 	at scala.reflect.internal.Trees.$anonfun$itransform$2(Trees.scala:1374)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
      [scalac] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1372)
      [scalac] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:755)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transformTermsAtExprOwner(Fields.scala:763)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.$anonfun$transformStats$3(Fields.scala:776)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:776)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:540)
      [scalac] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1415)
      [scalac] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:40)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:755)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:540)
      [scalac] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
      [scalac] 	at scala.reflect.internal.Trees.$anonfun$itransform$4(Trees.scala:1419)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
      [scalac] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1418)
      [scalac] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:755)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.$anonfun$transformStats$4(Fields.scala:776)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:776)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:540)
      [scalac] 	at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1437)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
      [scalac] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1437)
      [scalac] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
      [scalac] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
      [scalac] 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:755)
      [scalac] 	at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:540)
      [scalac] 	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
      [scalac] 	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
      [scalac] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
      [scalac] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
      [scalac] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
      [scalac] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
      [scalac] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
      [scalac] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
      [scalac] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
      [scalac] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
      [scalac] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
      [scalac] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
      [scalac] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
      [scalac] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1515)
      [scalac] 	at scala.tools.ant.Scalac.executeInternal(Scalac.scala:682)
      [scalac] 	at scala.tools.ant.Scalac.execute(Scalac.scala:630)
      [scalac] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
      [scalac] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      [scalac] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      [scalac] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [scalac] 	at java.lang.reflect.Method.invoke(Method.java:498)
      [scalac] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [scalac] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [scalac] 	at org.apache.tools.ant.Target.execute(Target.java:435)
      [scalac] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
      [scalac] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
      [scalac] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
      [scalac] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [scalac] 	at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
      [scalac] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      [scalac] 	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:712)
      [scalac] 	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:532)
      [scalac] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      [scalac] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      [scalac] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [scalac] 	at java.lang.reflect.Method.invoke(Method.java:498)
      [scalac] 	at org.eclipse.ant.core.AntRunner.run(AntRunner.java:371)
      [scalac] 	at org.eclipse.ant.internal.launching.launchConfigurations.AntLaunchDelegate$1.run(AntLaunchDelegate.java:270)
      [scalac] 	at java.lang.Thread.run(Thread.java:748)

**Comment by SethTisue** [comment] 2023-12-21 23:58
Closing since we don't have any reproduction details at all, let alone minimized ones (which is why the ticket never got any attention).

**Closed by SethTisue** 2023-12-21 23:58 UTC
