### ISSUE TITLE
Scala 2.13 ArrayStoreException due to incorrectly inferred type

### ISSUE THREAD

**Issue by ryanberckmans** [scala/bug#11701] opened 2019-08-21 15:39 UTC
## Bug

Reproduction https://scastie.scala-lang.org/Fryh4vxQSGyrBJ54dkFIsg

```scala
// throws ArrayStoreException because Vector's
// internal array is of type Array[None]:
val x: Vector[Option[Int]] = Vector(None, None, None) 

// Works due to Vector[Option[Int]] type hint
//val x = Vector[Option[Int]](None, None, None)

val y = x.updated(1, Some(5))
```

## Expectation

I expected `val x: Vector[Option[Int]] = Vector(None, None, None)` to propagate the `Option[Int]` type to the Vector literal so that I could update the Vector with a `Some[Int]`.

**Comment by ryanberckmans** [comment] 2019-08-21 15:40
Related to https://github.com/scala/bug/issues/11600

**Comment by martijnhoekstra** [comment] 2019-08-21 16:06
Your reproduction works -- maybe you over-minimized?

**Comment by ryanberckmans** [comment] 2019-08-21 16:09
@martijnhoekstra pardon me, the Scastie link had the bugged code commented out. Updated the Scastie link to throw ArrayStoreException.

**Comment by eed3si9n** [comment] 2019-08-21 18:04
Related or a duplicate of #11600?

**Comment by Jasper-M** [comment] 2019-08-22 08:33
How could this not be duplicate?

**Comment by SethTisue** [comment] 2019-08-22 14:16
yeah, seems sufficient to have the link on the other ticket

**Closed by SethTisue** 2019-08-22 14:16 UTC
Labels: blocker, library:collections
