### ISSUE TITLE
global `ExecutionContext` threads do not finish upon interruption

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala/bug#10587] opened 2017-11-05 15:31 UTC
global `ExecutionContext` threads do not react on interruption

see: https://github.com/scala-js/scala-js/issues/3169

**Comment by SethTisue** [comment] 2017-11-05 16:17
can you show code that demonstrates the problem?

**Comment by som-snytt** [comment] 2017-11-05 20:42
I wanted to refresh my memory about the API. It's possible to get a normal `global` by passing `null` to the factory method, supplying a reporter which detects the interruption.

Maybe it would be convenient to have a boolean flag `scala.concurrent.context.interruptible`.

```
package nofuture

import concurrent._
import util._
import java.util.concurrent.CountDownLatch

object test extends App with Runnable {
  implicit lazy val ec: ExecutionContextExecutorService = {
    ExecutionContext.fromExecutorService(null, {
      case t: InterruptedException =>
        println(s"Oh, there was an exception: $t")
        ec.shutdown()
      case _ =>
    })
    //ExecutionContext.global
  }
  val latch = new CountDownLatch(1)
  val group = new ThreadGroup("futuristic")
  val mainer = new Thread(group, this, "mainer")
  mainer.start()

  Thread.sleep(1000L)
  println(s"interrupting ${group.activeCount} threads")
  show()
  group.interrupt()
  latch.countDown()
  Thread.sleep(1000L)
  println(s"seeing ${group.activeCount} threads")
  show()

  def show(): Unit = {
    val ts = new Array[Thread](100)
    val n = group.enumerate(ts)
    println(ts.take(n).map(_.getName).mkString("Group threads\n","\n",""))
  }
  override def run(): Unit = {
    println(s"running on ${Thread.currentThread}")
    val f = Future {
      println("computing...")
      latch.await()
      42
      //???
    }
    val g = f.transform {
      case x @ Success(v) => println(s"computed $v on ${Thread.currentThread}") ; x
      case Failure(e) => println(s"failed $e on ${Thread.currentThread}") ; Success(-1)
    }
    for (v <- g) {
      println(s"completed $v on ${Thread.currentThread}")
    }
  }
}

```

**Comment by Andrei-Pozolotin** [comment] 2017-11-06 01:31
@SethTisue code that demonstrates the problem 
is in the convoluted stack trace of  `org.scalajs.cli.Scalajsld` by @sjrd 
see https://github.com/scala-js/scala-js/issues/3169, perhaps @sjrd can point to the relevant `import`

**Comment by viktorklang** [comment] 2017-11-06 09:08
Hey,

apologies for the terse response here, I'm a bit under pressure with a deadline.

Could someone please post a bit of more rationale here?

Testing group.interrupt() seems dubious at best since how would you know what group the threads belonging to the backing pool would belong to from the outside?

Also, what is the precedent here? What does ForkJoinPool.commonPool() do?

I'm being rigorous with this one since it has the potential of breaking existing applications.

**Comment by Andrei-Pozolotin** [comment] 2017-11-06 16:02
@viktorklang

see: https://gist.github.com/Andrei-Pozolotin/3089dc50fe20f18fc2c5d29eb001e81c

the rationale is:
-  `ForkJoinPool` and `ExecutionContext.global` behave differently
-  `ForkJoinPool` threads terminate upon interrupt
-  `ExecutionContext.global` threads stay alive upon interrupt

for `ForkJoinPool` see: main1.Main.scala
for `ExecutionContext.global` see: main2.Main.scala

**Comment by viktorklang** [comment] 2017-11-06 18:28
@Andrei-Pozolotin You're not using Futures in both examples. We need apples-to-apples comparisons here.

**Comment by viktorklang** [comment] 2017-11-07 13:14
@Andrei-Pozolotin My brief look into this revealed that the problem is not the pool, the problem is the AdaptedForkJoinTask, but it is unsure as to why it poses a problem, compared to the adaptation done by the FJP itself.

**Comment by viktorklang** [comment] 2017-11-07 21:09
@Andrei-Pozolotin @SethTisue @sjrd 

I think I have a fix.

~~~diff
@@ -121,30 +122,11 @@ private[concurrent] object ExecutionContextImpl {
                                                                       uncaught = uncaughtExceptionHandler)

     new ForkJoinPool(desiredParallelism, threadFactory, uncaughtExceptionHandler, true) {
-      override def execute(runnable: Runnable): Unit = {
-        val fjt: ForkJoinTask[_] = runnable match {
-          case t: ForkJoinTask[_] => t
-          case r                  => new ExecutionContextImpl.AdaptedForkJoinTask(r)
-        }
-        Thread.currentThread match {
-          case fjw: ForkJoinWorkerThread if fjw.getPool eq this => fjt.fork()
-          case _                                                => super.execute(fjt)
-        }
-      }
-    }
-  }
-
-  final class AdaptedForkJoinTask(runnable: Runnable) extends ForkJoinTask[Unit] {
-    final override def setRawResult(u: Unit): Unit = ()
-    final override def getRawResult(): Unit = ()
-    final override def exec(): Boolean = try { runnable.run(); true } catch {
-      case anything: Throwable =>
-        val t = Thread.currentThread
-        t.getUncaughtExceptionHandler match {
-          case null =>
-          case some => some.uncaughtException(t, anything)
-        }
-        throw anything
+      override def execute(runnable: Runnable): Unit =
+        if (runnable.isInstanceOf[ForkJoinTask[_]])
+          super.execute(runnable.asInstanceOf[ForkJoinTask[_]])
+        else
+          super.execute(runnable)
     }
   }
~~~

~~~diff
@@ -737,13 +738,36 @@ trait Exceptions extends TestBase {
 }

 trait GlobalExecutionContext extends TestBase {
+  import ExecutionContext.Implicits._
+
   def testNameOfGlobalECThreads(): Unit = once {
     done => Future({
         val expectedName = "scala-execution-context-global-"+ Thread.currentThread.getId
         done(expectedName == Thread.currentThread.getName)
-      })(ExecutionContext.global)
+      })
+  }
+
+  def testInterrupted(): Unit = once {
+    done =>
+      import java.util.concurrent.TimeUnit.SECONDS
+      val ec = implicitly[ExecutionContext]
+      val latch1, latch2 = new java.util.concurrent.CountDownLatch(1)
+      @volatile var thread: Thread = null
+
+      ec.execute(() => {
+        thread = Thread.currentThread
+        latch1.countDown()
+        latch2.await(5, SECONDS)
+      })
+
+      latch1.await(5, SECONDS)
+      thread.interrupt()
+      latch2.countDown()
+      Thread.sleep(250)
+      done(thread.isAlive == false)
   }

+  testInterrupted()
   testNameOfGlobalECThreads()
 }
~~~

**Comment by Andrei-Pozolotin** [comment] 2017-11-07 21:10
looks too easy

**Comment by viktorklang** [comment] 2017-11-07 21:35
@Andrei-Pozolotin Well, it took quite a few hours to get to a simple solution.

**Comment by Andrei-Pozolotin** [comment] 2017-11-07 22:17
will it work with this scenario? (to ensure no resource leaks):

https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java#L415

**Comment by som-snytt** [comment] 2017-11-08 00:29
I tried it on my test and it works. I think the override execute is mildly redundant?

It works, except that the pool spins up another thread. Looks like by default keep alive is a minute. With `-Dscala.concurrent.context.numThreads=0` it is a couple of seconds. There is a new constructor in java 9 that takes a `minRunnable` but I haven't tried it out.

**Comment by som-snytt** [comment] 2017-11-08 00:54
Thanks, this was interesting, though I still don't understand the result. A chance to refresh my memory what's the difference between `interrupted` and `isInterrupted`.

test/files/run/t10587.javaopts
```
-Dscala.concurrent.context.numThreads=0 -Dxscala.concurrent.context.minThreads=0
```
test/files/run/t10587.scala
```
// default global execution context threads should terminate after interruption

import concurrent._ 
import java.util.concurrent.{CountDownLatch, TimeUnit}

object Test extends App with Runnable {
  import ExecutionContext.Implicits._

  implicit class LatchOps(c: CountDownLatch) {
    def waitForIt(): Boolean = c.await(1L, TimeUnit.SECONDS)
  }
  
  val started, goosed = new CountDownLatch(1)
  val group = new ThreadGroup("futuristic")
  val mainer = new Thread(group, this, "mainer")

  mainer.start()
  assert(started.waitForIt())
  //group.interrupt()
  killem()
  goosed.countDown()
  Thread.sleep(1000L)
  
  killem()
  Thread.sleep(1000L)
  show(-1)

  Thread.sleep(1000L)
  /*
  Thread.sleep(5000L)
  show(-1)
  Thread.sleep(65000L)
  */
  show(0)

  def killem() = show(-1, killem = true)
  def show(x: Int, killem: Boolean = false): Unit = {
    val ts = new Array[Thread](100)
    val n = group.enumerate(ts)
    val k = if (killem) "Killing " else ""
    println(ts.take(n).map(_.getName).mkString(s"$k$n Group threads\n","\n",""))
    if (killem) ts.take(n).foreach(_.interrupt())
    if (x >= 0) assert(n == x)
  }
  override def run(): Unit = {
    Future {
      started.countDown()
      goosed.await()
      ()
    }
    Thread.sleep(10000L)
  }
} 
```
test/files/run/t10587-run.log
```
Killing 2 Group threads
mainer
scala-execution-context-global-11
Exception in thread "mainer" java.lang.InterruptedException: sleep interrupted
  at java.lang.Thread.sleep(Native Method)
  at Test$.run(t10587.scala:52)
  at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
  at Test$.$anonfun$run$1(t10587.scala:49)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
  at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
  at scala.util.Success.$anonfun$map$1(Try.scala:251)
  at scala.util.Try$.apply(Try.scala:209)
  at scala.util.Success.map(Try.scala:251)
  at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
  at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
  at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
  at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Killing 1 Group threads
scala-execution-context-global-12
1 Group threads
scala-execution-context-global-12
0 Group threads

```

**Comment by viktorklang** [comment] 2017-11-08 07:11
@som-snytt Yes, the override is reduntant. I kept it to show what made the difference. The AdaptedRunnableAction in FJP (which is used by the FJP when wrapping Runnables) has access to internal API which rethrows exception outside of the FJT execution, and the s.c AdaptedForkJoinTask has no access to that behavior and as such it cannot escalate the exception in the same way.

**Comment by viktorklang** [comment] 2017-11-08 10:40
I may have spoken too soon, it does seem like the UncaughtExecutionHandler isn't invoked with the proposed solution (which would break backwards compat). Not sure if it can be fixed. Looking into it.

**Comment by viktorklang** [comment] 2017-11-08 12:39
@Andrei-Pozolotin This seems to work fine (added a testcase to verify both error reporting and InterruptedExceptions). https://github.com/viktorklang/scala/tree/wip-10587-%E2%88%9A

**Comment by Andrei-Pozolotin** [comment] 2017-11-08 17:09
@viktorklang is `wip-10587` binary downloadable somewhere?

**Comment by SethTisue** [comment] 2017-11-08 17:13
> @viktorklang is wip-10587 binary downloadable somewhere?

yes, see "You can use Scala builds in the validation repository locally by..." at https://github.com/scala/scala/blob/2.13.x/README.md#scala-ci

**Comment by adriaanm** [comment] 2017-11-09 00:08
Specifically,
```
set resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
set scalaVersion := "2.13.0-pre-94021c5-SNAPSHOT"
```

**Comment by Andrei-Pozolotin** [comment] 2017-11-09 15:41
1) still trying to verify the issue
2) note: @sjrd will be coming after you:
there is enough change is `scala` to make `scala-js` fail regardless of the execution context
```
Caused by: java.lang.ClassNotFoundException: scala.collection.parallel.mutable.ParTrieMap$
    at java.net.URLClassLoader.findClass (URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$CollOps$.emptyParMap (ParIncOptimizer.scala:37)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$CollOps$.emptyParMap (ParIncOptimizer.scala:28)
    at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer.<init> (GenIncOptimizer.scala:89)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer.<init> (ParIncOptimizer.scala:26)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$.$anonfun$factory$1 (ParIncOptimizer.scala:205)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$.$anonfun$factory$1$adapted (ParIncOptimizer.scala:205)
    at org.scalajs.core.tools.linker.frontend.LinkerFrontend.$anonfun$optOptimizer$1 (LinkerFrontend.scala:41)
    at scala.Option.map (Option.scala:146)
    at org.scalajs.core.tools.linker.frontend.LinkerFrontend.<init> (LinkerFrontend.scala:41)
    at org.scalajs.core.tools.linker.LinkerPlatformExtensions.applyInternal (LinkerPlatformExtensions.scala:35)
    at org.scalajs.core.tools.linker.LinkerPlatformExtensions.applyInternal$ (LinkerPlatformExtensions.scala:24)
    at org.scalajs.core.tools.linker.Linker$.applyInternal (Linker.scala:80)
    at org.scalajs.core.tools.linker.StandardLinker$.apply (StandardLinker.scala:40)
    at org.scalajs.cli.Scalajsld$.$anonfun$main$1 (Scalajsld.scala:203)
    at org.scalajs.cli.Scalajsld$.$anonfun$main$1$adapted (Scalajsld.scala:164)
    at scala.Option.foreach (Option.scala:257)
    at org.scalajs.cli.Scalajsld$.main (Scalajsld.scala:164)
    at org.scalajs.cli.Scalajsld.main (Scalajsld.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by Andrei-Pozolotin** [comment] 2017-11-09 17:02
@sjrd I mean :
running `scala-js` linker 
http://search.maven.org/#artifactdetails%7Corg.scala-js%7Cscalajs-cli_2.12%7C0.6.21%7Cjar
against next `scala` library:
```
set resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
set scalaVersion := "2.13.0-pre-94021c5-SNAPSHOT"
```
shows next `scala` parallel collections are different from what `ParIncOptimizer` expects

**Comment by sjrd** [comment] 2017-11-09 17:28
That's the CLI built for 2.12. Of course it won't work out of the box with a 2.13-like build of Scala. You need to locally publish scalajs-cli (and its dependencies) for the 2.13-pre version that you are using.

Our build is already well configured for the CLI and its dependencies to use the new, extracted, parallel collections. But you have to use a CLI built for 2.13. Not one built for 2.12.

**Comment by Andrei-Pozolotin** [comment] 2017-11-09 17:30
ok, great.

**Comment by viktorklang** [comment] 2017-11-09 17:57
I created a branch against 2.12.x as well, I could open a PR for it but I am not sure if there are snapshots published for those.

**Comment by SethTisue** [comment] 2017-11-09 18:04
> I could open a PR for it but I am not sure if there are snapshots published for those.

there are

**Comment by Andrei-Pozolotin** [comment] 2017-11-09 18:05
if approved, will you apply this to both 2.12 and 2.13? then please publish PR

**Comment by SethTisue** [comment] 2017-11-09 18:06
everything merged onto 2.12.x eventually (usually within a few weeks) gets merged forward onto 2.13.x as well

**Comment by viktorklang** [comment] 2017-11-09 18:13
If the changes fix issues and do not impose other problems...

https://github.com/scala/scala/pull/6171

**Comment by Andrei-Pozolotin** [comment] 2017-11-09 20:52
https://github.com/scala/scala/pull/6171 needs /rebuild ?

**Comment by viktorklang** [comment] 2017-11-14 09:47
@Andrei-Pozolotin I issued the /rebuild (have been on vacation)

**Comment by viktorklang** [comment] 2017-11-15 08:41
@Andrei-Pozolotin Can you check https://github.com/scala/scala/pull/6171 now?

**Comment by Andrei-Pozolotin** [comment] 2017-11-15 13:16
I verified https://github.com/scala/scala/pull/6171 via `2.12.5-bin-90e997b-SNAPSHOT` 
and the issue is resolved.  thank you all guys!

**Closed** 2018-02-28 11:52 UTC

**Comment by SethTisue** [comment] 2021-06-25 01:05
in this same area: https://github.com/scala/bug/issues/12423
