### ISSUE TITLE
Semantic changes between two implementations of Future.find

### ISSUE THREAD

**Issue by REASY** [scala/bug#12325] opened 2021-01-29 04:37 UTC
## reproduction steps

using Scala 2.12.12

```scala
import scala.concurrent.duration._
import scala.concurrent.{Await, ExecutionContext, Future}

object FutureFindIssue {
  def getFutures(implicit ec: ExecutionContext): List[Future[Boolean]] = {
    List(Future { Thread.sleep(1000); false },
      Future { Thread.sleep(1000); false },
      Future { Thread.sleep(1); true }
    )
  }
  def predicate(x: Boolean): Boolean = x == true

  def findFast(futures: List[Future[Boolean]])
              (implicit ec: ExecutionContext): Unit = {
    val s = System.currentTimeMillis()
    // Deprecated find
    val f = Future.find(futures.toTraversable)(predicate)
    val r = Await.result(f, 10.seconds)
    val e = System.currentTimeMillis()
    println(s"findFast took ${e - s} ms, r = $r")
  }

  def findSlow(futures: List[Future[Boolean]])
              (implicit ec: ExecutionContext): Unit = {
    val s = System.currentTimeMillis()
    // New implementation of `find`
    val f = Future.find(futures)(predicate)
    val r = Await.result(f, 10.seconds)
    val e = System.currentTimeMillis()
    println(s"findSlow took ${e - s} ms, r = $r")
  }

  def main(args: Array[String]): Unit = {
    implicit val ec: scala.concurrent.ExecutionContext = scala.concurrent.ExecutionContext.global
    findFast(getFutures)
    findSlow(getFutures)
  }
}
```

## problem
Deprecated [Future.find](https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/Future.scala#L703) gives a result as soon as possible, but a new version of [Future.find](https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/Future.scala#L735) uses `transformWith` which is similar to map, so it waits until Future gets resolved. Output of the example could look like:
```
findFast took 101 ms, r = Some(true)
findSlow took 1018 ms, r = Some(true)
```

**Comment by REASY** [comment] 2021-01-29 05:12
Related: https://github.com/scala/bug/issues/11827

**Comment by matepek** [comment] 2021-01-29 08:22
I tried to combine the advantages of the deprecated `find` and `firstCompletedOf` and rid of the `toBuffer`.

```scala
  def find[T](futures: TraversableOnce[Future[T]])(predicate: T => Boolean)(
      implicit executor: ExecutionContext): Future[Option[T]] = {
    if (futures.isEmpty) Future.successful[Option[T]](None)
    else {
      val result = Promise[Option[T]]()
      val unfinishedCounter = new AtomicInteger(1) // temporarily incremented to prevent race condition
      val trySuccess = new AtomicReference[Promise[Option[T]]](result) with (Option[T] => Boolean) {
        override def apply(v1: Option[T]): Boolean = getAndSet(null) match {
          case null => false
          case some => some.trySuccess(v1)
        }
      }
      val completeHandler = (v1: Try[T]) => {
        val count = unfinishedCounter.decrementAndGet
        var changed = false
        try {
          v1 match {
            case Success(v) if trySuccess.get != null && predicate(v) =>
              changed = trySuccess(Some(v))
            case _ =>
          }
        } finally {
          if (count == 0 && !changed) { trySuccess(None); () }
        }
      }
      futures.foreach { fut =>
        unfinishedCounter.incrementAndGet
        fut.onComplete(completeHandler)(executor)
      }
      // reverts temporary incrementation and checks corner case
      if (unfinishedCounter.decrementAndGet == 0) trySuccess(None)

      result.future
    }
  }
```

**Comment by NthPortal** [comment] 2021-02-17 19:30
hmm... it seems that the worse performance would be present in 2.13 as well

**Comment by NthPortal** [comment] 2021-02-17 19:40
I feel like we can have a bit of a simpler implementation than yours @matepek 

```scala
  def find[T](futures: Iterable[Future[T]])(p: T => Boolean)(implicit executor: ExecutionContext): Future[Option[T]] = {
    if (futures.isEmpty) successful[Option[T]](None)
    else {
      val result = Promise[Option[T]]()
      val ref = new AtomicInteger(-1) // once we set callbacks, we'll add `count + 1` and do a check
      val search: Try[T] => Unit = v => try {
        v match {
          case Success(r) if p(r) => result tryComplete Success(Some(r))
          case _ =>
        }
      } finally {
        if (ref.decrementAndGet == 0) {
          result tryComplete Success(None)
        }
      }

      var count = 0
      futures.foreach { f => { f onComplete search; count += 1 })
      if (ref.addAndGet(count + 1) == 0) { // all the callbacks have already been executed
        result tryComplete Success(None)
      }

      result.future
    }
  }
```

**Comment by matepek** [comment] 2021-02-18 04:26
Hello @NthPortal,

Although your code is less complicated there are two differences between your (which is almost the same as the deprecated `Future.find`) and my implementation.

1) `predicate`/`p` evaluates "only" if the promise is not completed. ("only" is an approximation of course). This is a semantic change but can save cpu time.

2) usage of `AtomicReference` which I believe will save more cpu time in case of `scala.concurrent.impl.DefaultPromise` (should be measured)

The usage of negative values for AtomicInteger seems a smart idea but I'm not sure it's good enough.

I'm just thinking out loud about of how could the negative value be a problem:

```scala
class MyIterator(var n: Long, max: Long) extends Iterator[Future[Long]] {
  override def hasNext: Boolean = n <= max
  override def next(): Future[Long] = {
    val curr = n
    n += 1
    Future.successful(curr)
  }
}

class MyIterable(init: Long, max: Long) extends Iterable[Future[Long]] {
  override def iterator: Iterator[Future[Long]] = new MyIterator(init, max)
}

Future.find(new MyIterable(0, (1L << 32) + 1))
```
🤷‍♂️

**Comment by SethTisue** [comment] 2021-04-14 16:18
duplicate of #11827

**Closed by SethTisue** 2021-04-14 16:18 UTC
Labels: concurrency
