### ISSUE TITLE
StackOverflow Error during compilation using a library written in Kotlin.

### ISSUE THREAD

**Issue by pmjpawelec** [scala/bug#12037] opened 2020-06-12 22:07 UTC
## reproduction steps
https://gitlab.com/hemol33/zircon-stack

using Scala 2.13.2 on macOs

## problem

Compilation ends with StackOverflow Exception.

**Comment by NthPortal** [comment] 2020-06-13 03:40
the relevant exception:

```scala
java.lang.StackOverflowError
        at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1033)
        at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1032)
        at scala.reflect.internal.Types$Type.findMember(Types.scala:1037)
        at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:666)
        at scala.reflect.internal.Types$Type.nonPrivateMember(Types.scala:637)
        at scala.reflect.internal.Types.rebind(Types.scala:3980)
        at scala.reflect.internal.Types.typeRef(Types.scala:4061)
        at scala.reflect.internal.Types.typeRef$(Types.scala:4055)
        at scala.reflect.internal.Symbols$TypeSymbol.newTypeRef(Symbols.scala:3176)
        at scala.reflect.internal.Symbols$TypeSymbol.typeConstructor(Symbols.scala:3198)
        at scala.reflect.internal.Symbols$TypeSymbol.tpeHK(Symbols.scala:3201)
        at scala.reflect.internal.Types.copyTypeRef(Types.scala:4084)
        at scala.reflect.internal.Types.copyTypeRef$(Types.scala:4078)
        at scala.reflect.internal.SymbolTable.copyTypeRef(SymbolTable.scala:28)
        at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.toType(TypeMaps.scala:766)
        at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.toType(TypeMaps.scala:762)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.subst(TypeMaps.scala:704)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.substFor$1(TypeMaps.scala:729)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:744)
        at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:789)
        at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:762)
        at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2367)
        at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
        at scala.reflect.internal.Types$Type.substSym(Types.scala:750)
        at scala.reflect.internal.Types$ExistentialType.mapOver(Types.scala:3214)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:728)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:666)
        at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2367)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:728)
        at scala.reflect.internal.Types$Type.subst(Types.scala:740)
        at scala.reflect.internal.Types$Type.instantiateTypeParams(Types.scala:486)
        at scala.reflect.internal.Types$TypeRef.seenFromOwnerInstantiated$1(Types.scala:2486)
        at scala.reflect.internal.Types$TypeRef.relativize(Types.scala:2490)
        at scala.reflect.internal.Types$TypeRef.$anonfun$baseTypeSeqImpl$2(Types.scala:2615)
        at scala.reflect.internal.BaseTypeSeqs$BaseTypeSeq.map(BaseTypeSeqs.scala:157)
        at scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2615)
        at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef(Types.scala:2789)
        at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef$(Types.scala:2780)
        at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:28)
        at scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2622)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getClassParts$1(Implicits.scala:1359)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1394)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.$anonfun$companionImplicitMap$10(Implicits.scala:1395)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1395)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getClassParts$1(Implicits.scala:1362)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1394)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.$anonfun$companionImplicitMap$10(Implicits.scala:1395)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1395)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getClassParts$1(Implicits.scala:1362)
        at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.getParts$1(Implicits.scala:1394)
```

**Comment by joroKr21** [comment] 2020-06-13 12:37
Duplicate of #11775?

**Comment by NthPortal** [comment] 2020-06-14 08:43
@joroKr21 it seems like it, though I'm having trouble figuring out where the generic F-bounded type is

**Comment by dwijnand** [comment] 2020-11-18 16:40
Closing as duplicate, in the absence of clear evidence that it's distinct.

**Closed by dwijnand** 2020-11-18 16:40 UTC
