### ISSUE TITLE
-Ywarn-unused false positive for trait with default method implementation

### ISSUE THREAD

**Issue by ddrozdov** [scala/bug#10347] opened 2017-06-01 14:30 UTC
Given the following code:
```scala
trait T {
  def f(arg: String): String = ""
}

class C extends T {
  override def f(arg: String): String = arg
}
```

A warning is reported with Scala 2.12.2:
```
$ ./scalac -Ywarn-unused c.scala 
c.scala:2: warning: parameter value arg in method f is never used
  def f(arg: String): String = ""
        ^
one warning found
```

There is the same issue if an abstract class is used instead of the trait.

Compiling with `-Ywarn-unused:-params` works fine as well as compiling with Scala 2.12.1.

**Comment by ddrozdov** [comment] 2017-06-01 14:33
This seems to be related to https://github.com/scala/scala/pull/5402

**Comment by ddrozdov** [comment] 2017-06-01 14:59
There is also a similar kind of issue with implicit arguments:
```scala
trait T {
  def f[A](arg: A)(implicit m: Manifest[A]): String = ""
}

class C extends T {
  override def f[A](arg: A)(implicit m: Manifest[A]): String = s"${m.runtimeClass.toString} - ${arg.toString}"
}
```

```
$ ./scalac -Xlint -Ywarn-unused:-params,_ c.scala 
c.scala:2: warning: parameter value m in method f is never used
  def f[A](arg: A)(implicit m: Manifest[A]): String = ""
                            ^
one warning found
```

The workaround is to use `-Xlint:-unused -Ywarn-unused:-params,-implicits,_`. And again Scala 2.12.1 works fine here.

**Comment by som-snytt** [comment] 2017-06-01 16:24
It doesn't warn about a "deprecated" parameter.

```
scala> :se -Ywarn-unused:params

scala> :pa
// Entering paste mode (ctrl-D to finish)

trait T {
  def f(arg: String): String = ""
}

class C extends T {
  override def f(arg: String): String = arg
}

// Exiting paste mode, now interpreting.

<pastie>:13: warning: parameter value arg in method f is never used
         def f(arg: String): String = ""
               ^
defined trait T
defined class C

scala> :pa
// Entering paste mode (ctrl-D to finish)

trait T {
  def f(@deprecated("unused","") arg: String): String = ""
}

class C extends T {
  override def f(arg: String): String = arg
}

// Exiting paste mode, now interpreting.

defined trait T
defined class C
```

**Comment by som-snytt** [comment] 2017-06-01 17:13
Closing because it works as intended. One might wish for an `@unused` annotation instead of deprecated. There is a separate issue about "how do I suppress a warning at this location?"

**Closed by som-snytt** 2017-06-01 17:13 UTC

**Comment by ddrozdov** [comment] 2017-06-01 18:03
Looks a bit confusing since in fact the argument is not "unused" - it is used in the trait implementation. But anyway thanks for the workaround.

**Comment by som-snytt** [comment] 2017-06-01 19:29
Yes, global analysis would know that. Maybe the message could be tweaked to be more precise. "Parameter is not used in method body." Never say never!

**Comment by 14mr0n** [comment] 2017-07-27 08:11
This behaviour is very annoying, if you want to turn on warnings to be handled as errors.
Why is there no global analysis for this?
You say it is intended, but I doubt the intention.
Really ugly in my eyes, even with a better warning or unused annotation.
It makes `-Xfatal-warnings`for projects of non trivial size unuseable.

**Comment by jvican** [comment] 2017-07-27 08:15
The problem here is that there should be better configuration for warnings in the compiler, not this specific error, which seems reasonable given the limitations of the implementation.
  
@14mr0n You can always open a PR and take a shot at improving it. Or adding better warning configuration. There are lots of tickets / discussions about it.

**Comment by som-snytt** [comment] 2017-07-27 18:50
@14mr0n For a given implementation, `def f(x: X) = ???`, `x` is unused and could indicate a dumb mistake. In that sense, global analysis is irrelevant. There are syntaxes to work around, such as `def f(x: Int) = { locally(x) ; () }`, which avoids "pure expression in statement position".

For the narrower case of a sealed hierarchy, raising a ticket not to warn about a "default" implementation would be reasonable. So this would not warn:

```
sealed trait X { def f(x: Int) = () } ; class Y extends X { override def f(x: Int) = println(x) }
```
Would it never warn, if the concrete class disregards the parameter? Lots of wrinkles to iron out.

**Comment by vendethiel** [comment] 2017-08-29 16:07
> Would it never warn, if the concrete class disregards the parameter? Lots of wrinkles to iron out.

could maybe allow `def f(_: Int)` then? Not sure if this was discussed someplace else.

**Comment by hedefalk** [comment] 2018-05-11 13:19
>There is a separate issue about "how do I suppress a warning at this location?"
Could I ask where? I'm looking, but can't seem to find it.

I really want to enable warnings for unused explicit params in a pretty large piece of code. I immediately struck this case though which to me is just a false positive. We seem to have quite a few of these. I do not like the idea of using a deprecation warning for this since it's just not semantically correct. Its not deprecated, just there as part of a contract.

>could maybe allow def f(_: Int) then? Not sure if this was discussed someplace else.
This was the first thing I reached for intuitively, would have made perfect Scala sense :)

**Comment by SethTisue** [comment] 2018-05-11 13:44
> > There is a separate issue about "how do I suppress a warning at this location?"

> Could I ask where? I'm looking, but can't seem to find it.

https://github.com/scala/bug/issues/7934

> I do not like the idea of using a deprecation warning for this since it's just not semantically correct

Sam's suggestion at https://github.com/scala/bug/issues/10790 makes it a little nicer, that's what I would suggest for now

**Comment by hedefalk** [comment] 2018-05-11 13:57
@SethTisue Thanks!

**Comment by som-snytt** [comment] 2018-05-11 14:38
The other workaround:
```
trait U {
  def f(arg: String): String
}
trait T extends U {
  def f(arg: String): String = ""
}
class C extends T {
  override def f(arg: String): String = arg
}
```
