### ISSUE TITLE
2.13.2 regression: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving type BuilderType

### ISSUE THREAD

**Issue by thesamet** [scala/bug#12038] opened 2020-06-14 04:56 UTC
## reproduction steps

using Scala (2.13.2),

```build.sbt:
scalaVersion := "2.13.2"

libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-reflect" % scalaVersion.value,
  "com.google.protobuf" % "protobuf-java" % "3.11.4"
)
```

```scala
package foo

import scala.reflect.runtime.universe
import com.google.protobuf.DescriptorProtos.FileDescriptorProto

object Hello {
  def fromJava(t: FileDescriptorProto): Unit = {}
}

object Main {
  def main(args: Array[String]): Unit = {
    val mirror = universe.runtimeMirror(getClass.getClassLoader())

    println(
      mirror.reflectModule(
        mirror.staticModule("foo.Hello$"))
      .instance)
  }
}
```

## problem

when running:
```
[info] running foo.Main
[error] (run-main-b) scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving type BuilderType
```

The above works for 2.13.1 and 2.12.x.

Impact: this prevents updating ScalaPB to 2.13.2

**Comment by som-snytt** [comment] 2020-06-14 07:12
Looks like https://github.com/scala/scala/pull/8460 in so far as I reverted https://github.com/scala/scala/commit/4d377f1b7af6d62f3c2a4c80bcde2cc4e138a3a6#diff-70941ddb34bf0f19147df45ff6c8527cR1130 and it worked.

For debug, the stack trace is turned on by
```
    val universe = ru.asInstanceOf[scala.reflect.runtime.JavaUniverse]
    universe.settings.asInstanceOf[scala.reflect.internal.settings.MutableSettings].debug.value = true
```
and figuring that out blew my time budget. The economists have revised their estimate of how much debt as a percentage of GDP is sustainable, and I wonder if they have done that for technical debt.

I knew there were improvements to Java interop, but for the record I did not guess this commit by grepping for `What does this mean?`

**Comment by som-snytt** [comment] 2020-06-14 07:46
@SethTisue @hrhino if this is a one-line fix, it may be a good candidate for 2.13.3 if that is still in progress.

**Comment by SethTisue** [comment] 2020-06-15 20:42
@dwijnand will follow up with @hrhino soon

**Comment by hrhino** [comment] 2020-06-16 00:53
Yes, I'll have a look. Somehow I doubt it's a one-liner but perhaps I'll be lucky.

**Comment by hrhino** [comment] 2020-06-16 11:27
Hi @thesamet, does ScalaPB use runtime reflection as part of the library, or only in its tests?

**Comment by thesamet** [comment] 2020-06-16 14:01
Only in tests.

**Comment by ShaneDelmore** [comment] 2020-06-30 18:02
I believe I just ran into the same issue testing out 2.12.11 and 2.12.12-bin-6e2f336, but it works in 2.12.10.  Was some of this code backported to 2.12.11?

**Comment by ShaneDelmore** [comment] 2020-06-30 18:10
I just verified with Scastie (what an awesome tool!) that this reproduction succeeds with 2.12.10 and fails with 2.12.11 https://scastie.scala-lang.org/cbhpeqZGSP2bnxrq53dphg

**Comment by SethTisue** [comment] 2020-06-30 18:23
@ShaneDelmore I don't understand why, but when I download that scastie and (after commenting out the scastie-specific dependencies) run it locally, I don't get the errors:

```
sbt:cbhpeqzgsp2bnxrq53dphg> clean
[success] Total time: 0 s, completed Jun 30, 2020 11:22:34 AM
sbt:cbhpeqzgsp2bnxrq53dphg> show scalaVersion
[info] 2.12.11
sbt:cbhpeqzgsp2bnxrq53dphg> compile
[info] Compiling 1 Scala source to /Users/tisue/Desktop/cbhpeqZGSP2bnxrq53dphg/target/scala-2.12/classes ...
[success] Total time: 0 s, completed Jun 30, 2020 11:22:39 AM
```

**Comment by SethTisue** [comment] 2020-06-30 18:25
> Was some of this code backported to 2.12.11?

our current working hypothesis is that the PR responsible is https://github.com/scala/scala/pull/8460 which was included in both 2.12.11 and 2.13.2 (it was merged forward from 2.12.x to 2.13.x)

**Comment by ShaneDelmore** [comment] 2020-06-30 19:21
Thanks for confirming Seth.  I also noticed the scastie fails the first time, then succeeds after that but was hoping the link would still show the error on first opening.

**Comment by ShaneDelmore** [comment] 2020-06-30 19:22
Also, if you end up with a nightly with that PR reverted or a fix, post it and I'll test it out as it looks like I'll just skip 2.12.11 but if possible will upgrade to 2.12.12.

**Comment by SethTisue** [comment] 2020-06-30 20:00
> but was hoping the link would still show the error on first opening

I do see the error in-browser, I'm not just not able to reproduce it locally (not even once)

> Also, if you end up with a nightly with that PR reverted or a fix, post it and I'll test it out as it looks like I'll just skip 2.12.11 but if possible will upgrade to 2.12.12.

sounds good, we'll comment on this ticket if it progresses. you'll probably want to follow https://contributors.scala-lang.org/t/coming-soon-scala-2-12-12/4371 as well

**Comment by som-snytt** [comment] 2020-06-30 23:21
@SethTisue you forgot to say `run`.

It took me a minute to remember where I stashed the test project, but I confirmed it regressed in 2.12.11.

Also as @ShaneDelmore pointed out, it only fails the first time. Maybe Seth can add that to the release notes, making it a one-line fix.

```
package p

import scala.reflect.runtime.currentMirror
import com.google.protobuf.DescriptorProtos.FileDescriptorProto

object Hello {
  def fromJava(t: FileDescriptorProto): Unit = ()
}

object Main extends App {
  def f() =
    try currentMirror.reflectModule(currentMirror.staticModule("p.Hello$")).instance
    catch { case t: Throwable => s"ugh, $t" }

  println(f())
  println(f())
}
```

**Comment by mpollmeier** [comment] 2021-01-15 03:59
I ran into this as well and can confirm that a simple 'retry once' logic works as a workaround. It's obviously not pretty though. 

Proposal: until we have a proper fix, maybe we should move the retry logic into the scala.reflection implementation, to not bother ever single user with this ugly issue? (I'm aware that this means that we'll probably never have a proper fix.)
Thoughts?

**Comment by smarter** [comment] 2021-01-31 17:12
FYI, this issue lead to spark reverting their Scala 2.12 upgrade: https://github.com/apache/spark/pull/31223

**Comment by retronym** [comment] 2021-02-02 00:46
Instrumenting runtime reflection type completion a little shows the context that leads to the cycle.

```
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving type BuilderType
ugh, scala.reflect.internal.Types$TypeError: During typeToScala(class com.google.protobuf.DescriptorProtos$FileDescriptorProto, )
Caused by: scala.reflect.internal.Types$TypeError: During typeToScala(class com.google.protobuf.GeneratedMessageV3$FieldAccessorTable, )
Caused by: scala.reflect.internal.Types$TypeError: During typeToScala(interface com.google.protobuf.AbstractMessage$BuilderParent, )
Caused by: scala.reflect.internal.Types$TypeError: During typeToScala(class com.google.protobuf.AbstractMessageLite, )
Caused by: scala.reflect.internal.Types$TypeError: During typeToScala(com.google.protobuf.AbstractMessageLite$Builder<MessageType, BuilderType>, upper bound of type param BuilderType)
Caused by: scala.reflect.internal.Types$TypeError: During typeToScala(class com.google.protobuf.AbstractMessageLite, ParameterizedType#ownerType)
Caused by: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving type BuilderType
```

I'll use this to extract the relevant parts of the Java hierarchy into a test case.

The one-line fix is indeed to revert https://github.com/scala/scala/commit/4d377f1b7af6d62f3c2a4c80bcde2cc4e138a3a6#diff-ea9625e7b05a71c8ac4182c50918fd24c849f695c0c6c8354a3141f182971186L1130. That doesn't break the enclosed tests, but I assume that @hrhino came to the change for good reasons with manual testing and the test suite is deficient here.

**Comment by retronym** [comment] 2021-02-02 04:42
```java
package p1;

public class J_1 {
    public abstract static class AbstractMessageLite<
            BuilderType extends AbstractMessageLite.Builder<BuilderType>> {

        public abstract static class Builder<BuilderType extends Builder<BuilderType>>{

        }
    }

}
```

```scala
 qscala -cp /tmp
Welcome to Scala 2.12.14-20210128-150406-5f6e5a1 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> scala.reflect.runtime.currentMirror.staticClass("p1.J_1.AbstractMessageLite").info
scala.reflect.internal.Types$TypeError: while completing p1.J_1.AbstractMessageLite.BuilderType
  at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1554)
  at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$4.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:194)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
  at scala.reflect.runtime.Gil.gilSynchronized(Gil.scala:31)
  at scala.reflect.runtime.Gil.gilSynchronized$(Gil.scala:26)
  at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:30)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:149)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.gilSynchronizedIfNotThreadsafe$(SynchronizedSymbols.scala:145)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$4.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:194)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:158)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$4.info(SynchronizedSymbols.scala:194)
  at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1701)
  at scala.reflect.internal.Definitions$DefinitionsClass.fullyInitializeSymbol(Definitions.scala:229)
  at scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$fullyInitializeType$1(Definitions.scala:239)
  at scala.collection.immutable.List.foreach(List.scala:431)
  at scala.reflect.internal.Definitions$DefinitionsClass.fullyInitializeType(Definitions.scala:239)
  at scala.reflect.internal.Types$Type.toString(Types.scala:948)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:272)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:277)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:285)
  at .lzycompute(<console>:9)
  at .$print(<console>:6)
  at $print(<console>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:755)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1028)
  at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:576)
  at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
  at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
  at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:575)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:602)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:865)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:733)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:435)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:456)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:1048)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:89)
  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: scala.reflect.internal.Types$TypeError: During typeToScala(type var upper bound, BuilderType)(p1.J_1$AbstractMessageLite$Builder<BuilderType>)
  at scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScalaDescribed(JavaMirrors.scala:1155)
  at scala.reflect.runtime.JavaMirrors$JavaMirror$TypeParamCompleter.$anonfun$complete$1(JavaMirrors.scala:706)
  at scala.collection.immutable.List.map(List.scala:293)
  at scala.reflect.runtime.JavaMirrors$JavaMirror$TypeParamCompleter.complete(JavaMirrors.scala:706)
  at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1551)
  ... 47 more
Caused by: scala.reflect.internal.Types$TypeError: During typeToScala(generic applied type owner of, p1.J_1$AbstractMessageLite$Builder<BuilderType>)(class p1.J_1$AbstractMessageLite)
  at scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScalaDescribed(JavaMirrors.scala:1155)
  at scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScalaDescribed(JavaMirrors.scala:1144)
  ... 51 more
Caused by: scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving type BuilderType
  at scala.reflect.internal.Symbols$Symbol.$anonfun$completeInfo$3(Symbols.scala:1532)
  at scala.Function0.apply$mcV$sp(Function0.scala:39)
  at scala.reflect.internal.Symbols$Symbol.lock(Symbols.scala:580)
  at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1530)
  at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$4.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:194)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
  at scala.reflect.runtime.Gil.gilSynchronized(Gil.scala:31)
  at scala.reflect.runtime.Gil.gilSynchronized$(Gil.scala:26)
  at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:30)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:149)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.gilSynchronizedIfNotThreadsafe$(SynchronizedSymbols.scala:145)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$4.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:194)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:158)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
  at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$4.info(SynchronizedSymbols.scala:194)
  at scala.reflect.internal.Types.$anonfun$typeParamsToExistentials$1(Types.scala:3922)
  at scala.collection.immutable.List.map(List.scala:293)
  at scala.reflect.internal.Types.typeParamsToExistentials(Types.scala:3921)
  at scala.reflect.internal.Types.typeParamsToExistentials$(Types.scala:3920)
  at scala.reflect.internal.SymbolTable.typeParamsToExistentials(SymbolTable.scala:28)
  at scala.reflect.internal.Types.typeParamsToExistentials(Types.scala:3928)
  at scala.reflect.internal.Types.typeParamsToExistentials$(Types.scala:3927)
  at scala.reflect.internal.SymbolTable.typeParamsToExistentials(SymbolTable.scala:28)
  at scala.reflect.internal.tpe.TypeMaps$$anon$1.apply(TypeMaps.scala:360)
  at scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScalaDescribed(JavaMirrors.scala:1139)
  ... 52 more

scala>
```

**Closed** 2021-02-02 11:05 UTC
Labels: has PR, regression

**Comment by som-snytt** [comment] 2021-02-02 11:26
Practically a one-line fix after all.
