### ISSUE TITLE
Compiles successfully when need pass an arg with java Object type

### ISSUE THREAD

**Issue by changvvb** [scala/bug#12363] opened 2021-03-18 12:00 UTC
## reproduction steps

using Scala (add version here),
```java
public class TestJava {
    public boolean contains(Object o) {
        return false;
    }
}
```

```scala
object TestScala {
  val obj = new TestJava
  obj.contains()
}
```

## problem
Compiles successfully, but expect an error.
I see the bytecode, and the compiler passes a `Unit` to `TestJava#contains`.

```asm
public static {};
    descriptor: ()V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=2, locals=0, args_size=0
         0: new           #2                  // class TestScala$
         3: dup
         4: invokespecial #19                 // Method "<init>":()V
         7: putstatic     #21                 // Field MODULE$:LTestScala$;
        10: new           #23                 // class TestJava
        13: dup
        14: invokespecial #24                 // Method TestJava."<init>":()V
        17: putstatic     #26                 // Field obj:LTestJava;
        20: getstatic     #21                 // Field MODULE$:LTestScala$;
        23: invokevirtual #29                 // Method obj:()LTestJava;
        26: getstatic     #35                 // Field scala/runtime/BoxedUnit.UNIT:Lscala/runtime/BoxedUnit;
        29: invokevirtual #39                 // Method TestJava.contains:(Ljava/lang/Object;)Z
        32: pop
        33: return
      LineNumberTable:
        line 2: 0
        line 3: 10
        line 4: 20
        line 2: 33

```

**Comment by changvvb** [comment] 2021-03-18 12:08
I also test `contains` method in scala, and find
```scala
class TestAny {
  def contains(obj:Any):Boolean = false
}

class TestAnyRef {
  def contains(obj:AnyRef):Boolean = false
}

object TestScala {
  val obj = new TestJava
  obj.contains()

  val obj2 = new TestAny()
  obj2.contains()  // OK

  val obj3 = new TestAnyRef()
  obj3.contains()  // ERROR

}
```

I think `def contains(obj:AnyRef):Boolean` should be coincide  with `public boolean contains(Object o)`.

**Comment by lrytz** [comment] 2021-03-18 12:11
In current Scala (2.13.5) you get a warning:

```scala
scala> val t = new Test
val t: Test = Test@7a04f730

scala> t.contains()
                 ^
       warning: adaptation of an empty argument list by inserting () is deprecated: leaky (Object-receiving) target makes this especially dangerous
               signature: Test.contains(x$1: Object): Boolean
         given arguments: <none>
        after adaptation: Test.contains((): Unit)
val res1: Boolean = false
```

We treat `Object` in Java as `Any` in Scala for convenience; otherwise, a generic Java method or collection could not be used with Scala primitives (I *think* this is the reason, not entirely sure).

**Comment by Jasper-M** [comment] 2021-03-18 12:11
This is essentially a duplicate of #9278.

**Closed** 2021-03-18 12:12 UTC

**Comment by changvvb** [comment] 2021-03-18 15:33
Thanks, @lrytz @Jasper-M.

But I found we must execute `scalac` with `-deprecation` to show the full warning.

**Comment by som-snytt** [comment] 2021-03-18 16:28
Worth documenting that `-Xlint` enables `-deprecation`. REPL also enables it by default.

There is probably an easy `-Wconf` just to turn deprecation into error. `-Wconf:cat=deprecation:e`

Also, `-Xsource:3` adds more bite.
```
➜  ~ scala -Xsource:3
Welcome to Scala 2.13.4 (OpenJDK 64-Bit Server VM, Java 16).
Type in expressions for evaluation. Or try :help.

scala> List(42).contains()
                        ^
       error: adaptation of an empty argument list by inserting () has been removed
               signature: List.contains[A1 >: A](elem: A1): Boolean
         given arguments: <none>
```
Compare
```
➜  ~ scala -Wconf:cat=deprecation:e
Welcome to Scala 2.13.4 (OpenJDK 64-Bit Server VM, Java 16).
Type in expressions for evaluation. Or try :help.

scala> List(42).contains()
                        ^
       error: adaptation of an empty argument list by inserting () is deprecated: this is unlikely to be what you want
               signature: List.contains[A1 >: A](elem: A1): Boolean
         given arguments: <none>
        after adaptation: List.contains((): Unit)
```
