### ISSUE TITLE
scalac hangs in phase typer

### ISSUE THREAD

**Issue by gdiet** [scala/bug#12371] opened 2021-04-12 11:38 UTC
Using Scala 2.13.5 (on Ubuntu Java 11.0.10 x64)

```scala
object CompileHangs {
  def read1(): LazyList[Either[(Int, Int), String]] = ???
  def read2(): Option[LazyList[Either[(Int, Int), String]]] = ???

  def read(): LazyList[Either[(Int, Int), String]] =
    read1().flatMap {
      case Right(_) => LazyList()
      case Left(value) =>
        read2().getOrElse(
          Vector(Left(value))
        )
    }
}
```

compiling with `scalac` hangs in the typer phase (as shown by `scalac  -Ydebug`). Additional observations:

* I would expect a type error in the line containing `Vector`.
* If I replace the tuple `(Int, Int)` with a simple `Int`, the example compiles. I would have expected the type error, but maybe there is some implicit conversion at work here?
* If I replace `Vector` with `LazyList`, everything works as expected.

**Comment by joroKr21** [comment] 2021-04-12 12:20
That looks like a duplicate of #10908

**Closed** 2021-04-12 14:15 UTC
