### ISSUE TITLE
A bug of mutable.Set.contains method.

### ISSUE THREAD

**Issue by sunglowlee** [scala/bug#10847] opened 2018-04-25 13:24 UTC
The mutable.Set.contains method returns true for a new element which has different content and hashCode from existing elements in the set. The problem occurs many times. 
scala version: 2.12.5/ 2.12.3, OS:Windows 10, IDE: IntelliJ IDEA 2018.1. [JDK:1.8.0_77]
(https://docs.qq.com/doc/BrmBEC1dprKo0sQLCh0sfriJ2cumzw2IChzJ0 )

**Comment by sunglowlee** [comment] 2018-04-25 15:32
I used java.util.HashSet instead and solved the problem. It seems that there does exist something wrong with scala.collection.mutable.Set.

**Comment by Jasper-M** [comment] 2018-04-25 15:44
Do you have a self contained piece of code that shows this issue?

**Comment by sunglowlee** [comment] 2018-04-25 15:57
The program is a little big and complicated. I am using Scala to build a graph query engine. I used shared memory to contain and manipulate the data. It is hard to find a small piece of code containing the errors. The problem might occur when multiple events are handled concurrently, even though I have already put the related code in the synchronized section. 
Once I replaced the mutable.Set with java.util.HashSet (quite clumsy to embed HashSet into scala codes), the errors are gone at all. With mutable.Set, the problem occurs in a small dataset containing 5 records. Now with the HashSet, a big dataset containing 100,000 records can smoothly run without the problem.

**Comment by SethTisue** [comment] 2018-04-26 07:02
it's entirely possible that there is a bug in scala.collection.mutable.Set, but there's nothing actionable here unless we can reproduce the problem.

**Comment by Ichoran** [comment] 2018-04-26 13:57
I think it is rather unlikely that mutable.Set has a bug that shows up with five elements unless the set is being used in cases that it doesn't support (e.g. concurrent access), but it wouldn't surprise me if `java.util.HashSet` is more forgiving of those use cases.

**Comment by szeiger** [comment] 2018-10-19 09:49
For the record, I did not encounter any such issue while refactoring `HashSet` and `FlatHashTable` recently. It can do the opposite though: `mutable.HashSet` uses `hashCode` instead of `##` and will therefore not treat numeric values of different numeric types as equal.

**Comment by SethTisue** [comment] 2018-10-19 15:21
closing since this isn't actionable without a reproducer

**Closed by SethTisue** 2018-10-19 15:21 UTC
