### ISSUE TITLE
scala object don't support inheritance but in scala reference java class parent class static methods and static variable not  available

### ISSUE THREAD

**Issue by MrDLontheway** [scala/bug#11230] opened 2018-10-30 07:50 UTC
```
object AccumuloTest {
  def main(args: Array[String]): Unit = {
    //无法引用 父类静态方法
    Tjava.sayHello()
    Tjava.TJavaSayHello()

    //无法引用继承的静态变量
    val v = Tjava.v1
    val v1 = new Tjava
    Test1.MysayHello()
    //无法引用 父类静态方法
    Test1.sayHello()
  }

}

public class Father {
    public static String v1 = "haha";
    public static void sayHello() {
        System.out.println("hello");
    }
}

object Test1 extends Test2{
  def MysayHello(): Unit = {
    System.out.println("hello")
  }
}

public class Test2 {
    public static void sayHello(){
        System.out.println("hello");
    }
}

//object 不支持 继承object
object Test3 extends Test4{
  def MysayHello(): Unit = {
    System.out.println("hello")
  }
}

object Test4 {
  def sayHello(): Unit = {
    System.out.println("hello")
  }
}


public class Tjava extends Father{
    public static void TJavaSayHello(){
        System.out.println("tjava hello");
    }
    public static void main(String[] args) {
        Tjava.sayHello();
        Tjava.TJavaSayHello();

    }
}
```
[problem.txt](https://github.com/scala/bug/files/2528534/problem.txt)

**Comment by MrDLontheway** [comment] 2018-10-30 09:52
object AccumuloTest {
  def main(args: Array[String]): Unit = {
    //无法引用 父类静态方法
    Tjava.sayHello()
    Tjava.TJavaSayHello()

    //无法引用继承的静态变量
    val v = Tjava.v1
    val v1 = new Tjava
    Test1.MysayHello()
    //无法引用 父类静态方法
    Test1.sayHello()
  }

}

public class Father {
    public static String v1 = "haha";
    public static void sayHello() {
        System.out.println("hello");
    }
}

object Test1 extends Test2{
  def MysayHello(): Unit = {
    System.out.println("hello")
  }
}

public class Test2 {
    public static void sayHello(){
        System.out.println("hello");
    }
}

//object 不支持 继承object
object Test3 extends Test4{
  def MysayHello(): Unit = {
    System.out.println("hello")
  }
}

object Test4 {
  def sayHello(): Unit = {
    System.out.println("hello")
  }
}


public class Tjava extends Father{
    public static void TJavaSayHello(){
        System.out.println("tjava hello");
    }
    public static void main(String[] args) {
        Tjava.sayHello();
        Tjava.TJavaSayHello();

    }
}

**Comment by Jasper-M** [comment] 2018-10-30 13:30
Possibly a duplicate of #11226?

**Comment by SethTisue** [comment] 2018-10-30 13:38
which is itself a duplicate of https://github.com/scala/bug/issues/9272

**Closed by SethTisue** 2018-10-30 13:38 UTC

**Comment by HiIcy** [comment] 2020-07-01 02:52
@MrDLontheway  请问现在有好的解决方案吗，我最近也遇到这个问题/(ㄒoㄒ)/~~

**Comment by SethTisue** [comment] 2020-07-01 03:05
@Hilcy please use #9272 for discussion
