### ISSUE TITLE
knownDirectSubclasses regression in 2.11.9+, incl. 2.12.x

### ISSUE THREAD

**Issue by lloydmeta** [scala/bug#10330] opened 2017-05-22 15:15 UTC
As I was investigating a bug in Circe auto coded derivation, I confirmed what @witi83 [mentioned](https://github.com/lloydmeta/enumeratum/issues/90#issuecomment-295875285) a while ago; that in releases after 2.11.8, there seems to be a regression in the way `knownDirectSubclasses` behaves.

For example, in [this repository](https://github.com/lloydmeta/circe-auto-derive-repro#how-to-make-it-work), compilation will fail with 2.12.x and 2.11.11, but will pass under 2.11.8 and run fine to boot.

**Comment by milessabin** [comment] 2017-05-22 15:28
Do you have a minimization which doesn't have a circe dependency?

**Comment by lloydmeta** [comment] 2017-05-22 17:25
Sadly no, I haven't been able to minimise it further. If I manage to, I'll update this ticket.

**Comment by mahe-ymc** [comment] 2017-07-28 11:30
We observe the exact same behaviour without circe but with https://github.com/sksamuel/avro4s

**Comment by chwthewke** [comment] 2017-09-05 21:54
If I may, I believe I have a repro of the bug with only shapeless as a dependency : https://github.com/chwthewke/si-10330 

It seems to be deterministic, at least under clean compile.

**Comment by milessabin** [comment] 2017-09-06 08:58
@chwthewke I can't reproduce the error in your test project following https://github.com/scala/scala/pull/6029 ... I think it's possible that that fixes the cases reported in this ticket too.

**Comment by chwthewke** [comment] 2017-09-06 13:54
I've been able to test with scala at the merge commit for 6029 and I concur. Thank you !

**Comment by milessabin** [comment] 2017-09-06 20:18
Closing this as fixed in https://github.com/scala/scala/pull/6029.

**Closed by milessabin** 2017-09-06 20:18 UTC

**Comment by bbarker** [comment] 2018-04-26 15:09
Not sure if I should open a new bug report for this. I just came across it this morning and I appear to be using Scala 2.12.4:

```
[IJ]> ~web-server/re-start
[info] Compiling 4 Scala sources to /home/brandon/workspace/ProjectGists/CCRS_knownDirectSubclasses/web-server/target/scala-2.12/classes...
[error] knownDirectSubclasses of FileCommand observed before subclass ExecFile registered
[error] one error found
[error] (web-server/compile:compileIncremental) Compilation failed
[error] Total time: 1 s, completed Apr 26, 2018 3:00:49 PM
```

I stripped down my project a bit and put it at: 
https://github.com/bbarker/ProjectGists/tree/master/Scala/CCRS_knownDirectSubclasses

**Comment by bbarker** [comment] 2018-04-27 11:58
I also get this error in the staged release for Scala 2.12.6
