### ISSUE TITLE
Scala REPL Cyrillic symbols incorrect output  

### ISSUE THREAD

**Issue by slesarev-hub** [scala/bug#12361] opened 2021-03-16 12:27 UTC
## reproduction steps

using Scala 2.13.5,

```scala
scala> val s="АБВГД"
val s: String = ?????

scala> sys.props("file.encoding")
val res0: String = UTF-8
```

## problem

Question marks instead of symbols. In previous Scala version output was correct.

**Comment by lrytz** [comment] 2021-03-16 12:40
This is a duplicate of https://github.com/scala/bug/issues/12360, it will be fixed in 2.13.6

**Closed by lrytz** 2021-03-16 12:40 UTC
