### ISSUE TITLE
When using """ strings you can have unescaped chars except if use  s"""

### ISSUE THREAD

**Issue by krmoore2010** [scala/bug#12345] opened 2021-02-17 10:37 UTC
## reproduction steps

using Scala (2.13.4),

val s = """ \ """    <- works fine
val s  = s"""  \ """  <- fails with   error: invalid escape '\ '

## problem

I would not expect prefixing the string with s  to change the way  """ works

**Comment by dwijnand** [comment] 2021-02-17 11:54
Duplicate of #6476

**Closed by dwijnand** 2021-02-17 11:54 UTC
