### ISSUE TITLE
compile:doc results in compilation error for static inner classes in java

### ISSUE THREAD

**Issue by NAJ10** [scala/bug#10419] opened 2017-07-20 13:35 UTC
[ReproduceScalaDoc.zip](https://github.com/scala/bug/files/1162418/ReproduceScalaDoc.zip)

When "sbt compile:doc" is run on the attached mixed Java/Scala sbt project (unzip ReproduceScalaDoc.zip) the following error is seen

```
[error] /home/user/Development/repository/ReproduceScalaDoc/src/main/java/example/Trade.java:13: not found: type Identifier
[error]     public Trade(Identifier id) {
[error]                  ^
[info] No documentation generated with unsuccessful compiler run
```

sbt compile produces no error.

This is seen with Scala versions 2.12.0, 2.12.1 and 2.12.2. The problem does not occur on Scala 2.11.11.

This example has been distilled from our applications very large code base which is a mixture of Scala and Java. The application is the product of over 15 years work. The problem was found in the course of migrating from Scala 2.11 to Scala 2.12.

It seems like static inner classes are not being handled correctly. A similar/identical problem occurs when enums are nested inside a Java class.

**Comment by SethTisue** [comment] 2017-07-20 13:40
workaround: you can restore the 2.11 behavior with `scalacOptions += "-no-java-comments"`

**Comment by lrytz** [comment] 2017-07-20 14:02
This is a duplicate of https://github.com/scala/bug/issues/9111, it works if you use specify the outer name when referencing class `Trade`

```
    public Trade(Trade.Identifier id) {
```

**Closed** 2017-07-20 14:28 UTC
Labels: java interop, scaladoc
