### ISSUE TITLE
Scala Toolbox eval is giving java.lang.StackOverflowError 

### ISSUE THREAD

**Issue by schikkam** [scala/bug#10388] opened 2017-06-22 13:19 UTC
Code : 
val rt = scala.reflect.runtime.universe.runtimeMirror(getClass.getClassLoader)
val tb = rt.mkToolBox()
val template1 = """val a = Array(1,2,3,4); for(i<-a){ println(s"i=${i}") } """
val t = tb.parse(template1)
val k = tb.eval(t) 

Please  copy/paste the code in Scala StyleSheet/Ammonite to reproduce the same! 
Scala Version : 2.12.1
Note: It used to work in older version of scala, but when I upgraded to 2.12, I started seeing exception, Looks like something is broken in the library! 

"eval" is causing Java.Lang.StackOverFlow , here is the trace info:

java.lang.StackOverflowError
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$$outer(test.sc0.tmp:17)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map$(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.map(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap$(test.sc0.tmp:28)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.lateMap(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$map(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.$anonfun$map$1(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map$(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.map(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap$(test.sc0.tmp:28)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.lateMap(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$map(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.$anonfun$map$1(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map$(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.map(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap$(test.sc0.tmp:28)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.lateMap(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$map(test.sc0.tmp:30)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.$anonfun$map$1(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map(test.sc0.tmp:23)
	at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map$(test.sc0.tmp:23)
	at Output exceeds cutoff limit.

**Comment by schikkam** [comment] 2017-06-22 13:23
Most Importantly, It is Shutting down the app, hope some one confirms this soon.! 
FYI : Here is the actual error within my application.
Uncaught error from thread [Scalar-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Scalar]
java.lang.StackOverflowError
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map$(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.map(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap$(SynchronizedOps.scala:32)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.lateMap(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$map(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.$anonfun$map$1(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map$(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.map(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap$(SynchronizedOps.scala:32)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.lateMap(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$map(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.$anonfun$map$1(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.map$(SynchronizedOps.scala:27)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.map(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq.lateMap$(SynchronizedOps.scala:32)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.lateMap(SynchronizedOps.scala:34)
        at scala.reflect.runtime.SynchronizedOps$SynchronizedBaseTypeSeq$$anon$2.scala$reflect$runtime$SynchronizedOps$SynchronizedBaseTypeSeq$$super$map(SynchronizedOps.scala:34)

**Comment by larsrh** [comment] 2017-06-22 15:49
I think this is a duplicate of #10026, which has been fixed in 2.12.2.

**Closed** 2017-06-22 16:56 UTC
