### ISSUE TITLE
Foo[F] not a subtype of Foo[F] forSome { type F[_] }

### ISSUE THREAD

**Issue by TomasMikula** [scala/bug#10258] opened 2017-04-10 20:52 UTC
Tested with Scala 2.12.1.

I have a type `Foo` parameterized by type `F[_]`. In some contexts, the type `F[_]` doesn't matter and I want to be able to talk about `Foo` without specifying what `F` is. In other contexts, `F` needs to be known.

One attempt to model this is to have `F[_]` as a type parameter of `Foo`, and use an existential type alias `type Foo0 = Foo[F] forSome { type F[_] }` for when `F` doesn't matter:

```scala
trait Foo[F[_]]

object Foo {
  type Foo0 = Foo[F] forSome { type F[_] }
}
```

(Another (failed) attempt at modeling this situation is in #10257, using a type member.)

**The problem** is that `Foo[F]` does not satisfy a requirement for an implicit `Foo0`. The type checker cannot even prove that `Foo[F] <:< Foo.Foo0`.

```scala
import Foo._

def f(implicit foo: Foo0): Unit =
  ()

def test[F[_]](implicit foo: Foo[F]): Unit = {
  // It is not even the case that
  implicitly[Foo[F] <:< Foo0] // error: Cannot prove that Foo[F] <:< Foo.Foo0

  // so then of course this gives an
  // error: could not find implicit value for parameter foo: Foo.Foo0
  f
}
```

**Comment by joroKr21** [comment] 2017-10-11 09:45
Isn't this a duplicate of #9445?

**Comment by joroKr21** [comment] 2017-10-11 11:22
It seems that there are two parts to the problem:
```scala
trait Functor[F[_]]
import scala.reflect.runtime.universe._
typeOf[Functor[Option]] <:< typeOf[Functor[F] forSome { type F[_] }] // false
typeOf[Functor[Option]].contains(symbolOf[Option[_]]) // false
```

**Comment by eparejatobes** [comment] 2017-10-11 11:32
this looks related to #4377

**Comment by joroKr21** [comment] 2017-10-11 12:33
I don't believe it is. Actually I think #4337 is not an issue, but the correct behaviour.

**Comment by milessabin** [comment] 2017-10-12 11:13
I think this is most likely fixed by https://github.com/scala/scala/pull/6122.

**Comment by milessabin** [comment] 2017-10-12 11:40
Actually, no it isn't ... https://github.com/scala/scala/pull/6123 is necessary.

**Closed** 2017-12-01 00:18 UTC
