### ISSUE TITLE
"Unable to locate class file for inner class"

### ISSUE THREAD

**Issue by elfprince13** [scala/bug#11062] opened 2018-08-08 15:39 UTC
I have two source files, one Java, one Scala.
The Java class definition is as follows:
```java
public class HeapNode<Elem> extends Node<HeapNode<Elem>> implements Cloneable {
	volatile LazyBraunHeapLF.NodeEvalState<Elem> state;
	
	HeapNode(LazyBraunHeapLF.NodeEvalState<Elem> initState){
		state = initState;
	}
	
	@SuppressWarnings("rawtypes")
	public static final AtomicReferenceFieldUpdater<HeapNode, LazyBraunHeapLF.NodeEvalState> updateState 
					= AtomicReferenceFieldUpdater.newUpdater(HeapNode.class, LazyBraunHeapLF.NodeEvalState.class, "state");

	
}
```
The Scala source contains the following:
```scala
object LazyBraunHeapLF {
	
	class EmptyNode[E] extends HeapNode[E](Empty[E]()){
		marked = true
	}
	
	sealed trait Immediate[E]{ this: NodeEvalState[E] =>
		def force:NodeEvalState[E] with Immediate[E] = this
	}
	
	sealed abstract class NodeEvalState[E] {
		def force: NodeEvalState[E] with Immediate[E]
	}
	
	case class Empty[E]() extends NodeEvalState[E] with Immediate[E]
	// The remainder is commented out for a M(N)WE
}
```

Everything works fine with a clean build, *or* if the definition of `class EmptyNode[E]` is commented out; however, after roughly ~1 edit cycle, I get the following error message:

```
[error] Unable to locate class corresponding to inner class entry for NodeEvalState in owner LazyBraunHeapLF
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed Aug 8, 2018 11:30:33 AM
```

I'm using Scala 2.12.6 on Java 8. Notably, the class file in question exists on my file system.

**Comment by SethTisue** [comment] 2020-06-16 20:27
@ghik do you think you might be able to isolate this?

**Comment by ghik** [comment] 2020-06-16 20:41
@SethTisue since it is related to incremental compilation, it happens seemingly randomly and I'm afraid it won't be easy to reproduce.

**Comment by SethTisue** [comment] 2020-06-16 21:01
okay, I'm going to close this because it's almost certainly a zinc bug. unfortunately GitHub doesn't let me transfer issues from org to org, only within the same org.

**Closed by SethTisue** 2020-06-16 21:01 UTC

**Comment by dwijnand** [comment] 2020-06-17 10:06
Hand-transferred as https://github.com/sbt/zinc/issues/797.
