### ISSUE TITLE
Perfectly reasonable code doesn't compile

### ISSUE THREAD

**Issue by edadma** [scala/bug#10498] opened 2017-09-06 02:59 UTC
compiling the following function with Scala 2.12.3

	def unionOf( classes: (Char => Boolean)* ) = {
	  val union = new HashSet[Char]()
	  val buf = new ArrayBuffer[Char => Boolean]

	  classes foreach {
	    case s: Set[Char] => union ++= s
	    case c => buf += c
	  }

	  buf += union
	  (c: Char) => buf exists (_( c ))
	}

results in the error

    type arguments [?,Equals] do not conform to trait Subtractable's type parameter bounds [A,+Repr <: scala.collection.generic.Subtractable[A,Repr]]
    classes foreach {
            ^

**Comment by som-snytt** [comment] 2017-09-06 03:16
Probably https://github.com/scala/bug/issues/10151

**Comment by som-snytt** [comment] 2017-09-06 03:22
The Onion headline would be, Perfectly Reasonable Code Actually Compiles!

**Comment by edadma** [comment] 2017-09-06 16:02
tried the first workaround and it worked! thanks

**Comment by hrhino** [comment] 2017-09-06 16:12
For github's sake: "duplicate of #10151".

**Comment by SethTisue** [comment] 2017-09-06 23:33
duplicate of #10151

**Comment by hrhino** [comment] 2017-09-07 01:00
Apologies for spamming everyone's emails/notifications, but this issue is truly a duplicate of #10151, and it's important that GitHub knows that it duplicates #10151, to which end we can say "duplicates #10151" or even "duplicate of #10151", which it will pick up on. RIght?

**Closed by hrhino** 2017-09-07 01:00 UTC
