### ISSUE TITLE
Compiler not failing if function is named with implicit of diff types versus function is symbol '+', and called or not called

### ISSUE THREAD

**Issue by helena** [scala/bug#11298] opened 2018-12-09 21:43 UTC
```
scalaVersion: 2.12.8
sbt.version=1.2.6
OS: Mac Mohave build 10.14.1
```
Seeing an odd behavior, I think, where the compiler failed on functions using + or - vs a function name. e.g.

Compiler fails 
```scala
def +(key: A, oldElement: B, newElement: B)(implicit node: SelfUniqueAddress): ORMultiMap[A, B] =
def +(key: A, oldElement: B, newElement: B)(implicit node: Cluster): ORMultiMap[A, B] =
```

Compiler does not fail unless replaceBinding(key, old, new)(node: SelfUniqueAddress) is not called in code / test
```scala
def replaceBinding(key: A, oldElement: B, newElement: B)(implicit node: SelfUniqueAddress): ORMultiMap[A, B] =
  replaceBinding(node.uniqueAddress, key, oldElement, newElement)

@deprecated("Use `replaceBinding` that takes a `SelfUniqueAddress` parameter instead.", since = "2.5.19")
def replaceBinding(key: A, oldElement: B, newElement: B)(implicit node: Cluster): ORMultiMap[A, B] =
  replaceBinding(node.selfUniqueAddress, key, oldElement, newElement)
```

Raises an error only if called, otherwise does not raise:
```scala
implicit val selfUniqueAddress = SelfUniqueAddress(node1)
ORMultiMap().replaceBinding("a", "A", "B")
```

**Comment by Jasper-M** [comment] 2018-12-10 11:39
If I understand correctly this is more or less a duplicate of #11288. As far as I can see naming the methods `+` or something else doesn't really make a difference?

**Comment by som-snytt** [comment] 2019-01-08 05:53
Yes, on the linked ticket, Patrik mentions this is how overloading works. The compiler doesn't error on definition, but maybe someone should write a scalafix lint warning.

**Closed by som-snytt** 2019-01-08 05:53 UTC
