### ISSUE TITLE
Scalac doesn't write necessary INNERCLASS entries

### ISSUE THREAD

**Issue by dzharkov** [scala/bug#10341] opened 2017-05-29 13:48 UTC
Try the following akka build:
```
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-persistence_2.12</artifactId>
            <version>2.5.1</version>
        </dependency>
```
Look at the `akka.persistence.AbstractPersistentActorWithAtLeastOnceDelivery` class.
It implements method `public void akka$persistence$AtLeastOnceDeliveryLike$$unconfirmed_$eq(SortedMap<Object, Delivery> x$1)`

It has the following signature:
```
signature (Lscala/collection/immutable/SortedMap<Ljava/lang/Object;Lakka/persistence/AtLeastOnceDelivery$Internal$Delivery;>;)V
declaration: void akka$persistence$AtLeastOnceDeliveryLike$$unconfirmed_$eq(scala.collection.immutable.SortedMap<java.lang.Object, akka.persistence.AtLeastOnceDelivery$Internal$Delivery>)
```

The crucial part here is that `akka.persistence.AtLeastOnceDelivery$Internal$Delivery` is an inner class in `akka.persistence.AtLeastOnceDelivery`, but it's not written among INNERCLASS attributes written in `AbstractPersistentActorWithAtLeastOnceDelivery` while it must be according to the JVM spec (4.7.6)

It might lead to [the problems](https://discuss.kotlinlang.org/t/kotlin-class-inherit-from-scala-abstract-class-issues/2823) when compiling against such classes with Kotlin.

And while in Java it's possible to extend such class, it's impossible e.g. to override `akka$persistence$AtLeastOnceDeliveryLike$$unconfirmed_$eq` because javac cannot find mentioned inner class too

**Comment by lrytz** [comment] 2017-05-29 16:04
Given that the reference is in the generic signature, this is (most likely) a duplicate of https://github.com/scala/bug/issues/10180. I'll add a note there to make sure to check the example once it's fixed.

**Closed** 2017-05-29 16:16 UTC
