### ISSUE TITLE
REPL: regression on Windows: "Unable to create a system terminal"

### ISSUE THREAD

**Issue by flomebul** [scala/bug#12167] opened 2020-09-27 21:14 UTC
scala repl version 2.13.3 introduce a regression compared to 2.13.2.
My environment is Windows 10 / cygwin / mintty.
Jline could not create a system terminal and there is no echo.

```
$ scala
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 1.8.0_262).
Type in expressions for evaluation. Or try :help.
sept. 27, 2020 11:07:21 PM org.jline.utils.Log logr
AVERTISSEMENT: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

scala> val res0: Int = 3

scala> Luc@Mulan ~
$
```

**Comment by flomebul** [comment] 2020-09-27 21:20
For information, withe the same environment, dotr version 0.27-RC1 work well:
```
$ dotr -version
Starting dotty REPL...
Dotty compiler version 0.27.0-RC1 -- Copyright 2002-2020, LAMP/EPFL
scala> 1 + 3
val res0: Int = 4

scala>
Luc@Mulan ~
$
```

**Comment by lrytz** [comment] 2020-09-28 10:01
I took my windows VM in the state it happened to be right now (Windows 10 19041.508), installed a fresh cygwin x64 with all default options. If I understand correctly, the "cygwin64 terminal" is mintty. My Java is
```
$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

JLine worked correctly for me. I tried with both `./bin/scala` and `./bin/scala.bat`.

Maybe someone out there with java.util.logging experience can figure out how to run the repl with a more chatty log config? https://github.com/jline/jline3/wiki/Logging

**Comment by flomebul** [comment] 2020-09-28 16:04
Hello,
I have a additional information: in order to obtain a correct behavior with dotr 0.27.0-RC1 and sbt  1.3.13, I set the "CYGWIN" environment variable to "disable_pcon". This environment work well also with scala 2.13.2, but no more with 2.13.3.

**Comment by SethTisue** [comment] 2020-10-01 00:16
This is nearly certain to be a JLine 3 issue rather than a Scala issue per se. Searching this error message over at https://github.com/jline/jline3/issues turns up a number of potentially relevant tickets.

**Comment by flomebul** [comment] 2020-10-02 12:27
I understand your point. Nevertheless, I am surprise that dotr 0.27.0-RC1 and scala 2.13.3 could not work with the same environment.
Regars

**Comment by SethTisue** [comment] 2020-10-02 13:38
Thanks for reporting the problem, and especially thank you for recording the solution you found here. I'm closing the ticket, but hopefully people will find it in their search results and see your advice.

**Comment by SethTisue** [comment] 2020-10-02 13:47
sbt 1.3.13 uses JLine 2. (The 1.4 series, which is presently at 1.4.0-RC2, moves to JLine 3.)

Dotty uses JLine 3, but I'm not sure what version.

2.13.3 uses JLine 3.15.0 and JNA 5.3.1. Scala 2.13 has since been upgraded to JLine 3.16.0; you might give a recent 2.13 nightly (e.g. 2.13.4-bin-8c86b7d) a try and see if the version bump helped.

**Comment by flomebul** [comment] 2020-10-02 14:43
Hello,

With "2.13.4-bin-8c86b7d", it's "same player, shoot again" :-(
```
$ sbt
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_262)
[info] loading project definition from D:\Users\Luc\Documents\Home\ProjSbts\Scala_2.13\project
[info] loading settings for project scala_2-13 from build.sbt ...
[info] set current project to scala_2-13 (in build file:/D:/Users/Luc/Documents/Home/ProjSbts/Scala_2.13/)
[info] sbt server started at local:sbt-server-0a4af77c4fd1f54d0d26
sbt:scala_2-13> consoleQuick
[info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.4-bin-8c86b7d. Compiling...
[info]   Compilation completed in 19.479s.
[info] Starting scala interpreter...
Welcome to Scala 2.13.4-bin-8c86b7d (OpenJDK 64-Bit Server VM, Java 1.8.0_262).
Type in expressions for evaluation. Or try :help.
oct. 02, 2020 4:33:01 PM org.jline.utils.Log logr
AVERTISSEMENT: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

scala>
```
For information, I just check the version of jline used:
```
$ !find
find . -name *jline*
...
./dotty-0.27/lib/jline-reader-3.15.0.jar
./dotty-0.27/lib/jline-terminal-3.15.0.jar
./dotty-0.27/lib/jline-terminal-jna-3.15.0.jar
...
./scala-2.13.1/doc/licenses/bsd_jline.txt
./scala-2.13.1/lib/jline-2.14.6.jar
./scala-2.13.2/doc/licenses/bsd_jline.txt
./scala-2.13.2/lib/jline-3.14.1.jar
./scala-2.13.3/doc/licenses/bsd_jline.txt
./scala-2.13.3/lib/jline-3.15.0.jar
Luc@Mulan /cygdrive/c/scala
$
```
As a last check, I replace the lib jline-3.15.0.jar by jline-3.14.1.jar in the scala-2.13.3 distribution, and the issue  seems to disappear. But is it a right workaround?
Regards

**Comment by SethTisue** [comment] 2020-10-02 15:14
Downgrading Scala to use JLine 3.14 isn't really an option for us, but I'm glad it gets you running, and the fact that doing so works seems like an important clue as what to what the cause might be (and/or, what a better workaround might be).

**Comment by flomebul** [comment] 2020-10-04 14:11
Hello,
I eventually recover how to setup logs.
I use ```scala -Djava.util.logging.config.file=logging.properties```
with the following content for logging.properties
```
handlers= java.util.logging.ConsoleHandler
.level= FINEST
```
And the result is
```
$ scala -Djava.util.logging.config.file=logging.properties
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 1.8.0_262).
Type in expressions for evaluation. Or try :help.
oct. 04, 2020 4:10:51 PM org.jline.utils.Log logr
AVERTISSEMENT: Creating a dumb terminal
java.lang.IllegalStateException: Unable to create a system terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:317)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:263)
        at scala.tools.nsc.interpreter.jline.Reader$.apply(Reader.scala:72)
        at scala.tools.nsc.interpreter.shell.ILoop.defaultIn$lzycompute(ILoop.scala:68)
        at scala.tools.nsc.interpreter.shell.ILoop.defaultIn(ILoop.scala:63)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:952)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
        Suppressed: com.sun.jna.LastErrorException: [6] Descripteur non valide
                at com.sun.jna.Native.invokeVoid(Native Method)
                at com.sun.jna.Function.invoke(Function.java:415)
                at com.sun.jna.Function.invoke(Function.java:361)
                at com.sun.jna.Library$Handler.invoke(Library.java:265)
                at org.jline.terminal.impl.jna.win.$Proxy0.GetConsoleMode(Unknown Source)
                at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.createTerminal(JnaWinSysTerminal.java:40)
                at org.jline.terminal.impl.jna.JnaSupportImpl.winSysTerminal(JnaSupportImpl.java:39)
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:326)
                ... 10 more
        Suppressed: java.lang.NoClassDefFoundError: org/fusesource/jansi/internal/Kernel32
                at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.isWindowsConsole(JansiWinSysTerminal.java:75)
                at org.jline.terminal.impl.jansi.JansiSupportImpl.isWindowsConsole(JansiSupportImpl.java:140)
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:335)
                ... 10 more
        Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.internal.Kernel32
                at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                ... 13 more


scala> Luc@Mulan ~
```
Hope this can help

**Comment by SethTisue** [comment] 2020-10-04 17:04
Terminal support on Windows for JLine 3 is provided via one of two possible libraries, jna or jansi. Whichever one is present, JLine will use.

For Scala, we chose jna. So the "Suppressed: ClassNotFoundException: org.fusesource.jansi.internal.Kernel32" message doesn't actually seem abnormal. I would expect it to simply mean that JLine looked for jansi, didn't find it, and continued.

What's mysterious here is why, on your setup, JLine isn't successfully able to use jna instead.

**Comment by SethTisue** [comment] 2020-10-04 17:13
Perhaps there is some clue in the JLine 3.14.1 -> 3.15.0 changelog at https://github.com/jline/jline3/blob/master/changelog.md. , though the only change bullet that jumps out at me is https://github.com/jline/jline3/commit/0de635bedfccd025cc8634ebe890c4be1b4961e8

@flomebul what is the value of `TERM` in your terminal session?

**Comment by SethTisue** [comment] 2020-10-04 17:28
One more thought: It would be interesting to know if supplying Dotty with JLine 3.15.0 instead of 3.14.1 produces the same regression.

**Comment by flomebul** [comment] 2020-10-04 19:47
Dotty already run with jline 3.15.0 since dotty-0-25.

**Comment by SethTisue** [comment] 2020-10-06 00:04
What about giving 2.13.2 JLine 3.15.0?

**Comment by SethTisue** [comment] 2020-10-06 00:06
Another possible investigation approach here would be to try to identify the PR where this regressed for you, by bisecting. All the nightly builds (which are actually "mergely" builds: one per merged PR) from between 2.13.2 and 2.13.3 remain available.

**Comment by flomebul** [comment] 2020-10-06 09:56
The regression is introduces with the build  0b62c66 that (of course)  move from jline-3.14.0 to jline-3.15.0 (if I'm right).

**Comment by SethTisue** [comment] 2020-10-06 17:10
Weird. It seems quite mysterious that the JLine 3.15.0 + JNA combination would file for Scala 2 but work for Scala 3.

**Comment by flomebul** [comment] 2020-10-07 14:14
If I remove the JNA jar file from the lib dir, the issue look like to disappear for scala!!!
On the other side, if I remove the same ljar from the lib dir of dotty, no change: dotr continue to work without (visible) issue!!!

**Comment by SethTisue** [comment] 2020-10-07 14:35
Are the two JNA JARs in question byte-for-byte identical?

**Comment by flomebul** [comment] 2020-10-08 13:18
Yes, both use jna-5.3.1.

**Comment by flomebul** [comment] 2021-01-19 15:44
Last news: I found another solution by adding the "jansi-2.1.1.jar" in the path.

**Comment by flomebul** [comment] 2021-01-20 00:24
I just review all my environment...
With CYGWIN environment variable not set, all is ok with standard scala 2.13.4
With CYGWIN=disable_pcon, "warning: Unable to create a system terminal" and no echo
But If a add the jansi library in the classpath of in the lib dir, all is ok again.

I propose so to close this issue.

**Comment by SethTisue** [comment] 2021-01-20 00:34
yeah it's good to have the issue to help other searchers, but I think it's ultimately a JLine thing, we take what we get from JLine

**Closed by SethTisue** 2021-01-20 00:34 UTC
Labels: repl, windows
