### ISSUE TITLE
scalac adds illegal generic information for some anonymous types

### ISSUE THREAD

**Issue by scabug** [scala/bug#9964] opened 2016-10-15 11:49 UTC
When doing reflection over Scala types, this sometimes causes a NullPointerException. For example using:

```xml
<dependency>
  <groupId>com.typesafe.akka</groupId>
  <artifactId>akka-http-core_2.11</artifactId>
  <version>2.4.11</version>
</dependency>
```

and running:
   
```java
Class<?> type = Class.forName("akka.stream.scaladsl.Sink$$anon$1");
Field field = type.getDeclaredField("akka$stream$scaladsl$Sink$$anon$$in");
Type fieldType = field.getGenericType();
System.out.println(fieldType);
```

results in a NullPointerException.

This is a problem for code that processes types in a generic fashion. Looking at the class file, it seems like scalac declares the field to be of a generic type T without declaring such a type variable within the scope of this type. This results in a nullpointerexception when the reflection API attempts to resolve the declaration site of the type variable.

**Comment by SethTisue** [comment] 2018-03-01 20:03
we can't easily see if this is fixed in 2.12 since Akka 2.4 doesn't work on 2.12 and the new trait and lambda encodings in 2.12 make it unclear whether some counterpart of `akka.stream.scaladsl.Sink$$anon$1` even still exists in a current Akka version

it's certainly possible there's a bug here that remains unfixed, but in order for this ticket to be reopened, we'd need a way to reproduce it in current Scala.

**Closed by SethTisue** 2018-03-01 20:03 UTC
