### ISSUE TITLE
implicit resolution of F[A] for introduced F[_] and A

### ISSUE THREAD

**Issue by fommil** [scala/bug#10753] opened 2018-03-01 10:05 UTC
I expected the following code to compile

```scala
trait Bar[F[_]]

trait Foo[A]
object Foo {
  implicit def string: Foo[String] = ???
  implicit def bar: Bar[Foo] = ???
}

case class Problem[A](a: A)
object Problem {
  implicit def deriv[A, F[_]](implicit F: F[A], B: Bar[F]): F[Problem[A]] = ???

  deriv[String, Foo] // works

  implicitly[Foo[Problem[String]]]
}
```

but I get

```
could not find implicit value for parameter e: Foo[Problem[String]]
[error]   implicitly[Foo[Problem[String]]]
[error]             ^
```

This is minimised, if you remove the `B: Bar[F]` constraint, it compiles (but then I don't have everything I need)

Is there a workaround?

**Comment by fommil** [comment] 2018-03-01 10:14
closing... typo

**Comment by fommil** [comment] 2018-03-01 10:29
(I closed this because I had a typo, then I fixed it and reopened...)

**Comment by soronpo** [comment] 2018-03-01 10:33
FYI, works in dotty
https://scastie.scala-lang.org/znkjYw5gQayTwv6r1r15qQ

**Comment by soronpo** [comment] 2018-03-01 10:35
Error:(41, 13) diverging implicit expansion for type DFiant.Foo[DFiant.Problem[String]]
starting with method deriv in object Problem
  implicitly[Foo[Problem[String]]]

**Comment by fommil** [comment] 2018-03-01 10:37
@soronpo that's interesting about dotty! Where is the diverging implicit error coming from? Is this some additional debugging you've got?

**Comment by soronpo** [comment] 2018-03-01 10:39
The full error:
```
Error:(15, 13) diverging implicit expansion for type Foo[Problem[String]]
starting with method deriv in object Problem
  implicitly[Foo[Problem[String]]]
Error:(15, 13) not enough arguments for method implicitly: (implicit e: Foo[Problem[String]])Foo[Problem[String]].
Unspecified value parameter e.
  implicitly[Foo[Problem[String]]]
```
I'm using TLS 2.12.4 (literal types) with `-Xsource:2.13`

**Comment by Jasper-M** [comment] 2018-03-01 10:49
If `implicitly[Foo[Problem[String]]]` is inside object `Problem` I get diverging implicit expansion. If it's outside I get implicit not found.

**Comment by soronpo** [comment] 2018-03-01 10:54
> If implicitly[Foo[Problem[String]]] is inside object Problem I get diverging implicit expansion. If it's outside I get implicit not found.

In dotty it compiles in either case

**Comment by Jasper-M** [comment] 2018-03-01 11:05
> If implicitly[Foo[Problem[String]]] is inside object Problem I get diverging implicit expansion. If it's outside I get implicit not found.

Hmm, looks like that implicit not found error was rather because `deriv` was not in the implicit scope. (although I think it should be, because `Problem` is part of the type?)

**Comment by fommil** [comment] 2018-03-01 11:28
This hack of importing the `Foo._` doesn't work in the real (unminimised) version of the problem https://github.com/fthomas/refined/pull/447 it also wouldn't be a feasible workaround. I'd like to take the complexity hit in the `deriv` definition to avoid the user having to do anything. 

To make the minimisation more realistic, let's rename `object Problem` to `object Main`.

**Comment by fommil** [comment] 2018-03-01 11:32
changing to

```
object Deriver {
  implicit def deriv[A, F[_]](implicit F: F[A], B: Bar[F]): F[Problem[A]] = ???
}
object Main {
  import Deriver._
  deriv[String, Foo] // works

  import Foo._
  implicitly[Foo[Problem[String]]]
}
```

I still get

```
could not find implicit value for parameter e: Foo[Problem[String]]
[error]   implicitly[Foo[Problem[String]]]
```

**Comment by Jasper-M** [comment] 2018-03-01 11:37
Strange. It works for me.

**Comment by fommil** [comment] 2018-03-01 11:39
@Jasper-M I'm on scala 2.12.4, what are you using?

**Comment by Jasper-M** [comment] 2018-03-01 11:40
Same. Using REPL `:paste` however. That might make some difference in bizarre edge cases...

**Comment by fommil** [comment] 2018-03-01 11:41
@Jasper-M any special flags? I'm just using

```
scalaVersion in ThisBuild := "2.12.4"
scalacOptions in ThisBuild ++= Seq(
  "-language:_",
  "-Ypartial-unification",
  "-deprecation"
)
```

**Comment by Jasper-M** [comment] 2018-03-01 11:43
@fommil No flags. Enabling `-Ypartial-unification` brought the error back for me.

**Comment by fommil** [comment] 2018-03-01 11:45
@Jasper-M !!!!

**Comment by fommil** [comment] 2018-03-01 11:53
maybe playing around with the parameter ordering might help in that case.

**Comment by fommil** [comment] 2018-03-01 13:32
removing partial-unification PLUS adding the explicit `import Foo._` allows it to compile. But adding the `import` should not be necessary at all, it looks like there is a bug in implicit search here.

**Comment by soronpo** [comment] 2018-03-01 13:35
Indeed. That's why it works in dotty :smile: . I think I also ran into this in my own library, but didn't try to  minimize and have such implicits in an import.

**Comment by fommil** [comment] 2018-03-01 13:35
ok... I can get it to compile with the `partial-unification` enabled if I swap the implicit parameters

```
  implicit def deriv[F[_], A](implicit B: Bar[F], F: F[A]): F[Problem[A]] = ???
```

ordering of the type parameters does not matter.

We're still back to "why is the `import` needed?"

**Comment by joroKr21** [comment] 2018-03-01 20:08
Can you guess why it is diverging? Well we want an implicit `F[A]` for any `F[_]` and any `A`. But `F[Problem[A]]` is such an implicit! Thus infinite recursion and divergence. Moving `Bar[F]` in the beginning is the correct solution as it will fix `F` to `Foo`.

**Comment by fommil** [comment] 2018-03-01 20:43
@joroKr21 ah! Thanks for the explanation. However, we still need the `import Foo._` or it does not compile. This appears to be the bug.

**Comment by joroKr21** [comment] 2018-03-01 21:05
Ah yes, I convinced myself that it's a bug. It looks like the expected type `Foo[Problem[String]]` should constrain the type parameters enough so that only the correct implicits apply.

**Comment by fommil** [comment] 2018-03-03 11:02
ok, so I think I understand the restriction... it seems 

```scala
 implicit def deriv[F[_], A](implicit B: Bar[F], F: F[A]): F[Problem[A]] = ???
```

solving for `B` fixes `F`, but `F`'s companion is not included in implicit scope so it is not possible to solve for `F[A]`. In general I think the bug is that solved types do not contribute to the implicit score, but they should do!

**Comment by joroKr21** [comment] 2018-03-04 11:16
Well it looks in the immediate scope first, which doesn't include `object Foo` yet. The problem is that it's looking for `Bar[?]` (i.e. `F` is not instantiated to `Foo` yet, but it should be) which matches `F[Problem[A]]` so it doesn't proceed to the implicit scope. When we `import Foo._` we just get a better match `Bar[Foo]` in the immediate scope.

**Comment by fommil** [comment] 2018-03-04 11:28
right, so it can't solve for `Bar[F]` unless it knows to search on `F`'s companion... which probably means it needs to search all companions. *sigh*

**Comment by adriaanm** [comment] 2018-03-08 13:49
Excellent investigation, but I disagree that `F` should be instantiated to `Foo` before the implicit search starts. Consider the equivalent problem, forgetting about implicits for now:

```
trait Bar[F[_]]
trait Foo[A]
class Problem[A](a: A)
object Problem {
  def deriv[A, F[_]](implicit F: F[A], B: Bar[F]): F[Problem[A]] = ???

  deriv: Foo[Problem[String]]
}
```

When running with additional tracing (patch below), and under `-Ytyper-debug`:
```
|    |    |-- deriv : pt=Foo[Problem[String]] EXPRmode (site: value <local Problem> in Problem) 
[    create] ?A                       ( In Problem#deriv[A,F[_]] )
[    create] ?F                       ( In Problem#deriv[A,F[_]] )
[    create] ?F[?A]                   ( In Problem#deriv[A,F[_]] )
[ applyArgs] ?F[?A]                   ( In Problem#deriv[A,F[_]], apply args ?A to F )
[    create] ?F[?A]                   ( In Problem#deriv[A,F[_]] )
[ applyArgs] ?F[?A]                   ( In Problem#deriv[A,F[_]], apply args ?A to F )
[    create] ?F[Problem[?A]]          ( In Problem#deriv[A,F[_]] )
[ applyArgs] ?F[Problem[?A]]          ( In Problem#deriv[A,F[_]], apply args Problem[?A] to F )
[    create] ?F[Problem[?A]]          ( In Problem#deriv[A,F[_]] )
[ applyArgs] ?F[Problem[?A]]          ( In Problem#deriv[A,F[_]], apply args Problem[?A] to F )
[addHiBound] String                   ( In Problem#deriv[A,F[_]] / sharesConstraints=false )
[addLoBound] String                   ( In Problem#deriv[A,F[_]] / sharesConstraints=false )
[addLoBound] String                   ( In Problem#deriv[A,F[_]] / sharesConstraints=false )
[addHiBound] String                   ( In Problem#deriv[A,F[_]] / sharesConstraints=false )
[addHiBound] Foo                      ( In Problem#deriv[A,F[_]] / sharesConstraints=false )
|    |    |    solving for (A: ?A, F: ?F)
solving List(?A, ?F)/List(type A, type F)/List(, [_])
solveOne0(tv, tp, v, b)=(TVar<A=null>,type A,invariant,Nothing)
solving ?A false List(String)List(String)
[   setInst] String                   ( In Problem#deriv[A,F[_]], A=String )
solving =?String false List(String)List(String) = String
solveOne0(tv, tp, v, b)=(TVar<F=null>,type F,invariant,[_]Nothing)
solving ?F false List()List()
[   setInst] Nothing                  ( In Problem#deriv[A,F[_]], F=Nothing )
solving =?Nothing false List()List() = Nothing
```

Specifically, we only add an upper bound for `F` -- there is no lower one, and thus it gets instantiated to our good friend, `Nothing`.

Patch:
```diff
diff --git i/src/reflect/scala/reflect/internal/Types.scala w/src/reflect/scala/reflect/internal/Types.scala
index bec839b..0cf66cf 100644
--- i/src/reflect/scala/reflect/internal/Types.scala
+++ w/src/reflect/scala/reflect/internal/Types.scala
@@ -2887,11 +2887,11 @@ trait Types
     @inline final def trace[T](action: String, msg: => String)(value: T): T = {
       // Uncomment the following for a compiler that has some diagnostics about type inference
       // I doubt this is ever useful in the wild, so a recompile will be needed
-//    val s = msg match {
-//      case ""   => ""
-//      case str  => "( " + str + " )"
-//    }
-//    Console.err.println("[%10s] %-25s%s".format(action, value, s))
+       val s = msg match {
+         case ""   => ""
+         case str  => "( " + str + " )"
+       }
+       Console.err.println("[%10s] %-25s%s".format(action, value, s))
       value
     }
 
@@ -3088,6 +3088,7 @@ trait Types
     def addLoBound(tp: Type, isNumericBound: Boolean = false) {
       assert(tp != this, tp) // implies there is a cycle somewhere (?)
       //println("addLoBound: "+(safeToString, debugString(tp))) //DEBUG
+      TypeVar.trace("addLoBound", s"In $originLocation / sharesConstraints=${sharesConstraints(tp)}")(tp)
       if (!sharesConstraints(tp)) {
         undoLog record this
         constr.addLoBound(tp, isNumericBound)
@@ -3097,6 +3098,7 @@ trait Types
     def addHiBound(tp: Type, isNumericBound: Boolean = false) {
       // assert(tp != this)
       //println("addHiBound: "+(safeToString, debugString(tp))) //DEBUG
+      TypeVar.trace("addHiBound", s"In $originLocation / sharesConstraints=${sharesConstraints(tp)}")(tp)
       if (!sharesConstraints(tp)) {
         undoLog record this
         constr.addHiBound(tp, isNumericBound)
```

**Comment by fommil** [comment] 2018-03-08 13:58
@adriaanm thanks for that. What is the consequence, is there a workaround to force the lower bound or are you saying this is just not something scala compiler can do?

**Comment by adriaanm** [comment] 2018-03-08 14:17
It's not so much "can't" as "won't" -- a return type is in a covariant position, which is fundamental to OO (since a method is allowed to return a value of any subtype of its result type, we can only constrain from above the type variable that represents that unknown type). This applies equally for regular method calls as well as the method that produce implicit values -- there needs to be subtype slack, so that they can provide an instance of a subtype of the expected type.

It could be possible to refactor your application so that there are more constraints in the mix (such as what happens when you import the implicit values, which means their availability determines the result of type inference). I played around a bit with the code, but it really depends on the greater context.

**Comment by soronpo** [comment] 2018-03-08 14:20
Then why does it compile in Dotty?

**Comment by fommil** [comment] 2018-03-08 14:24
@adriaanm greater context is exactly this usecase 
 https://github.com/fthomas/refined/blob/master/modules/scalaz/shared/src/main/scala/eu/timepit/refined/scalaz/package.scala#L47-L73

example use in https://github.com/fthomas/refined/blob/master/modules/scalaz/shared/src/test/scala-2.12/eu/timepit/refined/scalaz/RefTypeSpecScalazMonadError.scala

**Comment by adriaanm** [comment] 2018-03-08 15:05
> Then why does it compile in Dotty?

I don't know, does it still work after https://github.com/lampepfl/dotty/pull/4080 was merged?

**Comment by joroKr21** [comment] 2018-03-08 22:56
@adriaanm The example compiles on dotty master, but your argument is compelling. Keeping subtyping in mind, we can modify it in in a way to make it compile with scalac and fail with dotty:
```scala
trait Bar[F[_]]
trait Foo[A]
trait Qux[A] extends Foo[A]
object Qux {
  implicit def string: Qux[String] = ???
  implicit def bar: Bar[Qux] = ???
}

case class Problem[A](a: A)
object Problem {
  import Qux._
  implicit def deriv[A, F[_]](implicit B: Bar[F], F: F[A]): F[Problem[A]] = ???
  implicitly[Foo[Problem[String]]]
}
```
Import still necessary ofc.

**Comment by adriaanm** [comment] 2018-03-09 09:24
I hope the meta-takeaway is also coming across, but, for the casual reader: relying on fancy type inference is bound to cause work at some point (even within the 2.x series, although we are generally very resistant to touching type inference for this very reason).

It would be great to have tooling that can insert the minimal set of annotations / type arguments to ensure type checking on different versions has the same result. Some kind of fancy cross-compiler AST diffing and patch generation.

**Comment by fommil** [comment] 2018-03-09 10:00
@adriaanm I assume you want to close the ticket then?

It would be good if there was some other workaround that we could use to avoid enforcing downstream users to import their contravariant / monaderror instances.

**Comment by adriaanm** [comment] 2018-03-09 10:26
Yes, I'm afraid this is a won't-fix for the 2.x series, unless there's an feasible carry-over from Dotty that allows us to improve this. I agree inferring Nothing is such a downer. 

Before closing, let me ping the other side of the street in case they have any suggestions /cc @smarter, @OlivierBlanvillain :-)

**Comment by fommil** [comment] 2018-03-29 19:46
scalaz has a `NotNothing` evidence. I was wondering if that would be worth trying out (I do not have high hopes).

**Closed** 2018-07-05 11:51 UTC
Labels: Lightbend support
