### ISSUE TITLE
False positive unused pattern var warning

### ISSUE THREAD

**Issue by philwalk** [scala/bug#12075] opened 2020-07-08 15:17 UTC
## reproduction steps

using Scala 2.13.3

```scala
package vastblue.apps

object FalsePositiveWarning extends App {
  val rows = Seq.empty[Map[String,Any]]
  for {
    row:Map[String,Any] <- rows
    item = ColItem(row)
  } yield item

  case class ColItem(row:Map[String,Any])
}
```

## problem
The compiler issue this incorrect warning:
```
[info] Compiling 1 Scala source to C:\opt\ue\apps\target\scala-2.13\classes ...
[warn] C:\opt\ue\apps\src\main\scala\vastblue\apps\FalsePositiveWarning.scala:6:5: pattern var row in value $anonfun is never used: use a wildcard `_` or suppress this warning with `row@_`
[warn]     row:Map[String,Any] <- rows
[warn]     ^
[warn] one warning found
```

**Comment by SethTisue** [comment] 2020-07-08 15:53
duplicate of #10287, I think?

**Comment by philwalk** [comment] 2020-07-08 16:04
With this version, there is no warning:

```
package vastblue.apps

object FalsePositiveWarning extends App {
  val rows = Seq.empty[Map[String,Any]]
  for {
    row <- rows
    item = ColItem(row)
  } yield item

  case class ColItem(row:Map[String,Any])
}
```

Perhaps it has the same underlying cause as #10287, I'll see if I can figure that out.

**Comment by SethTisue** [comment] 2020-07-08 16:24
adding a type ascription changes the desugaring

**Closed by SethTisue** 2020-07-08 16:24 UTC
