### ISSUE TITLE
Scala doc should not require FQCN for build.

### ISSUE THREAD

**Issue by He-Pin** [scala/bug#12884] opened 2023-09-26 11:30 UTC
## Reproduction steps

Scala version: 2.13

refs: https://github.com/apache/incubator-pekko/issues/353
refs: https://github.com/apache/incubator-pekko/pull/682

```scala
[error] /path/actor/src/main/scala/org/apache/pekko/actor/Scheduler.scala:16:18: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.pekko.actor
[error] import java.lang.IllegalArgumentException
[error]                  ^
[error] one error found
[error] (actor / Compile / compileIncremental) Compilation failed
```

&

````scala
   * @throws IllegalArgumentException if the given delays exceed the maximum
   * @throws java.lang.IllegalArgumentException if the given delays exceed the maximum
```

## Problem

1. scaladoc should support FQCN be imported
2. the `unused-imports` should not be needed if it's been used in scaladoc.

**Comment by som-snytt** [comment] 2023-09-26 16:15
I've encountered the first issue years ago, but don't recall the context. The user's perspective is that scaladoc is scalac plus doc generation. (In Scala 2, scaladoc departs in subtle ways.)

The second issue is interesting and reasonable. I think it will not happen in Scala 2, because it looks only at code trees, and doc has been discarded. It could have a mode where scalac retains doc nodes for this purpose? Maybe that is feasible.

**Comment by SethTisue** [comment] 2024-01-26 23:10
duplicate of #3695

**Closed by SethTisue** 2024-01-26 23:10 UTC
Labels: scaladoc tool, enhancement
