### ISSUE TITLE
Comparing boxed NaN values

### ISSUE THREAD

**Issue by scabug** [scala/bug#10112] opened 2016-12-19 12:50 UTC
reproduction: always
```scala
val boxed = Float.box(Float.NaN)
val boxed2 = Float.box(Float.NaN)

boxed == boxed2 // Boolean = true
```
This probably arrises from Float.NaN & Double.NaN being defines as
```scala
final val NaN              = java.lang.Float.NaN
```

in Java:
```scala
java.lang.Float boxed = java.lang.Float.valueOf(java.lang.Float.NaN)
java.lang.Float boxed2 = java.lang.Float.valueOf(java.lang.Float.NaN)

boxed == boxed // java.lang.Boolean = true
boxed == boxed2 // java.lang.Boolean = false
```

**Comment by soronpo** [comment] 2017-04-07 16:53
Pardon my ignorance, but why is this a bug? Shouldn't we be able to compare NaNs?

**Comment by sjrd** [comment] 2017-04-07 16:55
I believe this is a duplicate of https://github.com/scala/scala-dev/issues/329, which was fixed in https://github.com/scala/scala/pull/5761.

**Comment by adriaanm** [comment] 2017-04-07 22:43
Thanks!

**Closed by adriaanm** 2017-04-07 22:43 UTC
Labels: quickfix
