### ISSUE TITLE
no warning "reference for uninitialized value" if value accessed from function

### ISSUE THREAD

**Issue by dehun** [scala/bug#11141] opened 2018-09-11 08:18 UTC
In the next code snippet I reference `y` through method `foo` while initializing `x`. Initialization of `x` happens before initialization of `y`. I expected warning "Reference to uninitialized value". However no warning was generated in this case. 

```
object PrematureInitialization extends App {
  class Foo {
    val x:Int = foo() // expected warning, but no warning here
    val z:Int = y + 1 // got expected warning "Reference to uninitialized value"

    val y = 2
    def foo(): Int = {
      y + 1
    }
  }

  val r = new Foo().x
  require(r == 3)
}
```

Reproduced on scastie for scala versions 2.12.4 and  2.13.0-M4.

**Comment by martijnhoekstra** [comment] 2018-09-11 11:56
Duplicate of #339 -- that is, "fixed"  by `-Xcheckinit`?

**Comment by dehun** [comment] 2018-09-11 12:26
It is hard for me to see how #339 is related to this one.
As far as I understand `-Xcheckinit` will do a runtime check. 
Which is nice, but warning during compilation time will be way more valuable for me.

**Comment by martijnhoekstra** [comment] 2018-09-11 12:32
ugh - #399, not #339

**Comment by hrhino** [comment] 2018-09-11 12:33
I don't think this is likely to be fixed, or worth fixing.

```scala
object PI {
  class Foo {
    val x = foo(initializing = true)
    var y = 2
    def foo(initializing: Boolean): Int = if (initializing) -1 else y
    println(foo(initializing = false))
  }
}
```

and suddenly you need to do pretty complicated code analysis to determine that `y` is not actually used in `foo` while initializing `x`. There are of course even more complicated examples which could come up in real code.

**Comment by SethTisue** [comment] 2018-09-11 14:38
this has come up over and over in the past decade-plus, there have been many discussions about it, the reason nothing has been done is that it's very unclear how it could be addressed. a solution would require a SIP. if you're interested in discussing possible solution approaches, there's https://contributors.scala-lang.org for that

**Closed by SethTisue** 2018-09-11 14:38 UTC

**Comment by SethTisue** [comment] 2019-03-22 14:10
ticket of record is #399
