### ISSUE TITLE
Incorrect exhaustiveness warning when pattern matching on Nil.type

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#12186] opened 2020-10-12 13:48 UTC
## reproduction steps

using Scala 2.13.4-20201011-114304-1c1fa0c (equivalent roughly to HEAD a few days ago)

```scala
scala> def test(list: List[Int]): Boolean = list match {
     |   case h :: t => true
     |   case _: Nil.type => false
     | }
                                            ^
       warning: match may not be exhaustive.
       It would fail on the following input: Nil
def test(list: List[Int]): Boolean

scala> test(Nil)
val res0: Boolean = false

scala> def test(list: List[Int]): Boolean = list match {
     |   case h :: t => true
     |   case _: scala.collection.immutable.Nil.type => false
     | }
def test(list: List[Int]): Boolean
```

## problem

`Nil.type` is the type of `Nil`, so the match is exhaustive.

In 2.13.3, the same code does not raise an exhaustiveness warning.

Note: it only warns if you use the value alias of `Nil` (from the `scala` package, but presumably any value alias as well), and does not warn if you use the fully qualified type.

**Comment by dwijnand** [comment] 2020-10-12 14:07
That sucks, and 100% going to be due to https://github.com/scala/scala/pull/9208.

**Comment by NthPortal** [comment] 2020-10-12 14:20
I checked the Jenkins output, and you are correct. the bootstrap introduced an exhaustiveness warning (which we never saw, because we don't have fatal warnings yet).

technically, that PR didn't break it so much as expose it, as in principle this can happen for any sealed sum type for which you create a value alias

**Comment by dwijnand** [comment] 2020-10-13 10:52
Some notes:

Compare with the REPL:

```scala
scala> typeOf[Nil.type] =:= typeOf[scala.collection.immutable.Nil.type]
val res1: Boolean = true
```

One difference is `scala.collection.immutable.Nil.type` a `UniqueSingleType` in the REPL, but a `ModuleTypeRef` where it's checked in patmat (`Const#unique`).  `normalizePlus` converts `UniqueSingleType`s into `ModuleTypeRef`s, but only if the symbol is a module and ... 🥁 the symbol `Nil` in `scala.Nil.type` is a `MethodSymbol` - not a module 😞 (it's not even a `isVal`, surprisingly to me).

**Comment by lrytz** [comment] 2020-10-16 11:09
> the symbol `Nil` in `scala.Nil.type` is a `MethodSymbol` - not a module

Ah, this rings a bell...

https://github.com/scala/scala/blob/92fa9be7e88c81bceae91494b45297616c0f1728/src/reflect/scala/reflect/internal/Symbols.scala#L778-L782

Unfortunately, phase travel doesn't revert that flag...

```
scala> :power

scala> class C { object T }
scala> val t = typeOf[C].member(TermName("T"))
val t: $r.intp.global.Symbol = object T

scala> t.isMethod
val res0: Boolean = false

scala> enteringJVM(t.info)
val res1: $r.intp.global.Type = (): T.type

scala> t.isMethod
val res2: Boolean = true
```

**Comment by lrytz** [comment] 2020-10-16 11:12
Though the symbol doesn't change here, and you're saying you see a `MethodSymbol`, so there is something else goin on

```
scala> t.getClass
val res5: Class[_ <: $r.intp.global.Symbol] = class scala.reflect.internal.Symbols$ModuleSymbol
```

**Comment by dwijnand** [comment] 2020-10-16 13:17
Yeah, because my reference is the "val alias" `scala.Nil`, so more like:

```scala
scala> object Scala { val Nil: scala.collection.immutable.Nil.type = scala.collection.immutable.Nil }
object Scala

scala> val t = typeOf[Scala.type].member(TermName("Nil"))
val t: $r.intp.global.Symbol = value Nil

scala> t.getClass
val res0: Class[_ <: $r.intp.global.Symbol] = class scala.reflect.internal.Symbols$MethodSymbol

scala> t.isMethod
val res1: Boolean = true
```

**Comment by lrytz** [comment] 2020-10-16 13:19
Ah of course, sorry for the confusion

**Comment by adamw** [comment] 2020-12-15 08:24
I turned on nonexhaustive errors using `-Wconf:cat=other-match-analysis:error` and on 2.13.4 I'm now getting a lot of problems like this (simplified code from tapir)

```
def matchPath(pathInputs: Vector[String]): Unit = {
    pathInputs match {
      case Vector() => ???
      case _ :+ last => ???
    }
  }
```

causes:

```
[error] DecodeInputs.scala:122:5: match may not be exhaustive.
[error] It would fail on the following inputs: Vector0, Vector1(), Vector2(), Vector3(), Vector4(), Vector5(), Vector6()
[error]     pathInputs match {
[error]     ^
```

is this the same bug? I can create another one, but if that's already covered, there's no point.

Using 2.13.3 causes the code above to compile w/o error or warning.

**Comment by martijnhoekstra** [comment] 2020-12-15 17:28
@adamw  The issue you describe is that multiple extractors can't be shown to be exhaustive together. At the risk of stating the obvious, you can workaround by matching the extractor that extracts a value first, and use a fallback for the other:

```
case _ :+ last =>
case _ =>
```

**Comment by NthPortal** [comment] 2020-12-15 21:09
@adamw that is not the same bug; it is part of either #12243 or #12240 I believe

**Comment by adamw** [comment] 2020-12-16 07:16
@NthPortal thanks, though I suppose @martijnhoekstra says it's a feature, not a bug? :)

I'd prefer to avoid matching on `_` - that's something different than matching on an empty/non-empty vector.  Though, as I understand proving exhaustiveness basing on extractors is not possible. And I suppose that's correct, as the compiler can't possibly know what's extracted when

**Comment by martijnhoekstra** [comment] 2020-12-16 09:49
I wouldn't want to call it a feature, just that scala doesn't have a feature to declare extractors that are exhaustive together.

Without matching on `_`, you could write a method that extracts `Option[(init, last)]`, and match on that, or if #12240 gets fixed match on `.view.reverse` with `case Seq() => ; case Seq(last, _*) => `

**Comment by adamw** [comment] 2020-12-16 09:56
@martijnhoekstra This makes perfect sense, thank you for the explanation!

**Comment by adamw** [comment] 2020-12-16 10:58
@martijnhoekstra In fact, isn't checking head & tail such a common operation on sequences, that it might be justified to add sth like a `headAndTail`/`peel` deconstructing method?

**Comment by martijnhoekstra** [comment] 2020-12-16 11:25
Yes, potentially. They exist in `:+.unapply` and `+:.unapply`, but using them directly is ugly, in much the same way as https://github.com/scala/bug/issues/12243#issuecomment-737819124

**Comment by adamw** [comment] 2020-12-16 11:27
`uncons`, that's the name I was looking for! I knew it had a name just couldn't remember it. Thanks again :)

**Comment by dwijnand** [comment] 2020-12-17 08:17
Here you were only using the last element if available, so matching `lastOption` is also a... option 😄.

**Comment by adamw** [comment] 2020-12-17 08:28
@dwijnand yes true, there was a number of errors I started getting with 2.13.4, and I copied the least representative one of course ;)

**Closed** 2021-02-03 08:40 UTC
Labels: dealias, has PR, patmat, regression
