### ISSUE TITLE
Escape quotes don't seem to work in string interpolation

### ISSUE THREAD

**Issue by edadma** [scala/bug#10510] opened 2017-09-14 20:21 UTC
The following code (in Scala 2.12.3)

    object Main extends App {
      val num = "123"

      println( s"\t\"$num\"" )
    }

results in the error message

    /home/ed/projects/test/src/main/scala/Main.scala:4: ')' expected but string literal found.
      println( s"\t\"$num\"" )
                          ^

Just putting `\t` does work, however.

**Comment by som-snytt** [comment] 2017-09-14 20:28
Duplicate of https://github.com/scala/bug/issues/6476

**Closed by som-snytt** 2017-09-14 20:28 UTC

**Comment by Shokodemon** [comment] 2019-08-16 06:34
println(s""" interpolated tripple \"duck feet\" works tho""")
