### ISSUE TITLE
Implicit objects must be declared before use

### ISSUE THREAD

**Issue by Babofett** [scala/bug#11751] opened 2019-09-26 13:11 UTC
Stumbled across this strange behavior, when working on generic functions using implicit objects.

The following code snippet works just fine:

```
object DecBeforeUseImplicit extends App {
    trait Measure[A] {
        def measure(a: A): Int
    }

    case class ConstrWorker(name: String, age: Int, weight: Int)
    val andy = ConstrWorker("Andy", 25, 105)

    def measure[A](a: A)(implicit measure: Measure[A]): Int =
        measure.measure(a)

    implicit object MeasureWorker extends Measure[ConstrWorker] {
        override def measure(a: ConstrWorker): Int = a.weight
    }

    println(measure(andy))
}
```

But if I declare the implicit object after using measure, like this:
```
object DecBeforeUseImplicit extends App {
    trait Measure[A] {
        def measure(a: A): Int
    }

    case class ConstrWorker(name: String, age: Int, weight: Int)
    val andy = ConstrWorker("Andy", 25, 105)

    def measure[A](a: A)(implicit measure: Measure[A]): Int =
        measure.measure(a)

    println(measure(andy))

    implicit object MeasureWorker extends Measure[ConstrWorker] {
        override def measure(a: ConstrWorker): Int = a.weight
    }
}
```
The compiler can't find the implicit value for parameter measure and therefore there aren't enough arguments for measure.

Error Message:
Error:(18, 18) could not find implicit value for parameter measure: DecBeforeUseImplicits.Measure[DecBeforeUseImplicits.ConstrWorker]
  println(measure(andy))
Error:(18, 18) not enough arguments for method measure: (implicit measure: DecBeforeUseImplicits.Measure[DecBeforeUseImplicits.ConstrWorker])Int.
Unspecified value parameter measure.
  println(measure(andy))

Here is the file:
[DecBeforeUseImplicits.zip](https://github.com/scala/bug/files/3657844/DecBeforeUseImplicits.zip)

I'm using scala-sdk-2.13.0, JDK-11.0.3 and IntelliJ 2019.2.1 with Scala Plugin.

Maybe I'm totally wrong. If so, I'm very sorry and it'd be great, if you could link the part of the docs where the right way is mentioned.

**Comment by Jasper-M** [comment] 2019-09-26 13:54
I think #8697 is the canonical ticket for this issue.

**Comment by eed3si9n** [comment] 2019-09-26 15:18
I am going to close this as duplicate then.

**Closed by eed3si9n** 2019-09-26 15:18 UTC

**Comment by hrhino** [comment] 2019-09-26 15:27
duplicate of #8697
