### ISSUE TITLE
False positive in missing interpolator warning

### ISSUE THREAD

**Issue by scabug** [scala/bug#10217] opened 2017-03-02 14:59 UTC
```scala
scala> object T; """foo \$T bar"""
<console>:13: warning: possible missing interpolator: detected interpolated identifier `$T`
 """foo \$T bar"""
 ^
defined object T
res0: String = foo \$T bar
```

but then..

```scala
scala> object T; s"""foo \$T bar"""
scala.StringContext$InvalidEscapeException: invalid escape at terminal index 4 in "foo \". Use \\ for literal \.
  at scala.StringContext$.loop$1(StringContext.scala:211)
  at scala.StringContext$.replace$1(StringContext.scala:246)
  at scala.StringContext$.treatEscapes0(StringContext.scala:250)
  at scala.StringContext$.treatEscapes(StringContext.scala:195)
  at scala.StringContext.$anonfun$s$1(StringContext.scala:95)
  at scala.StringContext.standardInterpolator(StringContext.scala:123)
  at scala.StringContext.s(StringContext.scala:95)
  ... 29 elided
```

N.B. the difference between line 1 and line 2 is the extra 's' before the string.

The compiler warns about a "possible missing interpolator" when no interpolation would occur.

## workaround

Use the f-interpolator and double the "$"'s and the "\"s:

```
scala> object T; f"""foo \\$$T bar"""
object T
val res2: String = foo \$T bar
```

**Comment by som-snytt** [comment] 2024-02-21 21:02
The last suggestion was to suggest:
```
did you mean `raw"\$T"`?
```
That would be clever mind reading.

Closing as not a bug because of the example for windows file names.

Alternatively, use a hypothetical `id"\$T"` which does nothing but reconstruct the literal text.

As of 2.13, there is no warning for seeming to interpolate a module (object); and `\` is escape for quote in strings and interpolations.

**Closed** 2024-02-21 21:02 UTC
Labels: help wanted
