### ISSUE TITLE
assignment to tuple is not typechecked

### ISSUE THREAD

**Issue by happyser** [scala/bug#10574] opened 2017-10-29 06:56 UTC
scala 2.11.8 (doesn't work in scala 2.12.4 either)

Following code compiles and fails on tuple assignment

   def tupleIssue() = {

    val (d: Long, justCreated: Boolean) = {

      if (false) {
        (true)
      } else {
        (None, false)
      }
    }
  }

**Comment by martijnhoekstra** [comment] 2017-10-29 16:07
The if expression evaluates to Any, which just leaves us with https://github.com/scala/bug/issues/5898 - which makes this a duplicate I think?

**Comment by SethTisue** [comment] 2017-10-29 17:18
duplicate of #5898

**Closed by SethTisue** 2017-10-29 17:18 UTC
