### ISSUE TITLE
scala.jdk.CollectionConverters does not import OptionConverters

### ISSUE THREAD

**Issue by mslinn** [scala/bug#11615] opened 2019-07-06 20:33 UTC
Seems like an oversight. `CollectionConverters` should include all converters; if someone just wants `OptionConverters` they can just import that. Here is an example of what I mean:

```
trait DefineOptional {
  import java.util.Optional

  val x: Optional[String] = Optional.of("hi")
}

object TestOptional1 extends App with DefineOptional {
  import scala.jdk.CollectionConverters._ // does not define Optional.asScala or Optional.toScala

  x.asScala  // Error: value asScala is not a member of java.util.Optional[String]
  x.toScala  // Error: value toScala is not a member of java.util.Optional[String]
}

object TestOptional2 extends App with DefineOptional {
  import scala.jdk.CollectionConverters._ // currently does not include OptionConverters
  import scala.jdk.OptionConverters._

  x.asScala  // deprecated
  x.toScala
}
```

**Comment by dwijnand** [comment] 2019-07-06 20:40
> `CollectionConverters` should include all converters

All converters?  Why?

Personally, I'm in camp "Option isn't a collection" so the status quo seems right to me.

**Comment by mslinn** [comment] 2019-07-06 21:03
I disagree. Option has been sold as a collection to Scala programmers for years. I am unaware of any reason to change that message, and there was no prior warning that this would ever change.

**Comment by hrhino** [comment] 2019-07-06 21:13
I'd rather not have that wording at all; I'm in the same camp as @dwijnand.

However, doesn't 2.13 `Option` extend `IterableOnce` now? That's pretty unarguably a "collection" class, so that bridge has been crossed in a non-documentation way. I wouldn't expect `CollectionConverters` to include `OptionConverters` personally, but in 2.13+ it's less objectionable.

All that said, this will have to wait until 2.14; sorry.

**Comment by mslinn** [comment] 2019-07-06 21:18
That wording has been in the Scaladoc Option since Scala 2.9, without controversy: https://www.scala-lang.org/api/2.9.0/index.html#scala.Option

**Comment by hrhino** [comment] 2019-07-06 21:56
I don't know about "without controversy"; that documentation was put in relatively early in Scala's history (with probably little review). scala/scala#8038 contains a lot of points in favor and against `Option` being part of the "collections hierarchy". 

A PR would be an excellent way to invite further discussion and possibly get this changed. (There's no 2.14.x branch yet, but there will be soon.)

**Comment by mslinn** [comment] 2019-07-06 22:11
[Scala was 10 years old](https://www.javatpoint.com/history-of-scala) when v2.9 was released. Describing `Option` as a collection in the Scaladoc at that time was not a rash decision. Remember the collection classes were implemented the year before, with v2.8.

**Comment by dwijnand** [comment] 2019-07-06 23:10
I'd argue "treat it as a collection" never made Option a collection either.

(Also, giving it an iterator - which is +/- what extending 2.13's IterableOnce does - still doesn't _make_ it a collection, imho.  But... it's pushing it.)

**Comment by mslinn** [comment] 2019-07-06 23:19
Is there a business reason for making a philosophical change to Scala such as this? I have only seen discussion of implementation details by compiler folk so far. Scala's users are programmers, and a very select few are the only ones discussing this fundamental shift in the user's mental model of how to work with Scala. 

From a product point of view there should be no visible changes to an end user's understanding of what Scala is and how to work with it effectively unless there is data that shows clear and present benefit in such a change. What tremendous benefit would an end user enjoy from changing Scala in this way?

**Comment by hrhino** [comment] 2019-07-07 00:07
Which change do you mean?

**Comment by mslinn** [comment] 2019-07-07 00:22
Scala's `Option` is and always has been considered to be a proper collection that happens to have only two states: empty, or containing exactly one value. Implementing a Scala compiler and/or the Scala run-time library with a different opinion would be a significant change for end users (I'm talking about application programmers, not compiler technologists).

Implementation details are irrelevant to end users, and therefore are not of interest to me. This discussion is about the mental model that end users employ when using Scala to go about their business.

**Comment by hrhino** [comment] 2019-07-07 00:35
> Implementing a Scala compiler and/or the Scala run-time library with a different opinion would be a significant change for end users

I'm sorry; I've gotten lost somewhere. What about the compiler or the library has changed to reflect any change in the status of `Option`, other than the aforementioned addition of `IterableOnce` as a superclass?

> Implementation details are irrelevant to end users, and therefore are not of interest to me. This discussion is about the mental model that end users employ when using Scala to go about their business.

I feel like I've missed something. What concrete part of the scala library/compiler changed?

**Comment by mslinn** [comment] 2019-07-07 00:41
Collection classes were re-implemented for Scala 2.13. This bug report was created because those responsible for re-implementing the collection classes did not want `Option` to be considered as a collection and therefore did not import `OptionConverters` as part of the `scala.jdk.CollectionConverters` import.

**Comment by hrhino** [comment] 2019-07-07 00:54
Ah.

> some of those responsible for re-implementing the collection classes did not want `Option` to be considered as a collection and therefore did not import `OptionConverters` as part of the `scala.jdk.CollectionConverters` import.

I think this is quite unfair to the implementors of the 2.13 collections, and implies a motive which I doubt anyone held: namely, to "de-collectionify `Option`" by sneakily removing it from `CollectionConverters` in such a way as to "slip... [it] by the review process" against consensus. 

That is not what happened. Indeed, in 2.12 the situation is analogous: `import scala.collection.JavaConverters._` brings into scope no converters involving `Option` that I'm aware of; `scala-java8-compat` was the library containing the conversions. It wasn't until 2.13 that the conversion even existed in stdlib! I don't see how it can be considered a "change" that `import scala.jdk.CollectionConverters._` in 2.13 and `import scala.collection.JavaConverters._` in 2.12 operate on the same set of types. 

This could be a desirable change for 2.14, but I can't see it as a regression from 2.12.

**Comment by mslinn** [comment] 2019-07-07 01:17
If architecture is philosophy, then a change in philosophy is a change in architecture. So long as the Scala philosophy remains unchanged, this issue is more properly categorized as a bug, not an enhancement.

**Comment by NthPortal** [comment] 2019-07-07 02:23
@mslinn to reiterate and expand on what Harrison said:

In 2.12, what is currently `scala.jdk.CollectionConverters` was called `scala.collection.JavaConverters`. When merging the converters from scala-java8-compat into the standard library, there was a desire to keep them all together (in `scala.jdk`) rather than having them scattered across a variety of packages (`scala.collection`, `scala.concurrent`, etc.), for ease of discovery. As part of this, `JavaConverters` got renamed to `CollectionConverters` as it always only operated on collections and is no longer in the `collection` package.

scala-java8-compat for 2.12 contains the following converters under `scala.compat.java8`:
- `DurationConverters`
- `FutureConverters`
- `OptionConverters`
- `PrimitiveIteratorConversions`
- `SpliteratorConverters`
- `StreamConverters`

These were, with some amount of restructuring to account for core parts of them being in the standard library now, put in the `scala.jdk` package alonside the "existing" `CollectionConverters`. `OptionConverters` was previously separate from `CollectionConverters`.

In addition, it is worth noting that `java.util.Optional` is very much NOT a Java collection, and thus one would not expect (from a Java perspective) to find `OptionConverters` (which converts between `scala.Option` and `java.util.Optional`) to be part of `CollectionConverters`, regardless of whether or not `Option` is considered a collection from Scala's perspective. `CollectionConverters` converts between Java and Scala collections, and `OptionConverters` does not do that.

Additionally, even though Scala sometimes treats `Option` as a collection (and you may be used to doing this), it has never fully been a collection because it can only contain a single element (see scala/scala#8038 for more details of this discussion). Unlike the rest of the collections, which you can convert between (e.g. you can create a `Set` from a `Seq`, a `Seq` from a `Map`, etc.), you cannot create an `Option` from other collections because it cannot hold their elements; it can at most hold their `head`. You can also experience its not-a-collection-ness in the following code not compiling:

```scala
for {
  a <- Some(1)
  b <- List(1, 2, 3)
} yield a + b
```

It works if you replace the `Option` with any other collection (`HashSet(1)`, `Vector(1)`, `ArraySeq(1)`, `TreeSet(1)`, `BitSet(1)`, etc.). But it doesn't work with `Option` because `Option` can only hold a single element; and if somehow it *did* work, you'd get `Some(2)` and lose the elements `3` and `4`.

**Comment by mslinn** [comment] 2019-07-07 02:33
@odersky is the authority on a "philosophy of Scala" question. I'd be interested in his viewpoint.

**Comment by SethTisue** [comment] 2019-07-07 03:01
There are significant commonalities between `Option` and collections. Nonetheless,`Option` isn't a collection, never has been. and didn't become one when it became `IterableOnce`. I suggest we close this.

**Comment by mslinn** [comment] 2019-07-07 03:06
@odersky is the authority on a "philosophy of Scala" question. I'd be interested in his viewpoint.

**Comment by mslinn** [comment] 2019-07-07 03:07
This controlling of the narrative by sudden termination is what usually happens at this point.

**Comment by lrytz** [comment] 2019-07-07 06:24
> There are significant commonalities between `Option` and collections. Nonetheless,`Option` isn't a collection, never has been. and didn't become one when it became `IterableOnce`.

That's my view as well. `IterableOnce` is just `HasAnIteratorMethod`.

**Comment by dwijnand** [comment] 2019-07-07 07:06
How is disagreeing with you and suggesting to close the issue "controlling the narrative"?

To me it looks like, despite several people disagreeing with you and Nth presenting a great summary of events, you seem to insist to paint this as a "change in philosophy" when it's not.

It's common on the Scala project that when consensus isn't reached on a GitHub thread to close such thread and invite the participants to open a thread on the contributors discourse forums where, by the way, Martin is often present so we may get his perspective on this.

**Comment by som-snytt** [comment] 2019-07-07 10:45
This is an interesting question because it is likely to be played out many times during the transition to Scala 3, with respect to many features, despite efforts (on the part of the producers of the software) to minimize efforts (on the part of the consumers).

It would be nice if there were a document to point to as the current best understanding. Probably PRs won't suffice over the longer haul as migration documentation; they form the basis of release notes, but if I ask, "I expected to convert option this way, how should I do that?", there may or may not be a document to either consult or update with the answer I learned today.

Note that the Scaladoc for Option has always been among the best. The "treat it like a collection" recommendation is just a metaphor, and is in contrast to pattern matching, as a matter of philosophy. So maybe just updating the Scaladoc is called for, in this case.

One could add, consider going importless:

```
$ scala -Yimports:java.lang,scala,scala.Predef,scala.util.chaining,scala.jdk.OptionConverters
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 12.0.1).
Type in expressions for evaluation. Or try :help.

scala> val x = java.util.Optional.of("hi")
x: java.util.Optional[String] = Optional[hi]

scala> x.toScala
res0: Option[String] = Some(hi)
```

I suspect that if you addressed Dr Odersky as an authority, he would say, "Not an authority," the way Janet on "The Good Place" says, "Not a robot" and "Not a woman."  He's really a middle manager who is very good at corralling the hard efforts and strong opinions of some researchers and reconciling them with hard efforts and strong opinions of his own. The way Janet is a being who knows everything and can materialize universes.

**Comment by odersky** [comment] 2019-07-08 09:28
@NthPortal Thanks for the detailed summary. The reasoning about converter design looks solid to me.

**Closed** 2019-07-08 18:00 UTC
Labels: enhancement, java interop, library:collections
