### ISSUE TITLE
"Ambiguous implicit values" error caused by a mix of `-Xsource:3`, an explicit (not wildcard) import and a evicted/transitive(?) dependency

### ISSUE THREAD

**Issue by hmemcpy** [scala/bug#12350] opened 2021-02-23 19:14 UTC
We've hit a strange issue today, and it took me a while to track down, but I was able to reproduce it. Here's an example of the issue on Scastie: https://scastie.scala-lang.org/hmemcpy/PLSmFypOQ0arLZmTb50dfQ/7

It boils down to the following combination: compiling with `-Xsource:3`, a non-wildcard import, and referencing a dependency directly and indirectly via another one. I was able to reproduce this with the ZIO library. Given the conditions mentioned, the following code snippet doesn't compile:

```scala
import zio.ZIO

val nextRand = zio.random.nextDoubleBetween(0, 1)
ZIO.collectAll(List.fill(3)(nextRand))
```

failing with the following error:
```
ambiguous implicit values:
 both method buildFromAny in trait BuildFromCompat of type [Element, Collection[+Element] <: Iterable[Element] with scala.collection.IterableOps[Any,Collection,Any]]zio.package.BuildFrom[Collection[Any],Element,Collection[Element]]
 and method buildFromIterableOps in trait BuildFromLowPriority2 of type [CC[X] <: Iterable[X] with scala.collection.IterableOps[X, CC, _], A0, A]scala.collection.BuildFrom[CC[A0],A,CC[A]]
 match expected type zio.BuildFrom[List[zio.ZIO[zio.random.Random,Nothing,Double]],Double,List[Double]] [56:23]
```

## reproduction steps

using Scala 2.13.4 (and 2.13.5), and the following sbt definition:
```scala
lazy val zioVersion = "1.0.4-2"
lazy val zioConfigVersion = "1.0.0"

ThisBuild / scalaVersion := "2.13.4"

lazy val root = project
  .in(file("."))
  .settings(
    libraryDependencies ++= Seq(
      "dev.zio" %% "zio" % zioVersion,
      "dev.zio" %% "zio-config" % zioConfigVersion,
    ),
    scalacOptions ++= Seq(
       "-Xsource:3"
    ),
  )
```

Adding a file with the code snippet above causes it to fail with "ambiguous implicit values" error. Enabling `-Ydebug` revealed additional errors:
```
[ suppressed ] Cannot construct a collection of type immutable.this.List[scala.this.Double] with elements of type scala.this.Double based on a collection of type immutable.this.List[zio.this.ZIO[<root>.this.zio.random.Random,scala.this.Nothing,scala.this.Double]].
  ZIO.collectAll(List.fill(3)(nextRand))

[ suppressed ] not enough arguments for method collectAll: (implicit bf: zio.this.BuildFrom[immutable.this.List[zio.this.ZIO[<root>.this.zio.random.Random,scala.this.Nothing,scala.this.Double]],scala.this.Double,immutable.this.List[scala.this.Double]]): zio.this.ZIO[<root>.this.zio.random.Random,scala.this.Nothing,immutable.this.List[scala.this.Double]].
Unspecified value parameter bf.
  ZIO.collectAll(List.fill(3)(nextRand))
```

## problem analysis

The `ZIO.collectAll` function requires an implicit `BuildFrom`, and provides a conversion in the `zio.BuildFromCompat` trait.

The dependency `zio-config` depends itself on ZIO v1.4.0-2. However, when both are referenced - it causes the compilation error (even though I'm not using anything from zio-config directly). Removing zio-config from `libraryDependencies` does not cause the issue (I initially thought this had to do with a mismatched ZIO version being evicted, but was able to confirm this not working even with "matching" versions).

## workaround

When either removing `-Xsource:3` OR removing `zio-config` OR importing `zio._` instead of just `zio.ZIO` - the code compiles without problems!

I'm not sure who's the culprit here...

**Comment by Jasper-M** [comment] 2021-02-24 09:44
FWIW I get the compilation errors whether I select `v1.0.4-2` or `v1.0.4` in scastie.

**Comment by hmemcpy** [comment] 2021-02-24 13:40
@Jasper-M looks like you're right - seems I made a mistake and I can reproduce this even with referencing 1.4.0-2. However, it does seem that both libraries are required - when I remove `zio-config` (even though I'm not using it directly) - the problem does not occur!

I'll amend my issue. Thanks!

**Comment by Jasper-M** [comment] 2021-02-24 14:05
The trigger of the issue seems to be in zio 1.4.0-2. That version gives the error, while zio 1.4.0 doesn't (if 1.4.0-2 doesn't get pulled in transitively that is).

And it [looks like](https://github.com/zio/zio/compare/v1.0.4...v1.0.4-2#diff-69abee46f49b1a1cdfb67a3e80f5b0027b1bb37eebf37da65a89860914a85979) that `buildFromAny` method in the error message was added between those 2 versions.

I guess you'd have to cross-compile with actual Scala 3 to know if it's actually some kind of bug in `-Xsource:3` or if it's caused by a legitimate change in implicit resolution in Scala 3.

**Comment by hmemcpy** [comment] 2021-02-24 14:20
@Jasper-M looks like you're right again, I hadn't even looked at when the `buildFromAny` was added (seems [January 22nd](https://github.com/zio/zio/pull/4582)). Let me try cross-compiling and minimizing this even further. Cheers!

**Comment by Jasper-M** [comment] 2021-02-24 14:21
> I guess you'd have to cross-compile with actual Scala 3 to know if it's actually some kind of bug in -Xsource:3 or if it's caused by a legitimate change in implicit resolution in Scala 3.

Though I have to add that I doubt that all changes that affect implicit resolution have been ported to `-Xsource:3`.

**Comment by som-snytt** [comment] 2021-02-24 16:05
The big/only change is variance. (No other changes around shadowing, nesting.)

It's a good interview question, whether a single import can be more ambiguous than a wildcard.

I notice the zio test is in the zio package. I have noticed elsewhere that this convention means we don't test the imports ergonomics of the user.

**Comment by nartamonov** [comment] 2021-03-17 16:40
I've got the same issue with Scala 2.13.5 and ZIO 1.0.5:

![image](https://user-images.githubusercontent.com/1040557/111504093-61a4e380-8758-11eb-9a8c-86d9edb9c80d.png)

I haven't `zio-config` in classpath, but have `zio-interop-cats` 2.3.1.0 and `zio-test` 1.0.5

Wildcard import `zio._` instead of `zio.ZIO` fixed problem.

**Comment by joroKr21** [comment] 2021-03-17 17:46
See #12104 and zio/zio#4582

**Comment by SethTisue** [comment] 2021-03-17 18:18
closing — but of course happy to reopen if this is somehow found to be actionable in scala/scala

**Closed by SethTisue** 2021-03-17 18:18 UTC

**Comment by adamgfraser** [comment] 2021-03-17 18:32
I don't think this is a ZIO issue. The implicit defined there is a workaround for [this](https://github.com/scala/bug/issues/12104) Scala bug that is a regression from 2.12 and I have not seen any issues with its from any of our users except in this situation where there seem to be inconsistent versions that are not being properly handled.

**Comment by hmemcpy** [comment] 2021-03-17 19:10
FWIW, I don't think this is a ZIO issue, but it was the "easiest" for me to reproduce with, since it's a pretty weird constellation. I could try to minimize this even further, but I wish I had a hint as to where this problem occurs. I initially thought this was due to an evicted mismatched version, but as @Jasper-M pointed above - this happens when both the direct and indirect dependency have the same version.

The reason I reported this (despite having suitable workarounds) is that this error was discovered by a colleague who is quite new to Scala, and called me over to investigate. And it took some time to minimize.

**Comment by SethTisue** [comment] 2021-03-17 19:19
Understood — such reports, even though incomplete, are often valuable.

**Comment by SethTisue** [comment] 2021-03-17 19:20
>  I have not seen any issues with its from any of our users

The simplest explanation for that would be that most Scala users in general don't have `-Xsource:3` enabled.

**Comment by adamgfraser** [comment] 2021-03-17 19:32
@SethTisue My point was more that a lot of Scala users are have Scala 2.13 and I haven't seen any reports of issues related to interactions between that implicit instance and the ones in the Scala standard library. Agree about Scala 3.

**Comment by joroKr21** [comment] 2021-03-18 03:20
The implicit is being pulled into scope because `BuildFrom` is a type alias and the instance is located in the `zio` package object, is that right? It seems that this was intentional but it's clashing with the instances provided by the standard library.

**Comment by adamgfraser** [comment] 2021-03-18 03:24
Where is it clashing? We have had this out for a while and haven't had any reports of issues related to it. And instance is definitely not being provided by standard library in some cases which is why some operators were not working without this being added. Maybe there are some cases where it conflicts but have not seen them. I would like nothing more than to have this fixed in the standard library so we can delete all of these implicit from our code base! 😃

**Comment by adamgfraser** [comment] 2021-03-18 03:26
So is there something different about implicit resolution with this setting on that is causing an issue where it would not otherwise exist?

**Comment by som-snytt** [comment] 2021-03-18 03:36
> The big/only change is variance

https://github.com/scala/scala/pull/6037

is under `-Xsource:3`.
