### ISSUE TITLE
Compiler option `-Vtype-diffs` leads to  error type information lost in some case.

### ISSUE THREAD

**Issue by counter2015** [scala/bug#12561] opened 2022-03-18 11:51 UTC
## Reproduction steps

Scala version: 2.13.8

The `build.sbt`
```scala
ThisBuild / version := "0.1.0"

ThisBuild / scalaVersion := "2.13.8"


lazy val root = (project in file("."))
  .settings(
    name := "demo"
  )
  .aggregate(
    project1
  )

lazy val project1 =
  (project in file("project1"))
    .settings(
      commonSettings("project1"),
      libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.5.32"
    )



def commonSettings(module: String, languageVersion: String = "2.13.8") = {
  Seq[Setting[_]](
    name              := s"demo-$module",
    scalaVersion      := languageVersion,
    scalacOptions ++= Seq(
      "-Vtype-diffs",
    ),
    fork := true
  )
}
```
The code

```scala
import akka.actor.ActorSystem

import scala.concurrent.duration._

object BugExample {

  def main(args: Array[String]): Unit = {
    val system = ActorSystem("test")
    implicit val ec = system.dispatcher

    system.scheduler.schedule(1.second, 10.seconds, () => println("why cant convert this to Runnable"))
  }

}
```

## Problem

When compile above code, the type information is lost in error.
```
BugExample.scala:11:56: type mismatch;
[error]   () => scala.Unit
[error]     system.scheduler.schedule(1.second, 10.seconds, () => println("why cant convert this to Runnable"))
[error]                                                        ^
[error] one error found
[error] (project1 / Compile / compileIncremental) Compilation failed
```

It should be 
```
BugExample.scala:11:56: type mismatch;
[error]  found   : () => Unit
[error]  required: Runnable
[error]         system.scheduler.schedule(1.second, 10.seconds, () => println("why cant convert this to Runnable"))
```

see also #12560

**Comment by SethTisue** [comment] 2022-04-19 17:40
@tek @tribbloid thoughts? (might you be interested in attempting a fix?)

as an aside, it would be nice to have a minimization without external dependencies

**Comment by tribbloid** [comment] 2022-04-19 18:33
@SethTisue good discovery, trying to reproduce with various splain options now ...

**Comment by tribbloid** [comment] 2022-04-29 19:57
@counter2015 strange ... It compiles successfully with NO error. There seems to have an implicit conversion from `() => Unit` to java Runnable in scala Predef. Are you sure that Runnable in your error message refers to `java.lang.Runnable`?

**Comment by SethTisue** [comment] 2022-04-29 20:51
> There seems to have an implicit conversion from () => Unit to java Runnable in scala Predef

there's nothing for that in `Predef`  — `Runnable` is a SAM (Single Abstract Method) type (see https://github.com/scala/scala/releases/tag/v2.12.0)

**Comment by tribbloid** [comment] 2022-04-30 17:30
@SethTisue  you are right.

@counter2015 still it looks like your compiler environment may have disabled this feature. Could you instruct me the correct way to reproduce this? (Scastie environment preferred: https://scastie.scala-lang.org/)

**Comment by counter2015** [comment] 2022-04-30 17:43
@tribbloid https://scastie.scala-lang.org/qbYVjlKeSi2LOqdTXensHw
How about this ?
![image](https://user-images.githubusercontent.com/13608862/166116465-4de7f68a-7479-40f2-927b-9c5d9d3c6258.png)

**Comment by tribbloid** [comment] 2022-05-01 20:26
Thanks a lot, I've already reproduced it and added it into test suite, turns out the implicit cast cannot co-exist with ad-hoc polymorphism

**Comment by tribbloid** [comment] 2022-05-01 22:49
FIXED by changing to the following impl:

```
  override def formatDiffImpl(found: Type, req: Type, top: Boolean): Formatted = {
    val (left, right) = dealias(found) -> dealias(req)

    val normalized = Seq(left, right).map(_.normalize).distinct
    if (normalized.size == 1) return formatType(normalized.head, top)

    if (left.typeSymbol == right.typeSymbol) formatDiffInfix(left, right, top)
    else formatDiffSpecial(left, right, top).getOrElse(formatDiffSimple(left, right))
  }
```

should be in 2.13.9 soon

**Comment by tribbloid** [comment] 2022-05-07 20:35
https://github.com/scala/scala/pull/10029

**Closed** 2022-06-30 17:42 UTC
Labels: has PR, errors and warnings
