### ISSUE TITLE
java.util.TreeMap's lowerKey/higherKey should return Either[None, K] instead of K

### ISSUE THREAD

**Issue by Yuandong-Chen** [scala/bug#11350] opened 2019-01-13 19:32 UTC
```
scala> t
res55: java.util.TreeMap[Int,Int] = {0=9, 1=2, 2=3, 4=3, 6=3}
scala> t.lowerKey(0)
res56: Int = 0
scala> t.lowerKey(1)
res57: Int = 0
scala> t.lowerKey(0) == null
<console>:15: warning: comparing values of types Int and Null using `==' will always yield false
       t.lowerKey(0) == null
                     ^
res58: Boolean = true
scala> t.lowerKey(1) == null
<console>:15: warning: comparing values of types Int and Null using `==' will always yield false
       t.lowerKey(1) == null
                     ^
res59: Boolean = false
```
It is confusing to treats 0 as None here because we might have valid Int 0 as valid return value.

**Comment by lourkeur** [comment] 2019-01-13 20:56
As discussed on Gitter, this is an issue with the way Scala unboxes null values. The best way to avoid the issue is to prevent implicit unboxing by passing `java.lang.Integer` as a type parameter to `TreeMap` instead of `scala.Int`.

This is a little confusing, but I don't think it will be fixed since it's like that in the Scala Language Specification and is consistent with other things in the language.

More details: https://gist.github.com/lourkeur/d8de1b08f7357cb72c51f78f04b9e3fb

**Comment by Jasper-M** [comment] 2019-01-14 08:50
`Option[K]` might be preferable. For these edge cases in Java-Scala compatibility, probably the best you can do is add some extension methods that do the right Scala thing.

**Comment by ashwinbhaskar** [comment] 2019-02-07 01:52
@Yuandong-Chen How was the treemap 't' initialized?

**Comment by Yuandong-Chen** [comment] 2019-02-08 02:27
@ashwinbhaskar 
var t = new java.util.TreeMap[Int,Int]()
Check out scala java interop for more detail.

**Comment by SethTisue** [comment] 2023-10-16 22:11
This is working as designed. It's not clear what other design is possible.

**Closed by SethTisue** 2023-10-16 22:11 UTC
Labels: library:collections
