### ISSUE TITLE
ListMap and ListSet iterator optimization

### ISSUE THREAD

**Issue by neontorrent** [scala/bug#11752] opened 2019-09-27 01:09 UTC
Currently, for ListMap and ListSet, every call to iterator will build a whole List:

```
  def iterator: scala.collection.Iterator[A] = {
    var curr: ListSet[A] = this
    var res: List[A] = Nil
    while (!curr.isEmpty) {
      res = curr.elem :: res
      curr = curr.next
    }
    res.iterator
  }
```

 which means a simple call to head:

    listMap.head

will require building a whole list of all elements, and get the first item. This is disasterous for large ListSet and ListMap. 

We should optimize iterator implementation to create custom Iterator object, rather than build a whole list and get the list iterator.

**Comment by Jasper-M** [comment] 2019-09-27 08:27
Looks like this also means that the doc which says "last and init are O(1)" is very wrong.

**Comment by texasbruce** [comment] 2019-10-01 00:01
@SethTisue I'll try to draft a PR.

**Comment by joshlemer** [comment] 2019-10-03 14:13
>We should optimize iterator implementation to create custom Iterator object, rather than build a whole list and get the list iterator.


The problem is that ListSet and ListMap are stored in reverse-order, so to traverse the data in forward-order, you need to build some kind of buffer. An improvement might be to buffer the elements in an `ArrayBuffer`, but can't be avoided entirely.

**Comment by texasbruce** [comment] 2019-10-04 16:20
> > We should optimize iterator implementation to create custom Iterator object, rather than build a whole list and get the list iterator.
> 
> The problem is that ListSet and ListMap are stored in reverse-order, so to traverse the data in forward-order, you need to build some kind of buffer. An improvement might be to buffer the elements in an `ArrayBuffer`, but can't be avoided entirely.

We can change it to double linked list.

The current way is way too unoptimized and cannot even guarantee O(1) for head.

**Comment by joshlemer** [comment] 2019-10-04 17:03
If it's a double linked list though, that will increase the cost of insertions, because even new keys will require a complete rebuild. Though, TBH I am not really sure why someone would ever use a ListMap or ListSet, they are worse in virtually all circumstances than TreeMap or HashMap, in my opinion, the best option would be deprecation.

**Comment by plokhotnyuk** [comment] 2019-10-04 19:04
@joshlemer I'm happy that I'm not alone:
https://www.reddit.com/r/scala/comments/dbmetd/comment/f26874k

**Comment by texasbruce** [comment] 2019-10-05 00:33
@joshlemer Why does it need a new rebuild for every insertion?

Each node only has reference to previous and next node, and the collection includes a head and tail reference. It should only need to update 1-2 nodes for every insertion/deletion.

It is useful in some situations. As its name indicates, it retains the order of insertion. We use a custom ListMap (due to this issue in std lib) as a coalescing queue for event processing.

**Comment by joshlemer** [comment] 2019-10-05 01:03
> @joshlemer Why does it need a new rebuild for every insertion?
> 
> Each node only has reference to previous and next node, and the collection includes a head and tail reference. It should only need to update 1-2 nodes for every insertion/deletion.  
  
If you have a `DoubleListMap('a' -> 1, 'b' -> 2, 'c' -> 3)` it will look like this:
```
('a', 1) <-> ('b', 2) <-> ('c', 3)
```
If you then want to insert `'d' -> 4`, you would end up with 
```
('a', 1) <-> ('b', 2) <-> ('c', 3) <-> ('d',4)
```
So not only does the `('d',4)` node need to be created but also a new `('c',3)` node needs to be created so that it can have a backpointer to the `('d',4)` node, and because that node is changed, we must create a new `('b',2)` node to point to that new `'c'` node, and so on all the way to the front of the map. 

>it is useful in some situations. As its name indicates, it retains the order of insertion. We use a custom ListMap (due to this issue in std lib) as a coalescing queue for event processing.

Fair enough, but since 2.13, we have generic abstractions `collection.SeqMap[K,V]`, `immutable.SeqMap[K,V]` and `mutable.SeqMap[K, V]` as well as 2 other better implementations of the immutable SeqMap (`VectorMap` and `TreeSeqMap`), and perhaps better implementations could be made which are even more performant implementations may be possible (such as the `PersistentOrderedMap` in kotlinx immutable collections (https://github.com/Kotlin/kotlinx.collections.immutable/blob/master/core/commonMain/src/implementations/persistentOrderedMap/PersistentOrderedMap.kt), which may be faster).

**Comment by texasbruce** [comment] 2019-10-05 04:48
@joshlemer That's correct for immutable ListMap. I just realized in 2.13 mutable ListMap became deprecated. We don't need to do that way for mutable ListMap, as we can just modify the reference. Do you know why is the deprecation?

We should probably un-deprecate mutable ListMap and implement using double linked list. We don't have any mutable SeqMap implementation that behaves the same as current ListMap. (The only implementation LinkedHashMap behaves slightly different)

**Comment by joshlemer** [comment] 2019-10-05 14:59
In what way to LinkedHashMap and ListMap behave differently? Is it that LinkedHashMap updates its keys in-place, whereas ListMap updates its keys by moving them to the back?

**Comment by joshlemer** [comment] 2019-10-05 15:07
if that's the case, then the same semantics could be implemented really simply, utilizing the LinkedHashMap, with much greater performance. .

```scala
final class LinkedHashMapWithAppendingUpdates[K, V] private(lhm: LinkedHashMap[K, V]) extends SeqMap[K, V] {
  override def iterator: Iterator[(K, V)] = lhm.iterator
  override def subtractOne(elem: K): this.type = {
    lhm.subtractOne(elem)
    this
  }
  override def get(key: K): Option[V] = lhm.get(key)
  override def addOne(elem: (K, V)): this.type = {
    lhm.remove(elem._1)
    lhm.addOne(elem)
    this
  }
}

object LinkedHashMapWithAppendingUpdates extends MapFactory[LinkedHashMapWithAppendingUpdates] {
  override def empty[K, V]: mutable.LinkedHashMapWithAppendingUpdates[K, V] = 
    new mutable.LinkedHashMapWithAppendingUpdates[K, V](mutable.LinkedHashMap.empty)
  override def from[K, V](it: IterableOnce[(K, V)]): mutable.LinkedHashMapWithAppendingUpdates[K, V] = 
    Growable.from(empty[K, V], it)
  override def newBuilder[K, V]: mutable.Builder[(K, V), mutable.LinkedHashMapWithAppendingUpdates[K, V]] = 
    new GrowableBuilder(empty[K, V])
}
```

**Comment by chaitanyav** [comment] 2020-07-26 21:11
@SethTisue can I work on this

**Comment by texasbruce** [comment] 2020-07-26 21:29
Now I reviewed what we discussed, we should definitely fix this.

> If it's a double linked list though, that will increase the cost of insertions, because even new keys will require a complete rebuild. Though, TBH I am not really sure why someone would ever use a ListMap or ListSet, they are worse in virtually all circumstances than TreeMap or HashMap, in my opinion, the best option would be deprecation.

This is the case for many immutable collections. Whenever we do modifications of an immutable collection, a new collection is built and returned, which is totally normal. This cost is expected when it comes to immutable collections. But the cost of accessing iterator is not at all, and way too expensive comparing to insertion/modifications. Immutable collections should definitely be more optimized for accessing instead of insertion/updating, if it has to come to a choice.

For mutable version, doubly linked list makes even more sense and it doesn't require building a whole collection, which is very ideal.

**Comment by texasbruce** [comment] 2020-08-17 21:11
@chaitanyav Are you going to create a PR? If not I will do that.

**Comment by NthPortal** [comment] 2020-08-18 03:07
> This is the case for many immutable collections.

It is, in general, not the case for immutable collections (exceptions include `ArraySeq`). The vast majority of immutable collections have significant structural sharing that allow creating new collections while rebuilding only small parts of the collection, if any at all.

Obviously, properties differ between various collections, but most immutable collections have *some* way to append or remove elements without a full collection rebuild. For example, `List` and `LazyList` allow prepending and removing elements from the front without *any* rebuilding.

> ```
> listMap.head
> ```
>
> will require building a whole list of all elements, and get the first item. This is disasterous for large ListSet and ListMap.

This is correct, and is an intended and [well-documented](https://www.scala-lang.org/api/2.13.3/scala/collection/immutable/ListMap.html) tradeoff of the collection's design:

> As such, methods such as `head` and `tail` are O(n), while `last` and `init` are O(1). Other operations, such as inserting or removing entries, are also O(n), which makes this collection suitable only for a small number of elements.

Like `List`, `ListMap` has some operations that are highly efficient, and some that are not; it just so happens that they are (roughly) the inverse operations of each other (because `ListMap` is backed by a reversed list).

It's not clear to me that there is a bug here.

**Comment by NthPortal** [comment] 2020-08-18 03:12
To elaborate, there are other aspects of `ListMap` with unfixably poor performance, which are accepted as part of its design - such as `contains` and `get` being O(n). Honestly, there are better alternatives to `ListMap` at this point (i.e. better `SeqMap` implementations), admittedly with worse memory profiles. I don't think you can change the design of `ListMap` without removing the few efficient operations it has, which to my mind both undermines the collection and is not an acceptable change without a different name for the collection.

**Comment by texasbruce** [comment] 2020-08-18 15:30
@NthPortal It comes down to which efficiency is more preferred, e.g. appending, or iterating. An immutable collection, to me, should be more optimized for accessing, rather than appending. On the other hand, a mutable collection should be more optimized for mutating. I think it makes sense to make immutable ListMap to be more optimized for iterating, while undeprecating mutable version and make it more optimized for mutating (but then if it is mutable, we can just use doubly linked list which do not require rebuilding the whole collection anyway)

**Comment by chaitanyav** [comment] 2020-08-20 01:57
> @chaitanyav Are you going to create a PR? If not I will do that.

@texasbruce Please go ahead.

**Comment by texasbruce** [comment] 2020-10-13 20:36
ListMap possible fix: https://github.com/scala/scala/pull/9220

**Comment by mkeskells** [comment] 2020-10-22 23:28
> Looks like this also means that the doc which says "last and init are O(1)" is very wrong.

why? Looks to be constant time to me
```
    override def last: (A, B1) = (key, value)
    override def init: ListMap[A, B1] = next
```

**Comment by texasbruce** [comment] 2020-10-22 23:38
> 
> 
> > Looks like this also means that the doc which says "last and init are O(1)" is very wrong.
> 
> why? Looks to be constant time to me
> 
> ```
>     override def last: (A, B1) = (key, value)
>     override def init: ListMap[A, B1] = next
> ```

That comment was referring to Scala 2.12 I believe.

**Comment by mkeskells** [comment] 2020-10-22 23:42
> > > Looks like this also means that the doc which says "last and init are O(1)" is very wrong.
> > 
> > 
> > why? Looks to be constant time to me
> > ```
> >     override def last: (A, B1) = (key, value)
> >     override def init: ListMap[A, B1] = next
> > ```
> 
> That comment was referring to Scala 2.12 I believe.

as is this code ! last changed in 2015

**Comment by texasbruce** [comment] 2020-10-23 00:03
> 
> 
> > > > Looks like this also means that the doc which says "last and init are O(1)" is very wrong.
> > > 
> > > 
> > > why? Looks to be constant time to me
> > > ```
> > >     override def last: (A, B1) = (key, value)
> > >     override def init: ListMap[A, B1] = next
> > > ```
> > 
> > 
> > That comment was referring to Scala 2.12 I believe.
> 
> as is this code ! last changed in 2015

Not sure which version that is, but I see that in 2.13.

In 2.12.12 here https://github.com/scala/scala/blob/v2.12.12/src/library/scala/collection/immutable/ListMap.scala you can see it's not there

**Comment by texasbruce** [comment] 2020-10-23 00:05
> 
> 
> > > > Looks like this also means that the doc which says "last and init are O(1)" is very wrong.
> > > 
> > > 
> > > why? Looks to be constant time to me
> > > ```
> > >     override def last: (A, B1) = (key, value)
> > >     override def init: ListMap[A, B1] = next
> > > ```
> > 
> > 
> > That comment was referring to Scala 2.12 I believe.
> 
> as is this code ! last changed in 2015

You are right. Now I see those in the Node class.

**Comment by Ichoran** [comment] 2020-10-23 04:17
Changing which behavior is `O(1)` and which is `O(n)` just because it makes more sense to you is a very bad idea, because people have working code that probably relies (at least accidentally) on the complexity being the way it is.

**Comment by Jasper-M** [comment] 2020-10-26 09:11
@mkeskells 
> why? Looks to be constant time to me

I think I looked in the wrong place when I made the comment, and thought that `init` and `last` used the default `IterableOps` implementation. But indeed, the private implementations do override those methods.

**Comment by texasbruce** [comment] 2020-10-26 15:59
@mkeskells Do you also have PR to address other cases like ListSet?

**Comment by mkeskells** [comment] 2020-10-27 08:20
> @mkeskells Do you also have PR to address other cases like ListSet?

I haven't addressed ListSet, and that should be ls constrained ( e.g. `head` doesn't change type, so should be more amenable to optimisation). I was looking a ListMap due to the efficientMapBuilder (for HashMaps) and the interaction that hash-collisions have with that.

I suspect that ListSet has the same issues, but I have not looked. Jump in and make a few PRs :-) . Feel free to DM me if it helps (or not if it doesn't)

**Comment by NthPortal** [comment] 2020-10-28 07:29
@texasbruce I do think it would be valuable to have immutable `LinkedHash{Map,Set}` with poor insertion performance but good traversal and lookup performance, for cases where you're not going to mutate it much or at all after building it (similar to how nearly all operations on `ArraySeq` have poor performance, but it has great iteration and indexed lookup). potentially it could also have an efficient builder. possible candidate for `scala-library-next`?

**Comment by texasbruce** [comment] 2020-10-28 10:59
> @texasbruce I do think it would be valuable to have immutable `LinkedHash{Map,Set}` with poor insertion performance but good traversal and lookup performance, for cases where you're not going to mutate it much or at all after building it (similar to how nearly all operations on `ArraySeq` have poor performance, but it has great iteration and indexed lookup). potentially it could also have an efficient builder. possible candidate for `scala-library-next`?

Don’t think I’m concerned about LinkedHashColl at this point

**Comment by som-snytt** [comment] 2024-11-27 19:16
There hasn't been a justification of why a list-based collection intended for small sizes should receive extra LOC to optimize the large-collection use case.

The linked PR copies to an array for iteration. It received 6 months of attention in 2020, with Ichoran's final verdict that it might be OK to get in, "though I won't vouch for it on the basis of my quick glance-over". The benchmarks might be fine, but the power/weight is poor both in LOC and process. The other offers to PR did not materialize.

I hope @scala/collections agree to close the issue, without prejudice if you like.

**Closed** 2024-12-10 00:58 UTC
Labels: help wanted, library:collections

**Comment by mkeskells** [comment] 2024-12-10 08:27
The original reason for this was because this was used for the collision on hashmaps and sets. I don't think this is the case any more, but don't use scala any more so may be out of date
