### ISSUE TITLE
Cannot define companion object for deeply nested case class in 2.11.12

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/bug#10839] opened 2018-04-20 18:54 UTC
```
... PrivatePrimaryConstructor is already defined as (compiler-generated) case class companion object PrivatePrimaryConstructor
[error]       object PrivatePrimaryConstructor {
[error]              ^
[error] one error found
```

Code to reproduce:
```
import org.scalatest.{Matchers, WordSpec}


class PrivatePrimaryConstructorSpec extends WordSpec with Matchers {
  "PrivatePrimaryConstructor" should {
    "be available from the companion object" in {
      case class PrivatePrimaryConstructor private(i: Int) {
        def this(s: String) = this(s.toInt)
      }

      object PrivatePrimaryConstructor {
        def apply(s: String) = new PrivatePrimaryConstructor(s)
      }
    }
  }
}
```

**Comment by hrhino** [comment] 2018-04-20 18:58
Workaround: declare the companion object first:

```scala
import org.scalatest.{Matchers, WordSpec}


class PrivatePrimaryConstructorSpec extends WordSpec with Matchers {
  "PrivatePrimaryConstructor" should {
    "be available from the companion object" in {

      object PrivatePrimaryConstructor {
        def apply(s: String) = new PrivatePrimaryConstructor(s)
      }
      case class PrivatePrimaryConstructor private(i: Int) {
        def this(s: String) = this(s.toInt)
      }
    }
  }
}```

**Comment by hrhino** [comment] 2018-04-20 19:03
Oh, this is a duplicate of #3772; I knew it seemed familiar.

**Closed** 2018-04-20 19:05 UTC
Labels: duplicate
