### ISSUE TITLE
java.util.Set asScala map function bug

### ISSUE THREAD

**Issue by louisjiang** [scala/bug#11677] opened 2019-08-13 10:07 UTC
```scala
import scala.jdk.CollectionConverters._

class A(val a: String)

class B(val a: A)

case class C(a: A)

val jSet: java.util.HashSet[A] = new java.util.HashSet[A]()

jSet.add(new A("a"))
jSet.add(new A("b"))

val sSet = jSet.asScala

//expected
sSet

//bug
sSet.map(new B(_))

//expected
sSet.map(C(_))

val value = jSet.asScala.map { a =>
  new B(a)
}.toSet

value
jSet.size() // 2 
value.size //4
```

**Comment by louisjiang** [comment] 2019-08-13 10:09
https://scastie.scala-lang.org/louisjiang/TPD5gXBmSWCotESUGs2PNw/5

**Comment by Jasper-M** [comment] 2019-08-13 11:50
```
scala> class A(i: Int)
defined class A

scala> collection.mutable.HashSet.from(collection.View(1, 2).map(new A(_)))
res58: scala.collection.mutable.HashSet[A] = HashSet(A@6cef556, A@547ad1ae, A@5c5c5569, A@686492e3)
```

**Comment by lrytz** [comment] 2019-08-13 11:53
Duplicate of https://github.com/scala/bug/issues/11601

**Closed by lrytz** 2019-08-13 11:53 UTC
Labels: java interop, library:collections
