### ISSUE TITLE
Scala class cannot access protected static method from Java class it extends

### ISSUE THREAD

**Issue by stefanobaghino** [scala/bug#10697] opened 2018-01-20 08:24 UTC
It may be that [the fix](https://github.com/scala/scala/pull/6058) for #6934 has caused a regression, as pointed out in this [post on StackOverflow](https://stackoverflow.com/questions/48353393/scala-2-12-4-cannot-access-protected-static-java-method-from-another-package-an).

If you have Java class with a `protected static` method

```java
package parent;

public class Parent {

    protected static void parentMethod() {
        System.out.println("In parent static method");
    }

}
```

and try to access it from Scala in a class that extends it

```scala
package child

import parent.Parent

class Child extends Parent {

  def childMethod = {
    println("In child method, calling parent static method")
    Parent.parentMethod()
  }

}
```

you'll be able to compile (and run) this code on Scala 2.12.3 but not on Scala 2.12.4.

**Comment by Jasper-M** [comment] 2018-01-20 09:15
This looks like a duplicate of https://github.com/scala/bug/issues/10597 which is itself a duplicate of https://github.com/scala/bug/issues/10568

**Closed** 2018-01-20 09:23 UTC
Labels: duplicate

**Comment by stefanobaghino** [comment] 2018-01-20 09:32
Thanks, and sorry for the duplicate.
