### ISSUE TITLE
List and LazyList are like oil and water

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11914] opened 2020-03-19 19:32 UTC
## reproduction steps

```scala
scala> val b = true
val b: Boolean = true

scala> val res = if (b) List.empty else null.asInstanceOf[LazyList[Int]]
[hang]
```

## problem

```scala
"pool-6-thread-2" #51 prio=5 os_prio=31 cpu=85630.45ms elapsed=89.42s tid=0x00007ffadcdaf000 nid=0xaa07 runnable  [0x000070000ed01000]
   java.lang.Thread.State: RUNNABLE
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2346)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:756)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2355)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:777)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:756)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2355)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:777)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:756)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1855)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$MethodType.mapOver(Types.scala:2891)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$PolyType.mapOver(Types.scala:2993)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:122)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:116)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:120)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:134)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:127)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1856)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$MethodType.mapOver(Types.scala:2891)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:122)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:116)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:120)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:134)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:127)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1856)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$TypeBounds.mapOver(Types.scala:1569)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:122)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:116)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:120)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:134)
	at scala.reflect.internal.Types$PolyType.mapOver(Types.scala:2991)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:122)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:116)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:120)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:134)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:127)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1856)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$MethodType.mapOver(Types.scala:2891)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:122)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:116)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:120)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:134)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:127)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1856)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:756)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2355)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:777)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:756)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2355)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:777)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:756)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1855)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$MethodType.mapOver(Types.scala:2891)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:122)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:116)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.firstChangedSymbol(TypeMaps.scala:120)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:134)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:127)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1856)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:783)
	at scala.reflect.internal.Types$Type.substSym(Types.scala:751)
	at scala.reflect.internal.Types$MethodType.cloneInfo(Types.scala:2876)
	at scala.reflect.internal.Types$PolyType.cloneInfo(Types.scala:2978)
	at scala.reflect.internal.Types$PolyType.cloneInfo(Types.scala:2942)
	at scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2025)
	at scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2020)
	at scala.reflect.internal.Types.$anonfun$copyRefinedType$1(Types.scala:4004)
	at scala.reflect.internal.Types.copyRefinedType(Types.scala:4003)
	at scala.reflect.internal.Types.copyRefinedType$(Types.scala:3995)
	at scala.reflect.internal.SymbolTable.copyRefinedType(SymbolTable.scala:28)
	at scala.reflect.internal.Types$RefinedType.mapOver(Types.scala:1857)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:722)
	at scala.reflect.internal.Types$Type.subst(Types.scala:741)
	at scala.reflect.internal.Types$Type.instantiateTypeParams(Types.scala:487)
	at scala.reflect.internal.Types.appliedType(Types.scala:4119)
	at scala.reflect.internal.Types.appliedType$(Types.scala:4102)
	at scala.reflect.internal.SymbolTable.appliedType(SymbolTable.scala:28)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.correspondingTypeArgument(TypeMaps.scala:527)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.loop$3(TypeMaps.scala:560)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.classParameterAsSeen(TypeMaps.scala:565)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:438)
	at scala.reflect.internal.Types$AnnotatedType.mapOver(Types.scala:3843)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:439)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:409)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.correspondingTypeArgument(TypeMaps.scala:527)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.loop$3(TypeMaps.scala:560)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.classParameterAsSeen(TypeMaps.scala:565)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:438)
	at scala.reflect.internal.Types$MethodType.mapOver(Types.scala:2891)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:439)
	at scala.reflect.internal.Types$MethodType.mapOver(Types.scala:2891)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:439)
	at scala.reflect.internal.Types$PolyType.mapOver(Types.scala:2993)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:439)
	at scala.reflect.internal.Types$Type.asSeenFrom(Types.scala:699)
	at scala.reflect.internal.Types$Type.computeMemberType(Types.scala:734)
	at scala.reflect.internal.Symbols$MethodSymbol.typeAsMemberOf(Symbols.scala:3024)
	at scala.reflect.internal.Types$Type.memberType(Types.scala:725)
	at scala.reflect.internal.Types.specializesSym(Types.scala:4719)
	at scala.reflect.internal.Types.specializesSym$(Types.scala:4694)
	at scala.reflect.internal.SymbolTable.specializesSym(SymbolTable.scala:28)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$lub$17(GlbLubs.scala:339)
	at scala.reflect.internal.tpe.GlbLubs.refines$1(GlbLubs.scala:336)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$lub$10(GlbLubs.scala:306)
	at scala.reflect.internal.tpe.GlbLubs.excludeFromLub$1(GlbLubs.scala:306)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$lub$18(GlbLubs.scala:343)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$lub$18$adapted(GlbLubs.scala:343)
	at scala.reflect.internal.tpe.GlbLubs$$Lambda$5952/0x0000000801be8040.apply(Unknown Source)
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:455)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:874)
	at scala.reflect.internal.tpe.GlbLubs.lub1$1(GlbLubs.scala:343)
	at scala.reflect.internal.tpe.GlbLubs.lub0$1(GlbLubs.scala:283)
	at scala.reflect.internal.tpe.GlbLubs.lub0$1(GlbLubs.scala:272)
	at scala.reflect.internal.tpe.GlbLubs.lub(GlbLubs.scala:382)
	at scala.reflect.internal.tpe.GlbLubs.lub$(GlbLubs.scala:263)
	at scala.reflect.internal.SymbolTable.lub(SymbolTable.scala:28)
	at scala.reflect.internal.tpe.GlbLubs.lubsym$1(GlbLubs.scala:321)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$lub$19(GlbLubs.scala:344)
	at scala.reflect.internal.tpe.GlbLubs$$Lambda$5953/0x0000000801be8840.apply(Unknown Source)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:874)
	at scala.reflect.internal.tpe.GlbLubs.lub1$1(GlbLubs.scala:343)
	at scala.reflect.internal.tpe.GlbLubs.lub0$1(GlbLubs.scala:283)
	at scala.reflect.internal.tpe.GlbLubs.lub(GlbLubs.scala:382)
	at scala.reflect.internal.tpe.GlbLubs.lub$(GlbLubs.scala:263)
	at scala.reflect.internal.SymbolTable.lub(SymbolTable.scala:28)
	at scala.reflect.internal.tpe.GlbLubs.lub(GlbLubs.scala:242)
	at scala.reflect.internal.tpe.GlbLubs.lub$(GlbLubs.scala:235)
	at scala.reflect.internal.SymbolTable.lub(SymbolTable.scala:28)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIf$1(Typers.scala:4619)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5797)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5831)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5942)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1121)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1713)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1884)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1848)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:868)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2033)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2031)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2026)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1544)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1517)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1691)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5466)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2540)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5796)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5831)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:6122)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5774)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2050)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1880)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5775)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5475)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5778)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1510)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1494)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1615)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	- locked <0x000000079c543800> (a xsbt.CachedCompiler0)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.5/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.5/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.5/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.5/Method.java:566)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
	at sbt.internal.inc.MixedAnalyzingCompiler$$Lambda$3145/0x0000000801105040.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
	at sbt.internal.inc.IncrementalCompilerImpl$$Lambda$3084/0x00000008010d8040.apply(Unknown Source)
	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
	at sbt.internal.inc.Incremental$$$Lambda$3122/0x00000008010f8040.apply(Unknown Source)
	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
	at sbt.internal.inc.Incremental$$$Lambda$3119/0x00000008010f6040.apply(Unknown Source)
	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
	at sbt.internal.inc.IncrementalCompilerImpl$$Lambda$3021/0x0000000801079c40.apply(Unknown Source)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
	at sbt.Defaults$$$Lambda$1952/0x0000000800bbf040.apply(Unknown Source)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at scala.Function1$$Lambda$1727/0x0000000800b16840.apply(Unknown Source)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
	at sbt.internal.util.$tilde$greater$$Lambda$2551/0x0000000800d7c040.apply(Unknown Source)
	at sbt.std.Transform$$anon$4.work(System.scala:67)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
	at sbt.Execute$$Lambda$2568/0x0000000800d83c40.apply(Unknown Source)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:278)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
	at sbt.Execute$$Lambda$2559/0x0000000800d80c40.apply(Unknown Source)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2566/0x0000000800d83840.apply(Unknown Source)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.util.concurrent.FutureTask.run(java.base@11.0.5/FutureTask.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.5/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.5/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.5/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.5/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.5/Thread.java:834)


```

## expectation
More like:
```
scala> val res: LazyList[Int] = if (b) List.empty else null.asInstanceOf[LazyList[Int]]
                                            ^
       error: polymorphic expression cannot be instantiated to expected type;
        found   : [A]List[A]
        required: LazyList[Int]
```

**Comment by SethTisue** [comment] 2020-03-19 19:40
duplicate of #10908

**Closed by SethTisue** 2020-03-19 19:40 UTC
