### ISSUE TITLE
Scala 2.13 does not compile with Gradle on Windows

### ISSUE THREAD

**Issue by eyalroth** [scala/bug#11731] opened 2019-09-09 14:27 UTC
The [original bug](https://github.com/gradle/gradle/issues/9857) is reported in the Gradle repository, but I believe it should be brought into attention in this repository as well.

## steps

Use Gradle to compile Scala 2.13.0 project.

## problem

```
Compiling with Zinc Scala compiler.
'compiler-interface-2.13.0-55.0.jar' not yet compiled for Scala 2.13.0. Compiling...
C:\Users\petzold\AppData\Local\Temp\sbt_76a43d36\xsbt\Compat.scala:152: error: postfix operator headOption needs to be enabled
by making the implicit value scala.language.postfixOps visible.
This can be achieved by adding the import clause 'import scala.language.postfixOps'
or by setting the compiler option -language:postfixOps.
See the Scaladoc for value scala.language.postfixOps for a discussion
why the feature needs to be explicitly enabled.
} headOption
^
one error found
```

## expectation

compiles.

## notes

As I described in one of the comments on the original issue, I suspect that [this Scala change](https://github.com/scala/scala/pull/6559) is responsible for Gradle's inability to compile Scala 2.13, as this change makes Scala 2.13 incompatible with SBT 0.13.15, which is what Gradle uses for compilation.

Perhaps all it takes is to build and publish the [old Zinc project](https://github.com/typesafehub/zinc) with SBT 0.13.18. I was able to do it locally, but I can't really be sure I've done it properly as I'm quite unfamiliar with this project.

Furthermore, there might be other Scala 2.13 changes which are incompatible with SBT 0.13.18.

**Comment by SethTisue** [comment] 2019-09-09 16:40
attn @eed3si9n ?

**Comment by som-snytt** [comment] 2019-09-10 00:59
I don't know about "old Zinc", but the special sbt file that uses postfix is given a pass here:

https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/Reporting.scala#L118

If the problem is Windows-specific, it may be that the test uses forward slashes and Windows paths do not.

**Comment by eed3si9n** [comment] 2019-09-10 01:38
Commented on https://github.com/gradle/gradle/issues/9857#issuecomment-529730891

> sbt 0.13 and the old typesafehub/zinc have ended public support in 2018.
>
> There is [Zinc](https://github.com/sbt/zinc) library split out from sbt's code base and is used by sbt 1.x, Pants, Maven etc. There's also a nailgun wrapping of Zinc (similar to old Zinc), called [Bloop](https://scalacenter.github.io/bloop/docs/build-tools/gradle) that supports export from Gradle. I'd recommend finding a solution in either of the ways.

**Comment by eyalroth** [comment] 2019-09-10 02:02
@som-snytt Thanks! That seems to be the culprit. Is it possible to change the code to support windows paths as well?

@eed3si9n Bloop has only a ["first phase" integration](https://github.com/scalacenter/bloop/issues/152) with Gradle, which is by no means sufficient and is far from replacing a fully supported build tool. The Scala-Gradle community [have been long waiting for an integration with the new Zinc](https://github.com/gradle/gradle/issues/2158), which seems to planned for Gradle's 6.0 RC1 milestone.

Until then, though, there really doesn't seem to be a viable solution to this problem other than fixing the aforementioned problem with the "postfixOps" feature.

**Comment by SethTisue** [comment] 2019-09-10 03:34
marked as a blocker for 2.13.1 since it appears it may be an easy fix

**Comment by SethTisue** [comment] 2019-09-10 03:36
@som-snytt if you don't have the time/inclination to dig into this, let us know

**Comment by som-snytt** [comment] 2019-09-10 04:35
I'll try to time box it before I crash on the couch.

**Comment by eed3si9n** [comment] 2019-09-10 05:48
Assuming Som is boxed into couch rather than time by now, here's a PR to extend the postfixOp leniency - https://github.com/scala/scala/pull/8408

**Comment by som-snytt** [comment] 2019-09-10 05:55
Logically, you'd expect east coast eed3si9n to crash first. Not to start a rap battle between the coasts, but I think my fix is better. For one thing, it reminds me how bad the experimental `reflect.io` is. In collision or collusion with `java.io.File`, it's deeply flawed if not stamp-it-out evil. It is the Bay Area commuter traffic of file API.

**Comment by eyalroth** [comment] 2019-09-10 05:56
Guys thank you for the extremely fast responses and help!

@eed3si9n Can I help somehow by perhaps testing this on my Windows-Gradle environment?

**Comment by som-snytt** [comment] 2019-09-10 06:08
@eyalroth Do you know the instructions at the scala readme for using a version from jenkins?

https://github.com/scala/scala/pull/8409

I think this snippet is more adequate to the API. Also, who says path separator is always a slash? Let's go beyond our binary thinking etc. Also I seem to remember that slash is British slang, so I always say separator.

        && pos.source.file.name == "Compat.scala"
        && pos.source.file.file.getParentFile.getName == "xsbt"

I hope that's enough `file`s to solve the problem. I tried it out with a local sbt build, but not yet on Windows, which is not my favorite thing, but I do have a machine all warmed up.

**Comment by som-snytt** [comment] 2019-09-10 06:19
@SethTisue I was disinclined but did it anyway, and now that eed3si9n has chimed in with his characteristic alacrity, I feel like I have to follow through. BTW, MTT is doing Mahler's 6th, my favorite since I was a teen, I didn't know it was a landmark recording for them. Right now everything sounds like Mahler's 6th.

**Comment by eyalroth** [comment] 2019-09-10 06:34
@som-snytt I'm not quite sure. Am I simply supposed to use the published jar from your PR? https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/org/scala-lang/scala-library/2.13.1-bin-8d9f5f2-SNAPSHOT/

**Comment by som-snytt** [comment] 2019-09-10 07:01
Me neither. The Scala CI section says for example:

$ sbt
> set resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
> set scalaVersion := "2.12.2-bin-abcd123-SNAPSHOT"
> console

So yes, add the resolver and set the version.

**Comment by eyalroth** [comment] 2019-09-10 08:01
@som-snytt Ugh, it was a bit more tricky with Gradle. I had to manually download and move the jars into my maven local repository for each of the three core packages (lang, compiler, reflect).

Good news though, it seems to be compiling now :)

**Closed** 2019-09-10 12:51 UTC
Labels: blocker
