### ISSUE TITLE
Scaladoc exists on scala-lang.org for nonexistent Scala version "rc2" (and Google finds it)

### ISSUE THREAD

**Issue by iamprakashom** [scala/bug#10265] opened 2017-04-14 12:27 UTC
[Link](http://www.scala-lang.org/api/rc2/scala/math/package$.html), which I guess should show pacage definition for `log10` & `log1p` is broken.

Screen-shot is attached below.
![screenshot from 2017-04-14 17 54 53](https://cloud.githubusercontent.com/assets/4259587/25043164/8a75d7ec-213b-11e7-887f-09e37a63457a.png)

**Comment by adriaanm** [comment] 2017-04-14 15:33
That *rc2* in the url is unexpected! Where did you find this link?

For a modern version of scala:
  - http://www.scala-lang.org/api/2.12.x/scala/math/index.html
  - http://www.scala-lang.org/api/2.11.x/scala/math/index.html

**Comment by iamprakashom** [comment] 2017-04-14 16:04
Kindly open http://www.scala-lang.org/api/rc2/scala/math/package.html and click on `log10` and `log1p`. After expending down, click on `package` next to `Definition Classes`. It will lead you to error page.

![screenshot from 2017-04-14 21 33 36](https://cloud.githubusercontent.com/assets/4259587/25048414/10131cfc-215a-11e7-9ddd-2479830a4cb0.png)

- http://www.scala-lang.org/api/2.11.x/#scala.math.package not working. It is showing same error.

**Comment by SethTisue** [comment] 2017-04-14 16:12
> Kindly open http://www.scala-lang.org/api/rc2/scala/math/package.html

That URL is malformed — there is no Scala version "rc2". Adriaan is asking how you ended up at this URL in the first place.

> http://www.scala-lang.org/api/2.11.x/#scala.math.package not working. It is showing same error.

I'm not able to reproduce this — there is no "package" link to click and nothing to expand. It just looks like this:

<img width="647" alt="screen shot 2017-04-14 at 11 11 56 am" src="https://cloud.githubusercontent.com/assets/161079/25048681/3e08cd5c-2103-11e7-8fd6-44a50fc51d88.png">

**Comment by iamprakashom** [comment] 2017-04-14 16:59
I got that malformed link while gooling for a way to calculate logarithm in scala.

**Comment by SethTisue** [comment] 2017-04-14 17:08
> I got that malformed link while googling for a way to calculate logarithm in scala.

ah, I see it's the second-highest result when I google "scala logarithm" 😱

**Comment by adriaanm** [comment] 2017-04-14 17:24
Should we just delete that directory and let google update its index?

**Comment by SethTisue** [comment] 2017-04-14 17:31
yeah. I mean, it would be nice if we had some idea what the root cause is or was. but yeah, I think we could do that and then just close this and hope it doesn't recur.

**Comment by adriaanm** [comment] 2017-04-14 17:35
Back in the day these things were manual operations. There were rc and rc2 directories, which belonged to 2.10.0-RC5 and 2.9.3-RC1 based on their index.html. I renamed the directories. Now I'm on the fence to have rc and rc2 live on as aliases for 2.10.x

**Comment by adriaanm** [comment] 2017-04-14 17:37
Ideally, the webserver would serve a redirect for this URL. Since this is the top hit, I figure for now the best option is to use an alias. /cc @fsalvi

**Comment by SethTisue** [comment] 2017-04-14 17:43
> Since this is the top hit,

only for "logarithm", in some random experimenting I didn't find any other search term for which that was true, not that I spent super long on it.

regardless, an alias is easy to add.

**Comment by adriaanm** [comment] 2017-04-14 17:44
Our own search doesn't seem to cover all members: http://www.scala-lang.org/api/current/scala/math/index.html?search=log did not turn up the scala.math member

**Comment by adriaanm** [comment] 2017-04-14 17:44
I already made the alias, since the old names were wrong anyway.

**Comment by fsalvi** [comment] 2017-04-24 08:05
Back from holidays... Is there still an alias to add ?

**Comment by lrytz** [comment] 2017-04-24 08:19
I just checked if there's still something to do and saw the `rc2 -> 2.10.x` symlink in `/home/linuxsoft/archives/scala/api`, so I removed it. I guess http://www.scala-lang.org/api/rc2/ will disappear after some synchronization?

**Comment by fsalvi** [comment] 2017-04-24 12:59
It's ok. But, there's still http://www.scala-lang.org/api/rc/ 
Do you want to keep it ?

**Comment by lrytz** [comment] 2017-04-24 13:16
No, it would be good if you could delete that too.

**Comment by fsalvi** [comment] 2017-04-24 13:24
It's ok now.

**Closed by fsalvi** 2017-04-24 13:24 UTC
Labels: docs, quickfix

**Comment by SethTisue** [comment] 2017-04-25 21:32
thank you, Fabien!
