### ISSUE TITLE
compilation error for ^= operator

### ISSUE THREAD

**Issue by scabug** [scala/bug#10077] opened 2016-11-25 19:29 UTC
```scala
object Main {
    val arr1 = new Array[Byte](10)
    val arr2 = new Array[Byte](10)

    arr1(4) ^= arr2(5)
}
```

Expected: successful compilation
Actual: 
```
[error] /tmp/1/Main.scala:5: type mismatch;
[error]  found   : Int
[error]  required: Byte
[error]     arr1(4) ^= arr2(5)
[error]             ^
[error] one error found
```

**Comment by som-snytt** [comment] 2023-11-08 00:11
Closing as duplicate of the linked ticket by which the error message was improved.

**Closed by som-snytt** 2023-11-08 00:11 UTC
