### ISSUE TITLE
Type inference not working with java overloads

### ISSUE THREAD

**Issue by eatkins** [scala/bug#12139] opened 2020-09-04 15:15 UTC
Forgive me if this is a duplicate, but there are cases where the scala compiler will infer `Nothing` where it is unexpected. This came up in https://github.com/playframework/playframework/pull/10442. I was able to reproduce with 2.10.7, 2.11.11, 2.12.12 and 2.13.3.

## reproduction steps

create a java file Foo.java:
```java
public class Foo {
  void foo(Foo foo) {}
  void foo(java.util.Optional<Foo> foo) {}
}
```
create a scala file Bar.scala:
```scala
object Bar {
  Foo.foo(java.util.Optional.empty())
}
```
compile the project

## problem

```
sbt:overload> compile
[info] Compiling 1 Scala source and 1 Java source to /Users/ethanatkins/work/scratch/overload/target/scala-2.12/classes ...
[error] /Users/ethanatkins/work/scratch/overload/src/main/scala/Bar.scala:2:7: overloaded method value foo with alternatives:
[error]   (foo: java.util.Optional[Foo])Unit <and>
[error]   (foo: Foo)Unit
[error]  cannot be applied to (java.util.Optional[Nothing])
[error]   Foo.foo(java.util.Optional.empty());
[error]       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Sep 4, 2020 8:10:45 AM
```

If I remove the overloaded `foo` method that takes a `Foo`, it does compile.

**Comment by som-snytt** [comment] 2020-09-05 10:19
This is a known limitation and there are similar tickets which ticket fatigue prevents me from discovering.

Worth noting that if the overloads share the parameter of interest, inference is improved:
```
        public void foo(java.util.Optional<Foo> foo, Foo actual) {}
        public void foo(java.util.Optional<Foo> foo) {}
```
then
```
Bar.this.x.foo(java.util.Optional.empty[t12139.Foo]())   // not Nothing
```
The spec stipulates that arguments are typechecked without an expected type, but does not preclude adaptations after an overload is selected.

**Comment by eatkins** [comment] 2020-09-05 17:50
I'm not surprised to hear this is a known limitation. Feel free to close this if it's covered elsewhere.

**Comment by SethTisue** [comment] 2020-10-12 15:40
Duplicate of #10542? (I'm genuinely asking; superficially, they look similar.)

**Comment by SethTisue** [comment] 2020-10-12 15:42
We can reopen if someone can substantiate that this one is actually different.

**Closed by SethTisue** 2020-10-12 15:42 UTC
Labels: infer, java interop, overloading

**Comment by som-snytt** [comment] 2020-10-13 00:49
Seth is immune to ticket fatigue. Scala Center ought to present the Seth Tissue Award in Issuology in recognition of exceptional cross-ticketing.
