### ISSUE TITLE
Product fields a reordered

### ISSUE THREAD

**Issue by plaflamme** [scala/bug#11704] opened 2019-08-21 20:37 UTC
scalac will reorder the fields of a case class in a very specific case:

```scala
scala> case class Bad(a: String, b: String, `a-b`: Int)
defined class Bad

scala> val bad = Bad("a", "b", 42)
bad: Bad = Bad(a,42,b)

scala> bad.productElement(1)
res6: Any = 42

scala> bad match { case Bad(a, b, c) => b }
<console>:15: error: error during expansion of this match (this is a scalac bug).
The underlying error was: type mismatch;
 found   : Int
 required: String
       bad match { case Bad(a, b, c) => b }
```

This seems to be related to the fact that the class has a field name that is the prefix of a field with backticks. For example, this declaration doesn't reproduce the issue:

```scala
scala> case class NotBad(a: String, b: String, `b-a`: Int)
defined class NotBad

scala> val notBad = NotBad("a", "b", 42)
notBad: NotBad = NotBad(a,b,42)
```

This was reproduced on both 2.12.8 and 2.12.9 using the following JVM:
```$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

**Comment by SethTisue** [comment] 2019-08-21 20:51
duplicate of #8831?

**Comment by hrhino** [comment] 2019-08-21 21:10
Looks similar but that's a late-middle-end bug (in constructors IIRC). It seems likely that it's the same cause though.

**Closed** 2019-08-21 21:17 UTC

**Comment by plaflamme** [comment] 2019-08-21 21:19
Indeed, this the same as reported here https://github.com/scala/bug/issues/8831#issuecomment-292433587

Sorry for the noise!
