### ISSUE TITLE
TreeSet uses wrong implicit ordering for 'min'

### ISSUE THREAD

**Issue by raboof** [scala/bug#11507] opened 2019-04-29 15:59 UTC
TreeSet has an implicit `implicit val ordering: Ordering[A]`, but `min` from `SortedSetOps` also allows explicitly specifying an ordering (`override def min[B >: A](implicit ord: Ordering[B]): A`).

It seems that when `min` in `SortedSetOps` calls `super.min`, it passes the `implicit val ordering: Ordering[A]` field of `TreeSet` along instead of the `implicit ord: Ordering[B]` implicit parameter.

For example, this should show the smallest member by length (Bob), but shows the smalles member by alphabet (Alice):

```
  import scala.collection.immutable.SortedSet

  case class Member(name: String)

  val defaultOrdering: Ordering[Member] = Ordering.by(_.name)
  val nameLengthOrdering: Ordering[Member] = Ordering.by(_.name.length)

  val set = SortedSet(Member("Alice"), Member("Bob"))(defaultOrdering)
  println(set.min(nameLengthOrdering))
```

**Comment by NthPortal** [comment] 2019-04-29 17:08
This is probably a duplicate of #10942. Note that you can still use the set's ordering by doing `set.min(set.ordering)` even if it is not in implicit scope.

**Comment by NthPortal** [comment] 2019-04-29 17:14
I'm not certain, but I think this may be a case of explicitly specifying the `Ordering` (and the wrong one) when it could instead be passed implicitly.

**Comment by szeiger** [comment] 2019-04-29 17:15
This is a different issue. And it's a rather annoying problem because the definition of `min` looks entirely reasonable:

```scala
  override def min[B >: A](implicit ord: Ordering[B]): A =
    if (isEmpty) throw new UnsupportedOperationException("empty.min")
    else if (ord == ordering) head
    else if (ord isReverseOf ordering) last
    else super.min
```

Type checking of `super.min` is equally reasonable: The expected return type is `A` so the type parameter `B >: A` is inferred as `A` (not as our own `B`), making the call `super.min[A]`.

**Comment by szeiger** [comment] 2019-04-29 17:18
The obvious fix is to call `super.min[B]` explicitly but who knows how many other methods have the same problem? A more radical change would be to make `ordering` not `implicit` but this will require a lot of downstream changes.

**Comment by NthPortal** [comment] 2019-04-29 17:19
@szeiger why is it implicit in the first place? and if it is actually used as an implicit, it would seem that making it not implicit would be quite problematic

**Comment by szeiger** [comment] 2019-04-29 17:21
It's convenient for collection implementors. I can't think of any other reason why it should be implicit.

**Comment by NthPortal** [comment] 2019-04-29 17:26
After looking at `i.TreeSet` with IntelliJ's implicit view turned on, I can say that virtually every method uses the implicit at least once; removing it would be quite a pain for implementors I think.

**Comment by Ichoran** [comment] 2019-04-29 17:28
Why isn't the obvious fix to call `super.min(ordering)`?

**Comment by Ichoran** [comment] 2019-04-29 17:30
(Haha, one reason: I forgot which was `ordering` and which was `ord` and picked the wrong one.)

But, anyway, the point of being able to explicitly name implicit arguments is to use them explicitly where needed.

**Comment by szeiger** [comment] 2019-04-29 17:38
Sure, that's another obvious fix. Both work fine. The problem is that you have to known when to apply them. If you don't, then the code compiles and runs just fine, producing wrong results in some cases. I'd rather make it pick the right implicit by default or prevent it from compiling.

**Comment by Ichoran** [comment] 2019-04-29 17:43
Everything seems fragile to me.  If you shadow the name `ordering`, only the new one is even eligible to be used, isn't it?

But any fix is subject to breakage.  Explicit arguments I think are the hardest to drift, and none of them really help other implementors because there's no reason they can't do what we just did.

**Comment by Ichoran** [comment] 2019-04-29 17:52
Actually, I think there are deeper problems with this method.  The intuitive hierarchy seems to me to be

1. If a specific ordering is supplied to `min`, use that
2. else, if a specific ordering is supplied to `TreeSet`, use that
3. else, use whatever is/was implicitly filled in (still unclear what to do if context changes between construction and where `min` is called)

The current fixes being described don't seem to follow 1-2-3 even _granting_ that 3 may be ambiguous.  So I'm not sure that we shouldn't think harder about this.

**Comment by szeiger** [comment] 2019-04-29 17:57
@Ichoran That's basically https://github.com/scala/bug/issues/10942. A TreeSet always has an ordering, so there is no case 3. But I wouldn't want to mess with implicit resolution or defaults to achieve this. Taking a step back, maybe the question needs to be: Should a SortedSet be a Set at all? What do we really gain from the relationship?

**Comment by szeiger** [comment] 2019-04-29 17:59
@NthPortal `TreeSet` overrides `ordering` to be implicit. Only changing the original definition in `SortedOps` so that you are no longer forced to use it (but can still do so if you want to, just like `TreeSet` does) doesn't require a lot of changes after all: https://github.com/szeiger/scala/commit/2a8cb15a99e4f928c6fe4f35a331e9c674c62d6b

**Comment by smarter** [comment] 2019-04-29 18:11
> Should a SortedSet be a Set at all? What do we really gain from the relationship?

I don't know, but I know that SortedSet being a Set makes it impossible for Set to be covariant :) (https://github.com/scala/scala/pull/6728)

**Comment by Ichoran** [comment] 2019-04-29 18:24
@szeiger - Ah, I hadn't seen that one.  Well, hm.  This is rather unfortunate.  I can't think of any way to solve the issue that doesn't require language and compiler changes, or an unreasonably large reworking of the library, or rather ugly hacks.  (E.g. overloading with a `min` method with an explicit argument and a dummy implicit argument, and another `min` method with another dummy implicit argument.)

**Comment by Ichoran** [comment] 2019-04-29 18:27
(The hacks wouldn't be satisfying anyway because they would only work when the Sorted type is known.)

**Comment by NthPortal** [comment] 2019-04-30 00:55
> SortedSet being a Set makes it impossible for Set to be covariant

That *is* true, but there are also other reasons. Because `Set[A] <: (A => Boolean)`, `A` must be contravariant or invariant

**Comment by NthPortal** [comment] 2019-04-30 00:58
@szeiger if that's the case, I think I'm okay with it as a fix. although I'm a little bit concerned that a similar problem could exist in `TreeSet` just as easily

**Comment by lrytz** [comment] 2019-05-03 09:55
Fixed by https://github.com/scala/scala/pull/8013

**Closed by lrytz** 2019-05-03 09:55 UTC
Labels: library:collections, regression
