### ISSUE TITLE
Await.result keeps waiting for already completed awaitable

### ISSUE THREAD

**Issue by smanikim** [scala/bug#11903] opened 2020-03-06 13:37 UTC
## reproduction steps
Seems like not ideal scenario, But I am not able to repro at wish. Some race condition in some scenario seem to govern this.

## problem
I do believe that for very small duration awaitable, Await.result(awaitable, Duration.someDuration) keep running forever and time out after mentioned duration. I am not able to reproduce it in UT somehow to add it but I have observed it in production code at times.  I am using scala 2.12.10 and running with java 8. 

## expectation
For already completed task, Await should return immediately instead of timeout.

**Comment by som-snytt** [comment] 2020-03-08 02:44
I'm not sure there is enough information to be actionable.

There is [a check for completion](https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/impl/Promise.scala#L235); in 2.13, the short-circuit [is earlier](https://github.com/scala/scala/pull/7768).

In the event of a race between a completing thread and an awaiter, the awaiter sees either a result or the listeners it will join. You don't give any details: are there many awaiters? What is the execution context?

**Comment by smanikim** [comment] 2020-03-08 13:45
Yeah, I saw the [check for completion](https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/impl/Promise.scala#L235) .
ExecutionContext has threads equal to (number of cores  + 1)     and queue (number of cores * 100).

There is single awaiter for one [Future.sequence] (https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/Future.scala#L669). There are many such awaiters depending on number of futures.

I will try the early fix meanwhile in application side.

**Comment by viktorklang** [comment] 2020-03-09 10:19
@smanikim What EC are you using?

**Comment by ritschwumm** [comment] 2020-03-09 22:20
this sounds a lot like an issue i recently saw in one of our tests (scala 2.12.10).
i'm a bit hazy on the details, but iirc the future we were awaiting was in fact a Future.successful and the EC was the global one.
there was a twist, though: if the call t Await.result was inside an extension method on Future taking the EC as an implicit parameter, the code hung until the timeout of 5 seconds. strangely, inlining that method solved the issue.

**Comment by viktorklang** [comment] 2020-03-09 22:48
@ritschwumm Sounds like an initializer issue. If the initializer lock of one calls submits something else to execute on another thread, which accesses something which is being initialized in the first thread, and especially if the first awaits the completion of the other, you've got a deadly embrace situation happening.

**Comment by smanikim** [comment] 2020-03-11 08:23
@viktorklang I use custom EC which is created using scala.concurrent.ExecutionContext#fromExecutor for creating future. We use one more custom EC for Future.sequence. This seq is actually passed to Await.result.

**Comment by viktorklang** [comment] 2020-03-11 19:51
If you supply your own Executor then you also need to implement
BlockContext support yourself—so I expect that to cause your issue, unless
you can reproduce using EC.global

**Comment by ritschwumm** [comment] 2020-03-11 23:32
thanks @viktorklang - as this was inside a test class which inherts a lot of "interesting" stuff that might very well be the case. probably more likely than it having to do anything with this issue.

**Comment by som-snytt** [comment] 2020-03-12 01:50
Do we need a diagnostic "thread dump on timeout"?

**Comment by smanikim** [comment] 2020-03-12 05:35
@viktorklang in my case, my custom thread pool is running lot below capacity. If I understand correctly, blockContext will help me with more threads  (depending on maxExtraThreads) if I have more tasks concurrently than pool capacity. But In my case, I am not even using 10% of my pool capacity and plus there is no queue on my threadpool. Lemme check further to see more differences.

@som-snytt I can try for threadDump on timeout if helps

**Comment by SethTisue** [comment] 2020-03-12 09:23
I’m closing since it’s far from clear there is any Scala bug involved here. feel free to continue discussing; we can reopen if a Scala issue can be identified

**Closed by SethTisue** 2020-03-12 09:23 UTC

**Comment by smanikim** [comment] 2020-03-12 10:55
@SethTisue I am not sure how to prove it as I am not able to produce it in UT. But in other case, I would need help to prove otherwise.

**Comment by smanikim** [comment] 2020-03-13 15:33
FWIW, moving to java CompletableFuture helped fixing the issue

**Comment by viktorklang** [comment] 2020-03-13 15:53
@smanikim Could you share a gist of the Scala reproducer and a contrast to what your CompletableFuture solution looks like?

**Comment by smanikim** [comment] 2020-03-16 07:21
@viktorklang Below is my summary

Scala one:-  I iterate over a collection and get some future. These futures use 2 different type of execution context. Later, I use Future.sequence on these using some other EC and Await.result on these.

Java one:-  I iterate over a collection and get some CompletableFuture. These futures use 2 different type of execution context. Later, I use  CompletableFuture.allOf  to get one CompletableFuture on which I get to wait until my timeout. I then, join individual futures to get results from future.

  def scalaFutures() = {
    val names = Set.empty[String]
    val allFutures = names.map{ name =>
      val execContext = ctx(name)
      Future {
          someFn(....)
        }(execContext)
      }
    import futureSequencingContext //implicit one for future
    Await.result(Future.sequence(allFutures), Duration(Timeout.get(), duration.MILLISECONDS))
    }
  
  def javaFuture = {
    val names = Set.empty[String]
    val allFutures = names.map { name =>
      val execContext = ctx(name)

      CompletableFuture.supplyAsync(() => {
        someFn(.....)
      }, execContext)
    }

    val futures = CompletableFuture.allOf(allFutures.toSeq: _*)
    futures.get(Timeout.get(), duration.MILLISECONDS)
    allFutures.flatMap(future => future.join()).toSeq

  }

  private def ctx(x: String): ExecutionContextExecutor = {
    if (x.blah) XExecutionContextExecutor else YExecutionContextExecutor
  }

I tried https://github.com/scala/scala/pull/8795 but doesn't look connected.  I spent some time reading code scala futures but did not find anything which will cause this. I will spend more time to come up with theory/evidence.

**Comment by viktorklang** [comment] 2020-03-16 11:32
@smanikim Can you make the examples runnable? (so we can try them out locally)

**Comment by smanikim** [comment] 2020-03-16 14:01
Runnable has simple logic. runnable calls intersection on some set and just return it. somelike

def fn(in: Set[Int]) = {
store.intersect(in)
}

where store could be in memory or database depending on recency of data.

**Comment by smanikim** [comment] 2020-03-16 14:04
something funny is if we enable debug in fn, error goes away. debug does't do anything but just print count of intersected items

**Comment by smanikim** [comment] 2020-04-07 10:24
to add, we did not have this issue with 2.11

**Comment by viktorklang** [comment] 2020-04-07 11:03
@smanikim You might have an issue with reentrancy and class loading—what does your thread dumps say?

**Comment by smanikim** [comment] 2020-04-10 06:41
Nothing in stack trace except 
user error java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)

**Comment by viktorklang** [comment] 2020-04-10 14:31
@smanikim Can you paste in your endite thread dump so we can see what all threads are waiting for etc?

**Comment by smanikim** [comment] 2020-05-28 07:09
@viktorklang this response seems to got buried in emails. I won't be having this output now :(

**Comment by jaingaurav1990** [comment] 2021-05-13 05:15
@viktorklang I am seeing this issue getting reproduced again (me and @smanikim work on the same tech stack). Again, I am not able to reproduce the issue at will, but we do see some timeouts every now and then with Futures that finish almost instantaneously. 

The pattern of the Scala futures wait code is the same as what @smanikim pointed out above.

```
val asyncFlushers = queryPipelines.toList.zipWithIndex.map {
          case (opPipeline, idx) =>
            Future {
              // Await.result times out sometimes if processPipeline finishes almost instantaneously.
              processPipeline(opPipeline) 
            }
        }
Await.result(Future.sequence(asyncFlushers), Duration(flushTimeout, TimeUnit.MILLISECONDS))
```

An additional interesting thing that we now know is that if we wait on Scala futures naively in a loop (instead of using `Future.sequence` to convert multiple futures into one), the `Await.result` call doesn't time out. This is the code that doesn't time out:
```
def waitOnFuturesSerially[T](futures: Seq[Future[T]], timeout: Long): Unit = {
    import scala.language.postfixOps
    import scala.concurrent.duration._

    val timeoutAfter = now + timeout
    futures.foreach(Await.result(_, (timeoutAfter - now) millis))
  }

val asyncFlushers = queryPipelines.toList.zipWithIndex.map {
          case (opPipeline, idx) =>
            Future {
              processPipeline(opPipeline) 
            }
        }

waitOnFuturesSerially(asyncFlushers, flushTimeout))
```
The fact that the above serial wait does not time out makes me think that something is wrong with the combination of `Await.result` with `Future.sequence`. 

Also, for which threads do you want to see the thread-dump. I am guessing the thread that's supposed to complete the future and the one that's blocked on `Await.result`. Those two should be enough. Right? @viktorklang

**Comment by viktorklang** [comment] 2021-05-13 08:39
@jaingaurav1990 I think some form of reproducer would be ideal, as this seems to only have been noticed by you and @smanikim. Could you also list what configuration this problem manifests under? (OS, HW, JVM)
