### ISSUE TITLE
Behavior of .fold changed with Scala 2.13

### ISSUE THREAD

**Issue by DaniRey** [scala/bug#11550] opened 2019-05-31 15:58 UTC
The behavior of .fold changed (at least for ArrayOps) with Scala 2.13. If there is only one element in the Array, this element is returned, without executing the fold operation, together with the neutral element. 

This breaks code which expects the neutral element to be applied at least once. Although it is correct according to the documentation, it is unexpected to many developers.

> z a neutral element for the fold operation; may be added to the result an arbitrary number of times, and must not change the result (e.g., Nil for list concatenation, 0 for addition, or 1 for multiplication).

Example
```
object Fold extends App {
  val a = "rocks".split(" ").fold("")(_ + "scala " + _ )
  println(a)
}
```
Prints `scala rocks` with 2.12, but prints only `rocks` with 2.13. See https://scastie.scala-lang.org/QFBe1PcoTDu08EbvJMR88A

**Comment by Ichoran** [comment] 2019-05-31 16:06
Note that the following also give different answers presently:

```
Array(1).fold(2)(_ * _)  // 1
List(1).fold(2)(_ * _)   // 2
Vector(1).fold(2)(_ * _) // 2
```

Given that `2` isn't a zero of `_ * _`, this is I guess not strictly illegal, but it sure is surprising, especially since you might be thinking that you're good with using the zero as an initial value as long as the operator is commutative and distributive.  (I.e. "you can rearrange it in any order".)

**Comment by dwijnand** [comment] 2019-05-31 16:14
So if this is undefined behaviour (using fold with unlawful zero and combine operator) that has changed, that's not a regression/bug is it?

**Comment by Ichoran** [comment] 2019-05-31 16:19
I would be more inclined to say that this illustrates that the API for `fold` is buggy and should be fixed or the method should be deprecated.  An API for which undefined behavior is easy to evoke by accident is not a very desirable API.

**Comment by Jasper-M** [comment] 2019-05-31 16:28
Perhaps `fold` should enforce its precondition with `assert(op(z, z) == z)`. Or maybe it should indeed be deprecated. Weren't the parallel collections its raison d'être?

**Comment by dwijnand** [comment] 2019-05-31 16:42
@Ichoran Normally we refer to behaviours or implementations as buggy.  I agree with you that the _API_ is buggy.

**Comment by ashawley** [comment] 2019-05-31 16:49
Seems like an implementation bug to me:

```scala
scala> Array(1).fold(2)(_ * _)
res0: Int = 1

scala> Array(1).foldLeft(2)(_ * _)
res1: Int = 2

scala> Array(1).foldRight(2)(_ * _)
res2: Int = 2
```

**Comment by SethTisue** [comment] 2019-05-31 16:56
> Seems like an implementation bug to me

Why? given

> z a neutral element for the fold operation; may be added to the result an arbitrary number of times, and must not change the result (e.g., Nil for list concatenation, 0 for addition, or 1 for multiplication).

**Comment by SethTisue** [comment] 2019-05-31 16:59
> Weren't the parallel collections its raison d'être?

Yes, absolutely. It was never intended as "foldLeft or foldRight I don't care which".

I don't see a bug here except perhaps a naming bug. Should we give it a more elaborate name than `fold`, to signal more strongly that it is a different beast?

**Comment by SethTisue** [comment] 2019-05-31 17:00
> Or maybe it should indeed be deprecated

That seems like a good suggestion, since I can't think of a use case for it outside of the parallel collections?

maybe @axel22 has an opinion here

**Comment by szeiger** [comment] 2019-05-31 17:01
I agree that this is not a bug. Any code that relied on `fold` to use the neutral element exactly once would already have broken in 2.12 with parallel collections. Now that they don't share the same interfaces anymore we are free to deprecate and remove `fold` from the standard library if people find it too confusing. It still exists because it can be implemented more efficiently in some cases (but that's only because it is free to use the neutral element any number of times).

**Comment by ashawley** [comment] 2019-05-31 18:09
> z  a neutral element for the fold operation

I saw this, but this reads like a suggestion to the user, and not a requirement of the implementation.

**Comment by eed3si9n** [comment] 2019-05-31 18:39
> z a neutral element for the fold operation;

I think the key part of the Scaladoc is what follows that sentence.

> **may be added to the result an arbitrary number of times**, and must not change the result (e.g., Nil for list concatenation, 0 for addition, or 1 for multiplication).

Thus given `Array(1).fold(2)(_ * _)` the following are all valid answers according to Scaladoc:

- 1
- 2
- 4
- 6
- and so on...

**Comment by ashawley** [comment] 2019-05-31 19:00
That would be interesting.  Still, it's just a wordy way to describe to the user that `z` is supposed to not do anything.

**Comment by eed3si9n** [comment] 2019-05-31 19:05
IMO calculation order being non-deterministic doesn't necessarily lead to parallel collections. If that's the case, we should do something about `Set(1, 2, 3, 4, 5).toSeq` as well.

A better API might be to define `scala.math.CommutativeMonoid` and accept an instance of `CommutativeMonoid[Int]` as a parameter like we do with `scala.math.Ordering`. I also agree the name `fold` probably should change.

**Comment by DaniRey** [comment] 2019-05-31 19:26
Can we add information about this change in behavior to https://docs.scala-lang.org/overviews/core/collections-migration-213.html?

**Comment by Ichoran** [comment] 2019-05-31 19:30
@eed3si9n - This isn't just an issue about calculation order, though.  The API requires not just commutativity and distributivity of the operation `op`, but also that `z` is an identity element.  This is only important for parallel computations where you unpack the fold to such an extent that it might even be empty, and then want only a value back.

In particular, `Set(1, 2).fold(z)(_ + _)` could evaluate to `1 + 2` or `2 + 1` or `z + 1 + 2` or `2 + z + z + z + z + 1 + z` with the promises that the API currently gives.

**Comment by ashawley** [comment] 2019-05-31 20:40
In https://github.com/scala/scala/pull/8114, I try to fix `fold` for `Array` by just making it consistent with `fold` elsewhere in collections  by calling `foldLeft`.  Presumably, there isn't a reason to re-implement `fold` in `ArrayOps`, nor a reason to have a different behavior from 2.12 when size is one.

**Comment by Ichoran** [comment] 2019-05-31 21:01
@ashawley - Well, if people do a lot of folds over arrays of size one, it makes a huge speed difference that you just return the only value; and for small ones, the overhead of actually using rather than skipping the zero element may be noticeable.  That said, I would anticipate that the difference is small.

**Comment by Ichoran** [comment] 2019-05-31 21:16
Initial testing in Thyme says that the removed version takes only about 60% of the time of the foldLeft version with a single element, and only about 70% with four elements.  However, it crosses over at five, which makes me think that a lot of the difference is the manual loop unrolling of one more element.  And for large arrays (100), the removed version actually takes about 20% longer.

All kinda sketchy because I am doing it by hand in the REPL, but it looks self-consistent.

**Comment by Ichoran** [comment] 2019-05-31 21:19
Note: the timings are slightly different depending on whether you pull out `val length = xs.length - 1` or not, but the take-home message is similar--each is better in a certain regime.  (In the case without `val inline`, `foldLeft` wins at medium sizes and at large sizes both are identical.)

**Comment by ashawley** [comment] 2019-05-31 21:29
That is interesting.  Using`reduce`, instead of `fold`, could perhaps be an optimization for such cases.

**Comment by som-snytt** [comment] 2019-05-31 23:56
`foldSomething`, `foldSomehow`, `foldSomewhat`.

**Closed** 2019-06-18 11:24 UTC
Labels: has PR, library:collections
