### ISSUE TITLE
Scala console/REPL becomes unresponsive when using parallel collections

### ISSUE THREAD

**Issue by Delors** [scala/bug#10566] opened 2017-10-25 13:38 UTC
Start the scala console (2.12) and paste the following snippet:

`List(1,2).par.foreach(println)`

After pressing return nothing will happen; when ".par" is removed, the code works as expected. 

(The example works as soon as the code snippet is put in a def: `object o { def run = List(1,2).par.foreach(println) }` and calling o.run runs fine. )

**Comment by martijnhoekstra** [comment] 2017-10-25 13:41
Duplicate of #9076?

**Closed** 2017-10-25 13:56 UTC
