### ISSUE TITLE
2.13.15 is breaking

### ISSUE THREAD

**Issue by broij** [scala/bug#13044] opened 2024-10-10 18:41 UTC
My project uses scala 2.13.14, when updating to scala 2.13.15 in [this](https://github.com/broij/zarrow/pull/21) pull request the compilation now fails at [this](https://github.com/broij/zarrow/blob/main/src/test/scala-2/be/broij/ZArrowSpec.scala#L516) line. 

Here is the compilation error:
https://github.com/broij/zarrow/actions/runs/11220040920/job/31187333614?pr=21

It looks like a type is now inferred to Any while previously type inference was working correctly. This triggers a failure since I am using the compilation flags  -Xfatal-warnings and -Xlint. This is a breaking change. Explicitly setting the type doesn't fix the issue.

**Comment by SethTisue** [comment] 2024-10-10 19:13
sorry, but we only use for this tracker for proper bug reports. please use https://users.scala-lang.org for this sort of open-ended "hey, what changed, I think something might be wrong, can you help me figure out what?" type of question

come back here if you can provide a self-contained example reproduction and back it up with arguments/evidence that it's not an expected change (is there anything relevant in the 2.13.15 release notes or merged-PRs list?) and that the root cause is a bug in Scala, a bug that you are able to characterize

**Closed as not planned by SethTisue** 2024-10-10 19:13 UTC

**Comment by som-snytt** [comment] 2024-10-10 21:44
Sample explicit typing that does not warn (that is, providing the expression reported by `-Vprint`):
```
-          val zArrow      = dyingZArrow.catchAllCause(ZArrow.succeed(expected))
+          val zArrow: be.broij.ZArrow[Any,Any & Any,Nothing,String] = (be.broij.ZArrow.ZArrowOps[Any, Any, Any, Nothing](dyingZArrow).catchAllCause[Any, Nothing, String](ZArrow.succeed[String](expected)))
```
There are Anys in both the ops typeclass and the method invocation.

I did not delve into the minimum viable annotation. (Aside from `@nowarn`.)

Sampler:
```
➜  scala -Xlint
Welcome to Scala 2.13.15 (OpenJDK 64-Bit Server VM, Java 23).
Type in expressions for evaluation. Or try :help.

scala> List(42, "hello, world")
       ^
       warning: a type was inferred to be `Any`; this may indicate a programming error.
val res0: List[Any] = List(42, hello, world)

scala> List[Any](42, "hello, world")
val res1: List[Any] = List(42, hello, world)

scala> val ss: List[Any] = List(42, "hello, world")
val ss: List[Any] = List(42, hello, world)

scala>
```

**Comment by SethTisue** [comment] 2024-10-10 22:05
likely relevant: https://github.com/scala/scala/pull/9452

**Comment by som-snytt** [comment] 2024-10-10 22:24
On the [forum](https://users.scala-lang.org/t/2-13-15-is-breaking-type-inference/10284/2?u=som-snytt), I mentioned the release notes, in case they needed some ~love~ much-deserved appreciation. [Ed. Sorry for my misuse of the language. I didn't mean to suggest they need TLC.]

**Comment by SethTisue** [comment] 2024-10-11 01:46
note that we did already release-note scala/scala#9452
