### ISSUE TITLE
Possible to compile value class of tagged value class

### ISSUE THREAD

**Issue by Katrix-** [scala/bug#10591] opened 2017-11-06 12:22 UTC
This does not compile, as one would expect.
```scala
class ValueClass(val l: Long) extends AnyVal
object Extensions {
  implicit class ValueClassExtensions(val value: ValueClass) extends AnyVal {
    def asString: String = value.l.toString
  }
}
```

This however does. Using any of the extension methods causes a class cast exception at runtime.

```scala
object tag {
  def apply[U] = new Tagger[U]

  trait Tagged[U] extends Any
  type @@[+T, U] = T with Tagged[U]

  class Tagger[U] {
    def apply[T](t: T): T @@ U = t.asInstanceOf[T @@ U]
  }
}

class ValueClass(val l: Long) extends AnyVal
object Extensions extends App {
  import tag._
  sealed trait Specific
  type SpecificValueClass = ValueClass @@ Specific
  implicit class SpecificValueClassExtensions(val value: SpecificValueClass) extends AnyVal {
    def asString: String = value.l.toString
  }

  tag[Specific](new ValueClass(2)).asString //ClassCastException
}
```

I'd expect neither one to work.

**Comment by hrhino** [comment] 2018-01-12 14:36
This is fixed in current 2.12.x (it's a duplicate of #10530).

**Closed by hrhino** 2018-01-12 14:36 UTC
Labels: runtime crash, should-not-compile, valueclass
