### ISSUE TITLE
Scala compiler conflicts Java field names with class / package canonical names

### ISSUE THREAD

**Issue by fdaca** [scala/bug#11788] opened 2019-10-31 15:23 UTC
### Test example

**Foo.java**
```java
public class Foo {
    private String java;

    public java.lang.Integer test() {
        return null;
    }
}
```

**Bar.scala**
```scala
class Bar {
  def main(): Unit = {
    val bug = new Foo()
    bug.test()
  }
}
```

*compilation result:*
```
[error] /Users/fdaca/git/scala-bug-test/src/main/java/Foo.java:4:17: value lang is not a member of String
[error]     public java.lang.Integer test() {
[error]                 ^
```

### Bug description
Given a mixed Java / Scala project with a Java class having both:
- a method declaration with a canonical name of return type (e.g. `public java.lang.Integer test()`)
- a field with name equal to the first package of declared method return type (e.g. `private String java`)

Scala compiler would conflict the field identifier with package name and yield an error trying to lookup a member as if the first package was the previously declared field:  `value lang is not a member of String`.

The same problem occurs with different identifiers: `private Foo org;` + `public org.apache.commons.lang.CharSet getSet()` would try to lookup member `apache` in type `Foo`.

### Affected versions
- 2.13.1
- 2.12.8
- 2.11.8

**Comment by som-snytt** [comment] 2024-07-30 19:06
~Could have been a duplicate of~ Similar to https://github.com/scala/bug/issues/10350 but that fix did not do enough work.

**Comment by SethTisue** [comment] 2024-08-05 22:08
@som-snytt you're saying this one is also fixed and we should close it?

**Comment by som-snytt** [comment] 2024-08-05 23:42
I amended my comment and made the PR available for review. Open question is whether it's worth fixing on dotty, since this ticket has only 3 👍 from the field in 5 years.

**Closed** 2024-08-15 13:22 UTC
Labels: java interop, has PR, should compile
