### ISSUE TITLE
Spurious warning with varargs + default implicit

### ISSUE THREAD

**Issue by japgolly** [scala/bug#12239] opened 2020-11-23 08:26 UTC
## reproduction steps

using Scala 2.13.3

```scala
object Hmm {
  def zxc(b: Int*)(implicit x: Int = 3) = "" + b + x
  zxc(4)
}
```

## problem

```
> scalac -Xlint as.scala
as.scala:3: warning: local val x$1 in value <local Hmm> is never used
  zxc(4)
      ^
1 warning
```

Shouldn't be a warning.

**Comment by som-snytt** [comment] 2020-11-23 09:30
Maybe https://github.com/scala/bug/issues/11964

**Comment by SethTisue** [comment] 2021-04-15 16:20
just as at #11964, the desugaring shows an `immutable.Seq` being constructed and then not used:

```
        <artifact> val x$1: Seq = scala.collection.immutable.Seq.apply(scala.runtime.ScalaRunTime.wrapIntArray(Array[Int]{4})).$asInstanceOf[Seq]();
        <artifact> val x$2: Int = iw$Hmm.this.zxc$default$2(scala.runtime.ScalaRunTime.wrapIntArray(Array[Int]{4}));
        iw$Hmm.this.zxc(scala.runtime.ScalaRunTime.wrapIntArray(Array[Int]{4}), x$2)
```

**Comment by dwijnand** [comment] 2021-04-15 16:23
Duplicate of #11964

**Closed by dwijnand** 2021-04-15 16:23 UTC
Labels: errors and warnings

**Comment by SethTisue** [comment] 2021-04-15 16:24
Thanks for the report — your example is more minimized than what we had on the older ticket :+1:
