### ISSUE TITLE
Future is never completed when throwing a NoSuchMethodError in map

### ISSUE THREAD

**Issue by yanns** [scala/bug#12150] opened 2020-09-11 13:01 UTC
## reproduction steps

using Scala 2.13.3,

```scala
Future.unit
  .flatMap { _ =>
    Future.failed(new NoSuchMethodError("test"))
  }
```
return a failed future of `ExecutionException`.

```scala
Future.unit
  .map { a =>
    throw new NoSuchMethodError("test")
    a
  }
```
never completes

## problem

- A future should always complete
- throwing an `Exception` in `map` should be the same as `flatMap`  on `Future.failed`

**Comment by NthPortal** [comment] 2020-09-11 19:06
> A future should always complete

a `Future` is not intended to–and does not–handle fatal exceptions (as defined by `scala.util.control.NonFatal`). `NoSuchMethodError` is a subclass of `LinkageError` which is one of the types of fatal exceptions - it will be reported by the `reportFailure` method of the `ExecutionContext` in which the `Future` is executed. If you would like to handle fatal exceptions, you must handle them yourself in the block that throws the exception, or use an `ExecutionContext` with a `reportFailure` method that handles it (generally by terminating the JVM).

In general the occurrence of a fatal exception indicates that a program is in an unrecoverable state, and thus there is no sensible way for `Future` to handle it–thus, it doesn't. Usually, the only reasonable thing to do when a fatal exception occurs is to terminate the JVM.

--------

> throwing an `Exception` in `map` should be the same as `flatMap` on `Future.failed`

The fact that `Future.failed` allows you to pass in a fatal exception (arguably a bug) should not be used as evidence that `Future` should handle fatal exceptions. When a `Future` is created from a literal `Try` (which is what `Future.failed` does), it does not actually examine the `Try` to make sure it's not a `Failure` containing a fatal exception. However, when executing the body of a `Future` or a transformation on one, failing the `Future` would require catching and handling the fatal exception, which is ill-advised given the program is in an undefined/unrecoverable state.

--------

Duplicate of #9554

**Closed by NthPortal** 2020-09-11 19:06 UTC
Labels: duplicate, concurrency

**Comment by yanns** [comment] 2020-09-12 08:48
Thx for the explanation.
I was not aware that `NoSuchMethodError`  is a fatal error.

**Comment by yanns** [comment] 2020-09-12 08:49
We are using a `reportFailure` but the error was not reported there.

I'll check again.

**Comment by tmccombs** [comment] 2023-04-24 20:46
I just ran into this issue, because I was missing a runtime dependency for a library. Some Futures would never terminate. It took quite a while to figure out that the reason the Futures were stalled, is because a fatal exception was getting silently swallowed. 

This behavior can be quite a footgun. At the very least the documentation should have a big warning that fatal throwables aren't caught, and can't be handled with `recover` and similar, and the Future will never complete if they are thrown. And recommend that any execution context you use sets the unhandledExceptionHandler for the threads. The current documentation makes no mention of how fatal exceptions are handled (or not, as it were).

And maybe the ExecutionContext's in the standard librarly should do something more than just print a stack trace if it gets a fatal exception?  Perhaps exit the VM? Although I'm not sure how to fix that in a backwards compatible way.

**Comment by som-snytt** [comment] 2023-04-24 21:50
@tmccombs I created a ticket to improve the doc. I was surprised there is no mention, since it is a frequent topic of conversation over many years. I suspect that people get together to commiserate, and during the last round of drinks, say, "We oughta document it somewhere." And then the resolve dissolves.

**Comment by SethTisue** [comment] 2024-02-24 20:00
There is some discussion on the advisability of catching fatal exceptions at https://users.scala-lang.org/t/reconciling-fatal-exceptions-and-scala-futures/9827

**Comment by tmccombs** [comment] 2024-02-24 22:38
I don't entirely disagree with that, but:

1. The current default doesn't stop the program, it just prints an error to stdout (which may or may not end up in the same place as normal logs) and then never resolve the future. This can lead to strange behavior like timeouts or deadlocks because the future never completes even with an error, but the program keeps running.
2. Not all "fatal" exceptions are the same. An OOM is almost certainly unrecoverable. But  a LinkageError might very well be recoverable, or at least allow some final code to do cleanup before exiting. 
3. There isn't really a good escape hatch if you do really need to handle fatal exceptions for some reason.
