### ISSUE TITLE
-Xlint:infer-any doesn't catch all scenarios where a type is inferred to be Any

### ISSUE THREAD

**Issue by coreywoodfield** [scala/bug#12320] opened 2021-01-22 22:50 UTC
## Reproduction steps

using Scala 2.13.3,

Run scala with `scala -Xlint:infer-any -Wconf:cat=lint-infer-any:error`
```scala
scala> Option.empty[Int].contains("") // this errors as expected
                         ^
       error: a type was inferred to be `Any`; this may indicate a programming error.

scala> Option.empty[Int].contains("") || false // this does not throw an error, even though a type was inferred to be `Any`
val res1: Boolean = false
```
or, to see type information:
This fails as expected:
```
scalac -Xlint:infer-any -Wconf:cat=lint-infer-any:error -Xprint:typer /dev/stdin <<<'object Main { Option.empty[Int].contains("") }'
```
This doesn't fail (even though it should, according to the typer output):
```
scalac -Xlint:infer-any -Wconf:cat=lint-infer-any:error -Xprint:typer /dev/stdin <<<'object Main { Option.empty[Int].contains("") || ??? }'
```

## Problem
Expectation: The linter reports all instances of `Any` being inferred when `-Xlint:infer-any` is enabled
Actual: The linter sometimes doesn't report instances of `Any` being inferred with `-Xlint:infer-any` enabled

**Comment by coreywoodfield** [comment] 2021-01-22 22:57
I just checked scala 2.12.6, and the bug is reproducible there as well

**Comment by som-snytt** [comment] 2021-01-23 03:41
This is a duplicate of https://github.com/scala/bug/issues/9211 where the second example is a false negative. I'll add this example.

**Comment by som-snytt** [comment] 2021-01-23 11:46
I see that it silences the warning because it may want to rejigger the enclosing application. Letting it ignore that the context is non-erroring shows the warning. The existing test is https://github.com/scala/scala/blob/2.13.x/test/files/neg/warn-inferred-any.scala#L17

**Comment by dwijnand** [comment] 2021-04-14 16:20
Duplicate of #9211

**Closed by dwijnand** 2021-04-14 16:20 UTC
Labels: duplicate
