### ISSUE TITLE
HTML-like code in code blocks of Scaladoc should not be rendered as HTML

### ISSUE THREAD

**Issue by Atry** [scala/bug#12022] opened 2020-05-30 20:09 UTC
## reproduction steps

using Scala 2.13.2,

```scala
/** 
  * {{{
  * @html
  * val myDiv = <div class="my-class" tabindex="42"></div>
  * myDiv.value.nodeName should be("DIV")
  * myDiv.value.className should be("my-class")
  * myDiv.value.tabIndex should be(42)
  * }}}
  */
```

## problem

It rendered as:
```
@html
val myDiv =


myDiv.value.nodeName should be("DIV")
myDiv.value.className should be("my-class")
myDiv.value.tabIndex should be(42)
```

* Source code: https://github.com/GlasslabGames/html.scala/blob/75887b53ef55d341453cbaf4c0110ca4b24d4576/html/src/main/scala/org/lrng/binding/html.scala#L711
* Generated Scaladoc: https://javadoc.io/static/org.lrng.binding/html_sjs0.6_2.12/1.0.2+34-75887b53/org/lrng/binding/html.html 

This issue is created because it's similar but different from #11424

**Comment by danicheg** [comment] 2022-08-16 19:49
I guess this behavior is expected. Since the `div` tag is marked as dangerous and filtered out by intent. See https://github.com/scala/scala/blob/2.13.x/src/scaladoc/scala/tools/nsc/doc/base/CommentFactoryBase.scala#L128-L129.
If one will try out another tag, like `<foo>`, scaladoc from your snippet will be generated fine:
```
/**
 * {{{
 * @html
 * val myDiv = <foo class="my-class" tabindex="42"></foo>
 * myDiv.value.nodeName should be("DIV")
 * myDiv.value.className should be("my-class")
 * myDiv.value.tabIndex should be(42)
 * }}}
 */
```
That seems reasonable to me and works as designed at least. cc @SethTisue 🙇🏻‍♂️

**Closed** 2022-08-16 20:21 UTC
Labels: scaladoc tool
