### ISSUE TITLE
The Scaladoc HTML page for a package should contain its sub-packages

### ISSUE THREAD

**Issue by Atry** [scala/bug#10749] opened 2018-02-24 19:38 UTC
In Scala 2.11, the Scaladoc HTML page for a package contains its sub-packages
You can see `package control`,  `package hashing` and  `package matching` in https://www.scala-lang.org/api/2.11.12/scala/util/package.html

However, those sub-packages disappear in Scala 2.12
https://www.scala-lang.org/api/2.12.4/scala/util/index.html

**Comment by SethTisue** [comment] 2018-02-24 19:45
I think that might be intentional? after all the subpackages are in the sidebar:

<img width="196" alt="screen shot 2018-02-24 at 11 44 50 am" src="https://user-images.githubusercontent.com/161079/36634361-42fe4b5e-1958-11e8-8b5e-7093c52ee080.png">


@felixmulder might remember if this was on purpose

**Comment by Atry** [comment] 2018-02-24 19:51
A package usually contains a brief message that aims to shown in its parent package. Scaladoc 2.12 never shows the brief message.

**Comment by Jasper-M** [comment] 2018-02-24 20:29
Isn't that message shown on the packages own page?

**Comment by SethTisue** [comment] 2018-02-24 21:25
@Atry yes, I understand.

**Comment by SethTisue** [comment] 2018-02-24 21:26
@Atry yes, I understand. but it isn't clear to me that bringing that back is necessary and desirable

**Comment by SethTisue** [comment] 2018-02-24 21:27
@Atry where does that string come from?

**Comment by SethTisue** [comment] 2018-02-24 21:31
> Isn't that message shown on the package's own page?

yes, see e.g.
https://www.scala-lang.org/api/2.12.4/scala/collection/parallel/index.html

**Comment by felixmulder** [comment] 2018-03-06 13:53
I guess there could be a on-hover tooltip for the sidebar links if that's what you're getting at?

**Comment by Atry** [comment] 2018-03-06 15:05
In this style guideline(http://docs.scala-lang.org/style/naming-conventions.html#objects):
> An exception is when mimicking a package or function.

I think it is very common make `object` / `package` / `package object` mimick each other. I wonder why they are treated different in Scaladoc.

**Comment by m-sp** [comment] 2018-06-04 17:19
seems like this is a duplicate of #10397

I've tried some minor changes on my local machine and the following code:

``` scala
package a {
	/** Best package ever. Really! */
	package object b {
		class T
	}
	package b2 {
		trait Z
	}
	/** Test */
	object X
}
```

now generates https://matthias.sperl.me/10749/a/index.html

I still have to clean up some minor things (e.g. sorting seems to be off) but I can create a PR for it, if you want!

**Comment by SethTisue** [comment] 2018-06-12 02:37
> I still have to clean up some minor things (e.g. sorting seems to be off) but I can create a PR for it, if you want!

yes, that looks appealing. /cc @sjrd who reported #10397

**Closed** 2018-06-15 08:58 UTC
Labels: help wanted, regression, scaladoc tool
