### ISSUE TITLE
2.12.12 Regression? NoSuchMethodError in Reflection

### ISSUE THREAD

**Issue by etspaceman** [scala/bug#12100] opened 2020-07-29 14:44 UTC
## reproduction steps

using Scala 2.12.12, I have code that uses version 1.0.0 of the [scalaz-deriving plugin](https://github.com/scalaz/scalaz-deriving/tree/v1.0.0) and Magnolia to do the following

```scala
@deriving(Show, Eq, Encoder, Arbitrary)
final case class TestItem(
    int: Int,
    double: Double,
    boolean: Boolean,
    string: String)
```

This can be recreated pretty easily by using `@deriving` for any type-class, so I omitted the implementation details of those. The issue lies in the annotation itself. 

## problem

In 2.12.11, the above compiles great. In 2.12.12 however, I get the following:

```
[error] ## Exception when compiling 7 sources to /Users/emeisel/Documents/GitHub/sdk/testKitCommon/target/scala-2.12/classes
[error] java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: scala.collection.immutable.List.$anonfun$flatMap$1$adapted(Lscala/runtime/BooleanRef;Lscala/runtime/ObjectRef;Lscala/runtime/ObjectRef;Ljava/lang/Object;)Ljava/lang/Object;
[error] scalaz.plugins.deriving.AnnotationPlugin$$anon$1.decepticons(AnnotationPlugin.scala:280)
[error] scalaz.plugins.deriving.AnnotationPlugin$$anon$1.autobots(AnnotationPlugin.scala:207)
[error] scalaz.plugins.deriving.AnnotationPlugin$$anon$1$$anon$3.transform(AnnotationPlugin.scala:102)
[error] scalaz.plugins.deriving.AnnotationPlugin$$anon$1$$anon$3.transform(AnnotationPlugin.scala:100)
[error] scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
[error] scalaz.plugins.deriving.AnnotationPlugin$$anon$1$$anon$2.apply(AnnotationPlugin.scala:94)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] scala.tools.nsc.Global$GlobalPhase.run(Global.scala:402)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1511)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1495)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1488)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1614)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
```

Some relevant links in the stack seems to indicate the regression lies with the reflection library:

https://github.com/scalaz/scalaz-deriving/blob/v1.0.0/deriving-plugin/src/main/scala/scalaz/plugins/deriving/AnnotationPlugin.scala#L280

https://github.com/scalaz/scalaz-deriving/blob/v1.0.0/deriving-plugin/src/main/scala/scalaz/plugins/deriving/AnnotationPlugin.scala#L207

**Comment by SethTisue** [comment] 2020-07-29 15:40
Could be a Scala regression. Could also be that the macro needs adjusting, because it was making some fragile assumption about compiler internals that doesn't always hold, and then some 2.12.12 change surfaced the problem.

A possible next step would be to identify (via bisecting, with https://github.com/adriaanm/binfu/blob/master/bisect.sh or manually) the individual scala/scala PR responsible. That almost always gives very strong clues as to the nature of the problem.

Perhaps related: #10054 / #10554 ?

**Comment by etspaceman** [comment] 2020-07-29 16:15
> A possible next step would be to identify (via bisecting, with https://github.com/adriaanm/binfu/blob/master/bisect.sh or manual equivalent) the individual scala/scala PR responsible.

Sure I can run something like that tonight. I've never used this script before so I may need some guidance here.

> Could also be that the macro needs adjusting

Yeah this is an older version of the macro as well; it is possible that this macro has been updated with complete support here in later versions. I unfortunately cannot update that macro due to 2.11 support in my code base, but I would still expect the same to work across minor version updates of Scala.

**Comment by som-snytt** [comment] 2020-07-30 02:04
I did see that the adapter in a bootstrap method went away because `List.flatMap` was tweaked, see below.

I also witnessed that the adapter wound up in the plugin class.

I had looked at the build for scala-deriving but only after some time remembered to check the project dir.

Inlining from the standard library means the plugin is tied to the scala version it is compiled with.

```
  def extraScalacOptions(scalaVersion: String) =
    CrossVersion.partialVersion(scalaVersion) match {
      case Some((2, 12)) =>
        Seq(
          "-Ywarn-extra-implicit",
          "-Ywarn-unused:explicits,patvars,imports,privates,locals,implicits",
          "-opt:l:method,inline",
          "-opt-inline-from:scala.**",
          "-opt-inline-from:scalaz.**",
          "-opt-inline-from:fommil.**",
          "-opt-inline-from:iotaz.**",
          "-opt-inline-from:magnolia.**",
          "-opt-inline-from:shapeless.**",
          "-opt-inline-from:jsonformat.**",
          "-opt-inline-from:xmlformat.**"
        )
      case _ =>
        Seq(
          "-Xexperimental"
        )
    }
```
The javap diff for List is
```
>   private boolean isLikeListReusableCBF(scala.collection.generic.CanBuildFrom<?, ?, ?>);
126d121
<   public static final void $anonfun$flatMap$1(scala.runtime.BooleanRef, scala.runtime.ObjectRef, scala.runtime.ObjectRef, java.lang.Object);
131d125
<   public static final java.lang.Object $anonfun$flatMap$1$adapted(scala.runtime.BooleanRef, scala.runtime.ObjectRef, scala.runtime.ObjectRef, java.lang.Object);
```
and BTW I really miss REPL's `:javap -fun` feature, and it should be brought back.

**Comment by som-snytt** [comment] 2020-07-30 02:11
That was at `v1.0.0` of the plugin, I see `v2` is cross-compiled for `2.12` without opting for `-opt`.

I'll close this, but if I'm wrong feel free to re-open.

**Closed by som-snytt** 2020-07-30 02:11 UTC

**Comment by eed3si9n** [comment] 2020-08-14 12:19
I ran into this using an old version of json4s with Scala 2.12.12 since release prior to https://github.com/json4s/json4s/commit/658505f63e25b364caa26cd6ee7a5004d9618f40 had `-optimize` on.
