### ISSUE TITLE
Cannot shuffle a Range, but can shuffle Range.Inclusive

### ISSUE THREAD

**Issue by mbuzdalov** [scala/bug#11875] opened 2020-01-31 12:31 UTC
Scala 2.12.10:

```
scala> scala.util.Random.shuffle(1 to 10)
res0: scala.collection.immutable.IndexedSeq[Int] = Vector(8, 4, 7, 6, 3, 5, 10, 9, 1, 2)

scala> scala.util.Random.shuffle(1 until 10)
<console>:12: error: Cannot construct a collection of type scala.collection.AbstractSeq[Int] with elements of type Int based on a collection of type scala.collection.AbstractSeq[Int].
       scala.util.Random.shuffle(1 until 10)
```

Scala 2.13.1:

```
scala> scala.util.Random.shuffle(1 to 10)
res0: IndexedSeq[Int] = Vector(2, 8, 3, 7, 10, 6, 5, 4, 1, 9)

scala> scala.util.Random.shuffle(1 until 10)
                                ^
       error: Cannot construct a collection of type C with elements of type Int based on a collection of type scala.collection.immutable.Range.
```

There is definitely something wrong.

**Comment by lrytz** [comment] 2020-01-31 13:00
```
scala> implicitly[scala.collection.BuildFrom[Range.Inclusive, Int, _]]
val res5: scala.collection.BuildFrom[Range.Inclusive,Int,Any] = scala.collection.BuildFromLowPriority2$$anon$11@64b70f41

scala> implicitly[scala.collection.BuildFrom[Range, Int, _]]
                 ^
       error: Cannot construct a collection of type Any with elements of type Int based on a collection of type scala.collection.immutable.Range.
```

**Comment by ausmarton** [comment] 2020-02-01 18:06
I'm new to this dev community and found this issue interesting. As I was trying to understand the issue, I realised that `until`s return type is an `abstract class` while `to`s return type is a concrete type `Range.Inclusive`.

Would changing the [return type of `until` to `Range.Exclusive` here](https://github.com/scala/scala/blob/46a81568daeca71ee05364be2a224ffe227e8fe0/src/library/scala/runtime/RichInt.scala#L53-L66) be a step in the right direction?

```scala
def until(end: Int): Range.Exclusive = Range(self, end)
```

**Comment by som-snytt** [comment] 2020-02-02 05:21
https://github.com/scala/bug/issues/8569
https://github.com/scala/bug/issues/6948

**Comment by ausmarton** [comment] 2020-02-02 11:04
Thanks @som-snytt, should we close this issue given it's duplicate of #6948?

**Comment by dwijnand** [comment] 2020-02-02 14:40
Yeah, I think so, following #8569's lead.

Duplicate of #6948

**Comment by dwijnand** [comment] 2020-02-02 14:40
Duplicate of #6948

**Closed by dwijnand** 2020-02-02 14:40 UTC
Labels: library:collections
