### ISSUE TITLE
Warning should not be issued for erroneous type: "the existential type <error> forSome { type _$1; type _$2 }, which cannot be expressed by wildcards,  should be enabled"

### ISSUE THREAD

**Issue by retronym** [scala/bug#10938] opened 2018-06-10 23:42 UTC
```
scala> typeOf[scala.xxx.XXX[_, _]]
<console>:37: error: object xxx is not a member of package scala
       typeOf[scala.xxx.XXX[_, _]]
                    ^
<console>:37: warning: the existential type <error> forSome { type _$1; type _$2 }, which cannot be expressed by wildcards,  should be enabled
by making the implicit value scala.language.existentials visible.
This can be achieved by adding the import clause 'import scala.language.existentials'
or by setting the compiler option -language:existentials.
See the Scaladoc for value scala.language.existentials for a discussion
why the feature should be explicitly enabled.
       typeOf[scala.xxx.XXX[_, _]]
                        ^
```

**Comment by Jasper-M** [comment] 2018-06-11 12:45
I can't reproduce this :(

**Comment by som-snytt** [comment] 2018-06-11 13:03
```
$ scala -Dscala.repl.info
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.
[info] started at Mon Jun 11 06:00:52 PDT 2018

scala 2.12.6> def f: scala.xxx.XXX[_,_] = ???
<console>:11: error: object xxx is not a member of package scala
              def f: scala.xxx.XXX[_,_] = ???
                           ^
<console>:11: warning: the existential type <error> forSome { type _$1; type _$2 }, which cannot be expressed by wildcards,  should be enabled
by making the implicit value scala.language.existentials visible.
This can be achieved by adding the import clause 'import scala.language.existentials'
or by setting the compiler option -language:existentials.
See the Scaladoc for value scala.language.existentials for a discussion
why the feature should be explicitly enabled.
              def f: scala.xxx.XXX[_,_] = ???
                               ^
<console>:11: warning: the existential type <error> forSome { type _$1; type _$2 }, which cannot be expressed by wildcards,  should be enabled
by making the implicit value scala.language.existentials visible.
              def f: scala.xxx.XXX[_,_] = ???
                               ^

scala 2.12.6> :quit
$ skala -Dscala.repl.info
[info] started at Mon Jun 11 06:01:07 PDT 2018
banner

scala 2.13.0-20180609-021926-820ddf5> def f: scala.xxx.XXX[_,_] = ???
                                                   ^
                                      error: object xxx is not a member of package scala
                                                       ^
                                      warning: the existential type <error> forSome { type _$1; type _$2 }, which cannot be expressed by wildcards,  should be enabled
                                      by making the implicit value scala.language.existentials visible.
                                      ----
                                      This can be achieved by adding the import clause 'import scala.language.existentials'
                                      or by setting the compiler option -language:existentials.
                                      See the Scaladoc for value scala.language.existentials for a discussion
                                      why the feature should be explicitly enabled.

scala 2.13.0-20180609-021926-820ddf5> 
```
Double-feature reporting is fixed on 2.13.

**Comment by Jasper-M** [comment] 2018-06-11 13:24
All I get is:

```
Welcome to Scala 2.13.0-pre-c5da7a0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_152).
Type in expressions for evaluation. Or try :help.

scala> def f: scala.xxx.XXX[_,_] = ???
                    ^
       error: object xxx is not a member of package scala

scala> 
```

This is via sbt consoleQuick.

**Comment by som-snytt** [comment] 2018-06-11 13:32
There are things `sbt` isn't telling you. Also they don't customize the replay advice.

```
> consoleQuick
[info] Updating {file:/Users/andrew/workspace/scala/}root...
[info] Resolving jline#jline;2.14.6 ...
[info] Done updating.
[info] Starting scala interpreter...
[info] 
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> "hi" length
warning: there was one feature warning; for details, enable `:setting -feature' or `:replay -feature'
res0: Int = 2

scala> :replay -feature
Replaying: "hi" length

Failed to initialize compiler: object scala in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programmatically, settings.usejavacp.value = true.


scala> 
```

**Comment by Jasper-M** [comment] 2018-06-11 13:37
```
scala> def f: scala.xxx.XXX[_,_] = ???
                    ^
       error: object xxx is not a member of package scala

scala> :warning
                        ^
       warning: the existential type <error> forSome { type _$1; type _$2 }, which cannot be expressed by wildcards,  should be enabled
       by making the implicit value scala.language.existentials visible.
       ----
       This can be achieved by adding the import clause 'import scala.language.existentials'
       or by setting the compiler option -language:existentials.
       See the Scaladoc for value scala.language.existentials for a discussion
       why the feature should be explicitly enabled.
```

Ok, I'm going to guess the feature warning thing just gets overwritten in case there's also an error... Apologies for the noise.

**Comment by som-snytt** [comment] 2018-06-11 14:17
Thanks, you made me notice that the REPL Reporter needs to be tweaked for the recent Reporter upgrade. It shouldn't show the `----` divider. I actually just spent a half hour of wtf, which is french for finding the widget.

**Closed** 2018-06-14 04:56 UTC
Labels: errors and warnings, has PR, help wanted
