### ISSUE TITLE
False warning match may not be exhaustive when using +: on List

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/bug#12444] opened 2021-08-10 14:40 UTC
## reproduction steps

using Scala 2.13.6,

```scala
List() match {
        case Seq() =>
        case head +: tail =>
      }
```

## problem

I get warning:

> match may not be exhaustive.
> It would fail on the following input: List(_)

I do not get the warning when using `Seq()` instead of `List()`, I also do not get the warning when using `::` instead of `+:`.

I am convinced the warning is wrong, as when `::` matches, then `+:` matches as well.

The warning is shown on Scala 3.0.1 as well, only with a bit different words:

> match may not be exhaustive.
> It would fail on pattern case: List(_, _*)

**Comment by OndrejSpanel** [comment] 2021-08-10 14:51
I guess the explanation is in https://users.scala-lang.org/t/does-the-extractor-break-exhaustive-match-checking/6867

`::` works because it is a case class, while `+:` is an abstract method

**Comment by dwijnand** [comment] 2021-08-10 15:05
Duplicate of #12377

**Closed by dwijnand** 2021-08-10 15:05 UTC
