### ISSUE TITLE
value class with Unit member crashes the compiler

### ISSUE THREAD

**Issue by tpolecat** [scala/bug#10360] opened 2017-06-06 20:18 UTC
A value class whose member has type `Unit` crashes the compiler.

```
scala> class X(val a: Unit) extends AnyVal
scala.tools.asm.tree.analysis.AnalyzerException: While processing $line3/$read$$iw$$iw$X$.equals$extension
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils$AsmAnalyzer.<init>(BackendUtils.scala:40)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.removeUnreachableCodeImpl(LocalOpt.scala:488)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.removalRound$2(LocalOpt.scala:275)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:354)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1(LocalOpt.scala:195)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.$anonfun$methodOptimizations$1$adapted(LocalOpt.scala:194)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at scala.tools.nsc.backend.jvm.opt.LocalOpt.methodOptimizations(LocalOpt.scala:194)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.$anonfun$localOptimizations$1(GenBCode.scala:248)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.localOptimizations(GenBCode.scala:248)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.run(GenBCode.scala:267)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.buildAndSendToDisk(GenBCode.scala:384)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:350)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1427)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1412)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1407)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:432)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:801)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:759)
	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:948)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:943)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:601)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:590)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:562)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:830)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:698)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:416)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:437)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$1(ILoop.scala:1012)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:1023)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:82)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
Caused by: scala.tools.asm.tree.analysis.AnalyzerException: Error at instruction 37: Cannot pop operand off an empty stack.
	at scala.tools.asm.tree.analysis.Analyzer.analyze(Analyzer.java:302)
	at scala.tools.nsc.backend.jvm.analysis.BackendUtils$AsmAnalyzer.<init>(BackendUtils.scala:37)
	... 54 more
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
	at scala.tools.asm.tree.analysis.Frame.pop(Frame.java:235)
	at scala.tools.asm.tree.analysis.Frame.execute(Frame.java:338)
	at scala.tools.asm.tree.analysis.Analyzer.analyze(Analyzer.java:205)
	... 55 more
error: Error while emitting X$
While processing X$.equals$extension

scala> 
```

**Comment by dwijnand** [comment] 2017-06-08 09:27
Duplicate of https://github.com/scala/bug/issues/9240.

**Closed by dwijnand** 2017-06-08 09:27 UTC
