### ISSUE TITLE
New implementation of LinkedHashSet/LinkedHashMap

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11369] opened 2018-12-27 17:14 UTC
Recently, @szeiger rewrote the implementations of `mutable.HashMap` and `mutable.HashSet` [here](https://github.com/scala/scala/pull/7348). So far as I see there's no reason not to implement LinkedHashSet/Maps the same way, and in fact doing so will allow LinkedHashMaps/Sets to participate in hashcode sharing between:

* `s.c.i.HashMap`
* `s.c.i.HashSet`
* `s.c.i.VectorMap`
* `s.c.m.HashMap`
* `s.c.m.HashSet`
* `s.c.m.HashMap#keySet`
* `s.c.i.HashMap#keySet`
* `s.c.i.VectorMap#keySet`

as started [here](https://github.com/scala/scala/pull/7520)

**Comment by adriaanm** [comment] 2019-01-16 11:07
Is this still under consideration for RC1?

**Comment by mghildiy** [comment] 2019-01-16 14:20
I went through mutable.HashMap and found changes broadly as:

- mixesin trait mutable.AbstractMap

- Class level parameters added: initialCapacity: Int, loadFactor: Double

- Replaced HashTable field with Array named: private[this] var table = new Array[Node[K, V]](tableSizeFor(initialCapacity))

- field 'contentSize' intoduced

- method 'size' overriden

- inline method 'computeHash' added

- inline method 'index' added

- inline metod 'findNode' added to find an entry for input key(k) in array 'table'

- API methods overriden: sizeHint, addAll, remove

- abstract iterator class HashMapIterator added

- private classes Node, DeserializationFactory added

- Modified methods: apply, getOrElse, getOrElseUpdate, put

**Comment by szeiger** [comment] 2019-01-17 11:57
"changes" is an understatement - it's a completely new implementation. I think the idea here is to start with a copy of the new HashMap implementation and make the required changes for keeping track of the links.

**Comment by joshlemer** [comment] 2019-01-17 14:04
@mghildiy @szeiger is right, as well as for LinkedHashSet

**Comment by mghildiy** [comment] 2019-01-17 15:02
Thanks for the inputs.

**Comment by pavelpavlov** [comment] 2019-01-18 10:20
I would also like to contribute if there's need for it.
We use linked collections in our code very heavily.

**Comment by joshlemer** [comment] 2019-01-19 14:49
@mghildly actually those methods are being used, these are kind of "magic methods" that Java knows to call during Java serialization/deserialization. Also I would recommend not extending hashmap to implement linked hash map, but maybe some of the hashtable code can be factored out for reuse.

**Comment by mghildiy** [comment] 2019-01-27 13:09
As far as I understand, new implementation of HashMap/HashSet no more has hashtable related code.

**Comment by mghildiy** [comment] 2019-02-06 02:33
Hi,

Any more inputs here?

**Comment by joshlemer** [comment] 2019-02-07 00:38
@mghildiy If I were doing it, I would simply copy paste `mutable.HashMap` as `LinkedHashMap` and make necessary changes to make the nodes linked (taking the linking logic from the current `LinkedHashMap`), and same for `LinkedHashSet`

**Comment by joshlemer** [comment] 2019-02-07 00:40
@mghildiy the first step to changing the `mutable.HashMap` code into `LinkedHashMap` would be to change its private `Node[K, V]` class to include fields `var earlier: Node[K, V], var later: Node[K, V]`

Let me know if you have any more questions :smile:

**Comment by mghildiy** [comment] 2019-02-07 13:21
Thanks for the inputs @joshlemer . Would look into it this weekend.

**Comment by mghildiy** [comment] 2019-02-10 16:50
There are some methods,like apply, which are not implemented in current version of immutable.LinkedHashMap, but they are there in immutable.HashMap. 
Should they be implemented?

**Comment by SethTisue** [comment] 2019-02-10 18:39
> some methods [...] are not implemented

you mean because the implementations are inherited? in many cases the inherited implementations are fine and there's no reason to override them. concrete collections may override some of them, usually for efficiency

**Comment by mghildiy** [comment] 2019-02-11 01:24
Sorry, my mistake. I was actually referring to mutable versions, not immutable..

**Comment by mghildiy** [comment] 2019-02-14 01:43
I am done with changes in LinkedHashMap.
Do I need to write a benchmark class too, jst like done for HashMap?
Also, currently there is a single test for LinkedHashMap(in LinkedHashMapTest.scala). Should I add tests for entire code in LinkedHahsMap.scala?

**Comment by joshlemer** [comment] 2019-02-14 16:16
>Do I need to write a benchmark class too, jst like done for HashMap?

No not necessarily, 

>Also, currently there is a single test for LinkedHashMap(in LinkedHashMapTest.scala). Should I add tests for entire code in LinkedHahsMap.scala?

I think if you just get all existing LinkedHashMap tests to pass, that should be enough to put up a preliminary `[WIP]` pull request

**Comment by adriaanm** [comment] 2019-03-06 09:36
👋 I haven't seen a PR for this yet. As we're closing in rapidly on the RC1 due date, I'm going to have to defer this unless we can have a PR in a mergeable state this week or early next.

**Comment by mghildiy** [comment] 2019-03-07 02:07
I am facing 2 test failures for my change. Trying to find the cause.

**Comment by SethTisue** [comment] 2019-03-07 02:22
@mghildiy sounds good enough for a WIP PR, maybe it'll be obvious to somebody where the failures might be coming from

**Comment by mghildiy** [comment] 2019-03-07 02:33
I would create a PR in next 2-3 days. 
BTW, WIP PR is just like any other PR..right? May be it just has a WIP tag?

**Comment by SethTisue** [comment] 2019-03-07 03:15
> May be it just has a WIP tag?

right, or you can use GitHub's new "draft" feature, https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by mghildiy** [comment] 2019-03-09 15:15
Draft PR:
https://github.com/scala/scala/pull/7839

**Comment by joshlemer** [comment] 2019-03-09 16:22
Thanks a bunch @mghildiy :smile:

**Comment by adriaanm** [comment] 2019-03-21 15:22
It seems this PR won't be ready this week, which is the deadline for RC1. I'm going to put this on the backlog, since it doesn't sound like something we could do in 2.13.1. I haven't followed in detail, so please correct me if I'm missing something.

**Comment by SethTisue** [comment] 2020-10-08 15:45
the PR seems abandoned...? perhaps someone else would be interested in picking it up?

**Closed** 2022-12-02 11:10 UTC
Labels: help wanted, has PR, performance, library:collections
