### ISSUE TITLE
VerifyError: class overrides final method

### ISSUE THREAD

**Issue by durban** [scala/bug#12532] opened 2022-02-08 00:10 UTC
## reproduction steps

using Scala 2.13.8 and sbt 1.6.2 with OpenJDK 11.0.13

```scala
package com.example

class Sync

class Async extends Sync

trait Base {
  def foo: Sync
}

trait BaseSync extends Base {
  override def foo: Sync
}

trait BaseAsync extends Base  {
  override def foo: Async
}

abstract class ImplAsync extends BaseAsync {
  final override def foo: Async =
    new Async
}

final class StrangeClass extends ImplAsync with BaseSync

object Main {
  def main(args: Array[String]): Unit = {
    println((new StrangeClass).foo)
  }
}
```

## problem

When loading `StrangeClass` (I guess) the bytecode verifier (I think) throws an exception: `java.lang.VerifyError: class com.example.StrangeClass overrides final method com.example.ImplAsync.foo()Lcom/example/Sync;`

```
Exception in thread "sbt-bg-threads-52" java.lang.VerifyError: class com.example.StrangeClass overrides final method com.example.ImplAsync.foo()Lcom/example/Sync;
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.example.Main$.main(Strange.scala:28)
        at com.example.Main.main(Strange.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.Run.invokeMain(Run.scala:143)
        at sbt.Run.execute$1(Run.scala:93)
        at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
        at sbt.Run$.executeSuccess(Run.scala:186)
        at sbt.Run.runWithLoader(Run.scala:120)
        at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)
        at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

I'm not sure what to expect, but either a compile-time error, or a working program, and not a VerifyError.

**Comment by SethTisue** [comment] 2022-02-08 00:31
reproduces even on latest 2.13 nightly (with `scala-cli run -S 2.13.9-bin-d49c6a7 --repository https://scala-ci.typesafe.com/artifactory/scala-integration/ S.scala`)

does not reproduce (compiles & runs successfully) on Scala 3.1.1 (`scala-cli run -S 3.1.1 S.scala`)

**Comment by SethTisue** [comment] 2022-02-08 00:35
There are a ton of similar tickets but all of them (that I could find just now anyway) have been closed as fixed. @lrytz might like to take a look — I see his name on multiple such similar tickets.

**Comment by som-snytt** [comment] 2022-02-08 03:01
Modern JVM says
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: class StrangeClass overrides final method ImplAsync.foo()LSync;
```

**Comment by joroKr21** [comment] 2022-02-08 08:53
TIL you can put `override` on an abstract method

**Comment by som-snytt** [comment] 2022-02-08 08:57
I also had to check to the spec, where it says it's required. However, I had thought abstract was not overriding.

**Comment by joroKr21** [comment] 2022-02-08 09:05
There is a bridge generated:
```
public final $line3.$read$$iw$Sync foo();
    descriptor: ()L$line3/$read$$iw$Sync;
    flags: (0x1051) ACC_PUBLIC, ACC_FINAL, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokevirtual #26                 // Method foo:()L$line3/$read$$iw$Async;
         4: areturn
      LineNumberTable:
        line 22: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   L$line3/$read$$iw$StrangeClass;
```

**Comment by som-snytt** [comment] 2022-02-08 09:10
Seth's link is to a bridge over troubled waters.

**Comment by lrytz** [comment] 2022-03-16 19:45
This works in Scala 3 because it emits all bridges non-final. This change was at some point in Scala 2 as well, but then reverted (https://github.com/scala/scala/pull/7980, reverted in https://github.com/scala/scala/pull/8037).

The revert was for two PRs
  - https://github.com/scala/scala/pull/7843, which marked mixin forwarders as bridges
  - https://github.com/scala/scala/pull/7980, which made all bridges non-final

It seems both changes remained in Scala 3, mixin forwarders are marked `synthetic bridge`, and bridges are always non-final. @smarter suggested (https://github.com/scala/scala/pull/8037#pullrequestreview-234438497) that we could keep all bridges non-final and just revert the first change. This would fix the VerifyError of this ticket, and would probably not affect Java interop.

A different fix would be to not emit the bridge in StrangeClass, it seems unnecessary as there's already one in ImplAsync. But this change to earsure seems risky.

**Closed** 2022-05-10 10:49 UTC
Labels: has PR, backend, fixed in Scala 3
