### ISSUE TITLE
2.12 reports parser warnings twice

### ISSUE THREAD

**Issue by lrytz** [scala/bug#12354] opened 2021-02-26 19:38 UTC
In Scala 2.12.13, parser warnings are reported twice, or even trice. Typer warnings once.

```scala
scala> case class C(implicit x: Int)
<console>:1: warning: case classes should have a non-implicit parameter list; adapting to 'case class C()(...)'
case class C(implicit x: Int)
            ^
<console>:11: warning: case classes should have a non-implicit parameter list; adapting to 'case class C()(...)'
case class C(implicit x: Int)
            ^
defined class C

scala> for {x <- Nil; val y = 1} yield y
<console>:1: warning: val keyword in for comprehension is deprecated
for {x <- Nil; val y = 1} yield y
                     ^
<console>:2: warning: val keyword in for comprehension is deprecated
for {x <- Nil; val y = 1} yield y
                     ^
<console>:12: warning: val keyword in for comprehension is deprecated
for {x <- Nil; val y = 1} yield y
                     ^
res0: List[Int] = List()

scala> try 1
<console>:12: warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
try 1
^
res1: Int = 1
```

**Comment by SethTisue** [comment] 2021-02-26 19:41
@som-snytt does this look familiar to you? I feel like I remember seeing an issue and/or PR from you on this theme

**Comment by SethTisue** [comment] 2021-02-26 19:42
@lrytz did you determine if is this a recent regression? (related to configurable warnings backport?)

**Comment by lrytz** [comment] 2021-02-26 19:47
Seems to go back to at least 2.12.0... fixed in (current) 2.13

**Comment by som-snytt** [comment] 2021-02-26 19:49
https://github.com/scala/scala/pull/7467 Seth may recall.

There is a comment reminding us that parse trees are spliced into code template in 2.13 but template text is reparsed in 2.12.

**Comment by SethTisue** [comment] 2021-02-26 19:57
@lrytz if it's fixed in 2.13.x, then our usual policy would be to close the ticket (even if a 2.12.x fix would be welcome)

**Comment by som-snytt** [comment] 2021-02-26 20:01
Use `scala -Dscala.repl.trace` to see the parsings; in the case of the for comprehension, it's parsed, re-parsed with `val res1 =`, then parsed again in code template (actually twice, but the fourth warning is suppressed).

**Comment by som-snytt** [comment] 2021-02-26 20:37
More output regression.
```
➜  ~ sdk use scala 2.12.12

Using scala version 2.12.12 in this shell.
➜  ~ scala
Welcome to Scala 2.12.12 (OpenJDK 64-Bit Server VM, Java 15).
Type in expressions for evaluation. Or try :help.

scala> 1: String
<console>:12: error: type mismatch;
 found   : Int(1)
 required: String
       1: String
       ^

scala> :quit
➜  ~ sdk use scala 2.12.13

Using scala version 2.12.13 in this shell.
➜  ~ scala
Welcome to Scala 2.12.13 (OpenJDK 64-Bit Server VM, Java 15).
Type in expressions for evaluation. Or try :help.

scala> 1: String
<console>:12: error: type mismatch;
 found   : Int(1)
 required: String
1: String
^

scala> :quit
➜  ~
```

**Comment by som-snytt** [comment] 2021-02-26 20:45
@dwijnand welcomes feedback at https://github.com/scala/scala/pull/9298#issuecomment-722237830

**Comment by dwijnand** [comment] 2021-02-26 22:15
[mea culpa](https://github.com/scala/scala/pull/9248#discussion_r559912687) 🙏🏼

**Comment by dwijnand** [comment] 2021-02-26 22:17
Looks like [`335cae4` (#9248)](https://github.com/scala/scala/pull/9248/commits/335cae42a6643c867bb671463de0ad9584f78e59) is the commit I messed up, if someone wants to investigate/fix.

**Comment by som-snytt** [comment] 2021-02-27 07:02
I took 30 paces, turned, and fired a single shot. Then I took off my blindfold.

**Comment by som-snytt** [comment] 2021-03-01 19:54
Looks like the issue was not autolinked to close. Or am I just tired.

**Closed by som-snytt** 2021-03-01 19:54 UTC
Labels: errors and warnings

**Comment by SethTisue** [comment] 2021-03-01 20:13
iiuc GitHub only autocloses a ticket if the fix is merged onto the repo's main branch?

**Comment by som-snytt** [comment] 2021-03-01 20:22
Someone should definitely accept tickets only against the main branch.

Thanks @SethTisue for reminding me, I have an errand at the local branch of the bank.
