### ISSUE TITLE
initializationError java.lang.VerifyError: Bad invokespecial instruction: current class isn't assignable to reference class.

### ISSUE THREAD

**Issue by vasilmkd** [scala/bug#12154] opened 2020-09-14 23:31 UTC
## reproduction steps

using Scala 2.13.3

```
git clone https://github.com/vasilmkd/cats-effect.git
git checkout scalac-bug
sbt test
```

## problem
If `CatsEffectSuite` is defined as a `class` (it can also be `abstract`), everything is fine. As soon as it's changed to a `trait`, the 2.13.3 compiler doesn't complain (i.e. compilation succeeds). However, at runtime, the JVM throws a `java.lang.VerifyError`.

Here's some of the output:
```
cats.effect.TimerTests:
==> X cats.effect.TimerTests.initializationError  0.001s java.lang.VerifyError: Bad invokespecial instruction: current class isn't assignable to reference class.
Exception Details:
  Location:
    cats/effect/CatsEffectSuite.test(Ljava/lang/String;Lscala/Function0;)V @15: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2a2b 2a2c ba00 4000 002a b900 4201 00b7
    0000010: 0047 b1
```

More details about the class:
```scala
trait CatsEffectSuite extends DisciplineSuite with TestUtils (both traits)
```

`CatsEffectSuite` defines the following **overloaded** methods:
```scala
def test(name: String)(body: => Any): Unit
def property(name: String)(body: => org.scalacheck.Prop): Unit
```
which delegate to:
```scala
def test(name: String)(body: => Any)(implicit loc: munit.Location): Unit // defined in `DisciplineSuite` or its subclasses
def property(name: String)(body: => org.scalacheck.Prop)(implicit loc: munit.Location): Unit // defined in `DisciplineSuite` or its subclasses
```
via
```scala
super[DisciplineSuite].test
// and
super[DisciplineSuite].property
// respectively
```

cc @djspiewak

**Comment by SethTisue** [comment] 2020-09-14 23:53
can this be isolated/minimized any further? (the bug report is already valuable, but a standalone reproducer would be even better)

**Comment by som-snytt** [comment] 2020-09-15 02:38
```
abstract class Top {
  def f(s: String): Int = 42
  //def f(i: Int): Int = 27
}

trait T extends Top

// problematic adapter. super[Top] not allowed
trait C extends T {
  def f(d: Double): Int = super[T].f("")
}

class Bot extends C

object Test extends App {
  println(new Bot().f(3.14))
}
```

**Comment by som-snytt** [comment] 2020-09-15 03:07
Workaround in this case is just to say `super.test` instead of `super[DisciplineSuite].test`.

Sometimes we should just come out and say what we mean instead of qualifying it.

**Comment by SethTisue** [comment] 2020-09-15 03:28
Duplicate of #8693, then.

**Closed by SethTisue** 2020-09-15 03:28 UTC

**Comment by som-snytt** [comment] 2020-09-15 03:48
Thanks for the link. I'll reopen this ticket until somebody laughs at my "qualify" joke.
