### ISSUE TITLE
Implicit arguments lead to java.lang.StackOverflowError in the scalac 2.12.2

### ISSUE THREAD

**Issue by martinberger** [scala/bug#10421] opened 2017-07-20 17:57 UTC
Here is a short program that crashes the scala compiler (version 2.12.2) with a java.lang.StackOverflowError.

```
   object Main {
     def f ( implicit x : Int ) : Unit = {}
     def g () : Unit = { f _ }
   }

**Comment by hrhino** [comment] 2017-07-20 18:13
I think this is a duplicate of #10332...

**Comment by martinberger** [comment] 2017-07-21 08:42
I agree, that's the same bug. The new dotc compiler does not have this problem.

**Comment by lrytz** [comment] 2017-07-21 09:31
PR: https://github.com/scala/scala/pull/5983

**Closed** 2017-07-21 09:31 UTC
