### ISSUE TITLE
Copyrights in source code

### ISSUE THREAD

**Issue by Abrasha** [scala/bug#10531] opened 2017-09-28 15:40 UTC
In Scala source code there are a lot of headers where copyrights are outdated.
My question is: should we update them with every year?

Example of copyright header:

```
/*                     __                                               *\
**     ________ ___   / /  ___     Scala API                            **
**    / __/ __// _ | / /  / _ |    (c) 2003-2013, LAMP/EPFL             **
**  __\ \/ /__/ __ |/ /__/ __ |    http://scala-lang.org/               **
** /____/\___/_/ |_/____/_/ | |                                         **
**                          |/                                          **
\*   
```

I believe I can find some time to write script for such purposes.

**Comment by jvican** [comment] 2017-09-28 15:43
Sbt-header does this, I think.

**Comment by Abrasha** [comment] 2017-09-28 15:44
@jvican awesome! Than I believe it should be added to the build lifecycle.

**Comment by jvican** [comment] 2017-09-28 21:08
Go ahead and open a PR then :wink:.

**Comment by Abrasha** [comment] 2017-09-29 05:41
@jvican sure! In the requirements of sbt-header I see

```
Java 8 or higher
sbt 1.0.0 or higher
```

Is it possible for scala build system? (tip: this is my first contribution to scala, so there are components which I am not familiar with)

**Comment by Abrasha** [comment] 2017-09-29 05:50
FYI, @SethTisue

**Comment by Abrasha** [comment] 2017-09-29 06:11
See the linked ticket in order to be informed that sbt-header seems to be really incompatible with sbt 0.13.16: https://github.com/sbt/sbt-header/issues/133

**Comment by Abrasha** [comment] 2017-09-29 09:03
Okay, I found out that issue was that the author have not published the version to repository yet. So it is fixed now and seems to be working with sbt 0.13.16. Will take case of this during next week.

One question I have: @jvican after processing source code files, should the be committed to VSC (git)? It happens once a year, but nevertheless it is a big change to review.

Also we can add `headerCheck` to CI system to check that all new and updated files contain right copyright header. What do you think?

Thank you.

**Comment by som-snytt** [comment] 2017-09-29 15:51
There was another issue or PR about syncing the copyright with git history. I wrote a tool but Jason wanted sbtheader integration. That made me yawn, but recently I considered that scalafix is the better tool. The year should not be updated arbitrarily.

**Comment by Abrasha** [comment] 2017-09-29 15:52
@som-snytt so should I spend time on improving this?

**Comment by som-snytt** [comment] 2017-09-29 15:56
I don't know. My PR was 5201 as a reference. On a tablet pls 4give terse reply.

**Comment by Abrasha** [comment] 2017-09-29 16:00
@som-snytt awesome, thank you. So why did you give up with your PR? I see that there are no comments that are against your solution.

**Comment by som-snytt** [comment] 2017-09-29 16:03
Comments all on the linked PR by the other fellow. Jason nixes it late in thread.

**Comment by SethTisue** [comment] 2018-02-06 22:35
duplicate of #9026

**Closed by SethTisue** 2018-02-06 22:35 UTC
