### ISSUE TITLE
No warning about use of static method of a deprecated Java class

### ISSUE THREAD

**Issue by dhs3000** [scala/bug#10752] opened 2018-02-28 15:49 UTC
It seems that deprecation information of a static method of a Java class that itself is marked as _deprecated_ is not reported -- for a Scala object it works as expected.

*Example*:
Given these Java and Scala classes
```java
@Deprecated
public class JavaDeprecatedClassWithStaticMethod {
    public static void someMethod() {
    }
}
```

```java
public class JavaClassWithDeprecatedStaticMethod {
    @Deprecated
    public static void someMethod() {
    }
}
```

```scala
@deprecated("", "")
object ScalaDeprecatedClassWithStaticMethod {
  def someMethod(): Unit = ()
}
```

```scala
object ScalaClassWithDeprecatedStaticMethod {
  @deprecated("", "")
  def someMethod(): Unit = ()
}
```

Compiling this:
```scala
object UseDeprecatedMethods {
  JavaDeprecatedClassWithStaticMethod.someMethod()
  JavaClassWithDeprecatedStaticMethod.someMethod()

  ScalaDeprecatedClassWithStaticMethod.someMethod()
  ScalaClassWithDeprecatedStaticMethod.someMethod()
}
```

produces the following warnings:
> Warning: method someMethod in object JavaClassWithDeprecatedStaticMethod is deprecated: see corresponding Javadoc for more information.
>  JavaClassWithDeprecatedStaticMethod.someMethod()
>Warning: object ScalaDeprecatedClassWithStaticMethod in package test is deprecated: 
>  ScalaDeprecatedClassWithStaticMethod.someMethod()
>Warning: method someMethod in object ScalaClassWithDeprecatedStaticMethod is deprecated: 
>  ScalaClassWithDeprecatedStaticMethod.someMethod()

I don't get a warning from `JavaDeprecatedClassWithStaticMethod`. (I tried different things like making changes to the files, cleaning...)

I have the same issue with a Java class in a library that is _deprecated_ and the use of is not reported either.

Scala: 2.12.4
JVM: JDK 1.8.0_162
SBT: 0.13.13

**Comment by manasvigupta** [comment] 2018-03-10 18:12
Hello, I would like to work on this bug as my first (hopefully) contribution to Scala.

How do I assign this issue to myself?

**Comment by SethTisue** [comment] 2018-03-10 19:52
@manasvigupta welcome! it's sufficient just to comment and say you're working on it, as you've already done.

I hope this does indeed prove to be a "good first issue" for you. you will need to get into Scala compiler internals. but I put the "good first issue" label on because it seems likely the relevant code will just need tweaking, not restructuring

@dhs3000 @manasvigupta have either of you looked in scala/bug to see if there are closely related existing issues? if there are, there might be useful commentary there

**Comment by manasvigupta** [comment] 2018-03-11 09:06
Hmm,  this bug seem to be duplicate of https://github.com/scala/bug/issues/8883 or https://issues.scala-lang.org/browse/SI-8883?orig=1

**Comment by manasvigupta** [comment] 2018-03-11 10:37
Also, I was able to replicate this issue with latest Scala compiler -> Scala compiler version 2.13.0-20180307-145925-90ffe62

**Comment by SethTisue** [comment] 2018-03-13 21:42
@manasvigupta unless I misunderstand, this isn't a duplicate of #8883. this ticket doesn't involve Scala's `@deprecated` annotation; it's entirely about `@Deprecated` from Java. (the bug report includes examples with `@deprecated`, but only to show that they are already handled correctly.)

the `JavaDeprecatedClassWithStaticMethod` test shows that scalac sometimes emits deprecation warnings when `@Deprecated` is present, but the `JavaClassWithDeprecatedStaticMethod` test shows a case where a deprecation warning should be issued but isn't.

**Comment by mghildiy** [comment] 2018-03-23 16:03
If none is working on it,I can take it.

BTW,which part in scala repo contains Scala compiler internals :)?I anyways want to explore compiler internals.I guess this is what contains so called 'macros'.

**Comment by SethTisue** [comment] 2018-03-23 16:14
> which part in scala repo contains Scala compiler internals

https://github.com/scala/scala/tree/2.12.x/src/compiler — see http://www.scala-lang.org/contribute/hacker-guide.html

**Comment by MrRexZ** [comment] 2018-12-09 15:20
I was working on this issue, but I think it might be part of [this bug](https://github.com/scala/bug/issues/9617). I used incremental compilation (compiling the Java source only then the Scala source), and only then I received the warning.

**Comment by retronym** [comment] 2020-02-11 01:52
This looks like a separate problem from #9617. 

```
cat sandbox/DeprecatedClass.java && javac -d /tmp sandbox/DeprecatedClass.java && scala -cp /tmp -deprecation -e 'class C { def use = p1.DeprecatedClass.foo }'
package p1;

@Deprecated
public class DeprecatedClass {
   public static void foo() {}
}
```

The fix might be as simple as copying the `@Deprecated` annotation across from the Java class the fictional module symbol we create to own its static methods. Alternatively, deprecation checks could look for the annotation in both locations for Java code.

**Closed** 2020-02-14 09:54 UTC
Labels: Lightbend support, deprecation, good first issue, help wanted

**Comment by retronym** [comment] 2020-02-18 12:28
@dwijnand @mkeskells

Here's a case that still isn't reported:

```
cat sandbox/Test.java &&  javac -d /tmp sandbox/Test.java && scala-ref 2.12.x -nc -cp /tmp -deprecation -e 'def use(c2: Test.C2): Unit = c2.foo'

public class Test {
  @Deprecated
  public static class C1 {
    public void foo() {};
  }
  public static class C2 extends C1 {
  }
}
```

**Comment by dwijnand** [comment] 2020-02-18 16:39
Should that be reported?  Javac (separately) compiling everything in Java doesn't report it, and Scalac compiling everything in Scala doesn't report it.  In both cases the extension of a deprecated class is reported.  Is that not correct?

```
/s/C2.java:3: warning: [deprecation] C1 in p1 has been deprecated
public class C2 extends C1 {
                        ^
1 warning
```

```
scala> class C2 extends C1
                        ^
       warning: class C1 is deprecated:
defined class C2
```

**Comment by retronym** [comment] 2020-02-18 23:16
I reckon the fix will be to also add the `@Deprecated` annotation to the `ModuleClassSymbol` as well as the `ModuleSymbol`.

**Comment by retronym** [comment] 2020-02-19 00:12
> Should that be reported? Javac (separately) compiling everything in Java doesn't report it, and Scalac compiling everything in Scala doesn't report it. In both cases the extension of a deprecated class is reported. Is that not correct?

If Javac doesn't report it we shouldn't either. I'll keep digging for the case the @mkeskells believes is missing.
