### ISSUE TITLE
Source incompatibility with 2.12.8

### ISSUE THREAD

**Issue by jrudolph** [scala/bug#11289] opened 2018-12-05 10:40 UTC
Compiles with 2.12.7, fails with 2.12.8.

Is that expected?

https://jenkins.akka.io:8498/job/pr-validator-akka-http/3022/console

```
[error] /home/jenkins/workspace/workspace/pr-validator-akka-http/docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala:133:61: missing argument list for method akkaResponseTimeLoggingFunction
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `akkaResponseTimeLoggingFunction _` or `akkaResponseTimeLoggingFunction(_,_,_)(_)(_)` instead of `akkaResponseTimeLoggingFunction`.
[error]       akkaResponseTimeLoggingFunction(log, requestTimestamp)(_)
[error]                                                             ^
```

Code in question:

https://github.com/akka/akka-http/blob/aa3f86dfcbdf6b4aa18b5d14afdea3c8fbf62bc7/docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala#L116-L134

**Comment by SethTisue** [comment] 2018-12-05 22:38
possibly has to do with https://github.com/scala/scala/pull/7340 ?

**Comment by adriaanm** [comment] 2018-12-06 10:00
Thanks for reporting! I've investigated a bit and logged a ticket + wip branch at https://github.com/scala/bug/issues/11291. The original behavior in 2.12.7 was dubious (not supposed to do eta-expansion without an expected type, since there was only one `(_)` instead of two for the missing argument list), and the method value fix `m _` instead of `m(_)` works on both versions, so I assume we're ok here?

**Comment by jrudolph** [comment] 2018-12-06 10:10
Thanks for looking into it, @adriaanm. The code is several years old, so the bug must have been in there for a while. It's probably too much to ask for "bugwards" compatibility and as you say the code was dubious to begin with. For akka-http we are probably ok. Users probably aren't affected and I'm personally not too much concerned about source compatibility anyway so we could close it if there's nothing to be done.

**Comment by adriaanm** [comment] 2018-12-06 10:18
Ok, thanks for confirming. I'd still like to fix the bug with eta-expansion of curried methods. It's "just" a matter of polishing/hardening my wip :-)

**Comment by adriaanm** [comment] 2018-12-06 15:43
Closing as duplicate of  #11291

**Closed by adriaanm** 2018-12-06 15:43 UTC

**Comment by som-snytt** [comment] 2018-12-07 01:12
Personally, I flip-flopped a couple of times on this one, though my first take was that the previous behavior was obviously a bug. There are a couple of aspects to requiring the expected type: one is notational, when does `f` not mean its application, and the other is, what param types to infer.

In this case, `f(1)(_)` itself means a function is expected of the form `p => f(1)(p)` or `p => q => f(1)(p)(q)`. If you're eventually getting rid of method value syntax, why ask me to write `f(1)(_)(_)`? if there's only one reasonable reading of the expression? And now scalac will magically learn the required param types from `f`?

**Comment by adriaanm** [comment] 2018-12-07 09:22
I would argue `f(1)(_)` means `p => f(1)(p)`, and not `p => q => f(1)(p)(q)`, which is the bug I think we agree on (what comes before flip? flap?).

When it comes to getting rid of method value syntax `f _`, I don't think we can do that until we eta-expand regardless of expected type, which is where the real contention lies. I'm in favor, but others worry eta-expanding so recklessly will hide refactoring mistakes (adding an argument list, and then ending up with a bunch of functions rather than type checker complaints of unapplied methods)

**Comment by som-snytt** [comment] 2018-12-07 12:50
Thanks for hi-lighting the refactoring issue, I hadn't thought of that. I was just looking at some issue where the point was the behavior when typechecking the incomplete expression. From now on, I will try to think first of what is actually the usual case: I'm in the middle of an edit.
